export const DRAFT_RECOMMENDATION_SCORING_WEIGHTS = {
  BASE_ROLE_FIT: 40,
  INTENDED_CHAMPION_BONUS: 15,
  GOOD_MATCHUP_TAG: 8,
  WEAK_MATCHUP_TAG: -10,
  GOOD_SYNERGY_TAG: 6,
  TEAM_RISK_TAG: -6,
  BUILD_PROFILE_READY: 8,
  LOW_DATA_QUALITY_PENALTY: -5,
} as const;

export const DRAFT_RECOMMENDATION_SCORE_LIMITS = {
  MIN_SCORE: 0,
  MAX_SCORE: 100,
  DEFAULT_RECOMMENDATION_LIMIT: 5,
} as const;
