import { GameRole, PrismaClient } from '../../src/generated/prisma/client.js';

type ChampionSeed = {
  key: string;
  name: string;
  title?: string | null;
  titleVi?: string | null;
  roles: GameRole[];
  damageType: string;
  rangeType: string;
  difficulty: string;
  resourceType: string;
  classTags: string[];
  playstyleTags: string[];
  utilityTags: string[];
  riskTags: string[];
  strengths: string[];
  weaknesses: string[];
};

const championSeeds: ChampionSeed[] = [
  // AATROX
  {
    key: `aatrox`,
    name: `Aatrox`,
    title: `The Darkin Blade`,
    titleVi: `Quỷ Kiếm Darkin`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `NONE`,
    classTags: [`FIGHTER`, `BRUISER`],
    playstyleTags: [`SUSTAIN`, `DRAIN_TANK`, `TEAMFIGHT`],
    utilityTags: [`KNOCK_UP`, `SLOW`, `DASH`, `FEAR`],
    riskTags: [`SKILLSHOT_RELIANT`, `HEALING_RELIANT`, `KITEABLE`],
    strengths: [`SUSTAIN`, `EXTENDED_FIGHT`, `TEAMFIGHT`, `AREA_DAMAGE`],
    weaknesses: [`ANTI_HEAL`, `HIGH_MOBILITY`, `KITE`, `POINT_AND_CLICK_CC`],
  },
  // AHRI
  {
    key: `ahri`,
    name: `Ahri`,
    title: `The Nine-Tailed Fox`,
    titleVi: `Hồ Ly Chín Đuôi`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ASSASSIN`],
    playstyleTags: [`BURST`, `PICK`, `MOBILITY`],
    utilityTags: [`CHARM`, `DASH`],
    riskTags: [`SKILLSHOT_RELIANT`, `SQUISHY`],
    strengths: [`PICK_POTENTIAL`, `MOBILITY`, `BURST_DAMAGE`],
    weaknesses: [`WEAK_WHEN_BEHIND`, `SKILLSHOT_RELIANT`],
  },
  // AKALI
  {
    key: `akali`,
    name: `Akali`,
    title: `The Rogue Assassin`,
    titleVi: `Sát Thủ Đơn Độc`,
    roles: [GameRole.MID, GameRole.TOP],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `ENERGY`,
    classTags: [`ASSASSIN`],
    playstyleTags: [`BURST`, `MOBILITY`, `PICK`],
    utilityTags: [`DASH`, `STEALTH`, `SLOW`, `EXECUTE`],
    riskTags: [`HIGH_EXECUTION`, `CC_VULNERABLE`, `ENERGY_RELIANT`],
    strengths: [
      `BURST_DAMAGE`,
      `MOBILITY`,
      `KILL_PRESSURE`,
      `OUTPLAY_POTENTIAL`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `REVEAL`, `HARD_TO_PLAY`],
  },
  // AKSHAN
  {
    key: `akshan`,
    name: `Akshan`,
    title: `The Rogue Sentinel`,
    titleVi: `Vệ Binh Nổi Loạn`,
    roles: [GameRole.MID, GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `ASSASSIN`],
    playstyleTags: [`MOBILITY`, `ROAMING`, `PICK`, `ON_HIT_CHAMPION`],
    utilityTags: [`DASH`, `STEALTH`, `REVEAL`, `REVIVE`, `EXECUTE`],
    riskTags: [`HIGH_EXECUTION`, `CC_VULNERABLE`, `SQUISHY`],
    strengths: [`ROAMING`, `PICK_POTENTIAL`, `MOBILITY`, `KILL_PRESSURE`],
    weaknesses: [`POINT_AND_CLICK_CC`, `LOW_DURABILITY_TEAM`, `REVEAL`],
  },
  // ALISTAR
  {
    key: `alistar`,
    name: `Alistar`,
    title: `The Minotaur`,
    titleVi: `Quái Vật Đầu Bò`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `SUPPORT`],
    playstyleTags: [`ENGAGE`, `PEEL`, `TEAMFIGHT`],
    utilityTags: [`KNOCK_UP`, `KNOCK_BACK`, `STUN`, `HEALING`],
    riskTags: [`LOW_RANGE_CHAMPION`, `ABILITY_RELIANT_CHAMPION`],
    strengths: [`ENGAGE`, `PEEL`, `FRONTLINE`, `DAMAGE_REDUCTION`],
    weaknesses: [`POKE_COMPOSITION`, `DISENGAGE`, `LOW_RANGE_CHAMPION`],
  },
  // AMBESSA
  {
    key: `ambessa`,
    name: `Ambessa`,
    title: `The Matriarch of War`,
    titleVi: `Nữ Tướng Chiến Tranh`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `ENERGY`,
    classTags: [`FIGHTER`, `BRUISER`],
    playstyleTags: [`MOBILITY`, `DRAIN_TANK`, `EXTENDED_FIGHT_CHAMPION`],
    utilityTags: [`DASH`, `SHIELD`, `SLOW`, `STUN`],
    riskTags: [`HIGH_EXECUTION`, `ENERGY_RELIANT`, `KITEABLE`],
    strengths: [`MOBILITY`, `SUSTAIN`, `PERCENT_HEALTH_DAMAGE`, `DIVE`],
    weaknesses: [`POINT_AND_CLICK_CC`, `ANTI_HEAL`, `KITE`, `HARD_TO_PLAY`],
  },
  // AMUMU
  {
    key: `amumu`,
    name: `Amumu`,
    title: `The Sad Mummy`,
    titleVi: `Xác Ướp U Sầu`,
    roles: [GameRole.JUNGLE, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `MAGE`],
    playstyleTags: [`ENGAGE`, `TEAMFIGHT`, `AREA_DAMAGE`],
    utilityTags: [`STUN`, `ROOT`, `PULL`, `SLOW`],
    riskTags: [`SKILLSHOT_RELIANT`, `LOW_MOBILITY`, `KITEABLE`],
    strengths: [`TEAMFIGHT`, `CROWD_CONTROL`, `AREA_DAMAGE`, `ANTI_TANK`],
    weaknesses: [`KITE`, `DISENGAGE`, `HIGH_MOBILITY`],
  },
  // ANNIE
  {
    key: `annie`,
    name: `Annie`,
    title: `The Dark Child`,
    titleVi: `Đứa Trẻ Bóng Tối`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`BURST`, `PICK`, `TEAMFIGHT`],
    utilityTags: [`STUN`, `SHIELD`, `SPEED_UP`, `KNOCK_UP`],
    riskTags: [`LOW_MOBILITY`, `SHORT_RANGE_MAGE`, `FLASH_RELIANT`],
    strengths: [`BURST_DAMAGE`, `PICK_POTENTIAL`, `TEAMFIGHT`, `CROWD_CONTROL`],
    weaknesses: [`POKE_COMPOSITION`, `HIGH_MOBILITY`, `LONG_RANGE_CHAMPION`],
  },
  // ASHE
  {
    key: `ashe`,
    name: `Ashe`,
    title: `The Frost Archer`,
    titleVi: `Cung Băng`,
    roles: [GameRole.ADC, GameRole.SUPPORT],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`POKE`, `KITE`, `PICK`, `AUTO_ATTACK_CHAMPION`],
    utilityTags: [`SLOW`, `STUN`, `REVEAL`],
    riskTags: [`LOW_MOBILITY`, `SQUISHY`, `POSITIONING_RELIANT`],
    strengths: [`KITE`, `PICK_POTENTIAL`, `VISION_CONTROL`, `UTILITY_MARKSMAN`],
    weaknesses: [`DIVE`, `ASSASSIN`, `HIGH_MOBILITY`],
  },
  // AURELION SOL
  {
    key: `aurelion-sol`,
    name: `Aurelion Sol`,
    title: `The Star Forger`,
    titleVi: `Ác Long Thượng Giới`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`SCALING`, `ZONE_CONTROL`, `TEAMFIGHT`],
    utilityTags: [`STUN`, `KNOCK_UP`, `SLOW`, `PULL`],
    riskTags: [
      `WEAK_EARLY_GAME`,
      `POSITIONING_RELIANT`,
      `INTERRUPT_VULNERABLE`,
    ],
    strengths: [`SCALING_GAME`, `AREA_DAMAGE`, `TEAMFIGHT`, `ZONE_CONTROL`],
    weaknesses: [`EARLY_GAME_PRESSURE`, `ASSASSIN`, `POINT_AND_CLICK_CC`],
  },
  // AURORA
  {
    key: `aurora`,
    name: `Aurora`,
    title: `The Witch Between Worlds`,
    titleVi: `Phù Thủy Giữa Hai Thế Giới`,
    roles: [GameRole.MID, GameRole.TOP],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`MOBILITY`, `SKIRMISH`, `POKE`, `ZONE_CONTROL`],
    utilityTags: [`SLOW`, `STEALTH`, `DASH`],
    riskTags: [`POSITIONING_RELIANT`, `SQUISHY`, `HIGH_EXECUTION`],
    strengths: [
      `MOBILITY`,
      `ZONE_CONTROL`,
      `PERCENT_HEALTH_DAMAGE`,
      `SKIRMISH`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `BURST_DAMAGE`, `LONG_RANGE_CHAMPION`],
  },
  // BARD
  {
    key: `bard`,
    name: `Bard`,
    title: `The Wandering Caretaker`,
    titleVi: `Lữ Khách Tinh Linh`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `SUPPORT`],
    playstyleTags: [`ROAMING`, `PICK`, `ZONE_CONTROL`, `TEAM_SUPPORT`],
    utilityTags: [`SLOW`, `STUN`, `HEALING`, `STASIS`, `PORTAL`],
    riskTags: [`SKILLSHOT_RELIANT`, `HIGH_EXECUTION`, `POSITIONING_RELIANT`],
    strengths: [`ROAMING`, `PICK_POTENTIAL`, `ZONE_CONTROL`, `TEAM_SUPPORT`],
    weaknesses: [
      `LOW_DURABILITY_TEAM`,
      `HIGH_EXECUTION`,
      `POSITIONING_RELIANT`,
    ],
  },
  // BLITZCRANK
  {
    key: 'blitzcrank',
    name: 'Blitzcrank',
    title: 'The Great Steam Golem',
    titleVi: 'Người Máy Hơi Nước Vĩ Đại',
    roles: [GameRole.SUPPORT],
    damageType: 'MAGIC',
    rangeType: 'MELEE',
    difficulty: 'MEDIUM',
    resourceType: 'MANA',
    classTags: ['TANK', 'SUPPORT'],
    playstyleTags: ['PICK', 'ENGAGE', 'ROAMING'],
    utilityTags: ['PULL', 'KNOCK_UP', 'SILENCE', 'SPEED_UP', 'SHIELD'],
    riskTags: [
      'SKILLSHOT_RELIANT',
      'COOLDOWN_RELIANT',
      'PUNISHABLE_WHEN_MISSED',
    ],
    strengths: ['PICK_POTENTIAL', 'ENGAGE', 'ROAMING'],
    weaknesses: ['MISS_DEPENDENT', 'LOW_RANGE_CHAMPION', 'KITEABLE'],
  },
  // BRAND
  {
    key: `brand`,
    name: `Brand`,
    title: `The Burning Vengeance`,
    titleVi: `Ngọn Lửa Báo Thù`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`BURST`, `POKE`, `TEAMFIGHT`, `ZONE_CONTROL`],
    utilityTags: [`STUN`, `SLOW`],
    riskTags: [`SKILLSHOT_RELIANT`, `LOW_MOBILITY`, `SQUISHY`],
    strengths: [`AREA_DAMAGE`, `BURN_DAMAGE`, `TEAMFIGHT`, `POKE`],
    weaknesses: [`HIGH_MOBILITY`, `ASSASSIN`, `LONG_RANGE_CHAMPION`],
  },
  // BRAUM
  {
    key: `braum`,
    name: `Braum`,
    title: `The Heart of the Freljord`,
    titleVi: `Trái Tim của Freljord`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `SUPPORT`],
    playstyleTags: [`PEEL`, `TEAMFIGHT`, `TEAM_SUPPORT`],
    utilityTags: [`STUN`, `SLOW`, `KNOCK_UP`, `SHIELD`],
    riskTags: [`LOW_RANGE_CHAMPION`, `TEAM_DEPENDENT`, `LOW_DAMAGE`],
    strengths: [`PEEL`, `FRONTLINE`, `TEAM_SUPPORT`, `CROWD_CONTROL`],
    weaknesses: [`POKE_COMPOSITION`, `DISENGAGE`, `LOW_KILL_PRESSURE`],
  },
  // CAITLYN
  {
    key: `caitlyn`,
    name: `Caitlyn`,
    title: `The Sheriff of Piltover`,
    titleVi: `Cảnh Sát Trưởng Piltover`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`POKE`, `PICK`, `ZONE_CONTROL`, `AUTO_ATTACK_CHAMPION`],
    utilityTags: [`ROOT`, `SLOW`, `REVEAL`, `DASH`],
    riskTags: [`POSITIONING_RELIANT`, `SQUISHY`, `LOW_MOBILITY`],
    strengths: [
      `LONG_RANGE_POKE`,
      `LANE_PRESSURE`,
      `ZONE_CONTROL`,
      `PICK_POTENTIAL`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `POINT_AND_CLICK_CC`],
  },
  // CAMILLE
  {
    key: `camille`,
    name: `Camille`,
    title: `The Steel Shadow`,
    titleVi: `Bóng Thép`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `BRUISER`],
    playstyleTags: [`MOBILITY`, `PICK`, `SPLIT_PUSH`, `DIVE`],
    utilityTags: [`DASH`, `STUN`, `SLOW`, `SHIELD`],
    riskTags: [`HIGH_EXECUTION`, `COOLDOWN_RELIANT`, `CC_VULNERABLE`],
    strengths: [`MOBILITY`, `PICK_POTENTIAL`, `DIVE`, `SIDE_LANE`],
    weaknesses: [`POINT_AND_CLICK_CC`, `DISENGAGE`, `WEAK_WHEN_BEHIND`],
  },
  // YASUO
  {
    key: 'yasuo',
    name: 'Yasuo',
    title: 'The Unforgiven',
    titleVi: `Kẻ Bất Dung Thứ`,
    roles: [GameRole.MID],
    damageType: 'PHYSICAL',
    rangeType: 'MELEE',
    difficulty: 'HIGH',
    resourceType: 'FLOW',
    classTags: ['FIGHTER', 'SKIRMISHER'],
    playstyleTags: ['DPS', 'MOBILITY', 'SCALING'],
    utilityTags: ['KNOCK_UP', 'WIND_WALL'],
    riskTags: ['MELEE_MID', 'HIGH_EXECUTION', 'CC_VULNERABLE'],
    strengths: ['SCALING_DAMAGE', 'MOBILITY', 'TEAMFIGHT_FOLLOWUP'],
    weaknesses: ['HARD_TO_PLAY', 'WEAK_INTO_POINT_CLICK_CC'],
  },
  // VIKTOR
  {
    key: 'viktor',
    name: 'Viktor',
    title: 'The Machine Herald',
    titleVi: `Sứ Giả Máy Móc`,
    roles: [GameRole.MID],
    damageType: 'MAGIC',
    rangeType: 'RANGED',
    difficulty: 'MEDIUM',
    resourceType: 'MANA',
    classTags: ['MAGE', 'CONTROL_MAGE'],
    playstyleTags: ['SCALING', 'POKE', 'ZONE_CONTROL'],
    utilityTags: ['SLOW', 'ZONE_CONTROL'],
    riskTags: ['LOW_MOBILITY', 'SQUISHY'],
    strengths: ['WAVE_CLEAR', 'SCALING_DAMAGE', 'ZONE_CONTROL'],
    weaknesses: ['LOW_MOBILITY', 'VULNERABLE_TO_DIVE'],
  },
  // CORKI
  {
    key: `corki`,
    name: `Corki`,
    title: `The Daring Bombardier`,
    titleVi: `Phi Công Quả Cảm`,
    roles: [GameRole.MID, GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `MAGE`],
    playstyleTags: [`POKE`, `SCALING`, `MOBILITY`, `TEAMFIGHT`],
    utilityTags: [`DASH`, `REVEAL`],
    riskTags: [`MANA_HUNGRY_CHAMPION`, `POSITIONING_RELIANT`, `SQUISHY`],
    strengths: [`POKE`, `HYBRID_DAMAGE`, `AREA_DAMAGE`, `SCALING_DAMAGE`],
    weaknesses: [`DIVE`, `ASSASSIN`, `POINT_AND_CLICK_CC`],
  },
  // DARIUS
  {
    key: `darius`,
    name: `Darius`,
    title: `The Hand of Noxus`,
    titleVi: `Đại Tướng Noxus`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `BRUISER`],
    playstyleTags: [`EXTENDED_FIGHT_CHAMPION`, `DRAIN_TANK`, `TEAMFIGHT`],
    utilityTags: [`PULL`, `SLOW`, `EXECUTE`],
    riskTags: [`LOW_MOBILITY`, `KITEABLE`, `FLASH_RELIANT`],
    strengths: [`EXTENDED_FIGHT`, `SUSTAIN`, `EXECUTE`, `SNOWBALL`],
    weaknesses: [`KITE`, `HIGH_MOBILITY`, `DISENGAGE`],
  },
  // DIANA
  {
    key: `diana`,
    name: `Diana`,
    title: `Scorn of the Moon`,
    titleVi: `Vầng Trăng Ai Oán`,
    roles: [GameRole.MID, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ASSASSIN`, `FIGHTER`],
    playstyleTags: [`BURST`, `MOBILITY`, `DIVE`, `TEAMFIGHT`],
    utilityTags: [`DASH`, `SLOW`, `SHIELD`],
    riskTags: [`MELEE_MID`, `HIGH_EXECUTION`, `CC_VULNERABLE`],
    strengths: [`BURST_DAMAGE`, `MOBILITY`, `DIVE`, `TEAMFIGHT`],
    weaknesses: [`POINT_AND_CLICK_CC`, `DISENGAGE`, `WEAK_WHEN_BEHIND`],
  },
  // DR. MUNDO
  {
    key: `dr-mundo`,
    name: `Dr. Mundo`,
    title: `The Madman of Zaun`,
    titleVi: `Cuồng Nhân Xứ Zaun`,
    roles: [GameRole.TOP],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `HEALTH`,
    classTags: [`TANK`, `FIGHTER`],
    playstyleTags: [`DRAIN_TANK`, `EXTENDED_FIGHT_CHAMPION`, `SCALING`],
    utilityTags: [`SLOW`, `SPEED_UP`, `HEALING`],
    riskTags: [`KITEABLE`, `ANTI_HEAL_VULNERABLE`, `LOW_CC`],
    strengths: [`SUSTAIN`, `FRONTLINE`, `SCALING_HEALTH`, `ANTI_CC`],
    weaknesses: [`ANTI_HEAL`, `KITE`, `PERCENT_HEALTH_DAMAGE`],
  },
  // DRAVEN
  {
    key: `draven`,
    name: `Draven`,
    title: `The Glorious Executioner`,
    titleVi: `Đao Phủ Kiêu Hùng`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`SNOWBALL`, `AUTO_ATTACK_CHAMPION`, `HIGH_EXECUTION`],
    utilityTags: [`SLOW`, `KNOCK_BACK`, `MOVEMENT_SPEED`],
    riskTags: [`POSITIONING_RELIANT`, `TEAM_DEPENDENT`, `HIGH_EXECUTION`],
    strengths: [
      `LANE_PRESSURE`,
      `SNOWBALL`,
      `PHYSICAL_DAMAGE`,
      `AUTO_ATTACK_CHAMPION`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `DIVE`, `KITE`, `HARD_TO_PLAY`],
  },
  // EKKO
  {
    key: `ekko`,
    name: `Ekko`,
    title: `The Boy Who Shattered Time`,
    titleVi: `Cậu Bé Đảo Lộn Thời Gian`,
    roles: [GameRole.MID, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `MOBILITY`, `SKIRMISH`, `SCALING`],
    utilityTags: [`DASH`, `BLINK`, `SLOW`, `STUN`, `SHIELD`],
    riskTags: [`HIGH_EXECUTION`, `COOLDOWN_RELIANT`, `POSITIONING_RELIANT`],
    strengths: [
      `BURST_DAMAGE`,
      `MOBILITY`,
      `OUTPLAY_POTENTIAL`,
      `SCALING_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `LOCKDOWN_ZONE`, `EARLY_GAME_PRESSURE`],
  },
  // EVELYNN
  {
    key: `evelynn`,
    name: `Evelynn`,
    title: `Agony's Embrace`,
    titleVi: `Yêu Nữ Gai Góc`,
    roles: [GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `PICK`, `MOBILITY`],
    utilityTags: [`CAMOUFLAGE`, `CHARM`, `SLOW`, `MAGIC_RESIST_REDUCTION`],
    riskTags: [`HIGH_EXECUTION`, `POSITIONING_RELIANT`, `CC_VULNERABLE`],
    strengths: [
      `PICK_POTENTIAL`,
      `BURST_DAMAGE`,
      `MAGIC_DAMAGE`,
      `OUTPLAY_POTENTIAL`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `VISION_CONTROL`, `EARLY_GAME_PRESSURE`],
  },
  // EZREAL
  {
    key: `ezreal`,
    name: `Ezreal`,
    title: `The Prodigal Explorer`,
    titleVi: `Nhà Thám Hiểm Thiên Tài`,
    roles: [GameRole.ADC, GameRole.MID],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `MAGE`],
    playstyleTags: [
      `POKE`,
      `MOBILITY`,
      `SPELLBLADE_CHAMPION`,
      `ABILITY_RELIANT_CHAMPION`,
    ],
    utilityTags: [`BLINK`, `GLOBAL_RANGE`, `COOLDOWN_REDUCTION`],
    riskTags: [`SKILLSHOT_RELIANT`, `SQUISHY`, `MANA_HUNGRY_CHAMPION`],
    strengths: [`POKE`, `MOBILITY`, `HYBRID_DAMAGE`, `LONG_RANGE_POKE`],
    weaknesses: [`POINT_AND_CLICK_CC`, `DIVE`, `LOW_CC`, `SKILLSHOT_RELIANT`],
  },
  // FIDDLESTICKS
  {
    key: `fiddlesticks`,
    name: `Fiddlesticks`,
    title: `The Ancient Fear`,
    titleVi: `Nỗi Sợ Viễn Cổ`,
    roles: [GameRole.JUNGLE, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`BURST`, `ZONE_CONTROL`, `TEAMFIGHT`, `PICK`],
    utilityTags: [`FEAR`, `SLOW`, `SILENCE`, `BLINK`],
    riskTags: [`ULTIMATE_RELIANT_CHAMPION`, `CHANNEL`, `POSITIONING_RELIANT`],
    strengths: [`TEAMFIGHT`, `AREA_DAMAGE`, `CROWD_CONTROL`, `JUNGLE_CLEAR`],
    weaknesses: [
      `INTERRUPT_VULNERABLE`,
      `VISION_CONTROL`,
      `POINT_AND_CLICK_CC`,
    ],
  },
  // FIORA
  {
    key: `fiora`,
    name: `Fiora`,
    title: `The Grand Duelist`,
    titleVi: `Nữ Kiếm Sư Kiêu Hùng`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`SPLIT_PUSH`, `DUELIST`, `MOBILITY`, `SCALING`],
    utilityTags: [`DASH`, `SLOW`, `STUN`, `HEALING`],
    riskTags: [`HIGH_EXECUTION`, `POSITIONING_RELIANT`, `TEAM_DEPENDENT`],
    strengths: [
      `SPLIT_PUSH`,
      `TRUE_DAMAGE`,
      `DUELING`,
      `PERCENT_HEALTH_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `GROUPED_ENEMIES`, `HARD_TO_PLAY`],
  },
  // FIZZ
  {
    key: `fizz`,
    name: `Fizz`,
    title: `The Tidal Trickster`,
    titleVi: `Chú Cá Tinh Nghịch`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `MOBILITY`, `PICK`],
    utilityTags: [`DASH`, `BLINK`, `SLOW`, `KNOCK_UP`],
    riskTags: [`HIGH_EXECUTION`, `COOLDOWN_RELIANT`, `CC_VULNERABLE`],
    strengths: [`BURST_DAMAGE`, `MOBILITY`, `PICK_POTENTIAL`, `TOWER_DIVE`],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `EARLY_GAME_PRESSURE`,
      `HIGH_MAGIC_RESIST`,
    ],
  },
  // GALIO
  {
    key: `galio`,
    name: `Galio`,
    title: `The Colossus`,
    titleVi: `Vệ Thần Khổng Lồ`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`TANK`, `MAGE`],
    playstyleTags: [`TEAMFIGHT`, `ENGAGE`, `ROAMING`, `ZONE_CONTROL`],
    utilityTags: [`TAUNT`, `KNOCK_UP`, `SHIELD`, `DAMAGE_REDUCTION`],
    riskTags: [`COOLDOWN_RELIANT`, `LOW_MOBILITY`, `INTERRUPT_VULNERABLE`],
    strengths: [`TEAMFIGHT`, `ENGAGE`, `MAGIC_DAMAGE`, `TEAM_SUPPORT`],
    weaknesses: [`DISENGAGE`, `POKE_COMPOSITION`, `HIGH_MOBILITY`],
  },
  // GAREN
  {
    key: `garen`,
    name: `Garen`,
    title: `The Might of Demacia`,
    titleVi: `Sức Mạnh Demacia`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `NONE`,
    classTags: [`FIGHTER`, `TANK`],
    playstyleTags: [`BRUISER`, `SUSTAIN`, `SPLIT_PUSH`],
    utilityTags: [`SILENCE`, `SPEED_UP`, `SHIELD`, `DAMAGE_REDUCTION`],
    riskTags: [`LOW_MOBILITY`, `KITEABLE`, `COOLDOWN_RELIANT`],
    strengths: [`LANE_SURVIVAL`, `SUSTAIN`, `EXECUTE`, `ARMOR_SHRED`],
    weaknesses: [`KITE`, `DISENGAGE`, `LOW_RANGE_CHAMPION`],
  },
  // GNAR
  {
    key: `gnar`,
    name: `Gnar`,
    title: `The Missing Link`,
    titleVi: `Mắt Xích Thất Lạc`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `HYBRID`,
    difficulty: `HIGH`,
    resourceType: `RAGE`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`POKE`, `KITE`, `TEAMFIGHT`, `SPLIT_PUSH`],
    utilityTags: [`SLOW`, `STUN`, `KNOCK_BACK`, `DASH`],
    riskTags: [`TRANSFORMATION_RELIANT`, `HIGH_EXECUTION`, `TIMING_RELIANT`],
    strengths: [
      `LANE_PRESSURE`,
      `TEAMFIGHT`,
      `PERCENT_HEALTH_DAMAGE`,
      `ZONE_CONTROL`,
    ],
    weaknesses: [`RAGE_MANAGEMENT`, `POINT_AND_CLICK_CC`, `HARD_TO_PLAY`],
  },
  // GRAGAS
  {
    key: `gragas`,
    name: `Gragas`,
    title: `The Rabble Rouser`,
    titleVi: `Gã Bợm Rượu`,
    roles: [GameRole.JUNGLE, GameRole.TOP, GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`TANK`, `MAGE`, `FIGHTER`],
    playstyleTags: [`ENGAGE`, `BURST`, `ZONE_CONTROL`, `SUSTAIN`],
    utilityTags: [`SLOW`, `STUN`, `KNOCK_BACK`, `DAMAGE_REDUCTION`],
    riskTags: [`COOLDOWN_RELIANT`, `SKILLSHOT_RELIANT`, `POSITIONING_RELIANT`],
    strengths: [`ENGAGE`, `DISENGAGE`, `AREA_DAMAGE`, `PICK_POTENTIAL`],
    weaknesses: [`HIGH_MOBILITY`, `POINT_AND_CLICK_CC`, `LONG_RANGE_POKE`],
  },
  // GRAVES
  {
    key: `graves`,
    name: `Graves`,
    title: `The Outlaw`,
    titleVi: `Kẻ Ngoài Vòng Pháp Luật`,
    roles: [GameRole.JUNGLE],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `FIGHTER`],
    playstyleTags: [`BURST`, `SKIRMISH`, `KITE`],
    utilityTags: [`DASH`, `SLOW`, `VISION_DENIAL`, `KNOCK_BACK`],
    riskTags: [`POSITIONING_RELIANT`, `LOW_RANGE_CHAMPION`, `COOLDOWN_RELIANT`],
    strengths: [`JUNGLE_CLEAR`, `BURST_DAMAGE`, `DUELING`, `PHYSICAL_DAMAGE`],
    weaknesses: [`LONG_RANGE_CHAMPION`, `POINT_AND_CLICK_CC`, `LOW_CC`],
  },
  // GWEN
  {
    key: `gwen`,
    name: `Gwen`,
    title: `The Hallowed Seamstress`,
    titleVi: `Búp Bê Ước Nguyện`,
    roles: [GameRole.TOP, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`DPS`, `SCALING`, `SUSTAIN`, `DUELIST`],
    utilityTags: [`DASH`, `SLOW`, `UNTARGETABLE`, `BONUS_RESISTANCES`],
    riskTags: [`COOLDOWN_RELIANT`, `POSITIONING_RELIANT`, `CC_VULNERABLE`],
    strengths: [
      `SCALING_DAMAGE`,
      `PERCENT_HEALTH_DAMAGE`,
      `TRUE_DAMAGE`,
      `SUSTAIN_FIGHTER`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `EARLY_GAME_PRESSURE`, `KITE`],
  },
  // HECARIM
  {
    key: `hecarim`,
    name: `Hecarim`,
    title: `The Shadow of War`,
    titleVi: `Bóng Ma Chiến Tranh`,
    roles: [GameRole.JUNGLE],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `DIVER`],
    playstyleTags: [`ENGAGE`, `DIVER`, `SUSTAIN`, `MOBILITY`],
    utilityTags: [`FEAR`, `KNOCK_BACK`, `DASH`, `MOVEMENT_SPEED`],
    riskTags: [`ENGAGE`, `COOLDOWN_RELIANT`, `CC_VULNERABLE`],
    strengths: [
      `ENGAGE`,
      `JUNGLE_CLEAR`,
      `SUSTAIN_FIGHTER`,
      `FOLLOW_UP_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `KITE`, `DISENGAGE`],
  },
  // HEIMERDINGER
  {
    key: `heimerdinger`,
    name: `Heimerdinger`,
    title: `The Revered Inventor`,
    titleVi: `Nhà Phát Minh Lỗi Lạc`,
    roles: [GameRole.MID, GameRole.TOP, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`ZONE_CONTROL`, `POKE`, `SCALING`],
    utilityTags: [`SLOW`, `STUN`, `VISION_CONTROL`],
    riskTags: [`LOW_MOBILITY`, `POSITIONING_RELIANT`, `COOLDOWN_RELIANT`],
    strengths: [`ZONE_CONTROL`, `POKE`, `WAVE_CLEAR`, `AREA_DAMAGE`],
    weaknesses: [`DIVE`, `ASSASSIN`, `HIGH_MOBILITY`, `LONG_RANGE_CHAMPION`],
  },
  // IRELIA
  {
    key: `irelia`,
    name: `Irelia`,
    title: `The Blade Dancer`,
    titleVi: `Vũ Kiếm Sư`,
    roles: [GameRole.TOP, GameRole.MID],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`MOBILITY`, `DPS`, `SKIRMISH`, `SPLIT_PUSH`],
    utilityTags: [`DASH`, `STUN`, `SLOW`],
    riskTags: [`HIGH_EXECUTION`, `CC_VULNERABLE`, `TIMING_RELIANT`],
    strengths: [`MOBILITY`, `DUELING`, `COOLDOWN_RESET`, `EXTENDED_FIGHT`],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `DISENGAGE`,
      `BURST_DAMAGE`,
      `ANTI_HEAL`,
    ],
  },
  // JANNA
  {
    key: `janna`,
    name: `Janna`,
    title: `The Storm's Fury`,
    titleVi: `Cơn Thịnh Nộ Của Bão Tố`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`ENCHANTER`, `MAGE`],
    playstyleTags: [`PEEL`, `TEAM_SUPPORT`, `DISENGAGE`],
    utilityTags: [
      `SHIELD`,
      `HEALING`,
      `KNOCK_UP`,
      `KNOCK_BACK`,
      `MOVEMENT_SPEED`,
    ],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `LOW_DAMAGE`],
    strengths: [`PEEL`, `DISENGAGE`, `TEAM_SUPPORT`, `SHIELDING`],
    weaknesses: [`DIVE`, `BURST_DAMAGE`, `PICK_POTENTIAL`, `ANTI_SHIELD`],
  },
  // JARVAN IV
  {
    key: `jarvan-iv`,
    name: `Jarvan IV`,
    title: `The Exemplar of Demacia`,
    titleVi: `Biểu Tượng Của Demacia`,
    roles: [GameRole.JUNGLE, GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `TANK`],
    playstyleTags: [`ENGAGE`, `DIVE`, `TEAMFIGHT`],
    utilityTags: [`KNOCK_UP`, `SLOW`, `SHIELD`, `ATTACK_SPEED_STEROID`],
    riskTags: [`COMMIT_HEAVY`, `COOLDOWN_RELIANT`, `CC_VULNERABLE`],
    strengths: [`ENGAGE`, `DIVE`, `TEAMFIGHT`, `EARLY_GAME_PRESSURE`],
    weaknesses: [`DISENGAGE`, `KITE`, `ANTI_DIVE`, `HIGH_MOBILITY`],
  },
  // JAX
  {
    key: `jax`,
    name: `Jax`,
    title: `Grandmaster at Arms`,
    titleVi: `Bậc Thầy Vũ Khí`,
    roles: [GameRole.TOP, GameRole.JUNGLE],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`DPS`, `DUELING`, `SPLIT_PUSH`, `SCALING`],
    utilityTags: [`DASH`, `STUN`, `DAMAGE_REDUCTION`, `ATTACK_SPEED_STEROID`],
    riskTags: [`CC_VULNERABLE`, `COMMIT_HEAVY`, `COOLDOWN_RELIANT`],
    strengths: [`DUELING`, `SPLIT_PUSH`, `SCALING_DAMAGE`, `EXTENDED_FIGHT`],
    weaknesses: [`KITE`, `DISENGAGE`, `POINT_AND_CLICK_CC`, `BURST_DAMAGE`],
  },
  // JAYCE
  {
    key: `jayce`,
    name: `Jayce`,
    title: `The Defender of Tomorrow`,
    titleVi: `Người Bảo Hộ Tương Lai`,
    roles: [GameRole.TOP, GameRole.MID],
    damageType: `MIXED`,
    rangeType: `HYBRID`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `POKE`],
    playstyleTags: [`POKE`, `BURST`, `FORM_SWAP`, `LANE_PRESSURE`],
    utilityTags: [
      `KNOCK_BACK`,
      `MOVEMENT_SPEED`,
      `ARMOR_REDUCTION`,
      `MAGIC_RESIST_REDUCTION`,
    ],
    riskTags: [`HIGH_EXECUTION`, `COOLDOWN_RELIANT`, `FORM_DEPENDENT`],
    strengths: [`LANE_PRESSURE`, `POKE`, `BURST_DAMAGE`, `SPLIT_PUSH`],
    weaknesses: [
      `HARD_TO_PLAY`,
      `CC_VULNERABLE`,
      `WEAK_WHEN_BEHIND`,
      `SUSTAIN`,
    ],
  },
  // JHIN
  {
    key: `jhin`,
    name: `Jhin`,
    title: `The Virtuoso`,
    titleVi: `Nghệ Sĩ Tử Thần`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`BURST`, `PICK`, `POKE`],
    utilityTags: [`ROOT`, `SLOW`, `VISION_CONTROL`, `MOVEMENT_SPEED`],
    riskTags: [`POSITIONING_RELIANT`, `LOW_MOBILITY`, `RELOAD_RELIANT`],
    strengths: [`PICK_POTENTIAL`, `BURST_DAMAGE`, `LONG_RANGE_POKE`, `EXECUTE`],
    weaknesses: [`DIVE`, `HIGH_MOBILITY`, `TANK`, `SUSTAIN`],
  },
  // JINX
  {
    key: `jinx`,
    name: `Jinx`,
    title: `The Loose Cannon`,
    titleVi: `Khẩu Pháo Nổi Loạn`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`DPS`, `SCALING`, `TEAMFIGHT`, `SNOWBALL`],
    utilityTags: [`SLOW`, `ROOT`, `VISION`, `ATTACK_SPEED_STEROID`],
    riskTags: [`POSITIONING_RELIANT`, `LOW_MOBILITY`, `SQUISHY`],
    strengths: [
      `SCALING_DAMAGE`,
      `TEAMFIGHT`,
      `RESET_CARRY`,
      `OBJECTIVE_CONTROL`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `POINT_AND_CLICK_CC`, `BURST_DAMAGE`],
  },
  // K'SANTE
  {
    key: `ksante`,
    name: `K'Sante`,
    title: `The Pride of Nazumah`,
    titleVi: `Niềm Kiêu Hãnh Của Nazumah`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`TANK`, `FIGHTER`],
    playstyleTags: [`DUELING`, `TEAMFIGHT`, `FRONTLINE`],
    utilityTags: [`KNOCK_BACK`, `STUN`, `SLOW`, `SHIELD`, `UNSTOPPABLE`],
    riskTags: [`HIGH_EXECUTION`, `COMMIT_HEAVY`, `FORM_DEPENDENT`],
    strengths: [`FRONTLINE`, `DAMAGE_REDUCTION`, `DUELING`, `DISPLACEMENT`],
    weaknesses: [`KITE`, `TRUE_DAMAGE`, `ANTI_TANK`, `DISENGAGE`],
  },
  {
    key: `kaisa`,
    name: `Kai'Sa`,
    title: `Daughter of the Void`,
    titleVi: `Ái Nữ Hư Không`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `ASSASSIN`],
    playstyleTags: [
      `DPS`,
      `MOBILITY`,
      `SCALING`,
      `ON_HIT_CHAMPION`,
      `ABILITY_RELIANT_CHAMPION`,
    ],
    utilityTags: [`DASH`, `STEALTH`, `REVEAL`, `SHIELD`, `ABILITY_EVOLUTION`],
    riskTags: [
      `POSITIONING_RELIANT`,
      `SKILLSHOT_RELIANT`,
      `SHORT_RANGE_MARKSMAN`,
    ],
    strengths: [
      `HYBRID_DAMAGE`,
      `MOBILITY`,
      `SCALING_DAMAGE`,
      `PICK_POTENTIAL`,
      `MISSING_HEALTH_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `LONG_RANGE_POKE`, `WEAK_EARLY_GAME`],
  },
  // KALISTA
  {
    key: `kalista`,
    name: `Kalista`,
    title: `The Spear of Vengeance`,
    titleVi: `Mũi Giáo Phục Hận`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [
      `DPS`,
      `MOBILITY`,
      `ON_HIT_CHAMPION`,
      `AUTO_ATTACK_CHAMPION`,
      `DUELING`,
    ],
    utilityTags: [`DASH`, `REVEAL`, `SLOW`, `KNOCK_UP`, `ALLY_FOLLOW_UP`],
    riskTags: [
      `POSITIONING_RELIANT`,
      `HIGH_EXECUTION`,
      `OATHSWORN_RELIANT`,
      `CC_VULNERABLE`,
    ],
    strengths: [
      `MOBILITY`,
      `OBJECTIVE_CONTROL`,
      `LANE_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
    ],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `SLOW`,
      `BURST_DAMAGE`,
      `LOW_RANGE_CHAMPION`,
    ],
  },
  // KARMA
  {
    key: `karma`,
    name: `Karma`,
    title: `The Enlightened One`,
    titleVi: `Kẻ Được Khai Sáng`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ENCHANTER`],
    playstyleTags: [
      `POKE`,
      `UTILITY`,
      `TEAMFIGHT`,
      `SHIELDING`,
      `ZONE_CONTROL`,
    ],
    utilityTags: [`SHIELD`, `SPEED_UP`, `SLOW`, `ROOT`, `REVEAL`],
    riskTags: [`SKILLSHOT_RELIANT`, `POSITIONING_RELIANT`, `MANA_RELIANT`],
    strengths: [
      `POKE`,
      `TEAM_SUPPORT`,
      `SHIELDING`,
      `CROWD_CONTROL`,
      `TEAMFIGHT`,
    ],
    weaknesses: [`DIVE`, `BURST_DAMAGE`, `LONG_RANGE_CHAMPION`],
  },
  // KASSADIN
  {
    key: `kassadin`,
    name: `Kassadin`,
    title: `The Void Walker`,
    titleVi: `Lữ Khách Hư Không`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `MOBILITY`, `SCALING`, `ANTI_MAGE`],
    utilityTags: [`DASH`, `SHIELD`, `SILENCE`, `SLOW`],
    riskTags: [`WEAK_EARLY_GAME`, `MANA_RELIANT`, `MELEE_RANGE`],
    strengths: [
      `MAGIC_DAMAGE`,
      `MOBILITY`,
      `SCALING_DAMAGE`,
      `BURST_DAMAGE`,
      `ANTI_MAGIC`,
    ],
    weaknesses: [
      `EARLY_GAME_PRESSURE`,
      `PHYSICAL_DAMAGE`,
      `POINT_AND_CLICK_CC`,
    ],
  },
  // KATARINA
  {
    key: `katarina`,
    name: `Katarina`,
    title: `The Sinister Blade`,
    titleVi: `Ác Kiếm`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `NONE`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `MOBILITY`, `SNOWBALL`, `RESET_CHAMPION`],
    utilityTags: [`DASH`, `ANTI_HEAL`, `SPEED_UP`],
    riskTags: [`HIGH_EXECUTION`, `RESET_RELIANT`, `CC_VULNERABLE`],
    strengths: [`BURST_DAMAGE`, `MOBILITY`, `SNOWBALL`, `TEAMFIGHT_CLEANUP`],
    weaknesses: [`POINT_AND_CLICK_CC`, `LOCKDOWN_ZONE`, `EARLY_GAME_PRESSURE`],
  },
  // KAYLE
  {
    key: `kayle`,
    name: `Kayle`,
    title: `The Righteous`,
    titleVi: `Thiên Thần Phán Quyết`,
    roles: [GameRole.TOP, GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `MAGE`],
    playstyleTags: [`SCALING`, `DPS`, `ON_HIT_CHAMPION`, `HYPERCARRY`],
    utilityTags: [
      `HEAL`,
      `SPEED_UP`,
      `SLOW`,
      `INVULNERABILITY`,
      `RESISTANCE_REDUCTION`,
    ],
    riskTags: [`WEAK_EARLY_GAME`, `POSITIONING_RELIANT`, `SCALING_RELIANT`],
    strengths: [
      `SCALING_DAMAGE`,
      `MAGIC_DAMAGE`,
      `TEAMFIGHT`,
      `INVULNERABILITY`,
      `DPS`,
    ],
    weaknesses: [`EARLY_GAME_PRESSURE`, `DIVE`, `POINT_AND_CLICK_CC`],
  },
  // KAYN
  {
    key: `kayn`,
    name: `Kayn`,
    title: `The Shadow Reaper`,
    titleVi: `Tử Thần Bóng Tối`,
    roles: [GameRole.JUNGLE],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `NONE`,
    classTags: [`ASSASSIN`, `FIGHTER`],
    playstyleTags: [`MOBILITY`, `DIVE`, `FORM_CHANGE`, `SKIRMISH`, `SNOWBALL`],
    utilityTags: [
      `DASH`,
      `SPEED_UP`,
      `SLOW`,
      `KNOCK_UP`,
      `UNTARGETABLE`,
      `TERRAIN_WALK`,
    ],
    riskTags: [`FORM_RELIANT`, `HIGH_EXECUTION`, `CC_VULNERABLE`],
    strengths: [
      `MOBILITY`,
      `JUNGLE_CLEAR`,
      `DIVE`,
      `SUSTAIN`,
      `PERCENT_HEALTH_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `ANTI_HEAL`, `EARLY_GAME_PRESSURE`],
  },
  // KENNEN
  {
    key: `kennen`,
    name: `Kennen`,
    title: `The Heart of the Tempest`,
    titleVi: `Trái Tim Sấm Sét`,
    roles: [GameRole.TOP, GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `ENERGY`,
    classTags: [`MAGE`],
    playstyleTags: [`POKE`, `TEAMFIGHT`, `ZONE_CONTROL`, `ENGAGE`],
    utilityTags: [`STUN`, `SPEED_UP`, `DAMAGE_REDUCTION`, `AREA_DAMAGE`],
    riskTags: [`ENERGY_RELIANT`, `ULTIMATE_RELIANT`, `POSITIONING_RELIANT`],
    strengths: [
      `MAGIC_DAMAGE`,
      `TEAMFIGHT`,
      `AREA_DAMAGE`,
      `CROWD_CONTROL`,
      `ENGAGE`,
    ],
    weaknesses: [`LONG_RANGE_POKE`, `DISENGAGE`, `BURST_DAMAGE`],
  },
];

export async function seedChampions(prisma: PrismaClient) {
  for (const championSeed of championSeeds) {
    const champion = await prisma.champion.upsert({
      where: {
        key: championSeed.key,
      },
      update: {
        name: championSeed.name,
        title: championSeed.title ?? null,
        titleVi: championSeed.titleVi ?? null,
        roles: championSeed.roles,
        damageType: championSeed.damageType,
        rangeType: championSeed.rangeType,
        difficulty: championSeed.difficulty,
        resourceType: championSeed.resourceType,
        classTags: championSeed.classTags ?? [],
        playstyleTags: championSeed.playstyleTags ?? [],
        utilityTags: championSeed.utilityTags ?? [],
        riskTags: championSeed.riskTags ?? [],
        strengths: championSeed.strengths ?? [],
        weaknesses: championSeed.weaknesses ?? [],
        deletedAt: null,
        archivedAt: null,
      },
      create: championSeed,
    });

    console.log(`Seeded champion: ${champion.name}`);
  }

  console.log(`SEEDED CHAMPIONS`);
}
