import { Prisma, PrismaClient } from './../../src/generated/prisma/client.js';

type ChampionPatchStatSeed = {
  championKey: string;
  baseHealth?: number | null;
  baseArmor?: number | null;
  baseResource?: number | null;
  baseMagicResist?: number | null;
  baseAttackDamage?: number | null;
  baseAbilityPower?: number | null;
  attackSpeed?: number | null;
  moveSpeed?: number | null;
  healthGrowth?: number | null;
  resourceGrowth?: number | null;
  armorGrowth?: number | null;
  magicResistGrowth?: number | null;
  attackDamageGrowth?: number | null;
  attackSpeedGrowth?: number | null;
  scalingProfile?: Prisma.InputJsonValue | null;
  laneProfile?: Prisma.InputJsonValue | null;
  teamProfile?: Prisma.InputJsonValue | null;
  metaScore?: number | null;
};

const championPatchStatSeeds: ChampionPatchStatSeed[] = [
  // AATROX
  {
    championKey: `aatrox`,

    baseHealth: 630,
    baseResource: null,
    baseArmor: 46,
    baseMagicResist: 40,
    baseAttackDamage: 62,
    baseAbilityPower: 0,
    attackSpeed: 0.73,
    moveSpeed: 355,

    healthGrowth: 136,
    resourceGrowth: null,
    armorGrowth: 4,
    magicResistGrowth: 2,
    attackDamageGrowth: 5,
    attackSpeedGrowth: 0.007857,

    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 6,
          armor: 46,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 62,
          attackSpeed: 0.73,
        },
        {
          level: 2,
          health: 766,
          healthRegenPer5s: 7,
          armor: 50,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 67,
          attackSpeed: 0.74,
        },
        {
          level: 3,
          health: 902,
          healthRegenPer5s: 8,
          armor: 54,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 72,
          attackSpeed: 0.75,
        },
        {
          level: 4,
          health: 1038,
          healthRegenPer5s: 9,
          armor: 58,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 77,
          attackSpeed: 0.75,
        },
        {
          level: 5,
          health: 1174,
          healthRegenPer5s: 10,
          armor: 62,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 82,
          attackSpeed: 0.76,
        },
        {
          level: 6,
          health: 1310,
          healthRegenPer5s: 11,
          armor: 66,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 87,
          attackSpeed: 0.77,
        },
        {
          level: 7,
          health: 1446,
          healthRegenPer5s: 12,
          armor: 70,
          magicResist: 52,
          moveSpeed: 355,
          attackDamage: 92,
          attackSpeed: 0.78,
        },
        {
          level: 8,
          health: 1582,
          healthRegenPer5s: 13,
          armor: 74,
          magicResist: 54,
          moveSpeed: 355,
          attackDamage: 97,
          attackSpeed: 0.79,
        },
        {
          level: 9,
          health: 1718,
          healthRegenPer5s: 14,
          armor: 78,
          magicResist: 56,
          moveSpeed: 355,
          attackDamage: 102,
          attackSpeed: 0.79,
        },
        {
          level: 10,
          health: 1854,
          healthRegenPer5s: 15,
          armor: 82,
          magicResist: 58,
          moveSpeed: 355,
          attackDamage: 107,
          attackSpeed: 0.8,
        },
        {
          level: 11,
          health: 1990,
          healthRegenPer5s: 16,
          armor: 86,
          magicResist: 60,
          moveSpeed: 355,
          attackDamage: 112,
          attackSpeed: 0.81,
        },
        {
          level: 12,
          health: 2126,
          healthRegenPer5s: 17,
          armor: 90,
          magicResist: 62,
          moveSpeed: 355,
          attackDamage: 117,
          attackSpeed: 0.82,
        },
        {
          level: 13,
          health: 2262,
          healthRegenPer5s: 18,
          armor: 94,
          magicResist: 64,
          moveSpeed: 355,
          attackDamage: 122,
          attackSpeed: 0.82,
        },
        {
          level: 14,
          health: 2398,
          healthRegenPer5s: 19,
          armor: 98,
          magicResist: 66,
          moveSpeed: 355,
          attackDamage: 127,
          attackSpeed: 0.83,
        },
        {
          level: 15,
          health: 2534,
          healthRegenPer5s: 20,
          armor: 102,
          magicResist: 68,
          moveSpeed: 355,
          attackDamage: 132,
          attackSpeed: 0.84,
        },
      ],
    },

    laneProfile: {
      preferredRoles: [`TOP`],
      tradingPattern: `skillshot_combo`,
      sustainLevel: `high`,
      allInThreat: `high`,
      waveClear: `medium`,
      mobility: `medium`,
    },

    teamProfile: {
      provides: [`FRONTLINE`, `AREA_DAMAGE`, `KNOCK_UP`, `SUSTAIN`],
      needs: [`ENGAGE_SETUP`, `ANTI_HEAL_PROTECTION`],
      weakAgainst: [`ANTI_HEAL`, `KITE`, `HIGH_MOBILITY`, `POINT_AND_CLICK_CC`],
    },
  },

  // AHRI
  {
    championKey: `ahri`,
    baseHealth: 630,
    baseResource: 435,
    baseArmor: 34,
    baseMagicResist: 36,
    baseAttackDamage: 52,
    baseAbilityPower: 0,
    attackSpeed: 0.75,
    moveSpeed: 355,
    healthGrowth: 120,
    resourceGrowth: 37,
    armorGrowth: 4,
    magicResistGrowth: 1,
    attackDamageGrowth: 3,
    attackSpeedGrowth: 0,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 8,
          mana: 435,
          manaRegenPer5s: 18,
          armor: 34,
          magicResist: 36,
          moveSpeed: 355,
          attackDamage: 52,
          attackSpeed: 0.75,
        },
        {
          level: 2,
          health: 750,
          healthRegenPer5s: 9,
          mana: 472,
          manaRegenPer5s: 19,
          armor: 38,
          magicResist: 37,
          moveSpeed: 355,
          attackDamage: 55,
          attackSpeed: 0.75,
        },
        {
          level: 3,
          health: 870,
          healthRegenPer5s: 10,
          mana: 509,
          manaRegenPer5s: 20,
          armor: 42,
          magicResist: 38,
          moveSpeed: 355,
          attackDamage: 58,
          attackSpeed: 0.75,
        },
        {
          level: 4,
          health: 990,
          healthRegenPer5s: 11,
          mana: 546,
          manaRegenPer5s: 21,
          armor: 46,
          magicResist: 39,
          moveSpeed: 355,
          attackDamage: 61,
          attackSpeed: 0.75,
        },
        {
          level: 5,
          health: 1110,
          healthRegenPer5s: 12,
          mana: 583,
          manaRegenPer5s: 22,
          armor: 50,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 64,
          attackSpeed: 0.75,
        },
        {
          level: 6,
          health: 1230,
          healthRegenPer5s: 13,
          mana: 620,
          manaRegenPer5s: 23,
          armor: 54,
          magicResist: 41,
          moveSpeed: 355,
          attackDamage: 67,
          attackSpeed: 0.75,
        },
        {
          level: 7,
          health: 1350,
          healthRegenPer5s: 14,
          mana: 657,
          manaRegenPer5s: 24,
          armor: 58,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 70,
          attackSpeed: 0.75,
        },
        {
          level: 8,
          health: 1470,
          healthRegenPer5s: 15,
          mana: 694,
          manaRegenPer5s: 25,
          armor: 62,
          magicResist: 43,
          moveSpeed: 355,
          attackDamage: 73,
          attackSpeed: 0.75,
        },
        {
          level: 9,
          health: 1590,
          healthRegenPer5s: 16,
          mana: 731,
          manaRegenPer5s: 26,
          armor: 66,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 76,
          attackSpeed: 0.75,
        },
        {
          level: 10,
          health: 1710,
          healthRegenPer5s: 17,
          mana: 768,
          manaRegenPer5s: 27,
          armor: 70,
          magicResist: 45,
          moveSpeed: 355,
          attackDamage: 79,
          attackSpeed: 0.75,
        },
        {
          level: 11,
          health: 1830,
          healthRegenPer5s: 18,
          mana: 805,
          manaRegenPer5s: 28,
          armor: 74,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 82,
          attackSpeed: 0.75,
        },
        {
          level: 12,
          health: 1950,
          healthRegenPer5s: 19,
          mana: 842,
          manaRegenPer5s: 29,
          armor: 78,
          magicResist: 47,
          moveSpeed: 355,
          attackDamage: 85,
          attackSpeed: 0.75,
        },
        {
          level: 13,
          health: 2070,
          healthRegenPer5s: 20,
          mana: 879,
          manaRegenPer5s: 30,
          armor: 82,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 88,
          attackSpeed: 0.75,
        },
        {
          level: 14,
          health: 2190,
          healthRegenPer5s: 21,
          mana: 916,
          manaRegenPer5s: 31,
          armor: 86,
          magicResist: 49,
          moveSpeed: 355,
          attackDamage: 91,
          attackSpeed: 0.75,
        },
        {
          level: 15,
          health: 2310,
          healthRegenPer5s: 22,
          mana: 953,
          manaRegenPer5s: 32,
          armor: 90,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 94,
          attackSpeed: 0.75,
        },
      ],
    },
    laneProfile: {
      lanePressure: `MEDIUM`,
      roamThreat: `HIGH`,
      tradePattern: `SHORT_TRADES_AND_PICK_SETUP`,
      notes: `Ranged magic mid laner with charm pick threat, mobility, sustain from passive, and strong roam/skirmish potential after level 5.`,
    },
    teamProfile: {
      teamfightRole: `MOBILE_PICK_MAGE`,
      pickPotential: `HIGH`,
      mobility: `HIGH`,
      utility: [`CHARM`, `DASH`, `SUSTAIN`],
    },
    metaScore: null,
  },

  // AKSHAN
  {
    championKey: `akshan`,
    baseHealth: 630,
    baseResource: 390,
    baseArmor: 35,
    baseMagicResist: 30,
    baseAttackDamage: 52,
    baseAbilityPower: 0,
    attackSpeed: 0.7,
    moveSpeed: 340,
    healthGrowth: 128,
    resourceGrowth: 37,
    armorGrowth: 5,
    magicResistGrowth: 1,
    attackDamageGrowth: 5,
    attackSpeedGrowth: 0.00357,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 9,
          mana: 390,
          manaRegenPer5s: 15,
          armor: 35,
          magicResist: 30,
          moveSpeed: 340,
          attackDamage: 52,
          attackSpeed: 0.7,
        },
        {
          level: 2,
          health: 758,
          healthRegenPer5s: 10,
          mana: 427,
          manaRegenPer5s: 16,
          armor: 40,
          magicResist: 31,
          moveSpeed: 340,
          attackDamage: 57,
          attackSpeed: 0.7,
        },
        {
          level: 3,
          health: 886,
          healthRegenPer5s: 11,
          mana: 464,
          manaRegenPer5s: 17,
          armor: 45,
          magicResist: 32,
          moveSpeed: 340,
          attackDamage: 62,
          attackSpeed: 0.71,
        },
        {
          level: 4,
          health: 1014,
          healthRegenPer5s: 12,
          mana: 501,
          manaRegenPer5s: 18,
          armor: 50,
          magicResist: 33,
          moveSpeed: 340,
          attackDamage: 67,
          attackSpeed: 0.71,
        },
        {
          level: 5,
          health: 1142,
          healthRegenPer5s: 13,
          mana: 538,
          manaRegenPer5s: 19,
          armor: 55,
          magicResist: 34,
          moveSpeed: 340,
          attackDamage: 72,
          attackSpeed: 0.71,
        },
        {
          level: 6,
          health: 1270,
          healthRegenPer5s: 14,
          mana: 575,
          manaRegenPer5s: 20,
          armor: 60,
          magicResist: 35,
          moveSpeed: 340,
          attackDamage: 77,
          attackSpeed: 0.72,
        },
        {
          level: 7,
          health: 1398,
          healthRegenPer5s: 15,
          mana: 612,
          manaRegenPer5s: 21,
          armor: 65,
          magicResist: 36,
          moveSpeed: 340,
          attackDamage: 82,
          attackSpeed: 0.72,
        },
        {
          level: 8,
          health: 1526,
          healthRegenPer5s: 16,
          mana: 649,
          manaRegenPer5s: 22,
          armor: 70,
          magicResist: 37,
          moveSpeed: 340,
          attackDamage: 87,
          attackSpeed: 0.73,
        },
        {
          level: 9,
          health: 1654,
          healthRegenPer5s: 17,
          mana: 686,
          manaRegenPer5s: 23,
          armor: 75,
          magicResist: 38,
          moveSpeed: 340,
          attackDamage: 92,
          attackSpeed: 0.73,
        },
        {
          level: 10,
          health: 1782,
          healthRegenPer5s: 18,
          mana: 723,
          manaRegenPer5s: 24,
          armor: 80,
          magicResist: 39,
          moveSpeed: 340,
          attackDamage: 97,
          attackSpeed: 0.73,
        },
        {
          level: 11,
          health: 1910,
          healthRegenPer5s: 19,
          mana: 760,
          manaRegenPer5s: 25,
          armor: 85,
          magicResist: 40,
          moveSpeed: 340,
          attackDamage: 102,
          attackSpeed: 0.74,
        },
        {
          level: 12,
          health: 2038,
          healthRegenPer5s: 20,
          mana: 797,
          manaRegenPer5s: 26,
          armor: 90,
          magicResist: 41,
          moveSpeed: 340,
          attackDamage: 107,
          attackSpeed: 0.74,
        },
        {
          level: 13,
          health: 2166,
          healthRegenPer5s: 21,
          mana: 834,
          manaRegenPer5s: 27,
          armor: 95,
          magicResist: 42,
          moveSpeed: 340,
          attackDamage: 112,
          attackSpeed: 0.74,
        },
        {
          level: 14,
          health: 2294,
          healthRegenPer5s: 22,
          mana: 871,
          manaRegenPer5s: 28,
          armor: 100,
          magicResist: 43,
          moveSpeed: 340,
          attackDamage: 117,
          attackSpeed: 0.75,
        },
        {
          level: 15,
          health: 2422,
          healthRegenPer5s: 23,
          mana: 908,
          manaRegenPer5s: 29,
          armor: 105,
          magicResist: 44,
          moveSpeed: 340,
          attackDamage: 122,
          attackSpeed: 0.75,
        },
      ],
    },
    laneProfile: {
      lanePressure: `MEDIUM`,
      roamThreat: `HIGH`,
      tradePattern: `SHORT_TRADES_AND_ROAMS`,
      notes: `Ranged AD mid/marksman with strong roaming, reveal, mobility, and pick potential.`,
    },
    teamProfile: {
      teamfightRole: `BACKLINE_SKIRMISHER`,
      pickPotential: `HIGH`,
      mobility: `HIGH`,
      utility: [`REVIVE`, `REVEAL`, `EXECUTE`],
    },
    metaScore: null,
  },
];

export async function seedChampionPatchStats(
  prisma: PrismaClient,
  patchId: string,
) {
  for (const championPatchStatSeed of championPatchStatSeeds) {
    const champion = await prisma.champion.findUnique({
      where: {
        key: championPatchStatSeed.championKey,
      },
    });

    if (!champion || champion.deletedAt) {
      throw new Error(
        `Champion not found or deleted: ${championPatchStatSeed.championKey}`,
      );
    }

    await prisma.championPatchStat.upsert({
      where: {
        championId_patchId: {
          championId: champion.id,
          patchId,
        },
      },
      update: {
        baseHealth: championPatchStatSeed.baseHealth ?? null,
        baseResource: championPatchStatSeed.baseResource ?? null,
        baseArmor: championPatchStatSeed.baseArmor ?? null,
        baseMagicResist: championPatchStatSeed.baseMagicResist ?? null,
        baseAttackDamage: championPatchStatSeed.baseAttackDamage ?? null,
        baseAbilityPower: championPatchStatSeed.baseAbilityPower ?? null,
        attackSpeed: championPatchStatSeed.attackSpeed ?? null,
        moveSpeed: championPatchStatSeed.moveSpeed ?? null,
        healthGrowth: championPatchStatSeed.healthGrowth ?? null,
        resourceGrowth: championPatchStatSeed.resourceGrowth ?? null,
        armorGrowth: championPatchStatSeed.armorGrowth ?? null,
        magicResistGrowth: championPatchStatSeed.magicResistGrowth ?? null,
        attackDamageGrowth: championPatchStatSeed.attackDamageGrowth ?? null,
        attackSpeedGrowth: championPatchStatSeed.attackSpeedGrowth ?? null,
        scalingProfile: championPatchStatSeed.scalingProfile ?? Prisma.DbNull,
        laneProfile: championPatchStatSeed.laneProfile ?? Prisma.DbNull,
        teamProfile: championPatchStatSeed.teamProfile ?? Prisma.DbNull,
        metaScore: championPatchStatSeed.metaScore ?? null,
        deletedAt: null,
      },
      create: {
        championId: champion.id,
        patchId,
        baseHealth: championPatchStatSeed.baseHealth ?? null,
        baseResource: championPatchStatSeed.baseResource ?? null,
        baseArmor: championPatchStatSeed.baseArmor ?? null,
        baseMagicResist: championPatchStatSeed.baseMagicResist ?? null,
        baseAttackDamage: championPatchStatSeed.baseAttackDamage ?? null,
        baseAbilityPower: championPatchStatSeed.baseAbilityPower ?? null,
        attackSpeed: championPatchStatSeed.attackSpeed ?? null,
        moveSpeed: championPatchStatSeed.moveSpeed ?? null,
        healthGrowth: championPatchStatSeed.healthGrowth ?? null,
        resourceGrowth: championPatchStatSeed.resourceGrowth ?? null,
        armorGrowth: championPatchStatSeed.armorGrowth ?? null,
        magicResistGrowth: championPatchStatSeed.magicResistGrowth ?? null,
        attackDamageGrowth: championPatchStatSeed.attackDamageGrowth ?? null,
        attackSpeedGrowth: championPatchStatSeed.attackSpeedGrowth ?? null,
        scalingProfile: championPatchStatSeed.scalingProfile ?? Prisma.DbNull,
        laneProfile: championPatchStatSeed.laneProfile ?? Prisma.DbNull,
        teamProfile: championPatchStatSeed.teamProfile ?? Prisma.DbNull,
        metaScore: championPatchStatSeed.metaScore ?? null,
      },
    });

    console.log(`Seeded champion ${champion.name} for patch ${patchId}`);
  }

  console.log(`SEEDED CHAMPIONS PATCH STATS`);
}
