import { GameRole, PrismaClient } from '../../src/generated/prisma/client.js';

type ChampionSeed = {
  key: string;
  name: string;
  title?: string | null;
  titleVi?: string | null;
  roles: GameRole[];
  damageType: string;
  rangeType: string;
  difficulty: string;
  resourceType: string;
  classTags: string[];
  playstyleTags: string[];
  utilityTags: string[];
  riskTags: string[];
  strengths: string[];
  weaknesses: string[];
};

const championSeeds: ChampionSeed[] = [
  // AATROX
  {
    key: `aatrox`,
    name: `Aatrox`,
    title: `The Darkin Blade`,
    titleVi: `Quỷ Kiếm Darkin`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `NONE`,
    classTags: [`FIGHTER`, `BRUISER`],
    playstyleTags: [`SUSTAIN`, `DRAIN_TANK`, `TEAMFIGHT`],
    utilityTags: [`KNOCK_UP`, `SLOW`, `DASH`, `FEAR`],
    riskTags: [`SKILLSHOT_RELIANT`, `HEALING_RELIANT`, `KITEABLE`],
    strengths: [`SUSTAIN`, `EXTENDED_FIGHT`, `TEAMFIGHT`, `AREA_DAMAGE`],
    weaknesses: [`ANTI_HEAL`, `HIGH_MOBILITY`, `KITE`, `POINT_AND_CLICK_CC`],
  },
  // AHRI
  {
    key: `ahri`,
    name: `Ahri`,
    title: `The Nine-Tailed Fox`,
    titleVi: `Hồ Ly Chín Đuôi`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ASSASSIN`],
    playstyleTags: [`BURST`, `PICK`, `MOBILITY`],
    utilityTags: [`CHARM`, `DASH`],
    riskTags: [`SKILLSHOT_RELIANT`, `SQUISHY`],
    strengths: [`PICK_POTENTIAL`, `MOBILITY`, `BURST_DAMAGE`],
    weaknesses: [`WEAK_WHEN_BEHIND`, `SKILLSHOT_RELIANT`],
  },
  // AKALI
  {
    key: `akali`,
    name: `Akali`,
    title: `The Rogue Assassin`,
    titleVi: `Sát Thủ Đơn Độc`,
    roles: [GameRole.MID, GameRole.TOP],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `ENERGY`,
    classTags: [`ASSASSIN`],
    playstyleTags: [`BURST`, `MOBILITY`, `PICK`],
    utilityTags: [`DASH`, `STEALTH`, `SLOW`, `EXECUTE`],
    riskTags: [`HIGH_EXECUTION`, `CC_VULNERABLE`, `ENERGY_RELIANT`],
    strengths: [
      `BURST_DAMAGE`,
      `MOBILITY`,
      `KILL_PRESSURE`,
      `OUTPLAY_POTENTIAL`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `REVEAL`, `HARD_TO_PLAY`],
  },
  // AKSHAN
  {
    key: `akshan`,
    name: `Akshan`,
    title: `The Rogue Sentinel`,
    titleVi: `Vệ Binh Nổi Loạn`,
    roles: [GameRole.MID, GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `ASSASSIN`],
    playstyleTags: [`MOBILITY`, `ROAMING`, `PICK`, `ON_HIT_CHAMPION`],
    utilityTags: [`DASH`, `STEALTH`, `REVEAL`, `REVIVE`, `EXECUTE`],
    riskTags: [`HIGH_EXECUTION`, `CC_VULNERABLE`, `SQUISHY`],
    strengths: [`ROAMING`, `PICK_POTENTIAL`, `MOBILITY`, `KILL_PRESSURE`],
    weaknesses: [`POINT_AND_CLICK_CC`, `LOW_DURABILITY_TEAM`, `REVEAL`],
  },
  // ALISTAR
  {
    key: `alistar`,
    name: `Alistar`,
    title: `The Minotaur`,
    titleVi: `Quái Vật Đầu Bò`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `SUPPORT`],
    playstyleTags: [`ENGAGE`, `PEEL`, `TEAMFIGHT`],
    utilityTags: [`KNOCK_UP`, `KNOCK_BACK`, `STUN`, `HEALING`],
    riskTags: [`LOW_RANGE_CHAMPION`, `ABILITY_RELIANT_CHAMPION`],
    strengths: [`ENGAGE`, `PEEL`, `FRONTLINE`, `DAMAGE_REDUCTION`],
    weaknesses: [`POKE_COMPOSITION`, `DISENGAGE`, `LOW_RANGE_CHAMPION`],
  },
  // AMBESSA
  {
    key: `ambessa`,
    name: `Ambessa`,
    title: `The Matriarch of War`,
    titleVi: `Nữ Tướng Chiến Tranh`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `ENERGY`,
    classTags: [`FIGHTER`, `BRUISER`],
    playstyleTags: [`MOBILITY`, `DRAIN_TANK`, `EXTENDED_FIGHT_CHAMPION`],
    utilityTags: [`DASH`, `SHIELD`, `SLOW`, `STUN`],
    riskTags: [`HIGH_EXECUTION`, `ENERGY_RELIANT`, `KITEABLE`],
    strengths: [`MOBILITY`, `SUSTAIN`, `PERCENT_HEALTH_DAMAGE`, `DIVE`],
    weaknesses: [`POINT_AND_CLICK_CC`, `ANTI_HEAL`, `KITE`, `HARD_TO_PLAY`],
  },
  // AMUMU
  {
    key: `amumu`,
    name: `Amumu`,
    title: `The Sad Mummy`,
    titleVi: `Xác Ướp U Sầu`,
    roles: [GameRole.JUNGLE, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `MAGE`],
    playstyleTags: [`ENGAGE`, `TEAMFIGHT`, `AREA_DAMAGE`],
    utilityTags: [`STUN`, `ROOT`, `PULL`, `SLOW`],
    riskTags: [`SKILLSHOT_RELIANT`, `LOW_MOBILITY`, `KITEABLE`],
    strengths: [`TEAMFIGHT`, `CROWD_CONTROL`, `AREA_DAMAGE`, `ANTI_TANK`],
    weaknesses: [`KITE`, `DISENGAGE`, `HIGH_MOBILITY`],
  },
  // ANNIE
  {
    key: `annie`,
    name: `Annie`,
    title: `The Dark Child`,
    titleVi: `Đứa Trẻ Bóng Tối`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`BURST`, `PICK`, `TEAMFIGHT`],
    utilityTags: [`STUN`, `SHIELD`, `SPEED_UP`, `KNOCK_UP`],
    riskTags: [`LOW_MOBILITY`, `SHORT_RANGE_MAGE`, `FLASH_RELIANT`],
    strengths: [`BURST_DAMAGE`, `PICK_POTENTIAL`, `TEAMFIGHT`, `CROWD_CONTROL`],
    weaknesses: [`POKE_COMPOSITION`, `HIGH_MOBILITY`, `LONG_RANGE_CHAMPION`],
  },
  // ASHE
  {
    key: `ashe`,
    name: `Ashe`,
    title: `The Frost Archer`,
    titleVi: `Cung Băng`,
    roles: [GameRole.ADC, GameRole.SUPPORT],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`POKE`, `KITE`, `PICK`, `AUTO_ATTACK_CHAMPION`],
    utilityTags: [`SLOW`, `STUN`, `REVEAL`],
    riskTags: [`LOW_MOBILITY`, `SQUISHY`, `POSITIONING_RELIANT`],
    strengths: [`KITE`, `PICK_POTENTIAL`, `VISION_CONTROL`, `UTILITY_MARKSMAN`],
    weaknesses: [`DIVE`, `ASSASSIN`, `HIGH_MOBILITY`],
  },
  // AURELION SOL
  {
    key: `aurelion-sol`,
    name: `Aurelion Sol`,
    title: `The Star Forger`,
    titleVi: `Ác Long Thượng Giới`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`SCALING`, `ZONE_CONTROL`, `TEAMFIGHT`],
    utilityTags: [`STUN`, `KNOCK_UP`, `SLOW`, `PULL`],
    riskTags: [
      `WEAK_EARLY_GAME`,
      `POSITIONING_RELIANT`,
      `INTERRUPT_VULNERABLE`,
    ],
    strengths: [`SCALING_GAME`, `AREA_DAMAGE`, `TEAMFIGHT`, `ZONE_CONTROL`],
    weaknesses: [`EARLY_GAME_PRESSURE`, `ASSASSIN`, `POINT_AND_CLICK_CC`],
  },
  // AURORA
  {
    key: `aurora`,
    name: `Aurora`,
    title: `The Witch Between Worlds`,
    titleVi: `Phù Thủy Giữa Hai Thế Giới`,
    roles: [GameRole.MID, GameRole.TOP],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`MOBILITY`, `SKIRMISH`, `POKE`, `ZONE_CONTROL`],
    utilityTags: [`SLOW`, `STEALTH`, `DASH`],
    riskTags: [`POSITIONING_RELIANT`, `SQUISHY`, `HIGH_EXECUTION`],
    strengths: [
      `MOBILITY`,
      `ZONE_CONTROL`,
      `PERCENT_HEALTH_DAMAGE`,
      `SKIRMISH`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `BURST_DAMAGE`, `LONG_RANGE_CHAMPION`],
  },
  // BARD
  {
    key: `bard`,
    name: `Bard`,
    title: `The Wandering Caretaker`,
    titleVi: `Lữ Khách Tinh Linh`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `SUPPORT`],
    playstyleTags: [`ROAMING`, `PICK`, `ZONE_CONTROL`, `TEAM_SUPPORT`],
    utilityTags: [`SLOW`, `STUN`, `HEALING`, `STASIS`, `PORTAL`],
    riskTags: [`SKILLSHOT_RELIANT`, `HIGH_EXECUTION`, `POSITIONING_RELIANT`],
    strengths: [`ROAMING`, `PICK_POTENTIAL`, `ZONE_CONTROL`, `TEAM_SUPPORT`],
    weaknesses: [
      `LOW_DURABILITY_TEAM`,
      `HIGH_EXECUTION`,
      `POSITIONING_RELIANT`,
    ],
  },
  // BLITZCRANK
  {
    key: 'blitzcrank',
    name: 'Blitzcrank',
    title: 'The Great Steam Golem',
    titleVi: 'Người Máy Hơi Nước Vĩ Đại',
    roles: [GameRole.SUPPORT],
    damageType: 'MAGIC',
    rangeType: 'MELEE',
    difficulty: 'MEDIUM',
    resourceType: 'MANA',
    classTags: ['TANK', 'SUPPORT'],
    playstyleTags: ['PICK', 'ENGAGE', 'ROAMING'],
    utilityTags: ['PULL', 'KNOCK_UP', 'SILENCE', 'SPEED_UP', 'SHIELD'],
    riskTags: [
      'SKILLSHOT_RELIANT',
      'COOLDOWN_RELIANT',
      'PUNISHABLE_WHEN_MISSED',
    ],
    strengths: ['PICK_POTENTIAL', 'ENGAGE', 'ROAMING'],
    weaknesses: ['MISS_DEPENDENT', 'LOW_RANGE_CHAMPION', 'KITEABLE'],
  },
  // BRAND
  {
    key: `brand`,
    name: `Brand`,
    title: `The Burning Vengeance`,
    titleVi: `Ngọn Lửa Báo Thù`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`BURST`, `POKE`, `TEAMFIGHT`, `ZONE_CONTROL`],
    utilityTags: [`STUN`, `SLOW`],
    riskTags: [`SKILLSHOT_RELIANT`, `LOW_MOBILITY`, `SQUISHY`],
    strengths: [`AREA_DAMAGE`, `BURN_DAMAGE`, `TEAMFIGHT`, `POKE`],
    weaknesses: [`HIGH_MOBILITY`, `ASSASSIN`, `LONG_RANGE_CHAMPION`],
  },
  // BRAUM
  {
    key: `braum`,
    name: `Braum`,
    title: `The Heart of the Freljord`,
    titleVi: `Trái Tim của Freljord`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `SUPPORT`],
    playstyleTags: [`PEEL`, `TEAMFIGHT`, `TEAM_SUPPORT`],
    utilityTags: [`STUN`, `SLOW`, `KNOCK_UP`, `SHIELD`],
    riskTags: [`LOW_RANGE_CHAMPION`, `TEAM_DEPENDENT`, `LOW_DAMAGE`],
    strengths: [`PEEL`, `FRONTLINE`, `TEAM_SUPPORT`, `CROWD_CONTROL`],
    weaknesses: [`POKE_COMPOSITION`, `DISENGAGE`, `LOW_KILL_PRESSURE`],
  },
  // CAITLYN
  {
    key: `caitlyn`,
    name: `Caitlyn`,
    title: `The Sheriff of Piltover`,
    titleVi: `Cảnh Sát Trưởng Piltover`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`POKE`, `PICK`, `ZONE_CONTROL`, `AUTO_ATTACK_CHAMPION`],
    utilityTags: [`ROOT`, `SLOW`, `REVEAL`, `DASH`],
    riskTags: [`POSITIONING_RELIANT`, `SQUISHY`, `LOW_MOBILITY`],
    strengths: [
      `LONG_RANGE_POKE`,
      `LANE_PRESSURE`,
      `ZONE_CONTROL`,
      `PICK_POTENTIAL`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `POINT_AND_CLICK_CC`],
  },
  // CAMILLE
  {
    key: `camille`,
    name: `Camille`,
    title: `The Steel Shadow`,
    titleVi: `Bóng Thép`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `BRUISER`],
    playstyleTags: [`MOBILITY`, `PICK`, `SPLIT_PUSH`, `DIVE`],
    utilityTags: [`DASH`, `STUN`, `SLOW`, `SHIELD`],
    riskTags: [`HIGH_EXECUTION`, `COOLDOWN_RELIANT`, `CC_VULNERABLE`],
    strengths: [`MOBILITY`, `PICK_POTENTIAL`, `DIVE`, `SIDE_LANE`],
    weaknesses: [`POINT_AND_CLICK_CC`, `DISENGAGE`, `WEAK_WHEN_BEHIND`],
  },
  // YASUO
  {
    key: 'yasuo',
    name: 'Yasuo',
    title: 'The Unforgiven',
    titleVi: `Kẻ Bất Dung Thứ`,
    roles: [GameRole.MID],
    damageType: 'PHYSICAL',
    rangeType: 'MELEE',
    difficulty: 'HIGH',
    resourceType: 'FLOW',
    classTags: ['FIGHTER', 'SKIRMISHER'],
    playstyleTags: ['DPS', 'MOBILITY', 'SCALING'],
    utilityTags: ['KNOCK_UP', 'WIND_WALL'],
    riskTags: ['MELEE_MID', 'HIGH_EXECUTION', 'CC_VULNERABLE'],
    strengths: ['SCALING_DAMAGE', 'MOBILITY', 'TEAMFIGHT_FOLLOWUP'],
    weaknesses: ['HARD_TO_PLAY', 'WEAK_INTO_POINT_CLICK_CC'],
  },
  // VIKTOR
  {
    key: 'viktor',
    name: 'Viktor',
    title: 'The Machine Herald',
    titleVi: `Sứ Giả Máy Móc`,
    roles: [GameRole.MID],
    damageType: 'MAGIC',
    rangeType: 'RANGED',
    difficulty: 'MEDIUM',
    resourceType: 'MANA',
    classTags: ['MAGE', 'CONTROL_MAGE'],
    playstyleTags: ['SCALING', 'POKE', 'ZONE_CONTROL'],
    utilityTags: ['SLOW', 'ZONE_CONTROL'],
    riskTags: ['LOW_MOBILITY', 'SQUISHY'],
    strengths: ['WAVE_CLEAR', 'SCALING_DAMAGE', 'ZONE_CONTROL'],
    weaknesses: ['LOW_MOBILITY', 'VULNERABLE_TO_DIVE'],
  },
  // CORKI
  {
    key: `corki`,
    name: `Corki`,
    title: `The Daring Bombardier`,
    titleVi: `Phi Công Quả Cảm`,
    roles: [GameRole.MID, GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `MAGE`],
    playstyleTags: [`POKE`, `SCALING`, `MOBILITY`, `TEAMFIGHT`],
    utilityTags: [`DASH`, `REVEAL`],
    riskTags: [`MANA_HUNGRY_CHAMPION`, `POSITIONING_RELIANT`, `SQUISHY`],
    strengths: [`POKE`, `HYBRID_DAMAGE`, `AREA_DAMAGE`, `SCALING_DAMAGE`],
    weaknesses: [`DIVE`, `ASSASSIN`, `POINT_AND_CLICK_CC`],
  },
  // DARIUS
  {
    key: `darius`,
    name: `Darius`,
    title: `The Hand of Noxus`,
    titleVi: `Đại Tướng Noxus`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `BRUISER`],
    playstyleTags: [`EXTENDED_FIGHT_CHAMPION`, `DRAIN_TANK`, `TEAMFIGHT`],
    utilityTags: [`PULL`, `SLOW`, `EXECUTE`],
    riskTags: [`LOW_MOBILITY`, `KITEABLE`, `FLASH_RELIANT`],
    strengths: [`EXTENDED_FIGHT`, `SUSTAIN`, `EXECUTE`, `SNOWBALL`],
    weaknesses: [`KITE`, `HIGH_MOBILITY`, `DISENGAGE`],
  },
  // DIANA
  {
    key: `diana`,
    name: `Diana`,
    title: `Scorn of the Moon`,
    titleVi: `Vầng Trăng Ai Oán`,
    roles: [GameRole.MID, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ASSASSIN`, `FIGHTER`],
    playstyleTags: [`BURST`, `MOBILITY`, `DIVE`, `TEAMFIGHT`],
    utilityTags: [`DASH`, `SLOW`, `SHIELD`],
    riskTags: [`MELEE_MID`, `HIGH_EXECUTION`, `CC_VULNERABLE`],
    strengths: [`BURST_DAMAGE`, `MOBILITY`, `DIVE`, `TEAMFIGHT`],
    weaknesses: [`POINT_AND_CLICK_CC`, `DISENGAGE`, `WEAK_WHEN_BEHIND`],
  },
  // DR. MUNDO
  {
    key: `dr-mundo`,
    name: `Dr. Mundo`,
    title: `The Madman of Zaun`,
    titleVi: `Cuồng Nhân Xứ Zaun`,
    roles: [GameRole.TOP],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `HEALTH`,
    classTags: [`TANK`, `FIGHTER`],
    playstyleTags: [`DRAIN_TANK`, `EXTENDED_FIGHT_CHAMPION`, `SCALING`],
    utilityTags: [`SLOW`, `SPEED_UP`, `HEALING`],
    riskTags: [`KITEABLE`, `ANTI_HEAL_VULNERABLE`, `LOW_CC`],
    strengths: [`SUSTAIN`, `FRONTLINE`, `SCALING_HEALTH`, `ANTI_CC`],
    weaknesses: [`ANTI_HEAL`, `KITE`, `PERCENT_HEALTH_DAMAGE`],
  },
  // DRAVEN
  {
    key: `draven`,
    name: `Draven`,
    title: `The Glorious Executioner`,
    titleVi: `Đao Phủ Kiêu Hùng`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`SNOWBALL`, `AUTO_ATTACK_CHAMPION`, `HIGH_EXECUTION`],
    utilityTags: [`SLOW`, `KNOCK_BACK`, `MOVEMENT_SPEED`],
    riskTags: [`POSITIONING_RELIANT`, `TEAM_DEPENDENT`, `HIGH_EXECUTION`],
    strengths: [
      `LANE_PRESSURE`,
      `SNOWBALL`,
      `PHYSICAL_DAMAGE`,
      `AUTO_ATTACK_CHAMPION`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `DIVE`, `KITE`, `HARD_TO_PLAY`],
  },
  // EKKO
  {
    key: `ekko`,
    name: `Ekko`,
    title: `The Boy Who Shattered Time`,
    titleVi: `Cậu Bé Đảo Lộn Thời Gian`,
    roles: [GameRole.MID, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `MOBILITY`, `SKIRMISH`, `SCALING`],
    utilityTags: [`DASH`, `BLINK`, `SLOW`, `STUN`, `SHIELD`],
    riskTags: [`HIGH_EXECUTION`, `COOLDOWN_RELIANT`, `POSITIONING_RELIANT`],
    strengths: [
      `BURST_DAMAGE`,
      `MOBILITY`,
      `OUTPLAY_POTENTIAL`,
      `SCALING_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `LOCKDOWN_ZONE`, `EARLY_GAME_PRESSURE`],
  },
  // EVELYNN
  {
    key: `evelynn`,
    name: `Evelynn`,
    title: `Agony's Embrace`,
    titleVi: `Yêu Nữ Gai Góc`,
    roles: [GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `PICK`, `MOBILITY`],
    utilityTags: [`CAMOUFLAGE`, `CHARM`, `SLOW`, `MAGIC_RESIST_REDUCTION`],
    riskTags: [`HIGH_EXECUTION`, `POSITIONING_RELIANT`, `CC_VULNERABLE`],
    strengths: [
      `PICK_POTENTIAL`,
      `BURST_DAMAGE`,
      `MAGIC_DAMAGE`,
      `OUTPLAY_POTENTIAL`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `VISION_CONTROL`, `EARLY_GAME_PRESSURE`],
  },
  // EZREAL
  {
    key: `ezreal`,
    name: `Ezreal`,
    title: `The Prodigal Explorer`,
    titleVi: `Nhà Thám Hiểm Thiên Tài`,
    roles: [GameRole.ADC, GameRole.MID],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `MAGE`],
    playstyleTags: [
      `POKE`,
      `MOBILITY`,
      `SPELLBLADE_CHAMPION`,
      `ABILITY_RELIANT_CHAMPION`,
    ],
    utilityTags: [`BLINK`, `GLOBAL_RANGE`, `COOLDOWN_REDUCTION`],
    riskTags: [`SKILLSHOT_RELIANT`, `SQUISHY`, `MANA_HUNGRY_CHAMPION`],
    strengths: [`POKE`, `MOBILITY`, `HYBRID_DAMAGE`, `LONG_RANGE_POKE`],
    weaknesses: [`POINT_AND_CLICK_CC`, `DIVE`, `LOW_CC`, `SKILLSHOT_RELIANT`],
  },
  // FIDDLESTICKS
  {
    key: `fiddlesticks`,
    name: `Fiddlesticks`,
    title: `The Ancient Fear`,
    titleVi: `Nỗi Sợ Viễn Cổ`,
    roles: [GameRole.JUNGLE, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`BURST`, `ZONE_CONTROL`, `TEAMFIGHT`, `PICK`],
    utilityTags: [`FEAR`, `SLOW`, `SILENCE`, `BLINK`],
    riskTags: [`ULTIMATE_RELIANT_CHAMPION`, `CHANNEL`, `POSITIONING_RELIANT`],
    strengths: [`TEAMFIGHT`, `AREA_DAMAGE`, `CROWD_CONTROL`, `JUNGLE_CLEAR`],
    weaknesses: [
      `INTERRUPT_VULNERABLE`,
      `VISION_CONTROL`,
      `POINT_AND_CLICK_CC`,
    ],
  },
  // FIORA
  {
    key: `fiora`,
    name: `Fiora`,
    title: `The Grand Duelist`,
    titleVi: `Nữ Kiếm Sư Kiêu Hùng`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`SPLIT_PUSH`, `DUELIST`, `MOBILITY`, `SCALING`],
    utilityTags: [`DASH`, `SLOW`, `STUN`, `HEALING`],
    riskTags: [`HIGH_EXECUTION`, `POSITIONING_RELIANT`, `TEAM_DEPENDENT`],
    strengths: [
      `SPLIT_PUSH`,
      `TRUE_DAMAGE`,
      `DUELING`,
      `PERCENT_HEALTH_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `GROUPED_ENEMIES`, `HARD_TO_PLAY`],
  },
  // FIZZ
  {
    key: `fizz`,
    name: `Fizz`,
    title: `The Tidal Trickster`,
    titleVi: `Chú Cá Tinh Nghịch`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `MOBILITY`, `PICK`],
    utilityTags: [`DASH`, `BLINK`, `SLOW`, `KNOCK_UP`],
    riskTags: [`HIGH_EXECUTION`, `COOLDOWN_RELIANT`, `CC_VULNERABLE`],
    strengths: [`BURST_DAMAGE`, `MOBILITY`, `PICK_POTENTIAL`, `TOWER_DIVE`],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `EARLY_GAME_PRESSURE`,
      `HIGH_MAGIC_RESIST`,
    ],
  },
  // GALIO
  {
    key: `galio`,
    name: `Galio`,
    title: `The Colossus`,
    titleVi: `Vệ Thần Khổng Lồ`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`TANK`, `MAGE`],
    playstyleTags: [`TEAMFIGHT`, `ENGAGE`, `ROAMING`, `ZONE_CONTROL`],
    utilityTags: [`TAUNT`, `KNOCK_UP`, `SHIELD`, `DAMAGE_REDUCTION`],
    riskTags: [`COOLDOWN_RELIANT`, `LOW_MOBILITY`, `INTERRUPT_VULNERABLE`],
    strengths: [`TEAMFIGHT`, `ENGAGE`, `MAGIC_DAMAGE`, `TEAM_SUPPORT`],
    weaknesses: [`DISENGAGE`, `POKE_COMPOSITION`, `HIGH_MOBILITY`],
  },
  // GAREN
  {
    key: `garen`,
    name: `Garen`,
    title: `The Might of Demacia`,
    titleVi: `Sức Mạnh Demacia`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `NONE`,
    classTags: [`FIGHTER`, `TANK`],
    playstyleTags: [`BRUISER`, `SUSTAIN`, `SPLIT_PUSH`],
    utilityTags: [`SILENCE`, `SPEED_UP`, `SHIELD`, `DAMAGE_REDUCTION`],
    riskTags: [`LOW_MOBILITY`, `KITEABLE`, `COOLDOWN_RELIANT`],
    strengths: [`LANE_SURVIVAL`, `SUSTAIN`, `EXECUTE`, `ARMOR_SHRED`],
    weaknesses: [`KITE`, `DISENGAGE`, `LOW_RANGE_CHAMPION`],
  },
  // GNAR
  {
    key: `gnar`,
    name: `Gnar`,
    title: `The Missing Link`,
    titleVi: `Mắt Xích Thất Lạc`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `HYBRID`,
    difficulty: `HIGH`,
    resourceType: `RAGE`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`POKE`, `KITE`, `TEAMFIGHT`, `SPLIT_PUSH`],
    utilityTags: [`SLOW`, `STUN`, `KNOCK_BACK`, `DASH`],
    riskTags: [`TRANSFORMATION_RELIANT`, `HIGH_EXECUTION`, `TIMING_RELIANT`],
    strengths: [
      `LANE_PRESSURE`,
      `TEAMFIGHT`,
      `PERCENT_HEALTH_DAMAGE`,
      `ZONE_CONTROL`,
    ],
    weaknesses: [`RAGE_MANAGEMENT`, `POINT_AND_CLICK_CC`, `HARD_TO_PLAY`],
  },
  // GRAGAS
  {
    key: `gragas`,
    name: `Gragas`,
    title: `The Rabble Rouser`,
    titleVi: `Gã Bợm Rượu`,
    roles: [GameRole.JUNGLE, GameRole.TOP, GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`TANK`, `MAGE`, `FIGHTER`],
    playstyleTags: [`ENGAGE`, `BURST`, `ZONE_CONTROL`, `SUSTAIN`],
    utilityTags: [`SLOW`, `STUN`, `KNOCK_BACK`, `DAMAGE_REDUCTION`],
    riskTags: [`COOLDOWN_RELIANT`, `SKILLSHOT_RELIANT`, `POSITIONING_RELIANT`],
    strengths: [`ENGAGE`, `DISENGAGE`, `AREA_DAMAGE`, `PICK_POTENTIAL`],
    weaknesses: [`HIGH_MOBILITY`, `POINT_AND_CLICK_CC`, `LONG_RANGE_POKE`],
  },
  // GRAVES
  {
    key: `graves`,
    name: `Graves`,
    title: `The Outlaw`,
    titleVi: `Kẻ Ngoài Vòng Pháp Luật`,
    roles: [GameRole.JUNGLE],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `FIGHTER`],
    playstyleTags: [`BURST`, `SKIRMISH`, `KITE`],
    utilityTags: [`DASH`, `SLOW`, `VISION_DENIAL`, `KNOCK_BACK`],
    riskTags: [`POSITIONING_RELIANT`, `LOW_RANGE_CHAMPION`, `COOLDOWN_RELIANT`],
    strengths: [`JUNGLE_CLEAR`, `BURST_DAMAGE`, `DUELING`, `PHYSICAL_DAMAGE`],
    weaknesses: [`LONG_RANGE_CHAMPION`, `POINT_AND_CLICK_CC`, `LOW_CC`],
  },
  // GWEN
  {
    key: `gwen`,
    name: `Gwen`,
    title: `The Hallowed Seamstress`,
    titleVi: `Búp Bê Ước Nguyện`,
    roles: [GameRole.TOP, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`DPS`, `SCALING`, `SUSTAIN`, `DUELIST`],
    utilityTags: [`DASH`, `SLOW`, `UNTARGETABLE`, `BONUS_RESISTANCES`],
    riskTags: [`COOLDOWN_RELIANT`, `POSITIONING_RELIANT`, `CC_VULNERABLE`],
    strengths: [
      `SCALING_DAMAGE`,
      `PERCENT_HEALTH_DAMAGE`,
      `TRUE_DAMAGE`,
      `SUSTAIN_FIGHTER`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `EARLY_GAME_PRESSURE`, `KITE`],
  },
  // HECARIM
  {
    key: `hecarim`,
    name: `Hecarim`,
    title: `The Shadow of War`,
    titleVi: `Bóng Ma Chiến Tranh`,
    roles: [GameRole.JUNGLE],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `DIVER`],
    playstyleTags: [`ENGAGE`, `DIVER`, `SUSTAIN`, `MOBILITY`],
    utilityTags: [`FEAR`, `KNOCK_BACK`, `DASH`, `MOVEMENT_SPEED`],
    riskTags: [`ENGAGE`, `COOLDOWN_RELIANT`, `CC_VULNERABLE`],
    strengths: [
      `ENGAGE`,
      `JUNGLE_CLEAR`,
      `SUSTAIN_FIGHTER`,
      `FOLLOW_UP_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `KITE`, `DISENGAGE`],
  },
  // HEIMERDINGER
  {
    key: `heimerdinger`,
    name: `Heimerdinger`,
    title: `The Revered Inventor`,
    titleVi: `Nhà Phát Minh Lỗi Lạc`,
    roles: [GameRole.MID, GameRole.TOP, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`ZONE_CONTROL`, `POKE`, `SCALING`],
    utilityTags: [`SLOW`, `STUN`, `VISION_CONTROL`],
    riskTags: [`LOW_MOBILITY`, `POSITIONING_RELIANT`, `COOLDOWN_RELIANT`],
    strengths: [`ZONE_CONTROL`, `POKE`, `WAVE_CLEAR`, `AREA_DAMAGE`],
    weaknesses: [`DIVE`, `ASSASSIN`, `HIGH_MOBILITY`, `LONG_RANGE_CHAMPION`],
  },
  // IRELIA
  {
    key: `irelia`,
    name: `Irelia`,
    title: `The Blade Dancer`,
    titleVi: `Vũ Kiếm Sư`,
    roles: [GameRole.TOP, GameRole.MID],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`MOBILITY`, `DPS`, `SKIRMISH`, `SPLIT_PUSH`],
    utilityTags: [`DASH`, `STUN`, `SLOW`],
    riskTags: [`HIGH_EXECUTION`, `CC_VULNERABLE`, `TIMING_RELIANT`],
    strengths: [`MOBILITY`, `DUELING`, `COOLDOWN_RESET`, `EXTENDED_FIGHT`],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `DISENGAGE`,
      `BURST_DAMAGE`,
      `ANTI_HEAL`,
    ],
  },
  // JANNA
  {
    key: `janna`,
    name: `Janna`,
    title: `The Storm's Fury`,
    titleVi: `Cơn Thịnh Nộ Của Bão Tố`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`ENCHANTER`, `MAGE`],
    playstyleTags: [`PEEL`, `TEAM_SUPPORT`, `DISENGAGE`],
    utilityTags: [
      `SHIELD`,
      `HEALING`,
      `KNOCK_UP`,
      `KNOCK_BACK`,
      `MOVEMENT_SPEED`,
    ],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `LOW_DAMAGE`],
    strengths: [`PEEL`, `DISENGAGE`, `TEAM_SUPPORT`, `SHIELDING`],
    weaknesses: [`DIVE`, `BURST_DAMAGE`, `PICK_POTENTIAL`, `ANTI_SHIELD`],
  },
  // JARVAN IV
  {
    key: `jarvan-iv`,
    name: `Jarvan IV`,
    title: `The Exemplar of Demacia`,
    titleVi: `Biểu Tượng Của Demacia`,
    roles: [GameRole.JUNGLE, GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `TANK`],
    playstyleTags: [`ENGAGE`, `DIVE`, `TEAMFIGHT`],
    utilityTags: [`KNOCK_UP`, `SLOW`, `SHIELD`, `ATTACK_SPEED_STEROID`],
    riskTags: [`COMMIT_HEAVY`, `COOLDOWN_RELIANT`, `CC_VULNERABLE`],
    strengths: [`ENGAGE`, `DIVE`, `TEAMFIGHT`, `EARLY_GAME_PRESSURE`],
    weaknesses: [`DISENGAGE`, `KITE`, `ANTI_DIVE`, `HIGH_MOBILITY`],
  },
  // JAX
  {
    key: `jax`,
    name: `Jax`,
    title: `Grandmaster at Arms`,
    titleVi: `Bậc Thầy Vũ Khí`,
    roles: [GameRole.TOP, GameRole.JUNGLE],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`DPS`, `DUELING`, `SPLIT_PUSH`, `SCALING`],
    utilityTags: [`DASH`, `STUN`, `DAMAGE_REDUCTION`, `ATTACK_SPEED_STEROID`],
    riskTags: [`CC_VULNERABLE`, `COMMIT_HEAVY`, `COOLDOWN_RELIANT`],
    strengths: [`DUELING`, `SPLIT_PUSH`, `SCALING_DAMAGE`, `EXTENDED_FIGHT`],
    weaknesses: [`KITE`, `DISENGAGE`, `POINT_AND_CLICK_CC`, `BURST_DAMAGE`],
  },
  // JAYCE
  {
    key: `jayce`,
    name: `Jayce`,
    title: `The Defender of Tomorrow`,
    titleVi: `Người Bảo Hộ Tương Lai`,
    roles: [GameRole.TOP, GameRole.MID],
    damageType: `MIXED`,
    rangeType: `HYBRID`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `POKE`],
    playstyleTags: [`POKE`, `BURST`, `FORM_SWAP`, `LANE_PRESSURE`],
    utilityTags: [
      `KNOCK_BACK`,
      `MOVEMENT_SPEED`,
      `ARMOR_REDUCTION`,
      `MAGIC_RESIST_REDUCTION`,
    ],
    riskTags: [`HIGH_EXECUTION`, `COOLDOWN_RELIANT`, `FORM_DEPENDENT`],
    strengths: [`LANE_PRESSURE`, `POKE`, `BURST_DAMAGE`, `SPLIT_PUSH`],
    weaknesses: [
      `HARD_TO_PLAY`,
      `CC_VULNERABLE`,
      `WEAK_WHEN_BEHIND`,
      `SUSTAIN`,
    ],
  },
  // JHIN
  {
    key: `jhin`,
    name: `Jhin`,
    title: `The Virtuoso`,
    titleVi: `Nghệ Sĩ Tử Thần`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`BURST`, `PICK`, `POKE`],
    utilityTags: [`ROOT`, `SLOW`, `VISION_CONTROL`, `MOVEMENT_SPEED`],
    riskTags: [`POSITIONING_RELIANT`, `LOW_MOBILITY`, `RELOAD_RELIANT`],
    strengths: [`PICK_POTENTIAL`, `BURST_DAMAGE`, `LONG_RANGE_POKE`, `EXECUTE`],
    weaknesses: [`DIVE`, `HIGH_MOBILITY`, `TANK`, `SUSTAIN`],
  },
  // JINX
  {
    key: `jinx`,
    name: `Jinx`,
    title: `The Loose Cannon`,
    titleVi: `Khẩu Pháo Nổi Loạn`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`DPS`, `SCALING`, `TEAMFIGHT`, `SNOWBALL`],
    utilityTags: [`SLOW`, `ROOT`, `VISION`, `ATTACK_SPEED_STEROID`],
    riskTags: [`POSITIONING_RELIANT`, `LOW_MOBILITY`, `SQUISHY`],
    strengths: [
      `SCALING_DAMAGE`,
      `TEAMFIGHT`,
      `RESET_CARRY`,
      `OBJECTIVE_CONTROL`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `POINT_AND_CLICK_CC`, `BURST_DAMAGE`],
  },
  // K'SANTE
  {
    key: `ksante`,
    name: `K'Sante`,
    title: `The Pride of Nazumah`,
    titleVi: `Niềm Kiêu Hãnh Của Nazumah`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`TANK`, `FIGHTER`],
    playstyleTags: [`DUELING`, `TEAMFIGHT`, `FRONTLINE`],
    utilityTags: [`KNOCK_BACK`, `STUN`, `SLOW`, `SHIELD`, `UNSTOPPABLE`],
    riskTags: [`HIGH_EXECUTION`, `COMMIT_HEAVY`, `FORM_DEPENDENT`],
    strengths: [`FRONTLINE`, `DAMAGE_REDUCTION`, `DUELING`, `DISPLACEMENT`],
    weaknesses: [`KITE`, `TRUE_DAMAGE`, `ANTI_TANK`, `DISENGAGE`],
  },
  {
    key: `kaisa`,
    name: `Kai'Sa`,
    title: `Daughter of the Void`,
    titleVi: `Ái Nữ Hư Không`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `ASSASSIN`],
    playstyleTags: [
      `DPS`,
      `MOBILITY`,
      `SCALING`,
      `ON_HIT_CHAMPION`,
      `ABILITY_RELIANT_CHAMPION`,
    ],
    utilityTags: [`DASH`, `STEALTH`, `REVEAL`, `SHIELD`, `ABILITY_EVOLUTION`],
    riskTags: [
      `POSITIONING_RELIANT`,
      `SKILLSHOT_RELIANT`,
      `SHORT_RANGE_MARKSMAN`,
    ],
    strengths: [
      `HYBRID_DAMAGE`,
      `MOBILITY`,
      `SCALING_DAMAGE`,
      `PICK_POTENTIAL`,
      `MISSING_HEALTH_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `LONG_RANGE_POKE`, `WEAK_EARLY_GAME`],
  },
  // KALISTA
  {
    key: `kalista`,
    name: `Kalista`,
    title: `The Spear of Vengeance`,
    titleVi: `Mũi Giáo Phục Hận`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [
      `DPS`,
      `MOBILITY`,
      `ON_HIT_CHAMPION`,
      `AUTO_ATTACK_CHAMPION`,
      `DUELING`,
    ],
    utilityTags: [`DASH`, `REVEAL`, `SLOW`, `KNOCK_UP`, `ALLY_FOLLOW_UP`],
    riskTags: [
      `POSITIONING_RELIANT`,
      `HIGH_EXECUTION`,
      `OATHSWORN_RELIANT`,
      `CC_VULNERABLE`,
    ],
    strengths: [
      `MOBILITY`,
      `OBJECTIVE_CONTROL`,
      `LANE_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
    ],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `SLOW`,
      `BURST_DAMAGE`,
      `LOW_RANGE_CHAMPION`,
    ],
  },
  // KARMA
  {
    key: `karma`,
    name: `Karma`,
    title: `The Enlightened One`,
    titleVi: `Kẻ Được Khai Sáng`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ENCHANTER`],
    playstyleTags: [
      `POKE`,
      `UTILITY`,
      `TEAMFIGHT`,
      `SHIELDING`,
      `ZONE_CONTROL`,
    ],
    utilityTags: [`SHIELD`, `SPEED_UP`, `SLOW`, `ROOT`, `REVEAL`],
    riskTags: [`SKILLSHOT_RELIANT`, `POSITIONING_RELIANT`, `MANA_RELIANT`],
    strengths: [
      `POKE`,
      `TEAM_SUPPORT`,
      `SHIELDING`,
      `CROWD_CONTROL`,
      `TEAMFIGHT`,
    ],
    weaknesses: [`DIVE`, `BURST_DAMAGE`, `LONG_RANGE_CHAMPION`],
  },
  // KASSADIN
  {
    key: `kassadin`,
    name: `Kassadin`,
    title: `The Void Walker`,
    titleVi: `Lữ Khách Hư Không`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `MOBILITY`, `SCALING`, `ANTI_MAGE`],
    utilityTags: [`DASH`, `SHIELD`, `SILENCE`, `SLOW`],
    riskTags: [`WEAK_EARLY_GAME`, `MANA_RELIANT`, `MELEE_RANGE`],
    strengths: [
      `MAGIC_DAMAGE`,
      `MOBILITY`,
      `SCALING_DAMAGE`,
      `BURST_DAMAGE`,
      `ANTI_MAGIC`,
    ],
    weaknesses: [
      `EARLY_GAME_PRESSURE`,
      `PHYSICAL_DAMAGE`,
      `POINT_AND_CLICK_CC`,
    ],
  },
  // KATARINA
  {
    key: `katarina`,
    name: `Katarina`,
    title: `The Sinister Blade`,
    titleVi: `Ác Kiếm`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `NONE`,
    classTags: [`ASSASSIN`, `MAGE`],
    playstyleTags: [`BURST`, `MOBILITY`, `SNOWBALL`, `RESET_CHAMPION`],
    utilityTags: [`DASH`, `ANTI_HEAL`, `SPEED_UP`],
    riskTags: [`HIGH_EXECUTION`, `RESET_RELIANT`, `CC_VULNERABLE`],
    strengths: [`BURST_DAMAGE`, `MOBILITY`, `SNOWBALL`, `TEAMFIGHT_CLEANUP`],
    weaknesses: [`POINT_AND_CLICK_CC`, `LOCKDOWN_ZONE`, `EARLY_GAME_PRESSURE`],
  },
  // KAYLE
  {
    key: `kayle`,
    name: `Kayle`,
    title: `The Righteous`,
    titleVi: `Thiên Thần Phán Quyết`,
    roles: [GameRole.TOP, GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `MAGE`],
    playstyleTags: [`SCALING`, `DPS`, `ON_HIT_CHAMPION`, `HYPERCARRY`],
    utilityTags: [
      `HEAL`,
      `SPEED_UP`,
      `SLOW`,
      `INVULNERABILITY`,
      `RESISTANCE_REDUCTION`,
    ],
    riskTags: [`WEAK_EARLY_GAME`, `POSITIONING_RELIANT`, `SCALING_RELIANT`],
    strengths: [
      `SCALING_DAMAGE`,
      `MAGIC_DAMAGE`,
      `TEAMFIGHT`,
      `INVULNERABILITY`,
      `DPS`,
    ],
    weaknesses: [`EARLY_GAME_PRESSURE`, `DIVE`, `POINT_AND_CLICK_CC`],
  },
  // KAYN
  {
    key: `kayn`,
    name: `Kayn`,
    title: `The Shadow Reaper`,
    titleVi: `Tử Thần Bóng Tối`,
    roles: [GameRole.JUNGLE],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `NONE`,
    classTags: [`ASSASSIN`, `FIGHTER`],
    playstyleTags: [`MOBILITY`, `DIVE`, `FORM_CHANGE`, `SKIRMISH`, `SNOWBALL`],
    utilityTags: [
      `DASH`,
      `SPEED_UP`,
      `SLOW`,
      `KNOCK_UP`,
      `UNTARGETABLE`,
      `TERRAIN_WALK`,
    ],
    riskTags: [`FORM_RELIANT`, `HIGH_EXECUTION`, `CC_VULNERABLE`],
    strengths: [
      `MOBILITY`,
      `JUNGLE_CLEAR`,
      `DIVE`,
      `SUSTAIN`,
      `PERCENT_HEALTH_DAMAGE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `ANTI_HEAL`, `EARLY_GAME_PRESSURE`],
  },
  // KENNEN
  {
    key: `kennen`,
    name: `Kennen`,
    title: `The Heart of the Tempest`,
    titleVi: `Trái Tim Sấm Sét`,
    roles: [GameRole.TOP, GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `ENERGY`,
    classTags: [`MAGE`],
    playstyleTags: [`POKE`, `TEAMFIGHT`, `ZONE_CONTROL`, `ENGAGE`],
    utilityTags: [`STUN`, `SPEED_UP`, `DAMAGE_REDUCTION`, `AREA_DAMAGE`],
    riskTags: [
      `ENERGY_RELIANT`,
      `ULTIMATE_RELIANT_CHAMPION`,
      `POSITIONING_RELIANT`,
    ],
    strengths: [
      `MAGIC_DAMAGE`,
      `TEAMFIGHT`,
      `AREA_DAMAGE`,
      `CROWD_CONTROL`,
      `ENGAGE`,
    ],
    weaknesses: [`LONG_RANGE_POKE`, `DISENGAGE`, `BURST_DAMAGE`],
  },
  // KHAZIX
  {
    key: `khazix`,
    name: `Kha'Zix`,
    title: `The Voidreaver`,
    titleVi: `Sát Thủ Hư Không`,
    roles: [GameRole.JUNGLE],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`],
    playstyleTags: [
      `BURST`,
      `MOBILITY`,
      `PICK`,
      `RESET_RELIANT`,
      `ABILITY_EVOLUTION`,
    ],
    utilityTags: [`STEALTH`, `SLOW`, `REVEAL`, `DASH`, `COOLDOWN_RESET`],
    riskTags: [`SQUISHY`, `ISOLATION_RELIANT`, `CC_VULNERABLE`],
    strengths: [
      `PICK_POTENTIAL`,
      `BURST_DAMAGE`,
      `HIGH_MOBILITY`,
      `JUNGLE_CLEAR`,
    ],
    weaknesses: [
      `GROUPED_ENEMIES`,
      `POINT_AND_CLICK_CC`,
      `REVEAL`,
      `TEAMFIGHT`,
    ],
  },
  // KINDRED
  {
    key: `kindred`,
    name: `Kindred`,
    title: `The Eternal Hunters`,
    titleVi: `Thợ Săn Vĩnh Hằng`,
    roles: [GameRole.JUNGLE],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`SCALING`, `MOBILITY`, `ON_HIT_CHAMPION`, `JUNGLE_CLEAR`],
    utilityTags: [
      `DASH`,
      `SLOW`,
      `HEALING`,
      `INVULNERABILITY`,
      `ATTACK_SPEED_STEROID`,
    ],
    riskTags: [
      `POSITIONING_RELIANT`,
      `STACKING_RELIANT`,
      `SQUISHY`,
      `CC_VULNERABLE`,
    ],
    strengths: [
      `SCALING_DAMAGE`,
      `OBJECTIVE_CONTROL`,
      `JUNGLE_CLEAR`,
      `DUELING`,
    ],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `BURST_DAMAGE`,
      `LOW_RANGE_CHAMPION`,
      `WEAK_WHEN_BEHIND`,
    ],
  },
  // KOGMAW
  {
    key: `kogmaw`,
    name: `Kog'Maw`,
    title: `The Mouth of the Abyss`,
    titleVi: `Miệng Của Vực Thẳm`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [
      `DPS`,
      `SCALING`,
      `POKE`,
      `ON_HIT_CHAMPION`,
      `AUTO_ATTACK_CHAMPION`,
    ],
    utilityTags: [
      `SLOW`,
      `REVEAL`,
      `ARMOR_SHRED`,
      `MAGIC_RESIST_REDUCTION`,
      `ATTACK_SPEED_STEROID`,
    ],
    riskTags: [
      `SQUISHY`,
      `LOW_MOBILITY`,
      `POSITIONING_RELIANT`,
      `CC_VULNERABLE`,
    ],
    strengths: [
      `SCALING_DAMAGE`,
      `SUSTAIN_DAMAGE`,
      `PERCENT_HEALTH_DAMAGE`,
      `LONG_RANGE_POKE`,
    ],
    weaknesses: [`DIVE`, `BURST_DAMAGE`, `POINT_AND_CLICK_CC`, `ASSASSIN`],
  },
  // LEESIN
  {
    key: `lee-sin`,
    name: `Lee Sin`,
    title: `The Blind Monk`,
    titleVi: `Thầy Tu Mù`,
    roles: [GameRole.JUNGLE],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HARD`,
    resourceType: `ENERGY`,
    classTags: [`FIGHTER`, `ASSASSIN`],
    playstyleTags: [
      `MOBILITY`,
      `EARLY_GAME_PRESSURE`,
      `PLAYMAKING`,
      `HIGH_EXECUTION`,
    ],
    utilityTags: [`DASH`, `SHIELD`, `REVEAL`, `SLOW`, `KNOCK_BACK`, `KNOCK_UP`],
    riskTags: [
      `HIGH_EXECUTION`,
      `ENERGY_RELIANT`,
      `SKILLSHOT_RELIANT`,
      `FALLS_OFF_LATE`,
    ],
    strengths: [
      `EARLY_COMBAT`,
      `JUNGLE_CLEAR`,
      `PICK_POTENTIAL`,
      `OUTPLAY_POTENTIAL`,
    ],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `SCALING_GAME`,
      `LOW_RANGE_CHAMPION`,
      `TEAMFIGHT`,
    ],
  },
  // LEONA
  {
    key: `leona`,
    name: `Leona`,
    title: `The Radiant Dawn`,
    titleVi: `Bình Minh Rực Rỡ`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `EASY`,
    resourceType: `MANA`,
    classTags: [`TANK`, `SUPPORT`],
    playstyleTags: [`ENGAGE`, `TEAMFIGHT`, `PICK`, `PEEL`],
    utilityTags: [`STUN`, `ROOT`, `SLOW`, `DASH`, `LOCKDOWN_ZONE`],
    riskTags: [`MELEE_RANGE`, `TEAM_DEPENDENT`, `LOW_DAMAGE`],
    strengths: [`ENGAGE`, `CROWD_CONTROL`, `PICK_POTENTIAL`, `FRONTLINE`],
    weaknesses: [`POKE_COMPOSITION`, `DISENGAGE`, `KITE`, `LOW_MOBILITY`],
  },
  // LILLIA
  {
    key: `lillia`,
    name: `Lillia`,
    title: `The Bashful Bloom`,
    titleVi: `Nụ Hoa Bẽn Lẽn`,
    roles: [GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `MAGE`],
    playstyleTags: [`MOBILITY`, `DPS`, `SCALING`, `ZONE_CONTROL`, `SKIRMISH`],
    utilityTags: [`SLOW`, `SLEEP`, `REVEAL`, `MOVEMENT_SPEED`, `AREA_DAMAGE`],
    riskTags: [
      `POSITIONING_RELIANT`,
      `SKILLSHOT_RELIANT`,
      `SQUISHY`,
      `CC_VULNERABLE`,
    ],
    strengths: [`JUNGLE_CLEAR`, `SUSTAIN_DAMAGE`, `AREA_DAMAGE`, `TEAMFIGHT`],
    weaknesses: [
      `BURST_DAMAGE`,
      `POINT_AND_CLICK_CC`,
      `LONG_RANGE_POKE`,
      `DIVE`,
    ],
  },
  // LISSANDRA
  {
    key: `lissandra`,
    name: `Lissandra`,
    title: `The Ice Witch`,
    titleVi: `Mụ Phù Thủy Băng`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`BURST`, `PICK`, `TEAMFIGHT`, `ZONE_CONTROL`],
    utilityTags: [`SLOW`, `ROOT`, `STUN`, `DASH`, `STASIS`, `LOCKDOWN_ZONE`],
    riskTags: [
      `COOLDOWN_RELIANT`,
      `POSITIONING_RELIANT`,
      `MANA_HUNGRY_CHAMPION`,
    ],
    strengths: [
      `CROWD_CONTROL`,
      `PICK_POTENTIAL`,
      `TEAMFIGHT_FOLLOWUP`,
      `BURST_DAMAGE`,
    ],
    weaknesses: [
      `LONG_RANGE_POKE`,
      `HIGH_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `WEAK_WHEN_BEHIND`,
    ],
  },
  // LUCIAN
  {
    key: `lucian`,
    name: `Lucian`,
    title: `The Purifier`,
    titleVi: `Kẻ Thanh Trừng`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [
      `BURST`,
      `MOBILITY`,
      `AUTO_ATTACK_CHAMPION`,
      `ABILITY_RELIANT_CHAMPION`,
    ],
    utilityTags: [`DASH`, `REVEAL`, `MOVEMENT_SPEED`, `DOUBLE_SHOT`],
    riskTags: [
      `LOW_RANGE_CHAMPION`,
      `POSITIONING_RELIANT`,
      `MANA_HUNGRY_CHAMPION`,
      `CC_VULNERABLE`,
    ],
    strengths: [`LANE_PRESSURE`, `EARLY_COMBAT`, `BURST_DAMAGE`, `MOBILITY`],
    weaknesses: [
      `LONG_RANGE_POKE`,
      `POINT_AND_CLICK_CC`,
      `HIGH_RANGE_CHAMPION`,
      `FRONTLINE`,
    ],
  },
  // LULU
  {
    key: `lulu`,
    name: `Lulu`,
    title: `The Fae Sorceress`,
    titleVi: `Pháp Sư Tinh Linh`,
    roles: [GameRole.SUPPORT, GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `SUPPORT`, `ENCHANTER`],
    playstyleTags: [`UTILITY`, `PEEL`, `POKE`, `TEAM_SUPPORT`],
    utilityTags: [`SHIELD`, `SLOW`, `KNOCK_UP`, `SPEED_UP`, `POLYMORPH`],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `LOW_MOBILITY`],
    strengths: [`PEEL`, `ALLY_BUFF`, `TEAM_SUPPORT`, `LANE_SURVIVAL`],
    weaknesses: [`DIVE`, `ASSASSIN`, `BURST_DAMAGE`],
  },
  // LUX
  {
    key: `lux`,
    name: `Lux`,
    title: `The Lady of Luminosity`,
    titleVi: `Tiểu Thư Ánh Sáng`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`POKE`, `BURST`, `ZONE_CONTROL`, `PICK`],
    utilityTags: [`LOCKDOWN`, `ALLY_PROTECTION`, `SLOW`, `PICK_POTENTIAL`],
    riskTags: [
      `SQUISHY`,
      `SKILLSHOT_RELIANT`,
      `POSITIONING_RELIANT`,
      `LOW_MOBILITY`,
    ],
    strengths: [
      `PICK_POTENTIAL`,
      `LONG_RANGE_POKE`,
      `WAVE_CLEAR`,
      `TEAMFIGHT_FOLLOWUP`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `HIGH_MOBILITY`, `POINT_AND_CLICK_CC`],
  },
  // MALPHITE
  {
    key: `malphite`,
    name: `Malphite`,
    title: `Shard of the Monolith`,
    titleVi: `Mảnh Vỡ Thiên Thạch`,
    roles: [GameRole.TOP, GameRole.SUPPORT, GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `VANGUARD`],
    playstyleTags: [`ENGAGE`, `TEAMFIGHT`, `ZONE_CONTROL`],
    utilityTags: [`SHIELD`, `SLOW`, `KNOCK_UP`, `ANTI_ATTACK_SPEED`],
    riskTags: [`MANA_RELIANT`, `COOLDOWN_RELIANT`, `LOW_MOBILITY`],
    strengths: [`HARD_ENGAGE`, `TEAMFIGHT`, `FRONTLINE`, `ANTI_ATTACK_SPEED`],
    weaknesses: [`POKE_COMPOSITION`, `DISENGAGE`, `TRUE_DAMAGE`],
  },
  // MAOKAI
  {
    key: `maokai`,
    name: `Maokai`,
    title: `The Twisted Treant`,
    titleVi: `Ma Cây Vặn Xoắn`,
    roles: [GameRole.TOP, GameRole.SUPPORT, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `VANGUARD`],
    playstyleTags: [`ENGAGE`, `TEAMFIGHT`, `ZONE_CONTROL`, `SUSTAIN`],
    utilityTags: [`ROOT`, `KNOCK_BACK`, `SLOW`, `UNTARGETABLE`],
    riskTags: [`MANA_RELIANT`, `COOLDOWN_RELIANT`, `LOW_MOBILITY`],
    strengths: [`HARD_ENGAGE`, `TEAMFIGHT`, `FRONTLINE`, `ZONE_CONTROL`],
    weaknesses: [`ANTI_HEAL`, `POKE_COMPOSITION`, `DISENGAGE`, `TRUE_DAMAGE`],
  },
  // MASTER YI
  {
    key: `master-yi`,
    name: `Master Yi`,
    title: `The Wuju Bladesman`,
    titleVi: `Kiếm Sư Wuju`,
    roles: [GameRole.JUNGLE],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`SKIRMISHER`, `ASSASSIN`],
    playstyleTags: [`DPS`, `ON_HIT_CHAMPION`, `RESET_CHAMPION`, `SCALING`],
    utilityTags: [`UNTARGETABLE`, `SLOW_IMMUNITY`, `TRUE_DAMAGE`, `SELF_HEAL`],
    riskTags: [
      `CC_VULNERABLE`,
      `TEAM_DEPENDENT`,
      `WEAK_EARLY_GAME`,
      `COMMIT_HEAVY`,
    ],
    strengths: [
      `SCALING_DAMAGE`,
      `TEAMFIGHT_CLEANUP`,
      `SUSTAIN_DAMAGE`,
      `JUNGLE_CLEAR`,
    ],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `BURST_DAMAGE`,
      `ANTI_HEAL`,
      `EARLY_GAME_PRESSURE`,
    ],
  },
  // MEL
  {
    key: `mel`,
    name: `Mel`,
    title: `The Soul's Reflection`,
    titleVi: `Linh Hồn Phản Chiếu`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`POKE`, `BURST`, `ZONE_CONTROL`, `STACKING_RELIANT`],
    utilityTags: [`ROOT`, `SLOW`, `INVULNERABILITY`, `PROJECTILE_BLOCK`],
    riskTags: [
      `SQUISHY`,
      `SKILLSHOT_RELIANT`,
      `POSITIONING_RELIANT`,
      `LOW_MOBILITY`,
    ],
    strengths: [`BURST_DAMAGE`, `POKE_SETUP`, `ZONE_CONTROL`, `ANTI_BURST`],
    weaknesses: [
      `DIVE`,
      `ASSASSIN`,
      `POINT_AND_CLICK_CC`,
      `EARLY_GAME_PRESSURE`,
    ],
  },
  // MILIO
  {
    key: `milio`,
    name: `Milio`,
    title: `The Gentle Flame`,
    titleVi: `Ngọn Lửa Dịu Êm`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ENCHANTER`],
    playstyleTags: [`UTILITY`, `PEEL`, `TEAM_SUPPORT`, `LANE_SURVIVAL`],
    utilityTags: [`ALLY_BUFF`, `ALLY_HEAL`, `ALLY_SHIELD`, `CLEANSE`],
    riskTags: [
      `SQUISHY`,
      `POSITIONING_RELIANT`,
      `TEAM_DEPENDENT`,
      `LOW_DAMAGE`,
    ],
    strengths: [`PEEL`, `TEAM_SUPPORT`, `ALLY_PROTECTION`, `ANTI_CC`],
    weaknesses: [`DIVE`, `ASSASSIN`, `BURST_DAMAGE`, `ANTI_HEAL`],
  },
  // MISS FORTUNE
  {
    key: `miss-fortune`,
    name: `Miss Fortune`,
    title: `The Bounty Hunter`,
    titleVi: `Thợ Săn Tiền Thưởng`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`POKE`, `BURST`, `TEAMFIGHT`, `AUTO_ATTACK_CHAMPION`],
    utilityTags: [`SLOW`, `SPEED_UP`, `AREA_DAMAGE`],
    riskTags: [
      `SQUISHY`,
      `POSITIONING_RELIANT`,
      `INTERRUPT_VULNERABLE`,
      `LOW_MOBILITY`,
    ],
    strengths: [
      `LANE_PRESSURE`,
      `TEAMFIGHT_FOLLOWUP`,
      `AREA_DAMAGE`,
      `BURST_DAMAGE`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `POINT_AND_CLICK_CC`, `INTERRUPT`],
  },
  // MORDEKAISER
  {
    key: `mordekaiser`,
    name: `Mordekaiser`,
    title: `The Iron Revenant`,
    titleVi: `Ác Quỷ Thiết Giáp`,
    roles: [GameRole.TOP, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `NONE`,
    classTags: [`FIGHTER`, `JUGGERNAUT`],
    playstyleTags: [`DRAIN_TANK`, `EXTENDED_FIGHT_CHAMPION`, `DUELIST`],
    utilityTags: [`PULL`, `SLOW`, `SELF_SHIELD`, `SELF_HEAL`],
    riskTags: [`IMMOBILE`, `KITEABLE`, `COOLDOWN_RELIANT`, `MELEE_RANGE`],
    strengths: [`DUELING`, `SUSTAIN_DAMAGE`, `ISOLATED_TARGET`, `FRONTLINE`],
    weaknesses: [`KITE`, `LONG_RANGE_POKE`, `DISENGAGE`, `HIGH_MOBILITY`],
  },
  // MORGANA
  {
    key: `morgana`,
    name: `Morgana`,
    title: `The Fallen`,
    titleVi: `Thiên Thần Sa Ngã`,
    roles: [GameRole.SUPPORT, GameRole.MID, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`PICK`, `ZONE_CONTROL`, `TEAM_SUPPORT`, `POKE`],
    utilityTags: [`ROOT`, `MAGIC_SHIELD`, `ANTI_CC`, `SLOW`],
    riskTags: [`SKILLSHOT_RELIANT`, `POSITIONING_RELIANT`, `COOLDOWN_RELIANT`],
    strengths: [`PICK_POTENTIAL`, `ANTI_CC`, `ZONE_CONTROL`, `TEAMFIGHT_SETUP`],
    weaknesses: [`DIVE`, `ASSASSIN`, `LONG_RANGE_POKE`, `HIGH_MOBILITY`],
  },
  // NAMI
  {
    key: `nami`,
    name: `Nami`,
    title: `The Tidecaller`,
    titleVi: `Nàng Tiên Cá Gọi Sóng`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ENCHANTER`],
    playstyleTags: [`UTILITY`, `PEEL`, `TEAM_SUPPORT`, `POKE`],
    utilityTags: [`ALLY_HEAL`, `ALLY_BUFF`, `SLOW`, `KNOCK_UP`],
    riskTags: [
      `SQUISHY`,
      `SKILLSHOT_RELIANT`,
      `POSITIONING_RELIANT`,
      `LOW_MOBILITY`,
    ],
    strengths: [`PEEL`, `TEAM_SUPPORT`, `PICK_POTENTIAL`, `LANE_SURVIVAL`],
    weaknesses: [`DIVE`, `ASSASSIN`, `BURST_DAMAGE`, `ANTI_HEAL`],
  },
  // NASUS
  {
    key: `nasus`,
    name: `Nasus`,
    title: `The Curator of the Sands`,
    titleVi: `Nhà Thông Thái Sa Mạc`,
    roles: [GameRole.TOP, GameRole.JUNGLE],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `JUGGERNAUT`],
    playstyleTags: [
      `SCALING`,
      `DRAIN_TANK`,
      `DUELIST`,
      `EXTENDED_FIGHT_CHAMPION`,
    ],
    utilityTags: [`SLOW`, `ANTI_ATTACK_SPEED`, `ARMOR_REDUCTION`, `SELF_BUFF`],
    riskTags: [`WEAK_EARLY_GAME`, `KITEABLE`, `MANA_RELIANT`, `MELEE_RANGE`],
    strengths: [`SCALING_DAMAGE`, `DUELING`, `SUSTAIN_DAMAGE`, `SIDE_LANE`],
    weaknesses: [`EARLY_GAME_PRESSURE`, `KITE`, `LONG_RANGE_POKE`, `ANTI_HEAL`],
  },
  // NAUTILUS
  {
    key: `nautilus`,
    name: `Nautilus`,
    title: `The Titan of the Depths`,
    titleVi: `Khổng Lồ Biển Sâu`,
    roles: [GameRole.SUPPORT, GameRole.JUNGLE, GameRole.TOP],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `VANGUARD`],
    playstyleTags: [`ENGAGE`, `PICK`, `TEAMFIGHT`, `PEEL`],
    utilityTags: [`ROOT`, `HOOK`, `KNOCK_UP`, `STUN`],
    riskTags: [
      `LOW_MOBILITY`,
      `COOLDOWN_RELIANT`,
      `TEAM_DEPENDENT`,
      `MELEE_RANGE`,
    ],
    strengths: [`HARD_ENGAGE`, `PICK_POTENTIAL`, `LOCKDOWN`, `FRONTLINE`],
    weaknesses: [`POKE_COMPOSITION`, `DISENGAGE`, `KITE`, `TRUE_DAMAGE`],
  },
  // NIDALEE
  {
    key: `nidalee`,
    name: `Nidalee`,
    title: `The Bestial Huntress`,
    titleVi: `Nữ Thợ Săn Hóa Thú`,
    roles: [GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `SKIRMISHER`],
    playstyleTags: [`POKE`, `MOBILITY`, `FORM_SWAP`, `JUNGLE_CLEAR`],
    utilityTags: [`REVEAL`, `MARK`, `ALLY_HEAL`, `ATTACK_SPEED_STEROID`],
    riskTags: [
      `SKILLSHOT_RELIANT`,
      `HIGH_EXECUTION`,
      `FORM_RELIANT`,
      `SQUISHY`,
    ],
    strengths: [`POKE_SETUP`, `MOBILITY`, `JUNGLE_CLEAR`, `PICK_POTENTIAL`],
    weaknesses: [`LOCKDOWN`, `POINT_AND_CLICK_CC`, `TEAMFIGHT`, `HARD_ENGAGE`],
  },
  // NILAH
  {
    key: `nilah`,
    name: `Nilah`,
    title: `The Joy Unbound`,
    titleVi: `Hiện Thân Của Niềm Vui`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `SKIRMISHER`],
    playstyleTags: [
      `CRITICAL_SCALING`,
      `DIVE`,
      `EXTENDED_FIGHT_CHAMPION`,
      `MOBILITY`,
    ],
    utilityTags: [`SELF_HEAL`, `ALLY_HEAL`, `SELF_SHIELD`, `PULL`],
    riskTags: [
      `MELEE_RANGE`,
      `HIGH_EXECUTION`,
      `POSITIONING_RELIANT`,
      `CC_VULNERABLE`,
    ],
    strengths: [`SCALING_DAMAGE`, `TEAMFIGHT`, `SUSTAIN_DAMAGE`, `AOE_DAMAGE`],
    weaknesses: [
      `POKE_COMPOSITION`,
      `POINT_AND_CLICK_CC`,
      `DISENGAGE`,
      `BURST_DAMAGE`,
    ],
  },
  // NOCTURNE
  {
    key: `nocturne`,
    name: `Nocturne`,
    title: `The Eternal Nightmare`,
    titleVi: `Ác Mộng Vĩnh Cửu`,
    roles: [GameRole.JUNGLE],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `FIGHTER`],
    playstyleTags: [`DIVE`, `PICK`, `BURST`, `MOBILITY`],
    utilityTags: [`FEAR`, `SPELL_SHIELD`, `GLOBAL_RANGE`, `VISION_DENIAL`],
    riskTags: [`ULTIMATE_RELIANT_CHAMPION`, `COOLDOWN_RELIANT`, `KITEABLE`],
    strengths: [`PICK_POTENTIAL`, `MAP_PRESSURE`, `DIVE`, `BURST_DAMAGE`],
    weaknesses: [`POINT_AND_CLICK_CC`, `DISENGAGE`, `KITE`, `VISION_CONTROL`],
  },
  // NORRA
  {
    key: `norra`,
    name: `Norra`,
    title: `The Portal Mistress`,
    titleVi: `Bậc Thầy Cổng Dịch Chuyển`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ARTILLERY_MAGE`],
    playstyleTags: [`POKE`, `ZONE_CONTROL`, `SCALING`],
    utilityTags: [`SLOW`, `DISPLACEMENT`, `PORTAL`, `AREA_CC`],
    riskTags: [`SKILLSHOT_RELIANT`, `SQUISHY`, `POSITIONING_RELIANT`],
    strengths: [
      `LONG_RANGE_POKE`,
      `AREA_DAMAGE`,
      `ZONE_CONTROL`,
      `PICK_POTENTIAL`,
    ],
    weaknesses: [`ASSASSIN`, `DIVE`, `POINT_AND_CLICK_CC`, `HIGH_MOBILITY`],
  },
  // NUNU & WILLUMP
  {
    key: `nunu-willump`,
    name: `Nunu & Willump`,
    title: `The Boy and His Yeti`,
    titleVi: `Cậu Bé Và Người Tuyết`,
    roles: [GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `MAGE`],
    playstyleTags: [`ENGAGE`, `ROAMING`, `OBJECTIVE_CONTROL`, `TEAMFIGHT`],
    utilityTags: [`KNOCK_UP`, `ROOT`, `SLOW`, `SELF_SHIELD`, `SUSTAIN`],
    riskTags: [`CHANNEL_RELIANT`, `POSITIONING_RELIANT`, `KITEABLE`],
    strengths: [`OBJECTIVE_CONTROL`, `JUNGLE_CLEAR`, `ENGAGE`, `SUSTAIN`],
    weaknesses: [`INTERRUPT`, `DISENGAGE`, `HIGH_MOBILITY`, `ANTI_HEAL`],
  },
  // OLAF
  {
    key: `olaf`,
    name: `Olaf`,
    title: `The Berserker`,
    titleVi: `Chiến Binh Cuồng Nộ`,
    roles: [GameRole.JUNGLE, GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `JUGGERNAUT`],
    playstyleTags: [`DIVE`, `DUELING`, `SUSTAIN`, `EXTENDED_FIGHT`],
    utilityTags: [`SLOW`, `ARMOR_REDUCTION`, `ANTI_CC`, `TRUE_DAMAGE`],
    riskTags: [`KITEABLE`, `LOW_RANGE`, `COMMIT_RELIANT`],
    strengths: [`DUELING`, `SUSTAIN`, `TRUE_DAMAGE`, `ANTI_CC`],
    weaknesses: [`KITE`, `DISENGAGE`, `BURST_DAMAGE`, `ANTI_HEAL`],
  },
  // ORIANNA
  {
    key: `orianna`,
    name: `Orianna`,
    title: `The Lady of Clockwork`,
    titleVi: `Quý Cô Dây Cót`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`POKE`, `ZONE_CONTROL`, `SCALING`, `TEAMFIGHT`],
    utilityTags: [`ALLY_SHIELD`, `SLOW`, `SPEED_UP`, `DISPLACEMENT`],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `SKILLSHOT_RELIANT`],
    strengths: [`AREA_DAMAGE`, `ZONE_CONTROL`, `TEAMFIGHT`, `TEAM_SUPPORT`],
    weaknesses: [`ASSASSIN`, `DIVE`, `HIGH_MOBILITY`, `POINT_AND_CLICK_CC`],
  },
  // ORNN
  {
    key: `ornn`,
    name: `Ornn`,
    title: `The Fire Below the Mountain`,
    titleVi: `Ngọn Lửa Dưới Lòng Núi`,
    roles: [GameRole.TOP],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`TANK`, `VANGUARD`],
    playstyleTags: [`ZONE_CONTROL`, `SCALING`, `TEAMFIGHT`],
    utilityTags: [`KNOCK_UP`, `KNOCK_BACK`, `SLOW`],
    riskTags: [`LOW_MOBILITY`, `COOLDOWN_RELIANT`, `KITEABLE`],
    strengths: [
      `FRONTLINE`,
      `TEAMFIGHT`,
      `CROWD_CONTROL`,
      `ENGAGE`,
      `SURVIVABILITY`,
    ],
    weaknesses: [`KITE`, `DISENGAGE`, `HIGH_MOBILITY`, `ANTI_TANK`],
  },
  // PANTHEON
  {
    key: `pantheon`,
    name: `Pantheon`,
    title: `The Unbreakable Spear`,
    titleVi: `Ngọn Giáo Bất Diệt`,
    roles: [GameRole.TOP, GameRole.JUNGLE, GameRole.SUPPORT],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`FIGHTER`, `ASSASSIN`],
    playstyleTags: [`BURST`, `PICK`, `EARLY_COMBAT`],
    utilityTags: [`STUN`, `DASH`, `SLOW`],
    riskTags: [`COMMIT_HEAVY`, `COOLDOWN_RELIANT`, `KITEABLE`],
    strengths: [
      `EARLY_GAME_PRESSURE`,
      `PICK_POTENTIAL`,
      `BURST_DAMAGE`,
      `GLOBAL_RANGE`,
      `LOCKDOWN`,
    ],
    weaknesses: [`KITE`, `DISENGAGE`, `SCALING_RELIANT`, `POINT_AND_CLICK_CC`],
  },
  // POPPY
  {
    key: `poppy`,
    name: `Poppy`,
    title: `Keeper of the Hammer`,
    titleVi: `Người Giữ Búa`,
    roles: [GameRole.TOP, GameRole.JUNGLE, GameRole.SUPPORT],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`VANGUARD`, `FIGHTER`],
    playstyleTags: [`ZONE_CONTROL`, `PICK`, `TEAMFIGHT`],
    utilityTags: [`ANTI_DASH`, `STUN`, `KNOCK_BACK`, `SLOW`],
    riskTags: [`LOW_MOBILITY`, `KITEABLE`, `COOLDOWN_RELIANT`],
    strengths: [
      `ANTI_DIVE`,
      `FRONTLINE`,
      `PEEL`,
      `PICK_POTENTIAL`,
      `TERRAIN_CONTROL`,
    ],
    weaknesses: [
      `KITE`,
      `POKE_COMPOSITION`,
      `DISENGAGE`,
      `LONG_RANGE_CHAMPION`,
    ],
  },
  // PYKE
  {
    key: `pyke`,
    name: `Pyke`,
    title: `The Bloodharbor Ripper`,
    titleVi: `Sát Thủ Vùng Nước Đỏ`,
    roles: [GameRole.SUPPORT],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`, `SUPPORT`],
    playstyleTags: [`PICK`, `MOBILITY`, `ROAMING`],
    utilityTags: [`HOOK`, `STUN`, `CAMOUFLAGE`, `EXECUTE`],
    riskTags: [`HIGH_EXECUTION`, `COMMIT_HEAVY`, `SQUISHY`],
    strengths: [
      `PICK_POTENTIAL`,
      `ROAMING`,
      `EXECUTE`,
      `SNOWBALL`,
      `VISION_CONTROL`,
    ],
    weaknesses: [
      `ANTI_BURST`,
      `POINT_AND_CLICK_CC`,
      `REVEAL`,
      `GROUPED_ENEMIES`,
    ],
  },
  // RAKAN
  {
    key: `rakan`,
    name: `Rakan`,
    title: `The Charmer`,
    titleVi: `Anh Chàng Quyến Rũ`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`ENCHANTER`, `VANGUARD`],
    playstyleTags: [`MOBILITY`, `PICK`, `TEAM_SUPPORT`],
    utilityTags: [`DASH`, `KNOCK_UP`, `CHARM`, `SHIELDING`, `HEALING`],
    riskTags: [`COOLDOWN_RELIANT`, `TEAM_DEPENDENT`, `CC_VULNERABLE`],
    strengths: [`ENGAGE`, `PEEL`, `TEAM_SUPPORT`, `MOBILITY`, `TEAMFIGHT`],
    weaknesses: [`POINT_AND_CLICK_CC`, `DISENGAGE`, `ANTI_SHIELD`, `ANTI_HEAL`],
  },
  // RAMMUS
  {
    key: `rammus`,
    name: `Rammus`,
    title: `The Armordillo`,
    titleVi: `Tê Tê Gai`,
    roles: [GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`TANK`, `VANGUARD`],
    playstyleTags: [`ENGAGE`, `PICK`, `MOBILITY`],
    utilityTags: [`TAUNT`, `KNOCK_BACK`, `SLOW`],
    riskTags: [`KITEABLE`, `COOLDOWN_RELIANT`, `TEAM_DEPENDENT`],
    strengths: [
      `ANTI_ATTACK_SPEED`,
      `ANTI_DIVE`,
      `FRONTLINE`,
      `ENGAGE`,
      `PICK_POTENTIAL`,
    ],
    weaknesses: [
      `HIGH_MAGIC_RESIST`,
      `DISENGAGE`,
      `POKE_COMPOSITION`,
      `TRUE_DAMAGE`,
    ],
  },
  // RELL
  {
    key: `rell`,
    name: `Rell`,
    title: `The Iron Maiden`,
    titleVi: `Thiếu Nữ Sắt`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`VANGUARD`, `TANK`],
    playstyleTags: [`ENGAGE`, `TEAMFIGHT`, `TEAM_SUPPORT`],
    utilityTags: [`KNOCK_UP`, `PULL`, `STUN`, `ANTI_SHIELD`],
    riskTags: [`LOW_MOBILITY`, `TEAM_DEPENDENT`, `COOLDOWN_RELIANT`],
    strengths: [`FRONTLINE`, `ENGAGE`, `PEEL`, `CROWD_CONTROL`, `ANTI_SHIELD`],
    weaknesses: [`KITE`, `DISENGAGE`, `POKE_COMPOSITION`, `TRUE_DAMAGE`],
  },
  // RENEKTON
  {
    key: `renekton`,
    name: `Renekton`,
    title: `The Butcher of the Sands`,
    titleVi: `Đồ Tể Sa Mạc`,
    roles: [GameRole.TOP],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `FURY`,
    classTags: [`FIGHTER`, `BRUISER`],
    playstyleTags: [`DUELIST`, `BURST`, `EXTENDED_FIGHT`],
    utilityTags: [`DASH`, `STUN`, `ARMOR_SHRED`, `ANTI_SHIELD`],
    riskTags: [`KITEABLE`, `COOLDOWN_RELIANT`, `FALLS_OFF_LATE`],
    strengths: [
      `EARLY_GAME_PRESSURE`,
      `LANE_PRESSURE`,
      `BURST_DAMAGE`,
      `DUELING`,
      `ANTI_SHIELD`,
    ],
    weaknesses: [`KITE`, `DISENGAGE`, `SCALING_GAME`, `POINT_AND_CLICK_CC`],
  },
  // RENGAR
  {
    key: `rengar`,
    name: `Rengar`,
    title: `The Pridestalker`,
    titleVi: `Thú Săn Mồi Kiêu Hãnh`,
    roles: [GameRole.JUNGLE],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `FEROCITY`,
    classTags: [`ASSASSIN`, `FIGHTER`],
    playstyleTags: [`BURST`, `MOBILITY`, `ISOLATION_RELIANT`],
    utilityTags: [`LEAP`, `CAMOUFLAGE`, `ROOT`, `REVEAL`],
    riskTags: [`HIGH_EXECUTION`, `COMMIT_HEAVY`, `CC_VULNERABLE`],
    strengths: [
      `BURST_DAMAGE`,
      `PICK_POTENTIAL`,
      `SNOWBALL`,
      `DUELING`,
      `VISION_CONTROL`,
    ],
    weaknesses: [
      `GROUPED_ENEMIES`,
      `POINT_AND_CLICK_CC`,
      `REVEAL`,
      `ANTI_BURST`,
    ],
  },
  // RIVEN
  {
    key: `riven`,
    name: `Riven`,
    title: `The Exile`,
    titleVi: `Kẻ Lưu Đày`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `HIGH`,
    resourceType: `NONE`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`DUELIST`, `MOBILITY`, `BURST`],
    utilityTags: [`DASH`, `KNOCK_UP`, `STUN`, `SHIELD`],
    riskTags: [`HIGH_EXECUTION`, `COMMIT_HEAVY`, `CC_VULNERABLE`],
    strengths: [
      `DUELING`,
      `MOBILITY`,
      `BURST_DAMAGE`,
      `OUTPLAY_TOOL`,
      `TEAMFIGHT_FOLLOWUP`,
    ],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `KITE`,
      `ANTI_SHIELD`,
      `WEAK_WHEN_BEHIND`,
    ],
  },
  // RUMBLE
  {
    key: `rumble`,
    name: `Rumble`,
    title: `The Mechanized Menace`,
    titleVi: `Hiểm Họa Cơ Khí`,
    roles: [GameRole.TOP, GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `HEAT`,
    classTags: [`FIGHTER`, `MAGE`],
    playstyleTags: [`ZONE_CONTROL`, `EXTENDED_FIGHT`, `LANE_PRESSURE`],
    utilityTags: [`SLOW`, `MAGIC_RESIST_REDUCTION`, `SHIELD`],
    riskTags: [`COOLDOWN_MANAGEMENT`, `COMMIT_HEAVY`, `KITEABLE`],
    strengths: [
      `MAGIC_DAMAGE`,
      `AREA_DAMAGE`,
      `ZONE_CONTROL`,
      `TEAMFIGHT`,
      `LANE_PRESSURE`,
    ],
    weaknesses: [
      `HIGH_MAGIC_RESIST`,
      `DISENGAGE`,
      `LONG_RANGE_POKE`,
      `POINT_AND_CLICK_CC`,
    ],
  },
  // RYZE
  {
    key: `ryze`,
    name: `Ryze`,
    title: `The Rune Mage`,
    titleVi: `Pháp Sư Cổ Ngữ`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`SCALING`, `DPS`, `ABILITY_RELIANT_CHAMPION`],
    utilityTags: [`ROOT`, `SLOW`, `SPEED_UP`, `TELEPORT`],
    riskTags: [`MANA_RELIANT`, `POSITIONING_RELIANT`, `CC_VULNERABLE`],
    strengths: [
      `SCALING_DAMAGE`,
      `WAVE_CLEAR`,
      `MAP_PRESSURE`,
      `MACRO`,
      `TEAM_COORDINATION`,
    ],
    weaknesses: [
      `LONG_RANGE_POKE`,
      `HIGH_MAGIC_RESIST`,
      `POINT_AND_CLICK_CC`,
      `LOW_RANGE_CHAMPION`,
    ],
  },
  // SAMIRA
  {
    key: `samira`,
    name: `Samira`,
    title: `The Desert Rose`,
    titleVi: `Đóa Hồng Sa Mạc`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `ASSASSIN`],
    playstyleTags: [`BURST`, `MOBILITY`, `RESET_CHAMPION`],
    utilityTags: [`DASH`, `PROJECTILE_BLOCK`, `TAKEDOWN_RESET`],
    riskTags: [`SHORT_RANGE_MARKSMAN`, `COMMIT_HEAVY`, `CC_VULNERABLE`],
    strengths: [
      `TEAMFIGHT_CLEANUP`,
      `RESET_CARRY`,
      `BURST_DAMAGE`,
      `MOBILITY`,
      `SNOWBALL`,
    ],
    weaknesses: [
      `POINT_AND_CLICK_CC`,
      `LONG_RANGE_POKE`,
      `DISENGAGE`,
      `ANTI_BURST`,
    ],
  },
  // SENNA
  {
    key: `senna`,
    name: `Senna`,
    title: `The Redeemer`,
    titleVi: `Người Cứu Chuộc`,
    roles: [GameRole.SUPPORT, GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `ENCHANTER`],
    playstyleTags: [`SCALING`, `POKE`, `TEAM_SUPPORT`],
    utilityTags: [`HEALING`, `SHIELDING`, `ROOT`, `CAMOUFLAGE`],
    riskTags: [`POSITIONING_RELIANT`, `SQUISHY`, `WEAK_EARLY_GAME`],
    strengths: [
      `SCALING_DAMAGE`,
      `TEAM_SUPPORT`,
      `LONG_RANGE_POKE`,
      `VISION_CONTROL`,
      `GLOBAL_RANGE`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `ANTI_HEAL`, `ANTI_SHIELD`],
  },
  // SERAPHINE
  {
    key: `seraphine`,
    name: `Seraphine`,
    title: `The Starry-Eyed Songstress`,
    titleVi: `Ca Sĩ Mộng Mơ`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `ENCHANTER`],
    playstyleTags: [`POKE`, `TEAM_SUPPORT`, `SCALING`],
    utilityTags: [`SHIELDING`, `HEALING`, `CHARM`, `SLOW`],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `MANA_RELIANT`],
    strengths: [
      `TEAM_SUPPORT`,
      `LONG_RANGE_POKE`,
      `CROWD_CONTROL`,
      `TEAMFIGHT_SETUP`,
      `SHIELDING`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `ANTI_HEAL`, `ANTI_SHIELD`],
  },
  // SETT
  {
    key: `sett`,
    name: `Sett`,
    title: `The Boss`,
    titleVi: `Đại Ca`,
    roles: [GameRole.TOP],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `NONE`,
    classTags: [`FIGHTER`, `JUGGERNAUT`],
    playstyleTags: [`DUELIST`, `EXTENDED_FIGHT`, `LANE_PRESSURE`],
    utilityTags: [`SHIELD`, `STUN`, `SUPPRESS`, `SLOW`],
    riskTags: [`KITEABLE`, `LOW_MOBILITY`, `COOLDOWN_RELIANT`],
    strengths: [
      `DUELING`,
      `FRONTLINE`,
      `TRUE_DAMAGE`,
      `ANTI_TANK`,
      `TEAMFIGHT`,
    ],
    weaknesses: [`KITE`, `DISENGAGE`, `LONG_RANGE_POKE`, `HIGH_MOBILITY`],
  },
  // SHEN
  {
    key: `shen`,
    name: `Shen`,
    title: `The Eye of Twilight`,
    titleVi: `Mắt Hoàng Hôn`,
    roles: [GameRole.TOP, GameRole.SUPPORT],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `ENERGY`,
    classTags: [`TANK`, `VANGUARD`],
    playstyleTags: [`TEAM_SUPPORT`, `SPLIT_PUSH`, `MACRO`],
    utilityTags: [`TAUNT`, `SHIELDING`, `TELEPORT`, `DASH`],
    riskTags: [`TEAM_DEPENDENT`, `ENERGY_RELIANT`, `COOLDOWN_RELIANT`],
    strengths: [`FRONTLINE`, `PEEL`, `TEAM_SUPPORT`, `MAP_PRESSURE`, `DUELING`],
    weaknesses: [`KITE`, `DISENGAGE`, `TRUE_DAMAGE`, `ANTI_SHIELD`],
  },
  // SHYVANA
  {
    key: `shyvana`,
    name: `Shyvana`,
    title: `The Half-Dragon`,
    titleVi: `Long Nữ`,
    roles: [GameRole.JUNGLE],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `LOW`,
    resourceType: `FURY`,
    classTags: [`FIGHTER`, `JUGGERNAUT`],
    playstyleTags: [`EXTENDED_FIGHT`, `JUNGLE_CLEAR`, `SCALING`],
    utilityTags: [`DASH`, `KNOCK_BACK`, `SLOW`, `OMNIVAMP`],
    riskTags: [`ULTIMATE_RELIANT_CHAMPION`, `KITEABLE`, `FORM_RELIANT`],
    strengths: [
      `JUNGLE_CLEAR`,
      `OBJECTIVE_CONTROL`,
      `SCALING_DAMAGE`,
      `EXTENDED_FIGHT`,
      `TEAMFIGHT`,
    ],
    weaknesses: [`KITE`, `DISENGAGE`, `POINT_AND_CLICK_CC`, `LOW_CC`],
  },
  // SINGED
  {
    key: `singed`,
    name: `Singed`,
    title: `The Mad Chemist`,
    titleVi: `Dược Sĩ Điên`,
    roles: [GameRole.TOP],
    damageType: `MAGIC`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`TANK`, `MAGE`],
    playstyleTags: [`ZONE_CONTROL`, `DRAIN_TANK`, `SPLIT_PUSH`],
    utilityTags: [`SLOW`, `ROOT`, `DISPLACEMENT`, `ANTI_DASH`],
    riskTags: [`KITEABLE`, `MANA_RELIANT`, `TEAM_DEPENDENT`],
    strengths: [
      `ZONE_CONTROL`,
      `SUSTAIN_DAMAGE`,
      `DISENGAGE`,
      `ANTI_HEAL`,
      `SIDE_LANE`,
    ],
    weaknesses: [
      `LONG_RANGE_POKE`,
      `HIGH_MOBILITY`,
      `BURST_DAMAGE`,
      `LOW_RANGE_CHAMPION`,
    ],
  },
  // SION
  {
    key: `sion`,
    name: `Sion`,
    title: `The Undead Juggernaut`,
    titleVi: `Chiến Binh Bất Tử`,
    roles: [GameRole.TOP],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`TANK`, `JUGGERNAUT`],
    playstyleTags: [`ENGAGE`, `SPLIT_PUSH`, `SCALING`],
    utilityTags: [`KNOCK_UP`, `STUN`, `SLOW`, `ARMOR_SHRED`],
    riskTags: [`KITEABLE`, `INTERRUPT_VULNERABLE`, `COOLDOWN_RELIANT`],
    strengths: [
      `FRONTLINE`,
      `ENGAGE`,
      `TEAMFIGHT_SETUP`,
      `SCALING_HEALTH`,
      `TOWER_DIVE`,
    ],
    weaknesses: [
      `KITE`,
      `DISENGAGE`,
      `HIGH_MOBILITY`,
      `PUNISHABLE_WHEN_MISSED`,
    ],
  },
  // SIVIR
  {
    key: `sivir`,
    name: `Sivir`,
    title: `The Battle Mistress`,
    titleVi: `Nữ Chúa Chiến Trường`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`],
    playstyleTags: [`UTILITY_MARKSMAN`, `AUTO_ATTACK_CHAMPION`, `SCALING`],
    utilityTags: [`SPEED_UP`, `SPELL_SHIELD`, `TEAM_SUPPORT`],
    riskTags: [`POSITIONING_RELIANT`, `MANA_RELIANT`, `SQUISHY`],
    strengths: [
      `WAVE_CLEAR`,
      `TEAM_SUPPORT`,
      `SAFE_POSITIONING`,
      `SCALING_DAMAGE`,
      `MACRO`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `LONG_RANGE_POKE`, `LOW_RANGE_CHAMPION`],
  },
  // SKARNER
  {
    key: `skarner`,
    name: `Skarner`,
    title: `The Primordial Sovereign`,
    titleVi: `Đế Vương Nguyên Thủy`,
    roles: [GameRole.JUNGLE, GameRole.TOP],
    damageType: `MIXED`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`TANK`, `VANGUARD`],
    playstyleTags: [`ENGAGE`, `ZONE_CONTROL`, `EXTENDED_FIGHT`],
    utilityTags: [`SUPPRESS`, `STUN`, `SLOW`, `DISPLACEMENT`],
    riskTags: [`COMMIT_HEAVY`, `COOLDOWN_RELIANT`, `KITEABLE`],
    strengths: [
      `FRONTLINE`,
      `ENGAGE`,
      `PICK_POTENTIAL`,
      `TEAMFIGHT_SETUP`,
      `OBJECTIVE_CONTROL`,
    ],
    weaknesses: [`DISENGAGE`, `KITE`, `LONG_RANGE_POKE`, `HIGH_MOBILITY`],
  },
  // SMOLDER
  {
    key: `smolder`,
    name: `Smolder`,
    title: `The Fiery Fledgling`,
    titleVi: `Rồng Non Rực Lửa`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `MAGE`],
    playstyleTags: [`SCALING`, `POKE`, `ABILITY_RELIANT_CHAMPION`],
    utilityTags: [`SLOW`, `FLIGHT`, `TERRAIN_TRAVEL`, `VISION`],
    riskTags: [`WEAK_EARLY_GAME`, `POSITIONING_RELIANT`, `SQUISHY`],
    strengths: [
      `SCALING_DAMAGE`,
      `WAVE_CLEAR`,
      `MIXED_DAMAGE`,
      `LONG_RANGE_POKE`,
      `TEAMFIGHT`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `POINT_AND_CLICK_CC`, `WEAK_EARLY_GAME`],
  },
  // SONA
  {
    key: `sona`,
    name: `Sona`,
    title: `Maven of the Strings`,
    titleVi: `Đại Cầm Nữ`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`ENCHANTER`, `MAGE`],
    playstyleTags: [`TEAM_SUPPORT`, `SCALING`, `POKE`],
    utilityTags: [`HEALING`, `SHIELDING`, `SPEED_UP`, `STUN`],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `MANA_RELIANT`],
    strengths: [
      `TEAM_SUPPORT`,
      `SUSTAIN_TEAM`,
      `SCALING_GAME`,
      `PEEL`,
      `TEAMFIGHT`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `ANTI_HEAL`, `ANTI_SHIELD`],
  },
  // SORAKA
  {
    key: `soraka`,
    name: `Soraka`,
    title: `The Starchild`,
    titleVi: `Tinh Nữ`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`POKE`, `SUSTAIN`, `SCALING`],
    utilityTags: [`HEALING`, `SHIELDING`, `SILENCE`, `ROOT`, `SPEED_UP`],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `VULNERABLE_TO_DIVE`],
    strengths: [`HEALING`, `TEAM_SUPPORT`, `SUSTAIN_TEAM`, `LANE_SURVIVAL`],
    weaknesses: [`ANTI_HEAL`, `DIVE`, `ASSASSIN`, `LOW_MOBILITY`],
  },
  // SWAIN
  {
    key: `swain`,
    name: `Swain`,
    title: `The Noxian Grand General`,
    titleVi: `Đại Tướng Noxus`,
    roles: [GameRole.MID, GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`DRAIN_TANK`, `ZONE_CONTROL`, `EXTENDED_FIGHT_CHAMPION`],
    utilityTags: [`ROOT`, `PULL`, `SLOW`, `REVEAL`, `SELF_HEAL`],
    riskTags: [`LOW_MOBILITY`, `POSITIONING_RELIANT`, `ANTI_HEAL_VULNERABLE`],
    strengths: [`SUSTAIN`, `AREA_DAMAGE`, `TEAMFIGHT`, `SCALING_HEALTH`],
    weaknesses: [`ANTI_HEAL`, `KITE`, `LONG_RANGE_POKE`, `HIGH_MOBILITY`],
  },
  // SYNDRA
  {
    key: `syndra`,
    name: `Syndra`,
    title: `The Dark Sovereign`,
    titleVi: `Nữ Chúa Bóng Tối`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`BURST`, `PICK`, `ZONE_CONTROL`, `SCALING`],
    utilityTags: [`STUN`, `KNOCK_BACK`, `SLOW`, `LOW_HEALTH_EXECUTE`],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `SKILLSHOT_RELIANT`],
    strengths: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `AREA_DAMAGE`,
      `PICK_POTENTIAL`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `HIGH_MOBILITY`, `LONG_RANGE_POKE`],
  },
  // TALIYAH
  {
    key: `taliyah`,
    name: `Taliyah`,
    title: `The Stoneweaver`,
    titleVi: `Phù Thủy Đá`,
    roles: [GameRole.MID, GameRole.JUNGLE],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`, `CONTROL_MAGE`],
    playstyleTags: [`POKE`, `ZONE_CONTROL`, `ROAMING`, `SKIRMISH`],
    utilityTags: [`SLOW`, `STUN`, `KNOCK_BACK`, `TERRAIN_CONTROL`, `SPEED_UP`],
    riskTags: [`SKILLSHOT_RELIANT`, `POSITIONING_RELIANT`, `SQUISHY`],
    strengths: [`MAGIC_DAMAGE`, `AREA_DAMAGE`, `ZONE_CONTROL`, `ROAMING`],
    weaknesses: [`DIVE`, `ASSASSIN`, `HIGH_MOBILITY`, `POINT_AND_CLICK_CC`],
  },
  // TALON
  {
    key: `talon`,
    name: `Talon`,
    title: `The Blade's Shadow`,
    titleVi: `Sát Thủ Bóng Đêm`,
    roles: [GameRole.MID, GameRole.JUNGLE],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`ASSASSIN`],
    playstyleTags: [`BURST`, `MOBILITY`, `ROAMING`, `SNOWBALL`],
    utilityTags: [`DASH`, `INVISIBILITY`, `SPEED_UP`, `TERRAIN_TRAVEL`],
    riskTags: [`COMMIT_HEAVY`, `CC_VULNERABLE`, `HIGH_EXECUTION`],
    strengths: [`BURST_DAMAGE`, `PICK_POTENTIAL`, `MAP_PRESSURE`, `SNOWBALL`],
    weaknesses: [`POINT_AND_CLICK_CC`, `ANTI_BURST`, `PEEL`, `TEAMFIGHT`],
  },
  // TEEMO
  {
    key: `teemo`,
    name: `Teemo`,
    title: `The Swift Scout`,
    titleVi: `Trinh Sát Nhanh Nhẹn`,
    roles: [GameRole.TOP],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `MAGE`],
    playstyleTags: [`POKE`, `ZONE_CONTROL`, `ON_HIT_CHAMPION`],
    utilityTags: [`CAMOUFLAGE`, `SLOW`, `SPEED_UP`, `TRAP`],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `VULNERABLE_TO_DIVE`],
    strengths: [
      `MAGIC_DAMAGE`,
      `BURN_DAMAGE`,
      `ZONE_CONTROL`,
      `ANTI_ATTACK_SPEED`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `LONG_RANGE_POKE`, `POINT_AND_CLICK_CC`],
  },
  // THRESH
  {
    key: `thresh`,
    name: `Thresh`,
    title: `The Chain Warden`,
    titleVi: `Cai Ngục Xiềng Xích`,
    roles: [GameRole.SUPPORT],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `HIGH`,
    resourceType: `MANA`,
    classTags: [`VANGUARD`],
    playstyleTags: [`PICK`, `ZONE_CONTROL`, `UTILITY_MARKSMAN`],
    utilityTags: [`HOOK`, `PULL`, `ALLY_SHIELD`, `ALLY_DASH`, `SLOW`],
    riskTags: [`SKILLSHOT_RELIANT`, `HIGH_EXECUTION`, `PUNISHABLE_WHEN_MISSED`],
    strengths: [`PICK_POTENTIAL`, `PEEL`, `CROWD_CONTROL`, `TEAM_SUPPORT`],
    weaknesses: [
      `POKE_COMPOSITION`,
      `HIGH_MOBILITY`,
      `DISENGAGE`,
      `LOW_KILL_PRESSURE`,
    ],
  },
  // TRISTANA
  {
    key: `tristana`,
    name: `Tristana`,
    title: `The Yordle Gunner`,
    titleVi: `Tay Súng Yordle`,
    roles: [GameRole.ADC],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `LOW`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `HYPERCARRY`],
    playstyleTags: [`AUTO_ATTACK_CHAMPION`, `SCALING`, `SNOWBALL`],
    utilityTags: [`LEAP`, `KNOCK_BACK`, `SLOW`, `ATTACK_SPEED_STEROID`],
    riskTags: [`POSITIONING_RELIANT`, `RESET_RELIANT`, `VULNERABLE_TO_DIVE`],
    strengths: [
      `PHYSICAL_DAMAGE`,
      `SCALING_GAME`,
      `TEAMFIGHT_CLEANUP`,
      `TOWER_DIVE`,
    ],
    weaknesses: [`POINT_AND_CLICK_CC`, `ASSASSIN`, `ANTI_ATTACK_SPEED`, `DIVE`],
  },
  // TRYNDAMERE
  {
    key: `tryndamere`,
    name: `Tryndamere`,
    title: `The Barbarian King`,
    titleVi: `Bá Vương Man Di`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `MELEE`,
    difficulty: `MEDIUM`,
    resourceType: `FURY`,
    classTags: [`FIGHTER`, `SKIRMISHER`],
    playstyleTags: [`DUELIST`, `SPLIT_PUSH`, `AUTO_ATTACK_CHAMPION`],
    utilityTags: [`DASH`, `SELF_HEAL`, `INVULNERABILITY`, `SLOW`],
    riskTags: [`KITEABLE`, `CC_VULNERABLE`, `COMMIT_HEAVY`],
    strengths: [`DUELING`, `SPLIT_PUSH`, `SUSTAIN`, `TOWER_DIVE`],
    weaknesses: [`KITE`, `POINT_AND_CLICK_CC`, `ANTI_HEAL`, `DISENGAGE`],
  },
  // TWISTED FATE
  {
    key: `twisted-fate`,
    name: `Twisted Fate`,
    title: `The Card Master`,
    titleVi: `Thần Bài`,
    roles: [GameRole.MID],
    damageType: `MAGIC`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MAGE`],
    playstyleTags: [`BURST`, `PICK`, `ROAMING`, `BONUS_GOLD`],
    utilityTags: [`STUN`, `SLOW`, `REVEAL`, `TELEPORT`],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `LOW_MOBILITY`],
    strengths: [`PICK_POTENTIAL`, `MAP_PRESSURE`, `MACRO`, `BONUS_GOLD`],
    weaknesses: [`DIVE`, `ASSASSIN`, `POINT_AND_CLICK_CC`, `HIGH_MOBILITY`],
  },
  // TWITCH
  {
    key: `twitch`,
    name: `Twitch`,
    title: `The Plague Rat`,
    titleVi: `Chuột Thành Tinh`,
    roles: [GameRole.ADC, GameRole.JUNGLE],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `ASSASSIN`],
    playstyleTags: [`AUTO_ATTACK_CHAMPION`, `ON_HIT_CHAMPION`, `SCALING`],
    utilityTags: [`CAMOUFLAGE`, `SLOW`, `TRUE_DAMAGE`, `ATTACK_RANGE_BUFF`],
    riskTags: [`SQUISHY`, `POSITIONING_RELIANT`, `WEAK_EARLY_GAME`],
    strengths: [`TRUE_DAMAGE`, `DPS`, `TEAMFIGHT_CLEANUP`, `BACKLINE_ACCESS`],
    weaknesses: [`REVEAL`, `ASSASSIN`, `POINT_AND_CLICK_CC`, `DIVE`],
  },
  // URGOT
  {
    key: `urgot`,
    name: `Urgot`,
    title: `The Dreadnought`,
    titleVi: `Pháo Đài Di Động`,
    roles: [GameRole.TOP],
    damageType: `PHYSICAL`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`JUGGERNAUT`, `MARKSMAN`],
    playstyleTags: [`DPS`, `ZONE_CONTROL`, `DUELIST`],
    utilityTags: [`SLOW`, `STUN`, `DASH`, `SELF_SHIELD`, `LOW_HEALTH_EXECUTE`],
    riskTags: [`KITEABLE`, `LOW_MOBILITY`, `COMMIT_HEAVY`],
    strengths: [
      `PHYSICAL_DAMAGE`,
      `PERCENT_HEALTH_DAMAGE`,
      `DUELING`,
      `TEAMFIGHT`,
    ],
    weaknesses: [`KITE`, `LONG_RANGE_POKE`, `HIGH_MOBILITY`, `DISENGAGE`],
  },
  // VARUS
  {
    key: `varus`,
    name: `Varus`,
    title: `The Arrow of Retribution`,
    titleVi: `Mũi Tên Báo Thù`,
    roles: [GameRole.ADC],
    damageType: `MIXED`,
    rangeType: `RANGED`,
    difficulty: `MEDIUM`,
    resourceType: `MANA`,
    classTags: [`MARKSMAN`, `MAGE`],
    playstyleTags: [`POKE`, `ON_HIT_CHAMPION`, `ABILITY_RELIANT_CHAMPION`],
    utilityTags: [`ROOT`, `SLOW`, `GRIEVOUS_WOUNDS`, `PICK_POTENTIAL`],
    riskTags: [`IMMOBILE`, `POSITIONING_RELIANT`, `SKILLSHOT_RELIANT`],
    strengths: [
      `MIXED_DAMAGE`,
      `PERCENT_HEALTH_DAMAGE`,
      `POKE_SETUP`,
      `TEAMFIGHT_SETUP`,
    ],
    weaknesses: [`DIVE`, `ASSASSIN`, `HIGH_MOBILITY`, `POINT_AND_CLICK_CC`],
  },
];

export async function seedChampions(prisma: PrismaClient) {
  for (const championSeed of championSeeds) {
    const champion = await prisma.champion.upsert({
      where: {
        key: championSeed.key,
      },
      update: {
        name: championSeed.name,
        title: championSeed.title ?? null,
        titleVi: championSeed.titleVi ?? null,
        roles: championSeed.roles,
        damageType: championSeed.damageType,
        rangeType: championSeed.rangeType,
        difficulty: championSeed.difficulty,
        resourceType: championSeed.resourceType,
        classTags: championSeed.classTags ?? [],
        playstyleTags: championSeed.playstyleTags ?? [],
        utilityTags: championSeed.utilityTags ?? [],
        riskTags: championSeed.riskTags ?? [],
        strengths: championSeed.strengths ?? [],
        weaknesses: championSeed.weaknesses ?? [],
        deletedAt: null,
        archivedAt: null,
      },
      create: championSeed,
    });

    console.log(`Seeded champion: ${champion.name}`);
  }

  console.log(`SEEDED CHAMPIONS`);
}
