import { PrismaClient } from '../../src/generated/prisma/client.js';
import {
  DataQualityLevel,
  GameRole,
} from '../../src/generated/prisma/enums.js';

type ChampionMatchupProfileSeed = {
  championKey: string;
  role: GameRole;
  goodIntoTags: string[];
  weakIntoTags: string[];
  banRiskTags: string[];
  laneNotes?: string | null;
  dataQuality?: DataQualityLevel;
};

const championMatchupProfileSeeds: ChampionMatchupProfileSeed[] = [
  // AATROX
  {
    championKey: `aatrox`,
    role: GameRole.TOP,
    goodIntoTags: [
      `MELEE_CHAMPION`,
      `LOW_RANGE_CHAMPION`,
      `TANK`,
      `BRUISER`,
      `FRONTLINE`,
      `LOW_BURST`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `POINT_AND_CLICK_CC`,
      `ANTI_HEAL`,
      `KITE`,
      `LONG_RANGE_CHAMPION`,
      `DUELING`,
    ],
    banRiskTags: [`ANTI_HEAL`, `HIGH_MOBILITY`, `POINT_AND_CLICK_CC`, `KITE`],
    laneNotes: `Aatrox is strong into melee frontliners and slower bruisers because he can win extended trades through sustain, sweet spot damage, and repeated crowd control. He struggles into mobile duelists and champions that can dodge The Darkin Blade sweet spots or apply anti-heal. Fiora, Irelia, and Ambessa are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `aatrox`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `MELEE_CHAMPION`,
      `LOW_RANGE_CHAMPION`,
      `FRONTLINE`,
      `LOW_CC`,
      `EXTENDED_FIGHT`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `POINT_AND_CLICK_CC`,
      `ANTI_HEAL`,
      `DISENGAGE`,
      `KITE`,
    ],
    banRiskTags: [
      `ANTI_HEAL`,
      `HIGH_MOBILITY`,
      `DISENGAGE`,
      `POINT_AND_CLICK_CC`,
    ],
    laneNotes: `Jungle Aatrox prefers skirmish-heavy games where he can enter extended fights and drain tank. He is weaker when enemies can disengage, kite him, or lock him down before World Ender gets value.`,
    dataQuality: DataQualityLevel.MINIMAL,
  },
  // AHRI
  {
    championKey: `ahri`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_MAGIC_RESIST`,
      `LOW_CC`,
      `LOW_BURST`,
      `MELEE_CHAMPION`,
    ],
    weakIntoTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `LONG_RANGE_POKE`,
      `CONTROL_MAGE`,
      `POINT_AND_CLICK_CC`,
      `BURST_DAMAGE`,
    ],
    banRiskTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `LONG_RANGE_POKE`,
      `POINT_AND_CLICK_CC`,
      `BURST_DAMAGE`,
    ],
    laneNotes: `Ahri is strong into squishy or low-mobility mid laners because Charm creates pick windows and Spirit Rush lets her reposition after trades. She can struggle against champions that outrange her, punish missed Charm, or burst her before she can reset the fight. Akali, Syndra, and Orianna are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AKALI
  {
    championKey: `akali`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_MAGIC_RESIST`,
      `LOW_CC`,
      `LONG_RANGE_CHAMPION`,
      `POKE_COMPOSITION`,
    ],
    weakIntoTags: [
      `POINT_AND_CLICK_CC`,
      `LOCKDOWN`,
      `CROWD_CONTROL`,
      `ANTI_MAGIC`,
      `BURST_DAMAGE`,
      `LONG_RANGE_SAFE_PLAY`,
    ],
    banRiskTags: [
      `POINT_AND_CLICK_CC`,
      `LOCKDOWN`,
      `CROWD_CONTROL`,
      `ANTI_MAGIC`,
      `LONG_RANGE_SAFE_PLAY`,
    ],
    laneNotes: `Mid Akali is strong into squishy mages and low-mobility champions once she has enough levels to threaten all-ins. She struggles against reliable lockdown, point-and-click crowd control, and champions that can safely control space before she reaches them. Veigar, Lissandra, and Twisted Fate are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `akali`,
    role: GameRole.TOP,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_MAGIC_RESIST`,
      `MELEE_CHAMPION`,
      `LOW_CC`,
      `SIDE_LANE`,
    ],
    weakIntoTags: [
      `BRUISER`,
      `HIGH_MOBILITY`,
      `POINT_AND_CLICK_CC`,
      `ANTI_MAGIC`,
      `MELEE_TRADING`,
      `EARLY_GAME_PRESSURE`,
    ],
    banRiskTags: [
      `BRUISER`,
      `HIGH_MOBILITY`,
      `POINT_AND_CLICK_CC`,
      `EARLY_GAME_PRESSURE`,
      `ANTI_MAGIC`,
    ],
    laneNotes: `Solo lane Akali needs careful early trading and usually prefers scaling into mobility-based side lane fights. She can struggle into strong melee bruisers that punish her early cooldowns or survive her burst. Ambessa, Renekton, and Aatrox are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AKSHAN
  {
    championKey: `akshan`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `LOW_BURST`,
      `MELEE_CHAMPION`,
      `LOW_CC`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `ASSASSIN`,
      `POINT_AND_CLICK_CC`,
      `HARD_ENGAGE`,
      `WIND_WALL`,
      `BURST_DAMAGE`,
    ],
    banRiskTags: [
      `HIGH_MOBILITY`,
      `ASSASSIN`,
      `POINT_AND_CLICK_CC`,
      `HARD_ENGAGE`,
      `WIND_WALL`,
    ],
    laneNotes: `Akshan can punish low-mobility mid laners with ranged trades, roaming pressure, and cleanup threat. He struggles against champions that can block projectiles, force all-ins, or lock him down before he can kite with Heroic Swing. Yasuo, Vex, and Irelia are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // ALISTAR
  {
    championKey: `alistar`,
    role: GameRole.SUPPORT,
    goodIntoTags: [
      `DIVE`,
      `MELEE_CHAMPION`,
      `LOW_RANGE_CHAMPION`,
      `ASSASSIN`,
      `LOW_MOBILITY`,
      `LOW_CC`,
    ],
    weakIntoTags: [
      `DISENGAGE`,
      `ENCHANTER`,
      `LONG_RANGE_POKE`,
      `POKE_COMPOSITION`,
      `CROWD_CONTROL`,
      `LONG_RANGE_SAFE_PLAY`,
    ],
    banRiskTags: [
      `DISENGAGE`,
      `ENCHANTER`,
      `LONG_RANGE_POKE`,
      `POKE_COMPOSITION`,
      `CROWD_CONTROL`,
    ],
    laneNotes: `Alistar is strong into dive and short-range engage because he can interrupt, peel, and punish enemies that walk into Headbutt + Pulverize range. He struggles against disengage, long-range poke, and lanes that can keep him low before he finds an engage angle. Janna, Zyra, and Ashe are notable difficult lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AMBESSA
  {
    championKey: `ambessa`,
    role: GameRole.TOP,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `LOW_CC`,
      `SIDE_LANE`,
      `MELEE_CHAMPION`,
    ],
    weakIntoTags: [
      `BRUISER`,
      `TANK`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
      `ANTI_DASH`,
      `EARLY_GAME_PRESSURE`,
    ],
    banRiskTags: [
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
      `ANTI_DASH`,
      `EARLY_GAME_PRESSURE`,
      `TANK`,
    ],
    laneNotes: `Solo lane Ambessa is strongest when she can use mobility to win extended trades, dodge skillshots, and punish low-mobility targets. She struggles into champions that can interrupt dashes, survive her burst, or punish her early trading windows. Renekton, Malphite, and Irelia are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `ambessa`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_CC`,
      `ISOLATED_TARGET`,
      `LOW_DURABILITY_TEAM`,
      `SKIRMISH`,
    ],
    weakIntoTags: [
      `TANK`,
      `FRONTLINE`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
      `ANTI_DASH`,
      `HARD_ENGAGE`,
    ],
    banRiskTags: [
      `TANK`,
      `POINT_AND_CLICK_CC`,
      `ANTI_DASH`,
      `CROWD_CONTROL`,
      `HARD_ENGAGE`,
    ],
    laneNotes: `Jungle Ambessa prefers skirmish-heavy games where she can punish isolated or low-mobility targets. She struggles when enemy tanks and anti-dash tools deny her entry angles or lock her down after she commits. Rammus, Poppy, and Malphite are notable difficult examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AMUMU
  {
    championKey: `amumu`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `GROUPED_ENEMIES`,
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `MELEE_CHAMPION`,
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `DISENGAGE`,
      `LONG_RANGE_POKE`,
      `JUNGLE_CLEAR`,
      `ISOLATED_TARGET`,
      `ANTI_TANK`,
    ],
    banRiskTags: [
      `HIGH_MOBILITY`,
      `DISENGAGE`,
      `LONG_RANGE_POKE`,
      `ANTI_TANK`,
      `ISOLATED_TARGET`,
    ],
    laneNotes: `Amumu is strongest when enemies group and cannot easily avoid Bandage Toss or Curse of the Sad Mummy. He struggles against fast-clearing or mobile junglers that can invade, kite, or punish his early tempo. Lillia, Nocturne, and Nidalee are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // ANNIE
  {
    championKey: `annie`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_MAGIC_RESIST`,
      `LOW_RANGE_CHAMPION`,
      `LOW_BURST`,
      `GROUPED_ENEMIES`,
    ],
    weakIntoTags: [
      `LONG_RANGE_POKE`,
      `CONTROL_MAGE`,
      `LONG_RANGE_SAFE_PLAY`,
      `HIGH_MOBILITY`,
      `CROWD_CONTROL`,
      `BURST_DAMAGE`,
    ],
    banRiskTags: [
      `LONG_RANGE_POKE`,
      `CONTROL_MAGE`,
      `LONG_RANGE_SAFE_PLAY`,
      `HIGH_MOBILITY`,
      `CROWD_CONTROL`,
    ],
    laneNotes: `Annie is strong into low-mobility and short-range champions because her passive stun creates reliable burst and pick windows. She struggles against longer-range control mages that can poke safely, punish her short range, or stop her engage before she reaches priority targets. Syndra, Lissandra, and Viktor are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // ASHE
  {
    championKey: `ashe`,
    role: GameRole.ADC,
    goodIntoTags: [
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `MELEE_CHAMPION`,
      `LOW_CC`,
      `LOW_BURST`,
      `FRONTLINE`,
    ],
    weakIntoTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `BURST_DAMAGE`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `HARD_ENGAGE`,
    ],
    banRiskTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `BURST_DAMAGE`,
      `DIVE`,
      `HARD_ENGAGE`,
    ],
    laneNotes: `Ashe is strong into low-mobility targets and melee-heavy teams because Frost Shot makes kiting and follow-up easier. She struggles into longer-range marksmen, burst lanes, and aggressive all-in champions that can punish her lack of dash. Caitlyn, Draven, and Lucian are notable difficult duo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AURELION SOL
  {
    championKey: `aurelion-sol`,
    role: GameRole.MID,
    goodIntoTags: [
      `LOW_MOBILITY`,
      `GROUPED_ENEMIES`,
      `LOW_RANGE_CHAMPION`,
      `FRONTLINE`,
      `TANK`,
      `SCALING_GAME`,
    ],
    weakIntoTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `BURST_DAMAGE`,
      `WIND_WALL`,
      `POINT_AND_CLICK_CC`,
    ],
    banRiskTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `BURST_DAMAGE`,
      `WIND_WALL`,
    ],
    laneNotes: `Aurelion Sol is strong into slower teams and grouped enemies because his scaling damage, Singularity zone control, and upgraded ultimate can take over teamfights. He struggles against mobile assassins and dive champions that can punish his weak early windows or interrupt his positioning. Yone, Zed, and Yasuo are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AURORA
  {
    championKey: `aurora`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_MAGIC_RESIST`,
      `LOW_RANGE_CHAMPION`,
      `GROUPED_ENEMIES`,
      `LOW_CC`,
    ],
    weakIntoTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `BURST_DAMAGE`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
    ],
    banRiskTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `BURST_DAMAGE`,
      `POINT_AND_CLICK_CC`,
    ],
    laneNotes: `Aurora is strong into squishy or low-mobility mid laners because she can trade with burst, reposition, and trap enemies in strong teamfight zones. She struggles into mobile assassins and dive champions that can punish her before she controls the fight. Vex, Zed, and Irelia are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BARD
  {
    championKey: `bard`,
    role: GameRole.SUPPORT,
    goodIntoTags: [
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `LOW_CC`,
      `PICK_COMPOSITION`,
      `FOG_OF_WAR`,
      `GROUPED_ENEMIES`,
    ],
    weakIntoTags: [
      `ENCHANTER`,
      `LONG_RANGE_POKE`,
      `LONG_RANGE_SAFE_PLAY`,
      `SUSTAIN_TEAM`,
      `DISENGAGE`,
      `HIGH_MOBILITY`,
    ],
    banRiskTags: [
      `ENCHANTER`,
      `LONG_RANGE_POKE`,
      `SUSTAIN_TEAM`,
      `DISENGAGE`,
      `HIGH_MOBILITY`,
    ],
    laneNotes: `Bard is strong when he can roam, create picks with Cosmic Binding, and punish enemies through fog of war or terrain angles. He struggles into sustain-heavy or long-range support lanes that can poke safely and deny his engage windows. Nami, Senna, and Zilean are notable difficult support examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BLITZCRANK
  {
    championKey: `blitzcrank`,
    role: GameRole.SUPPORT,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `LONG_RANGE_CHAMPION`,
      `FOG_OF_WAR`,
      `LOW_DURABILITY_TEAM`,
    ],
    weakIntoTags: [
      `FRONTLINE`,
      `TANK`,
      `SPELL_SHIELD`,
      `PROJECTILE_BLOCK`,
      `DISENGAGE`,
      `POINT_AND_CLICK_CC`,
    ],
    banRiskTags: [
      `SPELL_SHIELD`,
      `PROJECTILE_BLOCK`,
      `DISENGAGE`,
      `FRONTLINE`,
      `POINT_AND_CLICK_CC`,
    ],
    laneNotes: `Blitzcrank is strongest when he can threaten squishy or low-mobility targets with Rocket Grab from fog of war. He struggles against tanky frontliners, spell shields, projectile blockers, and supports that can punish or deny his engage. Leona, Braum, and Morgana are notable difficult support examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BRAND
  {
    championKey: `brand`,
    role: GameRole.MID,
    goodIntoTags: [
      `GROUPED_ENEMIES`,
      `LOW_MOBILITY`,
      `FRONTLINE`,
      `TANK`,
      `LOW_RANGE_CHAMPION`,
      `LOW_DURABILITY_TEAM`,
    ],
    weakIntoTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `LONG_RANGE_POKE`,
      `BURST_DAMAGE`,
      `DIVE`,
      `POINT_AND_CLICK_CC`,
    ],
    banRiskTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `LONG_RANGE_POKE`,
      `BURST_DAMAGE`,
      `DIVE`,
    ],
    laneNotes: `Mid Brand is strong into grouped enemies and slower frontlines because his burn, area damage, and passive detonation punish clumped fights. He struggles against long-range poke, assassins, and dive champions that can punish his low mobility before he finishes his combo. Syndra, Zed, and Lux are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `brand`,
    role: GameRole.SUPPORT,
    goodIntoTags: [
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `GROUPED_ENEMIES`,
      `SUSTAIN_TEAM`,
      `TANK`,
      `FRONTLINE`,
    ],
    weakIntoTags: [
      `HARD_ENGAGE`,
      `DIVE`,
      `FRONTLINE`,
      `POINT_AND_CLICK_CC`,
      `BURST_DAMAGE`,
      `LONG_RANGE_SAFE_PLAY`,
    ],
    banRiskTags: [
      `HARD_ENGAGE`,
      `DIVE`,
      `POINT_AND_CLICK_CC`,
      `BURST_DAMAGE`,
      `FRONTLINE`,
    ],
    laneNotes: `Support Brand can dominate lanes where enemies are slow, short-ranged, or forced to group around minion waves. He struggles when engage supports or burst champions can reach him before he zones with spells. Braum, Pyke, and Maokai are notable difficult support examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BRAUM
  {
    championKey: `braum`,
    role: GameRole.SUPPORT,
    goodIntoTags: [
      `DIVE`,
      `ASSASSIN`,
      `LOW_RANGE_CHAMPION`,
      `MELEE_CHAMPION`,
      `PICK_COMPOSITION`,
      `BURST_DAMAGE`,
    ],
    weakIntoTags: [
      `LONG_RANGE_POKE`,
      `ENCHANTER`,
      `SUSTAIN_TEAM`,
      `DISENGAGE`,
      `HIGH_MOBILITY`,
      `LONG_RANGE_SAFE_PLAY`,
    ],
    banRiskTags: [
      `LONG_RANGE_POKE`,
      `ENCHANTER`,
      `SUSTAIN_TEAM`,
      `DISENGAGE`,
      `LONG_RANGE_SAFE_PLAY`,
    ],
    laneNotes: `Braum is strong into dive, burst, and projectile-based engage because he can protect carries with Unbreakable and punish enemies through Concussive Blows. He struggles into long-range poke and sustain-heavy supports that can avoid direct all-ins and slowly win lane. Senna, Bard, and Zilean are notable difficult support examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // CAITLYN
  {
    championKey: `caitlyn`,
    role: GameRole.ADC,
    goodIntoTags: [
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `MELEE_CHAMPION`,
      `LOW_CC`,
      `LOW_BURST`,
      `SAFE_POSITIONING`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `DIVE`,
      `HARD_ENGAGE`,
      `LONG_RANGE_POKE`,
      `BURST_DAMAGE`,
      `WAVE_CLEAR`,
    ],
    banRiskTags: [
      `HIGH_MOBILITY`,
      `DIVE`,
      `HARD_ENGAGE`,
      `BURST_DAMAGE`,
      `LONG_RANGE_POKE`,
    ],
    laneNotes: `Caitlyn is strong into shorter-range and low-mobility duo lanes because she can pressure with range, traps, and safe poke. She struggles against champions that can neutralize lane with wave clear, avoid her poke, or force all-ins before she can kite. Sivir, Ezreal, and Miss Fortune are notable difficult duo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // CAMILLE
  {
    championKey: `camille`,
    role: GameRole.TOP,
    goodIntoTags: [
      `TANK`,
      `FRONTLINE`,
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `SIDE_LANE`,
      `SQUISHY_CHAMPION`,
    ],
    weakIntoTags: [
      `BRUISER`,
      `POINT_AND_CLICK_CC`,
      `ANTI_DASH`,
      `CROWD_CONTROL`,
      `ANTI_TANK`,
      `MELEE_TRADING`,
    ],
    banRiskTags: [
      `POINT_AND_CLICK_CC`,
      `ANTI_DASH`,
      `CROWD_CONTROL`,
      `BRUISER`,
      `ANTI_TANK`,
    ],
    laneNotes: `Solo lane Camille is strong into slower frontliners and low-mobility targets because she can trade around Precision Protocol and threaten side-lane picks with Hextech Ultimatum. She struggles into champions that can outduel her early, deny her engage, or punish Hookshot timing. Malphite, Fiora, and Mordekaiser are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `camille`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `ISOLATED_TARGET`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `PICK_COMPOSITION`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `EARLY_GAME_PRESSURE`,
      `JUNGLE_CLEAR`,
      `CROWD_CONTROL`,
      `POINT_AND_CLICK_CC`,
      `DIVE`,
    ],
    banRiskTags: [
      `EARLY_GAME_PRESSURE`,
      `HIGH_MOBILITY`,
      `JUNGLE_CLEAR`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
    ],
    laneNotes: `Jungle Camille prefers games where she can punish isolated targets and use Hextech Ultimatum to guarantee picks. She can struggle against fast-tempo junglers that invade, duel early, or outpace her clear before she reaches strong gank windows. Lee Sin, Viego, and Nidalee are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // CORKI
  {
    championKey: `corki`,
    role: GameRole.ADC,
    goodIntoTags: [
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `FRONTLINE`,
      `TANK`,
      `GROUPED_ENEMIES`,
      `LOW_BURST`,
    ],
    weakIntoTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `LONG_RANGE_POKE`,
      `BURST_DAMAGE`,
      `DIVE`,
      `HIGH_MOBILITY`,
    ],
    banRiskTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `LONG_RANGE_POKE`,
      `BURST_DAMAGE`,
      `DIVE`,
    ],
    laneNotes: `Corki is strong when he can scale safely and poke before committing to fights. His mixed damage makes him useful into frontlines and teams that are harder to itemize against. He struggles into longer-range marksmen, strong lane poke, and burst or dive threats that can punish his positioning before he gets enough items. Kog'Maw, Miss Fortune, and Caitlyn are notable difficult duo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DARIUS
  {
    championKey: `darius`,
    role: GameRole.TOP,
    goodIntoTags: [
      `MELEE_CHAMPION`,
      `LOW_MOBILITY`,
      `TANK`,
      `FRONTLINE`,
      `BRUISER`,
      `EXTENDED_FIGHT`,
    ],
    weakIntoTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_MOBILITY`,
      `KITE`,
      `DISENGAGE`,
      `POINT_AND_CLICK_CC`,
      `ANTI_TANK`,
    ],
    banRiskTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_MOBILITY`,
      `KITE`,
      `DISENGAGE`,
      `POINT_AND_CLICK_CC`,
    ],
    laneNotes: `Solo lane Darius is strong into melee champions and slower frontliners because he can win extended trades, stack Hemorrhage, and threaten execute resets. He struggles into champions that can kite, poke, disengage, or deny his all-in windows before he reaches five stacks. Wukong, Malphite, and Jayce are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `darius`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `MELEE_CHAMPION`,
      `LOW_MOBILITY`,
      `FRONTLINE`,
      `TANK`,
      `LOW_CC`,
      `EXTENDED_FIGHT`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `KITE`,
      `LONG_RANGE_POKE`,
      `JUNGLE_CLEAR`,
      `DISENGAGE`,
      `ISOLATED_TARGET`,
    ],
    banRiskTags: [
      `HIGH_MOBILITY`,
      `KITE`,
      `LONG_RANGE_POKE`,
      `JUNGLE_CLEAR`,
      `DISENGAGE`,
    ],
    laneNotes: `Jungle Darius is strongest when fights happen around melee targets or slower frontlines that cannot easily escape his pull and bleed stacks. He struggles against fast, mobile junglers that can kite, invade, or out-tempo him before he reaches decisive skirmishes. Hecarim, Lillia, and Kindred are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DIANA
  {
    championKey: `diana`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_MAGIC_RESIST`,
      `GROUPED_ENEMIES`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
    ],
    weakIntoTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `ANTI_MAGE`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `BRUISER`,
    ],
    banRiskTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `ANTI_MAGE`,
      `HIGH_MOBILITY`,
      `CROWD_CONTROL`,
    ],
    laneNotes: `Mid Diana is strongest into squishy and low-mobility champions that can be punished by Crescent Strike into Lunar Rush and Moonfall. She struggles into champions that can interrupt her dash, survive her burst, or punish her commit-heavy engage. Vex, Galio, and Irelia are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `diana`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `GROUPED_ENEMIES`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `PICK_COMPOSITION`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `KITE`,
      `DUELING`,
      `ANTI_MAGE`,
      `POINT_AND_CLICK_CC`,
      `ISOLATED_TARGET`,
    ],
    banRiskTags: [
      `HIGH_MOBILITY`,
      `KITE`,
      `DUELING`,
      `ANTI_MAGE`,
      `POINT_AND_CLICK_CC`,
    ],
    laneNotes: `Jungle Diana is strong when lanes can help her enter fights and enemies are forced to group around objectives. She struggles against champions that can kite, duel her early, or isolate her before she lands Moonfall value. Master Yi, Kindred, and Mordekaiser are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DR. MUNDO
  {
    championKey: `dr-mundo`,
    role: GameRole.TOP,
    goodIntoTags: [
      `LOW_BURST`,
      `LOW_CC`,
      `TANK`,
      `FRONTLINE`,
      `LOW_RANGE_CHAMPION`,
      `SCALING_GAME`,
    ],
    weakIntoTags: [
      `ANTI_TANK`,
      `PERCENT_HEALTH_DAMAGE`,
      `TRUE_DAMAGE`,
      `ANTI_HEAL`,
      `DUELING`,
      `HIGH_MOBILITY`,
    ],
    banRiskTags: [
      `ANTI_TANK`,
      `PERCENT_HEALTH_DAMAGE`,
      `TRUE_DAMAGE`,
      `ANTI_HEAL`,
      `DUELING`,
    ],
    laneNotes: `Dr. Mundo is strong into teams that lack sustained damage, anti-heal, or reliable ways to punish his health stacking. He can absorb pressure well and scale into a durable frontline. He struggles into duelists and champions with true damage, percent-health damage, or strong anti-tank pressure. Riven, Gwen, and Fiora are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DRAVEN
  {
    championKey: `draven`,
    role: GameRole.ADC,
    goodIntoTags: [
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_DURABILITY_TEAM`,
      `LOW_BURST`,
      `SQUISHY_CHAMPION`,
      `EARLY_GAME_PRESSURE`,
    ],
    weakIntoTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `DIVE`,
      `BURST_DAMAGE`,
      `CROWD_CONTROL`,
      `HIGH_MOBILITY`,
    ],
    banRiskTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `DIVE`,
      `BURST_DAMAGE`,
      `CROWD_CONTROL`,
    ],
    laneNotes: `Draven is strongest into lanes he can bully early with Spinning Axe damage and snowball through Adoration cash-ins. He struggles when enemies outrange him, deny his axe positioning, or force burst all-ins before he can keep dealing damage. Caitlyn, Samira, and Kog'Maw are notable difficult duo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // EKKO
  {
    championKey: `ekko`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_MAGIC_RESIST`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `PICK_COMPOSITION`,
    ],
    weakIntoTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
      `BRUISER`,
      `HIGH_MOBILITY`,
      `BURST_DAMAGE`,
    ],
    banRiskTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
      `BRUISER`,
      `HIGH_MOBILITY`,
    ],
    laneNotes: `Mid Ekko is strong into squishy or low-mobility champions that can be punished by Phase Dive burst and passive proc trades. He struggles into champions that can interrupt his engage, lock him down before Chronobreak, or out-trade him in melee range. Vex, Irelia, and Lissandra are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `ekko`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `ISOLATED_TARGET`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `PICK_COMPOSITION`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `KITE`,
      `JUNGLE_CLEAR`,
      `CROWD_CONTROL`,
      `TANK`,
      `ANTI_ASSASSIN`,
    ],
    banRiskTags: [
      `HIGH_MOBILITY`,
      `KITE`,
      `JUNGLE_CLEAR`,
      `CROWD_CONTROL`,
      `ANTI_ASSASSIN`,
    ],
    laneNotes: `Jungle Ekko is strongest when he can attack squishy targets, punish isolated enemies, and use Chronobreak to survive aggressive skirmishes. He struggles against fast-clearing or mobile junglers that can kite him, invade his tempo, or deny his burst windows. Kindred, Lillia, and Amumu are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // EVELYNN
  {
    championKey: `evelynn`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MAGIC_RESIST`,
      `LOW_DURABILITY_TEAM`,
      `ISOLATED_TARGET`,
      `LOW_CC`,
      `LOW_MOBILITY`,
    ],
    weakIntoTags: [
      `VISION_CONTROL`,
      `TRUE_SIGHT`,
      `ANTI_ASSASSIN`,
      `POINT_AND_CLICK_CC`,
      `EARLY_GAME_PRESSURE`,
      `DUELING`,
    ],
    banRiskTags: [
      `VISION_CONTROL`,
      `TRUE_SIGHT`,
      `POINT_AND_CLICK_CC`,
      `EARLY_GAME_PRESSURE`,
      `DUELING`,
    ],
    laneNotes: `Evelynn is strongest into squishy teams and isolated targets because Demon Shade lets her create unexpected pick angles after level 5. She struggles against early invaders, strong duelists, vision control, and champions that can reveal or lock her down before she finishes her burst. Rengar, Twisted Fate, and Lee Sin are notable difficult examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // EZREAL
  {
    championKey: `ezreal`,
    role: GameRole.ADC,
    goodIntoTags: [
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `FRONTLINE`,
      `TANK`,
      `LOW_BURST`,
      `LONG_RANGE_SAFE_PLAY`,
    ],
    weakIntoTags: [
      `BURST_DAMAGE`,
      `HARD_ENGAGE`,
      `DIVE`,
      `HIGH_MOBILITY`,
      `PROJECTILE_BLOCK`,
      `LANE_KILL_PRESSURE`,
    ],
    banRiskTags: [
      `BURST_DAMAGE`,
      `HARD_ENGAGE`,
      `DIVE`,
      `PROJECTILE_BLOCK`,
      `LANE_KILL_PRESSURE`,
    ],
    laneNotes: `Ezreal is strong when he can farm safely, poke with Mystic Shot, and scale into mid-game item spikes. He performs well into slower or shorter-range teams because Arcane Shift gives him safe positioning. He struggles into high-pressure lanes, burst all-ins, and champions that can block or punish his skillshots. Draven, Miss Fortune, and Samira are notable difficult duo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // FIDDLESTICKS
  {
    championKey: `fiddlesticks`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `GROUPED_ENEMIES`,
      `LOW_MOBILITY`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `FOG_OF_WAR`,
      `TEAMFIGHT`,
    ],
    weakIntoTags: [
      `VISION_CONTROL`,
      `EARLY_GAME_PRESSURE`,
      `DUELING`,
      `INTERRUPT`,
      `DISENGAGE`,
      `POINT_AND_CLICK_CC`,
    ],
    banRiskTags: [
      `VISION_CONTROL`,
      `EARLY_GAME_PRESSURE`,
      `DUELING`,
      `INTERRUPT`,
      `DISENGAGE`,
    ],
    laneNotes: `Fiddlesticks is strongest when he can control vision, flank from fog of war, and punish grouped enemies with Crowstorm. He struggles against early invaders, duelists, interrupts, and disengage tools that deny his channel or prevent his ultimate from reaching priority targets. Nocturne, Aatrox, and Alistar are notable difficult examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // FIORA
  {
    championKey: `fiora`,
    role: GameRole.TOP,
    goodIntoTags: [
      `TANK`,
      `FRONTLINE`,
      `LOW_MOBILITY`,
      `MELEE_CHAMPION`,
      `SIDE_LANE`,
      `HIGH_HEALTH`,
    ],
    weakIntoTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `KITE`,
      `LONG_RANGE_CHAMPION`,
      `ANTI_TANK`,
      `AREA_DAMAGE`,
    ],
    banRiskTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `KITE`,
      `LONG_RANGE_CHAMPION`,
      `ANTI_TANK`,
    ],
    laneNotes: `Fiora is strongest into tanks, frontliners, and melee champions that let her trade around vitals and scale into side-lane duels. She struggles into champions that can deny Lunge angles, kite her, punish her short trades, or force teamfights before she wins split pressure. Rumble, Malphite, and Poppy are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // FIZZ
  {
    championKey: `fizz`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_MAGIC_RESIST`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `SKILLSHOT_RELIANT`,
    ],
    weakIntoTags: [
      `ANTI_ASSASSIN`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
      `ANTI_MAGE`,
      `DISENGAGE`,
      `BRUISER`,
    ],
    banRiskTags: [
      `ANTI_ASSASSIN`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
      `ANTI_MAGE`,
      `DISENGAGE`,
    ],
    laneNotes: `Mid Fizz is strongest into squishy and low-mobility champions that can be punished by Chum the Waters and Lich Bane burst. He struggles into anti-assassin mids, point-and-click crowd control, and durable champions that survive his first engage or punish his cooldowns. Galio, Lissandra, and Vex are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `fizz`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `ISOLATED_TARGET`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `PICK_COMPOSITION`,
    ],
    weakIntoTags: [
      `DUELING`,
      `HIGH_MOBILITY`,
      `POINT_AND_CLICK_CC`,
      `TANK`,
      `ANTI_ASSASSIN`,
      `JUNGLE_CLEAR`,
    ],
    banRiskTags: [
      `DUELING`,
      `HIGH_MOBILITY`,
      `POINT_AND_CLICK_CC`,
      `TANK`,
      `ANTI_ASSASSIN`,
    ],
    laneNotes: `Jungle Fizz is strong when he can attack isolated squishy targets and convert ultimate picks into objective pressure. He struggles against duelists, durable junglers, and crowd control-heavy teams that can survive his burst or punish him before he escapes. Master Yi, Riven, and Amumu are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GALIO
  {
    championKey: `galio`,
    role: GameRole.MID,
    goodIntoTags: [
      `MAGE`,
      `MAGIC_DAMAGE`,
      `ASSASSIN`,
      `DIVE`,
      `LOW_RANGE_CHAMPION`,
      `TEAMFIGHT`,
    ],
    weakIntoTags: [
      `LONG_RANGE_POKE`,
      `LONG_RANGE_SAFE_PLAY`,
      `DISENGAGE`,
      `SUSTAIN_TEAM`,
      `TRUE_DAMAGE`,
      `ADAPTIVE_DAMAGE`,
    ],
    banRiskTags: [
      `LONG_RANGE_POKE`,
      `DISENGAGE`,
      `SUSTAIN_TEAM`,
      `TRUE_DAMAGE`,
      `POINT_AND_CLICK_CC`,
    ],
    laneNotes: `Mid Galio is strong into magic damage, dive, and melee engage because he can absorb burst, taunt enemies, and follow skirmishes with Hero's Entrance. He struggles into champions that outrange him, safely wave clear, deny his engage, or sustain through his poke and all-in windows. Morgana, Ahri, and Swain are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `galio`,
    role: GameRole.SUPPORT,
    goodIntoTags: [
      `DIVE`,
      `ASSASSIN`,
      `MAGIC_DAMAGE`,
      `LOW_RANGE_CHAMPION`,
      `PICK_COMPOSITION`,
      `BURST_DAMAGE`,
    ],
    weakIntoTags: [
      `ENCHANTER`,
      `LONG_RANGE_POKE`,
      `SUSTAIN_TEAM`,
      `DISENGAGE`,
      `LONG_RANGE_SAFE_PLAY`,
      `HIGH_MOBILITY`,
    ],
    banRiskTags: [
      `ENCHANTER`,
      `LONG_RANGE_POKE`,
      `SUSTAIN_TEAM`,
      `DISENGAGE`,
      `LONG_RANGE_SAFE_PLAY`,
    ],
    laneNotes: `Support Galio is strong into engage, dive, and magic-damage threats because he can counter-initiate with taunt and protect allies with Hero's Entrance. He struggles into long-range enchanters and sustain supports that can poke safely, disengage his engage, or avoid grouped taunt windows. Senna, Nami, and Karma are notable difficult support examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GAREN
  {
    championKey: `garen`,
    role: GameRole.TOP,
    goodIntoTags: [
      `MELEE_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_CC`,
      `LOW_BURST`,
      `SQUISHY_CHAMPION`,
      `SIDE_LANE`,
    ],
    weakIntoTags: [
      `LONG_RANGE_CHAMPION`,
      `KITE`,
      `PERCENT_HEALTH_DAMAGE`,
      `TRUE_DAMAGE`,
      `HIGH_MOBILITY`,
      `ANTI_TANK`,
    ],
    banRiskTags: [
      `LONG_RANGE_CHAMPION`,
      `KITE`,
      `PERCENT_HEALTH_DAMAGE`,
      `TRUE_DAMAGE`,
      `HIGH_MOBILITY`,
    ],
    laneNotes: `Garen is strong into melee or low-mobility champions because he can take short trades, sustain through poke with Perseverance, and threaten execute kills with Demacian Justice. He struggles into ranged kiting, percent-health damage, true damage, and mobile duelists that can punish his predictable engage pattern. Vayne, Rumble, and Camille are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GNAR
  {
    championKey: `gnar`,
    role: GameRole.TOP,
    goodIntoTags: [
      `MELEE_CHAMPION`,
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `FRONTLINE`,
      `TANK`,
      `GROUPED_ENEMIES`,
    ],
    weakIntoTags: [
      `HIGH_MOBILITY`,
      `DIVE`,
      `HARD_ENGAGE`,
      `POINT_AND_CLICK_CC`,
      `ANTI_DASH`,
      `FORM_RELIANT`,
    ],
    banRiskTags: [
      `HIGH_MOBILITY`,
      `DIVE`,
      `HARD_ENGAGE`,
      `POINT_AND_CLICK_CC`,
      `ANTI_DASH`,
    ],
    laneNotes: `Gnar is strong into melee and low-range champions because Mini Gnar can kite and poke while Mega Gnar threatens crowd control and teamfight engage. He struggles into champions that can force fights when his Rage is low, dive through his spacing, or punish his form timing. Irelia, Malphite, and Ornn are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GRAGAS
  {
    championKey: `gragas`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `GROUPED_ENEMIES`,
      `LOW_RANGE_CHAMPION`,
      `LOW_MAGIC_RESIST`,
      `PICK_COMPOSITION`,
    ],
    weakIntoTags: [
      `ANTI_MAGE`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
      `HIGH_MOBILITY`,
      `SUSTAIN_TEAM`,
      `DISENGAGE`,
    ],
    banRiskTags: [
      `ANTI_MAGE`,
      `POINT_AND_CLICK_CC`,
      `CROWD_CONTROL`,
      `HIGH_MOBILITY`,
      `SUSTAIN_TEAM`,
    ],
    laneNotes: `Mid Gragas is strong when he can poke, threaten burst combos, and displace priority targets with Explosive Cask. He struggles into anti-mage champions, reliable crowd control, and opponents that can avoid or punish Body Slam windows. Galio, Vex, and Kassadin are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `gragas`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `GROUPED_ENEMIES`,
      `LOW_CC`,
      `PICK_COMPOSITION`,
      `FOG_OF_WAR`,
    ],
    weakIntoTags: [
      `TANK`,
      `FRONTLINE`,
      `EARLY_GAME_PRESSURE`,
      `HIGH_MOBILITY`,
      `KITE`,
      `DISENGAGE`,
    ],
    banRiskTags: [
      `TANK`,
      `FRONTLINE`,
      `EARLY_GAME_PRESSURE`,
      `HIGH_MOBILITY`,
      `DISENGAGE`,
    ],
    laneNotes: `Jungle Gragas is strongest when he can create gank angles with Body Slam and isolate targets with Explosive Cask. He can struggle against durable junglers, high-tempo invaders, and mobile champions that avoid his engage or kite his burst windows. Amumu, Nocturne, and Lillia are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GRAVES
  {
    championKey: `graves`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `SQUISHY_CHAMPION`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `JUNGLE_CLEAR`,
    ],
    weakIntoTags: [
      `TANK`,
      `FRONTLINE`,
      `ANTI_ATTACK_SPEED`,
      `POINT_AND_CLICK_CC`,
      `HIGH_MOBILITY`,
      `ANTI_MARKSMAN`,
    ],
    banRiskTags: [
      `TANK`,
      `FRONTLINE`,
      `ANTI_ATTACK_SPEED`,
      `POINT_AND_CLICK_CC`,
      `HIGH_MOBILITY`,
    ],
    laneNotes: `Graves is strongest when he can control jungle tempo, farm efficiently, and skirmish around short-range fights where his burst and armor stacking matter. He struggles against durable tanks, anti-marksman tools, reliable lockdown, and champions that can deny his close-range damage pattern. Rammus, Amumu, and Aatrox are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GWEN
  {
    championKey: `gwen`,
    role: GameRole.TOP,
    goodIntoTags: [
      `TANK`,
      `FRONTLINE`,
      `HIGH_HEALTH`,
      `LOW_MOBILITY`,
      `MELEE_CHAMPION`,
      `SCALING_GAME`,
    ],
    weakIntoTags: [
      `DUELING`,
      `HIGH_MOBILITY`,
      `BURST_DAMAGE`,
      `POINT_AND_CLICK_CC`,
      `ANTI_TANK`,
      `TRUE_DAMAGE`,
    ],
    banRiskTags: [
      `DUELING`,
      `HIGH_MOBILITY`,
      `BURST_DAMAGE`,
      `POINT_AND_CLICK_CC`,
      `TRUE_DAMAGE`,
    ],
    laneNotes: `Gwen is strong into tanks and high-health frontliners because her scaling magic damage and percent-health damage let her win extended fights. She struggles into strong duelists and burst-heavy melee champions that can punish her before she gets enough items or force fights around her cooldown windows. Fiora, Tryndamere, and Riven are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // HECARIM
  {
    championKey: `hecarim`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `LOW_MOBILITY`,
      `SQUISHY_CHAMPION`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `GROUPED_ENEMIES`,
      `PICK_COMPOSITION`,
    ],
    weakIntoTags: [
      `DUELING`,
      `HIGH_MOBILITY`,
      `KITE`,
      `POINT_AND_CLICK_CC`,
      `ANTI_DIVE`,
      `ANTI_ATTACK_SPEED`,
    ],
    banRiskTags: [
      `DUELING`,
      `HIGH_MOBILITY`,
      `KITE`,
      `POINT_AND_CLICK_CC`,
      `ANTI_DIVE`,
    ],
    laneNotes: `Hecarim is strongest when he can build speed, flank, and dive low-mobility targets before they can reposition. He struggles into strong duelists, kiting champions, and reliable crowd control that stops his engage or prevents him from escaping after committing. Master Yi, Kindred, and Graves are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // HEIMERDINGER
  {
    championKey: `heimerdinger`,
    role: GameRole.MID,
    goodIntoTags: [
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `MELEE_CHAMPION`,
      `GROUPED_ENEMIES`,
      `LOW_CC`,
      `PICK_COMPOSITION`,
    ],
    weakIntoTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `BURST_DAMAGE`,
      `WIND_WALL`,
      `POINT_AND_CLICK_CC`,
    ],
    banRiskTags: [
      `ASSASSIN`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `BURST_DAMAGE`,
      `WIND_WALL`,
    ],
    laneNotes: `Heimerdinger is strong into low-range and low-mobility champions because his turrets control space and punish enemies that walk into his setup. He struggles against mobile assassins and divers that can bypass his zone, dodge grenade setup, or burst him before his turrets finish fights. Zed, Yasuo, and Irelia are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // IRELIA
  {
    championKey: `irelia`,
    role: GameRole.TOP,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `SIDE_LANE`,
      `LOW_CC`,
      `SKILLSHOT_RELIANT`,
    ],
    weakIntoTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `TANK`,
      `FRONTLINE`,
      `BRUISER`,
      `CROWD_CONTROL`,
    ],
    banRiskTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `TANK`,
      `FRONTLINE`,
      `CROWD_CONTROL`,
    ],
    laneNotes: `Solo lane Irelia is strong into squishy or low-mobility champions that let her stack Ionian Fervor and chain Bladesurge resets through minion waves. She struggles into durable tanks, anti-dash tools, and champions that can interrupt her reset pattern or punish her melee commits. Malphite, Wukong, and Poppy are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `irelia`,
    role: GameRole.MID,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `MAGE`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `SKILLSHOT_RELIANT`,
    ],
    weakIntoTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `ANTI_MAGE`,
      `CROWD_CONTROL`,
      `SUSTAIN_TEAM`,
      `BRUISER`,
    ],
    banRiskTags: [
      `ANTI_DASH`,
      `POINT_AND_CLICK_CC`,
      `ANTI_MAGE`,
      `CROWD_CONTROL`,
      `SUSTAIN_TEAM`,
    ],
    laneNotes: `Mid Irelia can punish immobile mages and squishy champions by using minion waves for Bladesurge access and all-in pressure. She struggles into anti-dash champions, reliable crowd control, and durable mids that can survive her first commit or deny her reset windows. Vladimir, Vex, and Galio are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JANNA
  {
    championKey: `janna`,
    role: GameRole.SUPPORT,
    goodIntoTags: [
      `DIVE`,
      `ASSASSIN`,
      `HARD_ENGAGE`,
      `LOW_RANGE_CHAMPION`,
      `MELEE_CHAMPION`,
      `BURST_DAMAGE`,
    ],
    weakIntoTags: [
      `PICK_COMPOSITION`,
      `LONG_RANGE_POKE`,
      `SUSTAIN_TEAM`,
      `ENCHANTER`,
      `HOOK`,
      `LOW_DURABILITY_TEAM`,
    ],
    banRiskTags: [
      `PICK_COMPOSITION`,
      `LONG_RANGE_POKE`,
      `HOOK`,
      `SUSTAIN_TEAM`,
      `ENCHANTER`,
    ],
    laneNotes: `Janna is strong into dive and hard-engage teams because she can interrupt engages, shield carries, and reset fights with Monsoon. She struggles into hook supports, long-range poke, and sustain-heavy enchanters that can either catch her before she disengages or outscale her lane pressure. Blitzcrank, Senna, and Sona are notable difficult support examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JARVAN IV
  {
    championKey: `jarvan-iv`,
    role: GameRole.JUNGLE,
    goodIntoTags: [
      `LOW_MOBILITY`,
      `SQUISHY_CHAMPION`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `GROUPED_ENEMIES`,
      `PICK_COMPOSITION`,
    ],
    weakIntoTags: [
      `TANK`,
      `FRONTLINE`,
      `DUELING`,
      `ANTI_DASH`,
      `DISENGAGE`,
      `HIGH_MOBILITY`,
    ],
    banRiskTags: [`TANK`, `FRONTLINE`, `DUELING`, `ANTI_DASH`, `DISENGAGE`],
    laneNotes: `Jarvan IV is strongest when he can punish low-mobility targets with early ganks and trap priority carries inside Cataclysm. He struggles against durable tanks, strong duelists, and champions that can disengage or ignore his dash engage. Rammus, Master Yi, and Amumu are notable difficult jungle examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JAX
  {
    championKey: `jax`,
    role: GameRole.TOP,
    goodIntoTags: [
      `AUTO_ATTACK_CHAMPION`,
      `MELEE_CHAMPION`,
      `LOW_MOBILITY`,
      `SIDE_LANE`,
      `TANK`,
      `SCALING_GAME`,
    ],
    weakIntoTags: [
      `ANTI_DASH`,
      `BLIND`,
      `KITE`,
      `LONG_RANGE_CHAMPION`,
      `POINT_AND_CLICK_CC`,
      `BURN_DAMAGE`,
    ],
    banRiskTags: [
      `ANTI_DASH`,
      `BLIND`,
      `KITE`,
      `LONG_RANGE_CHAMPION`,
      `POINT_AND_CLICK_CC`,
    ],
    laneNotes: `Jax is strong into auto-attack champions and melee side-lane matchups because Counter Strike can deny key damage windows while he scales into a strong duelist. He struggles into anti-dash tools, blind effects, ranged kiting, and burn-heavy champions that punish his short-range engage. Poppy, Teemo, and Rumble are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JAYCE
  {
    championKey: `jayce`,
    role: GameRole.MID,
    goodIntoTags: [
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `SQUISHY_CHAMPION`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `LONG_RANGE_POKE`,
    ],
    weakIntoTags: [
      `LONG_RANGE_SAFE_PLAY`,
      `BURST_DAMAGE`,
      `ANTI_MAGE`,
      `DIVE`,
      `HIGH_MOBILITY`,
      `CROWD_CONTROL`,
    ],
    banRiskTags: [
      `LONG_RANGE_SAFE_PLAY`,
      `BURST_DAMAGE`,
      `ANTI_MAGE`,
      `DIVE`,
      `HIGH_MOBILITY`,
    ],
    laneNotes: `Mid Jayce is strong when he can control lane with ranged poke, punish low-mobility targets, and convert early pressure into skirmishes. He struggles into champions that outrange his pressure, survive his burst, or force melee all-ins when his cooldowns are down. Syndra, Galio, and Irelia are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `jayce`,
    role: GameRole.TOP,
    goodIntoTags: [
      `MELEE_CHAMPION`,
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `TANK`,
      `FRONTLINE`,
      `SIDE_LANE`,
    ],
    weakIntoTags: [
      `HARD_ENGAGE`,
      `DIVE`,
      `POINT_AND_CLICK_CC`,
      `TANK`,
      `FRONTLINE`,
      `HIGH_MOBILITY`,
    ],
    banRiskTags: [
      `HARD_ENGAGE`,
      `DIVE`,
      `POINT_AND_CLICK_CC`,
      `TANK`,
      `FRONTLINE`,
    ],
    laneNotes: `Solo lane Jayce is strong into melee champions he can poke and pressure before they reach their item spikes. He struggles against durable frontliners and hard-engage champions that can absorb his poke, force all-ins, or punish his hammer-form commits. Irelia, Malphite, and Ornn are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JHIN
  {
    championKey: `jhin`,
    role: GameRole.ADC,
    goodIntoTags: [
      `SQUISHY_CHAMPION`,
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `LOW_DURABILITY_TEAM`,
      `PICK_COMPOSITION`,
      `LONG_RANGE_POKE`,
    ],
    weakIntoTags: [
      `LANE_KILL_PRESSURE`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `BURST_DAMAGE`,
      `AUTO_ATTACK_CHAMPION`,
      `KITE`,
    ],
    banRiskTags: [
      `LANE_KILL_PRESSURE`,
      `HIGH_MOBILITY`,
      `DIVE`,
      `BURST_DAMAGE`,
      `AUTO_ATTACK_CHAMPION`,
    ],
    laneNotes: `Jhin is strongest when he can control lane with poke, chain crowd control with Deadly Flourish, and finish low-health targets from range. He struggles into aggressive marksmen and dive threats that can punish his reload windows or force extended DPS fights where his fixed attack pattern is weaker. Draven, Ashe, and Lucian are notable difficult duo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JINX
  {
    championKey: `jinx`,
    role: GameRole.ADC,
    goodIntoTags: [
      `LOW_MOBILITY`,
      `FRONTLINE`,
      `TANK`,
      `GROUPED_ENEMIES`,
      `LOW_BURST`,
      `SCALING_GAME`,
    ],
    weakIntoTags: [
      `LANE_KILL_PRESSURE`,
      `BURST_DAMAGE`,
      `DIVE`,
      `HIGH_MOBILITY`,
      `LONG_RANGE_POKE`,
      `HARD_ENGAGE`,
    ],
    banRiskTags: [
      `LANE_KILL_PRESSURE`,
      `BURST_DAMAGE`,
      `DIVE`,
      `HIGH_MOBILITY`,
      `HARD_ENGAGE`,
    ],
    laneNotes: `Jinx is strongest when she can scale safely and reach teamfights where rocket splash damage and reset movement speed take over. She struggles into aggressive lanes, burst damage, and dive threats that can punish her low mobility before she gets resets. Jhin, Miss Fortune, and Kog'Maw are notable difficult duo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // K'SANTE
  {
    championKey: `k-sante`,
    role: GameRole.TOP,
    goodIntoTags: [
      `MELEE_CHAMPION`,
      `LOW_MOBILITY`,
      `FRONTLINE`,
      `TANK`,
      `LOW_RANGE_CHAMPION`,
      `SIDE_LANE`,
    ],
    weakIntoTags: [
      `TRUE_DAMAGE`,
      `PERCENT_HEALTH_DAMAGE`,
      `ANTI_TANK`,
      `HIGH_MOBILITY`,
      `KITE`,
      `DUELING`,
    ],
    banRiskTags: [
      `TRUE_DAMAGE`,
      `PERCENT_HEALTH_DAMAGE`,
      `ANTI_TANK`,
      `HIGH_MOBILITY`,
      `KITE`,
    ],
    laneNotes: `K'Sante is strong into melee champions and frontliners because he can absorb damage, trade with tank scaling, and isolate priority targets with All Out. He struggles into champions that can kite him, shred tanks, or punish his lower damage before he finds a strong displacement angle. Ambessa, Vayne, and Garen are notable difficult solo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KAI'SA
  {
    championKey: `kaisa`,
    role: GameRole.ADC,
    goodIntoTags: [
      `FRONTLINE`,
      `TANK`,
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `SCALING_GAME`,
      `GROUPED_ENEMIES`,
    ],
    weakIntoTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `LANE_KILL_PRESSURE`,
      `BURST_DAMAGE`,
      `LONG_RANGE_POKE`,
      `DIVE`,
    ],
    banRiskTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `LANE_KILL_PRESSURE`,
      `BURST_DAMAGE`,
      `LONG_RANGE_POKE`,
    ],
    laneNotes: `Kai'Sa is strongest when she can scale into on-hit item spikes and fight around Plasma stacks with frontline or crowd control support. She struggles into long-range marksmen and aggressive lane bullies that can punish her shorter range before she reaches strong DPS windows. Caitlyn, Draven, and Kog'Maw are notable difficult duo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KALISTA
  {
    championKey: `kalista`,
    role: GameRole.ADC,
    goodIntoTags: [
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `TANK`,
      `FRONTLINE`,
      `LOW_BURST`,
      `EXTENDED_FIGHT`,
    ],
    weakIntoTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `KITE`,
      `SLOW`,
      `POINT_AND_CLICK_CC`,
      `BURST_DAMAGE`,
    ],
    banRiskTags: [
      `LONG_RANGE_CHAMPION`,
      `HIGH_RANGE_CHAMPION`,
      `SLOW`,
      `POINT_AND_CLICK_CC`,
      `BURST_DAMAGE`,
    ],
    laneNotes: `Kalista is strongest in extended fights where she can kite with Martial Poise, stack spears, and convert Rend into kill or objective pressure. She struggles into long-range marksmen, slows, and reliable crowd control because those tools limit her movement and punish her shorter attack range. Ashe, Kog'Maw, and Caitlyn are notable difficult duo lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KARMA
  {
    championKey: `karma`,
    role: GameRole.SUPPORT,
    goodIntoTags: [
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `MELEE_CHAMPION`,
      `POKE_COMPOSITION`,
      `LANE_SURVIVAL`,
      `LOW_BURST`,
    ],
    weakIntoTags: [
      `HOOK`,
      `PICK_COMPOSITION`,
      `HARD_ENGAGE`,
      `SUSTAIN_TEAM`,
      `ENCHANTER`,
      `LONG_RANGE_POKE`,
    ],
    banRiskTags: [
      `HOOK`,
      `PICK_COMPOSITION`,
      `HARD_ENGAGE`,
      `SUSTAIN_TEAM`,
      `LONG_RANGE_POKE`,
    ],
    laneNotes: `Support Karma is strong when she can poke safely, shield her carry, and speed allies through trades or disengage windows. She struggles against hook and pick supports that can punish her positioning, as well as sustain-heavy lanes that reduce her poke value. Pyke, Nami, and Bard are notable difficult support examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `karma`,
    role: GameRole.MID,
    goodIntoTags: [
      `LOW_RANGE_CHAMPION`,
      `LOW_MOBILITY`,
      `SQUISHY_CHAMPION`,
      `LOW_CC`,
      `POKE_COMPOSITION`,
      `LONG_RANGE_SAFE_PLAY`,
    ],
    weakIntoTags: [
      `ASSASSIN`,
      `DIVE`,
      `HIGH_MOBILITY`,
      `BURST_DAMAGE`,
      `CROWD_CONTROL`,
      `LONG_RANGE_POKE`,
    ],
    banRiskTags: [
      `ASSASSIN`,
      `DIVE`,
      `HIGH_MOBILITY`,
      `BURST_DAMAGE`,
      `CROWD_CONTROL`,
    ],
    laneNotes: `Mid Karma can pressure low-range or low-mobility champions with poke and empowered spell trades while still offering shielding utility in skirmishes. She struggles into assassins and high-burst mids that can reach her before she controls space or shields safely. Irelia, Zed, and Syndra are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KASSADIN
  {
    championKey: `kassadin`,
    role: GameRole.MID,
    goodIntoTags: [
      `MAGE`,
      `MAGIC_DAMAGE`,
      `LOW_MOBILITY`,
      `LOW_RANGE_CHAMPION`,
      `SCALING_GAME`,
      `LOW_CC`,
    ],
    weakIntoTags: [
      `ASSASSIN`,
      `PHYSICAL_DAMAGE`,
      `EARLY_GAME_PRESSURE`,
      `LONG_RANGE_POKE`,
      `HIGH_MOBILITY`,
      `CROWD_CONTROL`,
    ],
    banRiskTags: [
      `ASSASSIN`,
      `PHYSICAL_DAMAGE`,
      `EARLY_GAME_PRESSURE`,
      `LONG_RANGE_POKE`,
      `HIGH_MOBILITY`,
    ],
    laneNotes: `Kassadin is strongest into magic-damage and low-mobility mid laners because he can survive lane, scale, and later punish backlines with Riftwalk. He struggles into physical-damage assassins, early lane pressure, and long-range poke that can punish him before his scaling items and ultimate levels come online. Zed, Yasuo, and Jayce are notable difficult mid lane examples.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
];

export async function seedChampionMatchupProfiles(
  prisma: PrismaClient,
  patchId: string,
) {
  console.log(`Seeding champion matchup profiles...`);

  for (const championMatchupProfileSeed of championMatchupProfileSeeds) {
    const champion = await prisma.champion.findUnique({
      where: {
        key: championMatchupProfileSeed.championKey,
      },
    });

    if (!champion || champion.deletedAt) {
      throw new Error(
        `Champion not found or deleted: ${championMatchupProfileSeed.championKey}`,
      );
    }

    await prisma.championMatchupProfile.upsert({
      where: {
        championId_patchId_role: {
          championId: champion.id,
          patchId,
          role: championMatchupProfileSeed.role,
        },
      },
      update: {
        goodIntoTags: championMatchupProfileSeed.goodIntoTags,
        weakIntoTags: championMatchupProfileSeed.weakIntoTags,
        banRiskTags: championMatchupProfileSeed.banRiskTags,
        laneNotes: championMatchupProfileSeed.laneNotes ?? null,
        dataQuality:
          championMatchupProfileSeed.dataQuality ?? DataQualityLevel.MINIMAL,
        deletedAt: null,
      },
      create: {
        championId: champion.id,
        patchId,
        role: championMatchupProfileSeed.role,
        goodIntoTags: championMatchupProfileSeed.goodIntoTags,
        weakIntoTags: championMatchupProfileSeed.weakIntoTags,
        banRiskTags: championMatchupProfileSeed.banRiskTags,
        laneNotes: championMatchupProfileSeed.laneNotes ?? null,
        dataQuality:
          championMatchupProfileSeed.dataQuality ?? DataQualityLevel.MINIMAL,
      },
    });

    console.log(
      `Seeded ${champion.name}'s matchup profile for patch ${patchId}`,
    );
  }

  console.log(`SEEDED CHAMPIONS MATCHUP PROFILES`);
}
