import { PrismaClient } from '../../src/generated/prisma/client.js';
import {
  DataQualityLevel,
  GamePlan,
  GameRole,
} from '../../src/generated/prisma/enums.js';

type ChampionBuildProfileSeed = {
  profileKey: string;
  championKey: string;
  role: GameRole;
  gamePlan: GamePlan[];
  coreItemKeys: string[];
  situationalItemKeys: string[];
  recommendedRuneKeys: string[];
  recommendedSpellKeys: string[];
  playStyleTags: string[];
  buildTags: string[];
  notes?: string | null;
  dataQuality?: DataQualityLevel;
};

const championBuildProfileSeeds: ChampionBuildProfileSeed[] = [
  // AATROX
  {
    profileKey: `aatrox-top-standard`,
    championKey: `aatrox`,
    role: GameRole.TOP,
    gamePlan: [GamePlan.STANDARD, GamePlan.ANTI_TANK, GamePlan.SURVIVE_DIVE],
    coreItemKeys: [`eclipse`, `trinity-force`, `seryldas-grudge`],
    situationalItemKeys: [
      `deaths-dance`,
      `spear-of-shojin`,
      `serpents-fang`,
      `guardian-angel`,
      `maw-of-malmortius`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `stridebreaker`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `courage-of-the-colossus`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `DRAIN_TANK`,
      `EXTENDED_FIGHT_CHAMPION`,
      `DUELING`,
      `SKIRMISH`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ABILITY_HASTE`,
      `SUSTAIN`,
      `ANTI_TANK`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Solo lane bruiser build focused on extended fights, ability haste, armor penetration, and sustain. Eclipse, Trinity Force, and Serylda's Grudge form the main damage core. Situational items cover shielding, burst damage, ability power threats, and crowd control.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `aatrox-jungle-standard`,
    championKey: `aatrox`,
    role: GameRole.JUNGLE,
    gamePlan: [GamePlan.STANDARD, GamePlan.ANTI_TANK, GamePlan.SURVIVE_DIVE],
    coreItemKeys: [`eclipse`, `trinity-force`, `seryldas-grudge`],
    situationalItemKeys: [
      `deaths-dance`,
      `spear-of-shojin`,
      `serpents-fang`,
      `guardian-angel`,
      `maw-of-malmortius`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `stridebreaker`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `courage-of-the-colossus`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [
      `DRAIN_TANK`,
      `EXTENDED_FIGHT_CHAMPION`,
      `SKIRMISH`,
      `OBJECTIVE_CONTROL`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ABILITY_HASTE`,
      `SUSTAIN`,
      `JUNGLE_CLEAR`,
      `ANTI_TANK`,
    ],
    notes: `Jungle profile keeps the same bruiser core while swapping Ignite for Smite. Best used when Aatrox can fight around early skirmishes, objectives, and extended frontline pressure.`,
    dataQuality: DataQualityLevel.MINIMAL,
  },
  // AHRI
  {
    profileKey: `ahri-mid-burst`,
    championKey: `ahri`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_HEAL,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`ludens-echo`, `lich-bane`, `rabadons-deathcap`],
    situationalItemKeys: [
      `infinity-orb`,
      `crown-of-the-shattered-queen`,
      `oceanids-trident`,
      `morellonomicon`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `electrocute`,
      `empowered-attack`,
      `chain-assault`,
      `eyeball-collector`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`BURST`, `PICK`, `MOBILITY`, `POKE`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MAGIC_PENETRATION`,
      `ANTI_HEAL`,
      `ANTI_SHIELD`,
      `SPELL_SHIELD`,
    ],
    notes: `Mid lane burst mage profile focused on pick pressure, Charm setup, and mobile burst trades. Luden's Echo, Lich Bane, and Rabadon's Deathcap form the main AP burst core. Infinity Orb improves finishing power, Crown adds safety against burst, Oceanid's Trident answers shielding, and Morellonomicon answers healing.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AKALI
  {
    profileKey: `akali-mid-burst`,
    championKey: `akali`,
    role: GameRole.MID,
    gamePlan: [GamePlan.BURST, GamePlan.STANDARD, GamePlan.SAFE],
    coreItemKeys: [`infinity-orb`, `rabadons-deathcap`, `riftmaker`],
    situationalItemKeys: [
      `oceanids-trident`,
      `crown-of-the-shattered-queen`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `electrocute`,
      `unshakeable`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`BURST`, `MOBILITY`, `PICK`, `SKIRMISH`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MAGIC_PENETRATION`,
      `MAGIC_VAMP`,
      `ANTI_SHIELD`,
      `SPELL_SHIELD`,
    ],
    notes: `Mid lane assassin profile focused on burst windows, backline access, and snowball skirmishes. Infinity Orb, Rabadon's Deathcap, and Riftmaker give Akali strong execute pressure and sustained AP threat. Oceanid's Trident answers shielding while Crown and Stasis help her survive high-burst fights after committing.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `akali-top-scaling`,
    championKey: `akali`,
    role: GameRole.TOP,
    gamePlan: [GamePlan.SCALING, GamePlan.SAFE, GamePlan.STANDARD],
    coreItemKeys: [`rod-of-ages`, `rabadons-deathcap`, `psychic-projector`],
    situationalItemKeys: [
      `riftmaker`,
      `oceanids-trident`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `fleet-footwork`,
      `unshakeable`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`SCALING`, `MOBILITY`, `SKIRMISH`, `DUELIST`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `SCALING_HEALTH`,
      `SCALING`,
      `SUSTAIN`,
      `MAGIC_VAMP`,
      `ANTI_SHIELD`,
    ],
    notes: `Solo lane profile focused on safer scaling and durability. Rod of Ages and Psychic Projector give Akali more health-based scaling and survivability, while Rabadon's Deathcap keeps her burst threat relevant. Fleet Footwork improves lane sustain into harder Baron lane matchups.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AKSHAN
  {
    profileKey: `akshan-mid-standard`,
    championKey: `akshan`,
    role: GameRole.MID,
    gamePlan: [GamePlan.STANDARD, GamePlan.BURST, GamePlan.SCALING],
    coreItemKeys: [`the-collector`, `magnetic-blaster`, `lord-dominiks-regard`],
    situationalItemKeys: [
      `infinity-edge`,
      `bloodthirster`,
      `mortal-reminder`,
      `serpents-fang`,
      `guardian-angel`,
      `gluttonous-greaves`,
      `galeforce`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `empowerment`,
      `brutal`,
      `cut-down`,
      `legend-alacrity`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `UTILITY_MARKSMAN`,
      `AUTO_ATTACK_CHAMPION`,
      `MOBILITY`,
      `PICK`,
      `SNOWBALL`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `PHYSICAL_DAMAGE`,
      `ON_HIT`,
      `EXECUTE`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
      `ANTI_SHIELD`,
    ],
    notes: `Mid lane marksman profile focused on lane pressure, roaming picks, physical burst, and cleanup. The Collector, Magnetic Blaster, and Lord Dominik's Regard form the main damage core. Mortal Reminder answers healing, Serpent's Fang answers shielding, Guardian Angel helps into assassins, and Quicksilver helps into crowd control.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // ALISTAR
  {
    profileKey: `alistar-support-standard`,
    championKey: `alistar`,
    role: GameRole.SUPPORT,
    gamePlan: [GamePlan.STANDARD, GamePlan.SURVIVE_DIVE, GamePlan.SAFE],
    coreItemKeys: [
      `bulwark-of-the-mountain`,
      `zekes-convergence`,
      `radiant-virtue`,
    ],
    situationalItemKeys: [
      `frozen-heart`,
      `amaranths-twinguard`,
      `thornmail`,
      `randuins-omen`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `protobelt`,
    ],
    recommendedRuneKeys: [
      `ice-overlord`,
      `courage-of-the-colossus`,
      `second-wind`,
      `overgrowth`,
      `hextech-flashtraption`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`VANGUARD`, `TEAM_SUPPORT`, `ENGAGE`, `PEEL`, `TEAMFIGHT`],
    buildTags: [
      `SUPPORT`,
      `DEFENSIVE`,
      `HEALTH`,
      `ABILITY_HASTE`,
      `ANTI_ATTACK_SPEED`,
      `ANTI_HEAL`,
    ],
    notes: `Support tank profile focused on engage, peel, and frontline durability. Bulwark of the Mountain, Zeke's Convergence, and Radiant Virtue form the main support tank core. Frozen Heart helps against attack speed users, Thornmail answers healing, Randuin's Omen helps against critical strike damage, and Mercury's Treads or Quicksilver-style options are useful into heavy crowd control.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AMBESSA
  {
    profileKey: `ambessa-top-standard`,
    championKey: `ambessa`,
    role: GameRole.TOP,
    gamePlan: [GamePlan.STANDARD, GamePlan.ANTI_TANK, GamePlan.SURVIVE_DIVE],
    coreItemKeys: [`eclipse`, `spear-of-shojin`, `seryldas-grudge`],
    situationalItemKeys: [
      `deaths-dance`,
      `guardian-angel`,
      `serpents-fang`,
      `maw-of-malmortius`,
      `gluttonous-greaves`,
      `goredrinker`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `unshakeable`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `MOBILITY`,
      `SKIRMISH`,
      `DUELING`,
      `DIVE`,
      `EXTENDED_FIGHT_CHAMPION`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ABILITY_HASTE`,
      `PHYSICAL_DAMAGE`,
      `SUSTAIN`,
      `ANTI_TANK`,
      `ANTI_SHIELD`,
    ],
    notes: `Solo lane bruiser profile focused on mobility, extended trades, cooldown cycling, and backline access. Eclipse, Spear of Shojin, and Serylda's Grudge form the main ability-haste and armor-penetration core. Serpent's Fang answers shielding, Maw of Malmortius helps into ability power threats, Guardian Angel improves commit-heavy fights, and Quicksilver helps into crowd control.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `ambessa-jungle-standard`,
    championKey: `ambessa`,
    role: GameRole.JUNGLE,
    gamePlan: [GamePlan.STANDARD, GamePlan.ANTI_TANK, GamePlan.SAFE],
    coreItemKeys: [`trinity-force`, `spear-of-shojin`, `seryldas-grudge`],
    situationalItemKeys: [
      `deaths-dance`,
      `guardian-angel`,
      `serpents-fang`,
      `maw-of-malmortius`,
      `gluttonous-greaves`,
      `stasis`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `battle-zeal`,
      `cut-down`,
      `legend-alacrity`,
      `overgrowth`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [
      `MOBILITY`,
      `SKIRMISH`,
      `DIVE`,
      `JUNGLE_CLEAR`,
      `EXTENDED_FIGHT_CHAMPION`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `ABILITY_HASTE`,
      `PHYSICAL_DAMAGE`,
      `ANTI_TANK`,
      `ANTI_SHIELD`,
    ],
    notes: `Jungle profile focused on faster skirmishing, objective pressure, and repeated ability casts. Trinity Force, Spear of Shojin, and Serylda's Grudge give a strong fighter core. Serpent's Fang answers shielding, Maw of Malmortius helps into magic damage, and Stasis or Quicksilver can protect Ambessa after deep engages.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AMUMU
  {
    profileKey: `amumu-jungle-tank`,
    championKey: `amumu`,
    role: GameRole.JUNGLE,
    gamePlan: [GamePlan.STANDARD, GamePlan.SURVIVE_DIVE, GamePlan.ANTI_HEAL],
    coreItemKeys: [`searing-crown`, `thornmail`, `zekes-convergence`],
    situationalItemKeys: [
      `frozen-heart`,
      `amaranths-twinguard`,
      `randuins-omen`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `gargoyle`,
    ],
    recommendedRuneKeys: [
      `ice-overlord`,
      `unshakeable`,
      `bone-plating`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [
      `VANGUARD`,
      `TEAMFIGHT`,
      `ZONE_CONTROL`,
      `TEAM_SUPPORT`,
      `JUNGLE_CLEAR`,
    ],
    buildTags: [
      `DEFENSIVE`,
      `HEALTH`,
      `ARMOR_REDUCTION`,
      `ANTI_HEAL`,
      `ANTI_ATTACK_SPEED`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Jungle tank profile focused on durable engage, repeated area damage, and teamfight lockdown. Searing Crown, Thornmail, and Zeke's Convergence form the main tank utility core. Frozen Heart helps against attack speed users, Randuin's Omen helps against critical strike damage, Amaranth's Twinguard improves late-fight durability, and Mercury's Treads are useful into ability power or crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // ANNIE
  {
    profileKey: `annie-mid-burst`,
    championKey: `annie`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`malignance`, `awakened-soulstealer`, `rabadons-deathcap`],
    situationalItemKeys: [
      `infinity-orb`,
      `crown-of-the-shattered-queen`,
      `oceanids-trident`,
      `boots-of-mana`,
      `protobelt`,
    ],
    recommendedRuneKeys: [
      `electrocute`,
      `hextech-flashtraption`,
      `transcendence`,
      `nimbus-cloak`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`BURST`, `PICK`, `TEAMFIGHT`, `ULTIMATE_RELIANT_CHAMPION`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `ULTIMATE_HASTE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
      `SPELL_SHIELD`,
    ],
    notes: `Mid lane burst mage profile focused on Flash or Protobelt engage, Pyromania stun setup, and Tibbers burst. Malignance, Awakened Soulstealer, and Rabadon's Deathcap support frequent high-impact ultimate plays. Infinity Orb improves execute pressure, Crown adds safety, and Oceanid's Trident answers shielding.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // ASHE
  {
    profileKey: `ashe-adc-standard`,
    championKey: `ashe`,
    role: GameRole.ADC,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.SAFE,
      GamePlan.ANTI_TANK,
    ],
    coreItemKeys: [`bloodthirster`, `magnetic-blaster`, `lord-dominiks-regard`],
    situationalItemKeys: [
      `phantom-dancer`,
      `guardian-angel`,
      `mortal-reminder`,
      `blade-of-the-ruined-king`,
      `berserkers-greaves`,
      `galeforce`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `lethal-tempo`,
      `brutal`,
      `cut-down`,
      `legend-alacrity`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ghost`],
    playStyleTags: [
      `UTILITY_MARKSMAN`,
      `AUTO_ATTACK_CHAMPION`,
      `DPS`,
      `KITE`,
      `TEAM_SUPPORT`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `PHYSICAL_DAMAGE`,
      `ON_HIT`,
      `SUSTAIN`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
    ],
    notes: `Duo lane utility marksman profile focused on sustained DPS, slows, kiting, and long-range pick setup. Bloodthirster, Magnetic Blaster, and Lord Dominik's Regard form the main damage core. Mortal Reminder answers healing, Blade of the Ruined King helps into tanks, Guardian Angel improves safety, and Quicksilver helps into crowd control.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AURELION SOL
  {
    profileKey: `aurelion-sol-mid-scaling`,
    championKey: `aurelion-sol`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.SCALING,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_HEAL,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [
      `rylais-crystal-scepter`,
      `liandrys-torment`,
      `psychic-projector`,
    ],
    situationalItemKeys: [
      `rabadons-deathcap`,
      `riftmaker`,
      `morellonomicon`,
      `oceanids-trident`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `dark-harvest`,
      `botanist`,
      `absolute-focus`,
      `gathering-storm`,
      `overgrowth`,
    ],
    recommendedSpellKeys: [`flash`, `exhaust`],
    playStyleTags: [
      `SCALING`,
      `ARTILLERY`,
      `ZONE_CONTROL`,
      `TEAMFIGHT`,
      `POKE`,
    ],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURN_DAMAGE`,
      `SCALING_HEALTH`,
      `SUSTAIN`,
      `ANTI_HEAL`,
      `ANTI_SHIELD`,
    ],
    notes: `Mid lane scaling mage profile focused on zone control, sustained magic damage, and late-game teamfight impact. Rylai's Crystal Scepter, Liandry's Torment, and Psychic Projector form the main control and scaling core. Morellonomicon answers healing, Oceanid's Trident answers shielding, and Stasis helps Aurelion Sol survive dives after committing to fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AURORA
  {
    profileKey: `aurora-mid-burst`,
    championKey: `aurora`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_HEAL,
      GamePlan.ANTI_TANK,
    ],
    coreItemKeys: [`infinity-orb`, `rabadons-deathcap`, `awakened-soulstealer`],
    situationalItemKeys: [
      `oceanids-trident`,
      `crown-of-the-shattered-queen`,
      `liandrys-torment`,
      `morellonomicon`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `electrocute`,
      `sudden-impact`,
      `chain-assault`,
      `eyeball-collector`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`BURST`, `MOBILITY`, `PICK`, `ZONE_CONTROL`, `TEAMFIGHT`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
      `ANTI_HEAL`,
      `BURN_DAMAGE`,
    ],
    notes: `Mid lane burst mage profile focused on mobility, pick pressure, and controlling fights with Between Worlds. Infinity Orb, Rabadon's Deathcap, and Awakened Soulstealer form the main AP burst core. Oceanid's Trident answers shielding, Morellonomicon answers healing, Liandry's Torment helps into tanks, and Crown plus Stasis improve safety against burst or dive.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BARD
  {
    profileKey: `bard-support-burst`,
    championKey: `bard`,
    role: GameRole.SUPPORT,
    gamePlan: [GamePlan.BURST, GamePlan.STANDARD, GamePlan.SAFE],
    coreItemKeys: [`black-mist-scythe`, `lich-bane`, `infinity-orb`],
    situationalItemKeys: [
      `oceanids-trident`,
      `rabadons-deathcap`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `electrocute`,
      `cheap-shot`,
      `chain-assault`,
      `zombie-ward`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `TEAM_SUPPORT`,
      `ROAMING`,
      `PICK`,
      `BURST`,
      `VISION_CONTROL`,
    ],
    buildTags: [
      `SUPPORT`,
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `SPELLBLADE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
    ],
    notes: `Support AP utility profile focused on roaming, pick pressure, and burst follow-up. Black Mist Scythe, Lich Bane, and Infinity Orb give Bard strong support damage and empowered attack pressure. Oceanid's Trident answers shielding, Rabadon's Deathcap increases carry threat, and Stasis helps Bard survive after aggressive Tempered Fate or portal plays.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BLITZCRANK
  {
    profileKey: `blitzcrank-support-pick`,
    championKey: `blitzcrank`,
    role: GameRole.SUPPORT,
    gamePlan: [GamePlan.STANDARD, GamePlan.SAFE, GamePlan.ANTI_HEAL],
    coreItemKeys: [`bulwark-of-the-mountain`, `yordle-trap`, `warmogs-armor`],
    situationalItemKeys: [
      `frozen-heart`,
      `kaenic-rookern`,
      `thornmail`,
      `randuins-omen`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `protobelt`,
    ],
    recommendedRuneKeys: [
      `ice-overlord`,
      `courage-of-the-colossus`,
      `second-wind`,
      `overgrowth`,
      `hextech-flashtraption`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `TEAM_SUPPORT`,
      `PICK`,
      `ROAMING`,
      `ENGAGE`,
      `ZONE_CONTROL`,
    ],
    buildTags: [
      `SUPPORT`,
      `DEFENSIVE`,
      `HEALTH`,
      `ABILITY_HASTE`,
      `ANTI_ATTACK_SPEED`,
      `ANTI_HEAL`,
    ],
    notes: `Support pick-tank profile focused on hook threat, fog-of-war pressure, and single-target lockdown. Bulwark of the Mountain, Yordle Trap, and Warmog's Armor form the main durable support core. Frozen Heart helps against attack speed users, Thornmail answers healing, Randuin's Omen helps into critical strike damage, and Mercury's Treads helps against ability power or crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BRAND
  {
    profileKey: `brand-mid-burn`,
    championKey: `brand`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.BURST,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_HEAL,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`liandrys-torment`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `oceanids-trident`,
      `crown-of-the-shattered-queen`,
      `morellonomicon`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `electrocute`,
      `battle-zeal`,
      `cut-down`,
      `legend-bloodline`,
      `transcendence`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`BURST`, `POKE`, `ZONE_CONTROL`, `TEAMFIGHT`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURN_DAMAGE`,
      `AREA_DAMAGE`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
      `ANTI_SHIELD`,
    ],
    notes: `Mid lane burn mage profile focused on area damage, passive detonation, and teamfight damage over time. Liandry's Torment, Infinity Orb, and Rabadon's Deathcap form the main AP damage core. Morellonomicon answers healing, Oceanid's Trident answers shielding, and Crown plus Stasis help Brand survive burst or dive after committing damage.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `brand-support-burn`,
    championKey: `brand`,
    role: GameRole.SUPPORT,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.BURST,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [
      `black-mist-scythe`,
      `liandrys-torment`,
      `rylais-crystal-scepter`,
    ],
    situationalItemKeys: [
      `oceanids-trident`,
      `crown-of-the-shattered-queen`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `electrocute`,
      `cheap-shot`,
      `tyrant`,
      `zombie-ward`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`POKE`, `ZONE_CONTROL`, `TEAMFIGHT`, `TEAM_SUPPORT`],
    buildTags: [
      `SUPPORT`,
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURN_DAMAGE`,
      `AREA_DAMAGE`,
      `ANTI_SHIELD`,
    ],
    notes: `Support damage profile focused on poke, lane pressure, and burn-based teamfight value. Black Mist Scythe, Liandry's Torment, and Rylai's Crystal Scepter give Brand support income, sustained magic damage, and control. Oceanid's Trident helps into shielding while Crown and Stasis give safety against hard engage.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BRAUM
  {
    profileKey: `braum-support-peel`,
    championKey: `braum`,
    role: GameRole.SUPPORT,
    gamePlan: [GamePlan.SAFE, GamePlan.STANDARD, GamePlan.SURVIVE_DIVE],
    coreItemKeys: [`bulwark-of-the-mountain`, `redemption`, `knights-vow`],
    situationalItemKeys: [
      `frozen-heart`,
      `force-of-nature`,
      `thornmail`,
      `randuins-omen`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `locket`,
    ],
    recommendedRuneKeys: [
      `guardian`,
      `font-of-life`,
      `second-wind`,
      `overgrowth`,
      `ingenious-hunter`,
    ],
    recommendedSpellKeys: [`flash`, `heal`],
    playStyleTags: [
      `TEAM_SUPPORT`,
      `PEEL`,
      `SURVIVABILITY`,
      `TEAMFIGHT`,
      `LANE_SURVIVAL`,
    ],
    buildTags: [
      `SUPPORT`,
      `DEFENSIVE`,
      `HEALTH`,
      `SHIELD`,
      `ANTI_ATTACK_SPEED`,
      `ANTI_HEAL`,
    ],
    notes: `Support peel tank profile focused on protecting carries, blocking projectiles, and enabling extended front-to-back fights. Bulwark of the Mountain, Redemption, and Knight's Vow form the main defensive support core. Frozen Heart helps against attack speed users, Thornmail answers healing, Randuin's Omen helps into critical strike damage, and Locket adds teamwide protection.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // CAITLYN
  {
    profileKey: `caitlyn-adc-standard`,
    championKey: `caitlyn`,
    role: GameRole.ADC,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.SAFE,
      GamePlan.ANTI_TANK,
    ],
    coreItemKeys: [`the-collector`, `magnetic-blaster`, `lord-dominiks-regard`],
    situationalItemKeys: [
      `infinity-edge`,
      `bloodthirster`,
      `mortal-reminder`,
      `blade-of-the-ruined-king`,
      `guardian-angel`,
      `berserkers-greaves`,
      `galeforce`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `lethal-tempo`,
      `brutal`,
      `cut-down`,
      `legend-alacrity`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ghost`],
    playStyleTags: [
      `AUTO_ATTACK_CHAMPION`,
      `DPS`,
      `POKE`,
      `ZONE_CONTROL`,
      `SAFE_POSITIONING`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `PHYSICAL_DAMAGE`,
      `CRITICAL_STRIKE`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
      `SUSTAIN`,
    ],
    notes: `Duo lane long-range marksman profile focused on lane pressure, trap control, safe DPS, and finishing low-health targets. The Collector, Magnetic Blaster, and Lord Dominik's Regard form the main physical damage core. Mortal Reminder answers healing, Blade of the Ruined King helps into tanks, Guardian Angel improves safety against assassins, and Quicksilver helps into crowd control.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // CAMILLE
  {
    profileKey: `camille-top-split-push`,
    championKey: `camille`,
    role: GameRole.TOP,
    gamePlan: [GamePlan.STANDARD, GamePlan.ANTI_TANK, GamePlan.SURVIVE_DIVE],
    coreItemKeys: [`trinity-force`, `hullbreaker`, `sundered-sky`],
    situationalItemKeys: [
      `deaths-dance`,
      `amaranths-twinguard`,
      `blade-of-the-ruined-king`,
      `serpents-fang`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `goredrinker`,
    ],
    recommendedRuneKeys: [
      `grasp-of-the-undying`,
      `demolish`,
      `second-wind`,
      `overgrowth`,
      `scorch`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`SPLIT_PUSH`, `DUELING`, `MOBILITY`, `PICK`, `SIDE_LANE`],
    buildTags: [
      `ATTACK_DAMAGE`,
      `SPELLBLADE`,
      `HEALTH`,
      `TRUE_DAMAGE`,
      `ANTI_TANK`,
      `ANTI_SHIELD`,
    ],
    notes: `Solo lane split-push fighter profile focused on side lane pressure, Precision Protocol trades, and Hextech Ultimatum pick threat. Trinity Force, Hullbreaker, and Sundered Sky form the main side-lane bruiser core. Blade of the Ruined King helps into tanks, Serpent's Fang answers shielding, Death's Dance improves physical-damage survivability, and Mercury's Treads help into magic damage or crowd control.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `camille-jungle-pick`,
    championKey: `camille`,
    role: GameRole.JUNGLE,
    gamePlan: [GamePlan.STANDARD, GamePlan.ANTI_TANK, GamePlan.SAFE],
    coreItemKeys: [`trinity-force`, `eclipse`, `deaths-dance`],
    situationalItemKeys: [
      `hullbreaker`,
      `amaranths-twinguard`,
      `blade-of-the-ruined-king`,
      `gluttonous-greaves`,
      `goredrinker`,
    ],
    recommendedRuneKeys: [
      `fleet-footwork`,
      `battle-zeal`,
      `cut-down`,
      `legend-alacrity`,
      `overgrowth`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [`PICK`, `MOBILITY`, `SKIRMISH`, `DIVE`, `JUNGLE_CLEAR`],
    buildTags: [
      `ATTACK_DAMAGE`,
      `SPELLBLADE`,
      `SUSTAIN`,
      `TRUE_DAMAGE`,
      `ANTI_TANK`,
    ],
    notes: `Jungle Camille profile focused on pick pressure, skirmishing, and locking priority targets with Hextech Ultimatum. Trinity Force, Eclipse, and Death's Dance form the main fighter core. Blade of the Ruined King helps into tankier targets, while Amaranth's Twinguard improves durability in longer fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // CORKI
  {
    profileKey: `corki-adc-standard`,
    championKey: `corki`,
    role: GameRole.ADC,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.SAFE,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_HEAL,
    ],
    coreItemKeys: [
      `essence-reaver`,
      `magnetic-blaster`,
      `lord-dominiks-regard`,
    ],
    situationalItemKeys: [
      `infinity-edge`,
      `bloodthirster`,
      `mortal-reminder`,
      `guardian-angel`,
      `gluttonous-greaves`,
      `stasis`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `brutal`,
      `cut-down`,
      `legend-alacrity`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `barrier`],
    playStyleTags: [
      `DPS`,
      `POKE`,
      `ABILITY_RELIANT_CHAMPION`,
      `SCALING`,
      `SAFE_POSITIONING`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `PHYSICAL_DAMAGE`,
      `MAGIC_DAMAGE`,
      `HYBRID_DAMAGE`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
    ],
    notes: `Duo lane hybrid marksman profile focused on safe scaling, poke, and sustained damage through abilities and attacks. Essence Reaver, Magnetic Blaster, and Lord Dominik's Regard form the main damage core. Mortal Reminder answers healing, Guardian Angel improves safety against assassins, and Quicksilver helps into crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DARIUS
  {
    profileKey: `darius-top-juggernaut`,
    championKey: `darius`,
    role: GameRole.TOP,
    gamePlan: [GamePlan.STANDARD, GamePlan.SURVIVE_DIVE, GamePlan.ANTI_HEAL],
    coreItemKeys: [`trinity-force`, `steraks-gage`, `amaranths-twinguard`],
    situationalItemKeys: [
      `dead-mans-plate`,
      `force-of-nature`,
      `mortal-reminder`,
      `randuins-omen`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `protobelt`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `unshakeable`,
      `second-wind`,
      `overgrowth`,
      `nimbus-cloak`,
    ],
    recommendedSpellKeys: [`flash`, `ghost`],
    playStyleTags: [
      `JUGGERNAUT`,
      `DUELING`,
      `EXTENDED_FIGHT_CHAMPION`,
      `DRAIN_TANK`,
      `TEAMFIGHT_CLEANUP`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `HEALTH`,
      `SUSTAIN`,
      `DAMAGE_REDUCTION`,
      `ANTI_HEAL`,
      `MOVEMENT_SPEED`,
    ],
    notes: `Solo lane juggernaut profile focused on extended trades, Hemorrhage stacking, and reset execution with Noxian Guillotine. Trinity Force, Sterak's Gage, and Amaranth's Twinguard form the main bruiser durability core. Mortal Reminder answers healing, Randuin's Omen helps into critical strike damage, Mercury's Treads and Quicksilver help into crowd control, and Protobelt improves engage reach.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `darius-jungle-tempo`,
    championKey: `darius`,
    role: GameRole.JUNGLE,
    gamePlan: [GamePlan.STANDARD, GamePlan.SURVIVE_DIVE, GamePlan.ANTI_HEAL],
    coreItemKeys: [`trinity-force`, `steraks-gage`, `amaranths-twinguard`],
    situationalItemKeys: [
      `dead-mans-plate`,
      `force-of-nature`,
      `mortal-reminder`,
      `randuins-omen`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `protobelt`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `phase-rush`,
      `hextech-flashtraption`,
      `celerity`,
      `nimbus-cloak`,
      `overgrowth`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [
      `JUGGERNAUT`,
      `JUNGLE_CLEAR`,
      `SKIRMISH`,
      `EXTENDED_FIGHT_CHAMPION`,
      `TEAMFIGHT_CLEANUP`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `HEALTH`,
      `SUSTAIN`,
      `DAMAGE_REDUCTION`,
      `ANTI_HEAL`,
      `MOVEMENT_SPEED`,
    ],
    notes: `Jungle Darius profile focused on skirmishing, tempo ganks, and snowballing fights through Hemorrhage stacks and Noxian Guillotine resets. Trinity Force, Sterak's Gage, and Amaranth's Twinguard provide the main bruiser core. Mortal Reminder answers healing, Randuin's Omen helps into critical strike damage, and Quicksilver helps when crowd control prevents him from reaching targets.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DIANA
  {
    profileKey: `diana-mid-burst`,
    championKey: `diana`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`lich-bane`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `awakened-soulstealer`,
      `crown-of-the-shattered-queen`,
      `oceanids-trident`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `electrocute`,
      `sudden-impact`,
      `chain-assault`,
      `eyeball-collector`,
      `second-wind`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`BURST`, `DIVE`, `MOBILITY`, `SKIRMISH`, `TEAMFIGHT`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `SPELLBLADE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
      `SPELL_SHIELD`,
    ],
    notes: `Mid lane AP diver profile focused on Crescent Strike setup, Lunar Rush access, and Moonfall burst. Lich Bane, Infinity Orb, and Rabadon's Deathcap form the main burst core. Awakened Soulstealer improves ultimate uptime, Oceanid's Trident answers shielding, and Crown plus Stasis help Diana survive after committing into the enemy team.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `diana-jungle-burst`,
    championKey: `diana`,
    role: GameRole.JUNGLE,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`lich-bane`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `awakened-soulstealer`,
      `crown-of-the-shattered-queen`,
      `oceanids-trident`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `fleet-footwork`,
      `sudden-impact`,
      `chain-assault`,
      `eyeball-collector`,
      `transcendence`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [`BURST`, `DIVE`, `MOBILITY`, `JUNGLE_CLEAR`, `TEAMFIGHT`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `SPELLBLADE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
      `SPELL_SHIELD`,
    ],
    notes: `Jungle Diana profile focused on fast AP skirmishes, ultimate engage, and burst follow-up from fog of war. Lich Bane, Infinity Orb, and Rabadon's Deathcap form the main magic burst core. Oceanid's Trident answers shielding, Crown improves safety against counter-engage, and Stasis lets Diana buy time after Moonfall.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DR. MUNDO
  {
    profileKey: `dr-mundo-top-tank`,
    championKey: `dr-mundo`,
    role: GameRole.TOP,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.SURVIVE_DIVE,
      GamePlan.ANTI_HEAL,
    ],
    coreItemKeys: [`heartsteel`, `sunfire-aegis`, `thornmail`],
    situationalItemKeys: [
      `mantle-of-the-twelfth-hour`,
      `amaranths-twinguard`,
      `hollow-radiance`,
      `randuins-omen`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `gargoyle`,
    ],
    recommendedRuneKeys: [
      `grasp-of-the-undying`,
      `demolish`,
      `second-wind`,
      `overgrowth`,
      `last-stand`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `JUGGERNAUT`,
      `DRAIN_TANK`,
      `SPLIT_PUSH`,
      `SCALING`,
      `SURVIVABILITY`,
    ],
    buildTags: [
      `HEALTH`,
      `SCALING_HEALTH`,
      `DEFENSIVE`,
      `SUSTAIN`,
      `BURN_DAMAGE`,
      `ANTI_HEAL`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Solo lane health-scaling tank profile focused on absorbing pressure, sustaining through fights, and becoming difficult to kill with Maximum Dosage. Heartsteel, Sunfire Aegis, and Thornmail form the main health, burn, and anti-heal core. Hollow Radiance helps into magic damage, Randuin's Omen helps into critical strike damage, and Gargoyle adds strong frontline durability in teamfights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DRAVEN
  {
    profileKey: `draven-adc-snowball`,
    championKey: `draven`,
    role: GameRole.ADC,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.BURST,
      GamePlan.SAFE,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_HEAL,
    ],
    coreItemKeys: [`bloodthirster`, `essence-reaver`, `lord-dominiks-regard`],
    situationalItemKeys: [
      `magnetic-blaster`,
      `infinity-edge`,
      `mortal-reminder`,
      `guardian-angel`,
      `gluttonous-greaves`,
      `stasis`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `brutal`,
      `cut-down`,
      `legend-alacrity`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `barrier`],
    playStyleTags: [
      `AUTO_ATTACK_CHAMPION`,
      `SNOWBALL`,
      `LANE_PRESSURE`,
      `ADORATION`,
      `BONUS_GOLD`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `PHYSICAL_DAMAGE`,
      `SUSTAIN`,
      `CRITICAL_STRIKE`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
      `RAW_DAMAGE`,
    ],
    notes: `Duo lane snowball marksman profile focused on early lane pressure, Spinning Axe damage, and converting kills into gold through League of Draven. Bloodthirster, Essence Reaver, and Lord Dominik's Regard form the main damage and sustain core. Mortal Reminder answers healing, Guardian Angel improves safety against assassins, and Quicksilver helps into crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // EKKO
  {
    profileKey: `ekko-mid-burst`,
    championKey: `ekko`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`lich-bane`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `awakened-soulstealer`,
      `riftmaker`,
      `oceanids-trident`,
      `crown-of-the-shattered-queen`,
      `boots-of-mana`,
      `protobelt`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `fleet-footwork`,
      `battle-zeal`,
      `cut-down`,
      `legend-alacrity`,
      `transcendence`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`BURST`, `MOBILITY`, `PICK`, `SKIRMISH`, `OUTPLAY_TOOL`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `SPELLBLADE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
      `SUSTAIN`,
    ],
    notes: `Mid lane AP assassin profile focused on short burst trades, Phase Dive pick windows, and Chronobreak outplay safety. Lich Bane, Infinity Orb, and Rabadon's Deathcap form the main burst core. Oceanid's Trident answers shielding, Crown improves safety into crowd control or burst, Riftmaker adds sustain, and Quicksilver helps against lock-down heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `ekko-jungle-burst`,
    championKey: `ekko`,
    role: GameRole.JUNGLE,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`lich-bane`, `nashors-tooth`, `rabadons-deathcap`],
    situationalItemKeys: [
      `awakened-soulstealer`,
      `riftmaker`,
      `oceanids-trident`,
      `crown-of-the-shattered-queen`,
      `boots-of-mana`,
      `protobelt`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `fleet-footwork`,
      `sudden-impact`,
      `hubris`,
      `eyeball-collector`,
      `overgrowth`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [
      `BURST`,
      `MOBILITY`,
      `JUNGLE_CLEAR`,
      `SKIRMISH`,
      `OUTPLAY_TOOL`,
    ],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `SPELLBLADE`,
      `ATTACK_SPEED`,
      `ANTI_SHIELD`,
      `SUSTAIN`,
    ],
    notes: `Jungle Ekko profile focused on AP skirmishing, fast burst access, and safe dives with Chronobreak. Lich Bane, Nashor's Tooth, and Rabadon's Deathcap form the main jungle damage core. Oceanid's Trident answers shielding, Crown improves safety into crowd control, Riftmaker adds extended-fight sustain, and Quicksilver helps when lock-down prevents Ekko from resetting fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // EVELYNN
  {
    profileKey: `evelynn-jungle-burst`,
    championKey: `evelynn`,
    role: GameRole.JUNGLE,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`lich-bane`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `awakened-soulstealer`,
      `crown-of-the-shattered-queen`,
      `oceanids-trident`,
      `boots-of-mana`,
      `protobelt`,
    ],
    recommendedRuneKeys: [
      `first-strike`,
      `sudden-impact`,
      `hubris`,
      `eyeball-collector`,
      `transcendence`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [`BURST`, `PICK`, `MOBILITY`, `SNOWBALL`, `VISION_DENIAL`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `SPELLBLADE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
      `SPELL_SHIELD`,
    ],
    notes: `Jungle AP assassin profile focused on stealth picks, charm setup, and executing low-health targets with Last Caress. Lich Bane, Infinity Orb, and Rabadon's Deathcap form the main burst core. Awakened Soulstealer improves ultimate uptime, Oceanid's Trident answers shielding, Crown adds safety, and Protobelt helps Evelynn reach priority targets.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // EZREAL
  {
    profileKey: `ezreal-adc-poke`,
    championKey: `ezreal`,
    role: GameRole.ADC,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.SAFE,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`manamune`, `trinity-force`, `seryldas-grudge`],
    situationalItemKeys: [
      `spear-of-shojin`,
      `blade-of-the-ruined-king`,
      `maw-of-malmortius`,
      `serpents-fang`,
      `gluttonous-greaves`,
      `stasis`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `brutal`,
      `cut-down`,
      `legend-bloodline`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `barrier`],
    playStyleTags: [
      `POKE`,
      `MOBILITY`,
      `SCALING`,
      `SKILLSHOT_RELIANT`,
      `ABILITY_RELIANT_CHAMPION`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `PHYSICAL_DAMAGE`,
      `SCALING_MANA`,
      `SPELLBLADE`,
      `ABILITY_HASTE`,
      `ANTI_TANK`,
      `ANTI_SHIELD`,
    ],
    notes: `Duo lane poke marksman profile focused on safe Mystic Shot damage, scaling mana value, and kiting with Arcane Shift. Manamune, Trinity Force, and Serylda's Grudge form the main poke and spellblade core. Blade of the Ruined King helps into tanks, Maw of Malmortius helps into magic damage, Serpent's Fang answers shielding, and Quicksilver helps into crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // FIDDLESTICKS
  {
    profileKey: `fiddlesticks-jungle-teamfight`,
    championKey: `fiddlesticks`,
    role: GameRole.JUNGLE,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.ANTI_SHIELD,
      GamePlan.ANTI_HEAL,
    ],
    coreItemKeys: [`awakened-soulstealer`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `crown-of-the-shattered-queen`,
      `malignance`,
      `oceanids-trident`,
      `morellonomicon`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `first-strike`,
      `axiom-arcanist`,
      `absolute-focus`,
      `gathering-storm`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [
      `ULTIMATE_RELIANT_CHAMPION`,
      `TEAMFIGHT`,
      `ZONE_CONTROL`,
      `BURST`,
      `VISION_DENIAL`,
    ],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `AREA_DAMAGE`,
      `ULTIMATE_HASTE`,
      `ANTI_SHIELD`,
      `ANTI_HEAL`,
    ],
    notes: `Jungle teamfight mage profile focused on fog-of-war Crowstorm engages, area fear setup, and burst magic damage. Awakened Soulstealer, Infinity Orb, and Rabadon's Deathcap form the main AP burst core. Malignance improves ultimate pressure, Oceanid's Trident answers shielding, Morellonomicon answers healing, and Crown plus Stasis help Fiddlesticks survive after committing into fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // FIORA
  {
    profileKey: `fiora-top-duelist`,
    championKey: `fiora`,
    role: GameRole.TOP,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`trinity-force`, `eclipse`, `hullbreaker`],
    situationalItemKeys: [
      `spear-of-shojin`,
      `amaranths-twinguard`,
      `blade-of-the-ruined-king`,
      `serpents-fang`,
      `gluttonous-greaves`,
      `goredrinker`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `demolish`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `DUELIST`,
      `SPLIT_PUSH`,
      `SIDE_LANE`,
      `MOBILITY`,
      `HIGH_EXECUTION`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `SPELLBLADE`,
      `SUSTAIN`,
      `TRUE_DAMAGE`,
      `ANTI_TANK`,
      `ANTI_SHIELD`,
      `ABILITY_HASTE`,
    ],
    notes: `Solo lane duelist profile focused on side-lane pressure, vital procs, Riposte outplays, and Grand Challenge healing zones. Trinity Force, Eclipse, and Hullbreaker form the main split-push and dueling core. Blade of the Ruined King helps into tanks, Serpent's Fang answers shielding, Spear of Shojin improves ability uptime, and Quicksilver helps into crowd control-heavy matchups.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // FIZZ
  {
    profileKey: `fizz-mid-burst`,
    championKey: `fizz`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`lich-bane`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `awakened-soulstealer`,
      `crown-of-the-shattered-queen`,
      `oceanids-trident`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `fleet-footwork`,
      `sudden-impact`,
      `chain-assault`,
      `eyeball-collector`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`BURST`, `MOBILITY`, `PICK`, `DIVE`, `UNTARGETABLE`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `SPELLBLADE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
      `SPELL_SHIELD`,
    ],
    notes: `Mid lane AP assassin profile focused on Chum the Waters pick setup, Lich Bane burst, and Playful / Trickster outplay safety. Lich Bane, Infinity Orb, and Rabadon's Deathcap form the main burst core. Awakened Soulstealer improves ultimate uptime, Oceanid's Trident answers shielding, and Crown plus Stasis help Fizz survive after diving priority targets.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `fizz-jungle-burst`,
    championKey: `fizz`,
    role: GameRole.JUNGLE,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`lich-bane`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `awakened-soulstealer`,
      `riftmaker`,
      `oceanids-trident`,
      `crown-of-the-shattered-queen`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `fleet-footwork`,
      `sudden-impact`,
      `hubris`,
      `eyeball-collector`,
      `transcendence`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [`BURST`, `MOBILITY`, `PICK`, `DIVE`, `JUNGLE_CLEAR`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `SPELLBLADE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
      `SUSTAIN`,
    ],
    notes: `Jungle Fizz profile focused on AP burst ganks, target access from fog of war, and safe dive resets with Playful / Trickster. Lich Bane, Infinity Orb, and Rabadon's Deathcap form the main assassin core. Riftmaker adds sustain for extended skirmishes, Oceanid's Trident answers shielding, and Crown improves safety into crowd control or counter-burst.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GALIO
  {
    profileKey: `galio-mid-tank`,
    championKey: `galio`,
    role: GameRole.MID,
    gamePlan: [GamePlan.STANDARD, GamePlan.SURVIVE_DIVE, GamePlan.ANTI_HEAL],
    coreItemKeys: [`riftmaker`, `hollow-radiance`, `thornmail`],
    situationalItemKeys: [
      `dawnshroud`,
      `amaranths-twinguard`,
      `boots-of-mana`,
      `protobelt`,
    ],
    recommendedRuneKeys: [
      `ice-overlord`,
      `courage-of-the-colossus`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `VANGUARD`,
      `TEAMFIGHT`,
      `ROAMING`,
      `TEAM_SUPPORT`,
      `ANTI_MAGE`,
    ],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `DEFENSIVE`,
      `HEALTH`,
      `SUSTAIN`,
      `ANTI_HEAL`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Mid lane tank-mage profile focused on anti-magic durability, teamfight engage, and cross-map follow-up with Hero's Entrance. Riftmaker, Hollow Radiance, and Thornmail form the main sustain, magic-resist, and anti-heal core. Dawnshroud improves engage value, Amaranth's Twinguard adds late-fight durability, and Protobelt helps Galio find taunt or Justice Punch angles.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `galio-support-tank`,
    championKey: `galio`,
    role: GameRole.SUPPORT,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SURVIVE_DIVE,
      GamePlan.SAFE,
      GamePlan.ANTI_HEAL,
    ],
    coreItemKeys: [`bulwark-of-the-mountain`, `yordle-trap`, `warmogs-armor`],
    situationalItemKeys: [
      `frozen-heart`,
      `kaenic-rookern`,
      `thornmail`,
      `randuins-omen`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `gargoyle`,
    ],
    recommendedRuneKeys: [
      `ice-overlord`,
      `courage-of-the-colossus`,
      `second-wind`,
      `overgrowth`,
      `hextech-flashtraption`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`TEAM_SUPPORT`, `VANGUARD`, `ENGAGE`, `PEEL`, `TEAMFIGHT`],
    buildTags: [
      `SUPPORT`,
      `DEFENSIVE`,
      `HEALTH`,
      `ABILITY_HASTE`,
      `ANTI_ATTACK_SPEED`,
      `ANTI_HEAL`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Support tank profile focused on engage, peel, taunt threat, and protecting allies with Hero's Entrance. Bulwark of the Mountain, Yordle Trap, and Warmog's Armor form the main durable support core. Frozen Heart helps against attack speed users, Thornmail answers healing, Randuin's Omen helps into critical strike damage, and Gargoyle adds frontline durability after engaging.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GAREN
  {
    profileKey: `garen-top-juggernaut`,
    championKey: `garen`,
    role: GameRole.TOP,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SURVIVE_DIVE,
      GamePlan.ANTI_SHIELD,
      GamePlan.ANTI_HEAL,
    ],
    coreItemKeys: [`black-cleaver`, `dead-mans-plate`, `spear-of-shojin`],
    situationalItemKeys: [
      `force-of-nature`,
      `amaranths-twinguard`,
      `serpents-fang`,
      `thornmail`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `gargoyle`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `demolish`,
      `second-wind`,
      `overgrowth`,
      `nimbus-cloak`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `JUGGERNAUT`,
      `DUELING`,
      `SPLIT_PUSH`,
      `SURVIVABILITY`,
      `SIDE_LANE`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `HEALTH`,
      `DEFENSIVE`,
      `ARMOR_REDUCTION`,
      `MOVEMENT_SPEED`,
      `ANTI_SHIELD`,
      `ANTI_HEAL`,
    ],
    notes: `Solo lane juggernaut profile focused on durable side-lane pressure, Decisive Strike engage, Judgment armor shred, and Demacian Justice execute threat. Black Cleaver, Dead Man's Plate, and Spear of Shojin form the main bruiser mobility and ability-haste core. Serpent's Fang answers shielding, Thornmail answers healing, Force of Nature helps into magic damage, and Gargoyle improves frontline durability in teamfights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GNAR
  {
    profileKey: `gnar-top-bruiser`,
    championKey: `gnar`,
    role: GameRole.TOP,
    gamePlan: [GamePlan.STANDARD, GamePlan.SCALING, GamePlan.SURVIVE_DIVE],
    coreItemKeys: [`trinity-force`, `black-cleaver`, `steraks-gage`],
    situationalItemKeys: [
      `amaranths-twinguard`,
      `guardian-angel`,
      `hullbreaker`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `gargoyle`,
    ],
    recommendedRuneKeys: [
      `fleet-footwork`,
      `unshakeable`,
      `second-wind`,
      `overgrowth`,
      `brutal`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `FORM_CHANGE`,
      `DUELING`,
      `TEAMFIGHT`,
      `SPLIT_PUSH`,
      `ZONE_CONTROL`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `HEALTH`,
      `SPELLBLADE`,
      `ARMOR_REDUCTION`,
      `DEFENSIVE`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Solo lane bruiser profile focused on ranged lane control in Mini Gnar, Rage timing, and Mega Gnar teamfight engage. Trinity Force, Black Cleaver, and Sterak's Gage form the main bruiser damage and durability core. Hullbreaker is available for split pushing, while Amaranth's Twinguard, Guardian Angel, and Gargoyle improve durability when committing as Mega Gnar.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GRAGAS
  {
    profileKey: `gragas-mid-burst`,
    championKey: `gragas`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`ludens-echo`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `awakened-soulstealer`,
      `lich-bane`,
      `oceanids-trident`,
      `crown-of-the-shattered-queen`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `electrocute`,
      `hextech-flashtraption`,
      `transcendence`,
      `nimbus-cloak`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`BURST`, `PICK`, `MOBILITY`, `ZONE_CONTROL`, `TEAMFIGHT`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MAGIC_PENETRATION`,
      `ULTIMATE_HASTE`,
      `SPELLBLADE`,
      `ANTI_SHIELD`,
    ],
    notes: `Mid lane AP burst profile focused on Barrel Roll poke, Body Slam engage, and Explosive Cask displacement picks. Luden's Echo, Infinity Orb, and Rabadon's Deathcap form the main burst core. Lich Bane adds combo damage, Oceanid's Trident answers shielding, Crown improves safety into crowd control or burst, and Stasis helps after aggressive engage plays.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `gragas-jungle-burst`,
    championKey: `gragas`,
    role: GameRole.JUNGLE,
    gamePlan: [
      GamePlan.BURST,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`lich-bane`, `infinity-orb`, `rabadons-deathcap`],
    situationalItemKeys: [
      `awakened-soulstealer`,
      `crown-of-the-shattered-queen`,
      `oceanids-trident`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `first-strike`,
      `sudden-impact`,
      `chain-assault`,
      `eyeball-collector`,
      `transcendence`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [`BURST`, `PICK`, `MOBILITY`, `JUNGLE_CLEAR`, `TEAMFIGHT`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `SPELLBLADE`,
      `MAGIC_PENETRATION`,
      `ANTI_SHIELD`,
      `SPELL_SHIELD`,
    ],
    notes: `Jungle AP burst profile focused on Body Slam ganks, Explosive Cask displacement, and burst follow-up from fog of war. Lich Bane, Infinity Orb, and Rabadon's Deathcap form the main assassin-style jungle core. Awakened Soulstealer improves ultimate uptime, Oceanid's Trident answers shielding, and Crown plus Stasis improve safety after committing into fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GRAVES
  {
    profileKey: `graves-jungle-marksman`,
    championKey: `graves`,
    role: GameRole.JUNGLE,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_HEAL,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`the-collector`, `bloodthirster`, `lord-dominiks-regard`],
    situationalItemKeys: [
      `essence-reaver`,
      `infinity-edge`,
      `mortal-reminder`,
      `maw-of-malmortius`,
      `serpents-fang`,
      `gluttonous-greaves`,
      `galeforce`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `fleet-footwork`,
      `sudden-impact`,
      `hubris`,
      `eyeball-collector`,
      `overgrowth`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [
      `AUTO_ATTACK_CHAMPION`,
      `JUNGLE_CLEAR`,
      `SKIRMISH`,
      `DPS`,
      `SNOWBALL`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `PHYSICAL_DAMAGE`,
      `CRITICAL_STRIKE`,
      `SUSTAIN`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
      `ANTI_SHIELD`,
    ],
    notes: `Jungle marksman-skirmisher profile focused on fast clear, close-range burst, sustained physical damage, and snowballing through early tempo. The Collector, Bloodthirster, and Lord Dominik's Regard form the main damage and sustain core. Mortal Reminder answers healing, Maw of Malmortius helps into magic damage, Serpent's Fang answers shielding, and Quicksilver helps into crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GWEN
  {
    profileKey: `gwen-top-scaling`,
    championKey: `gwen`,
    role: GameRole.TOP,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_HEAL,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`rod-of-ages`, `psychic-projector`, `rabadons-deathcap`],
    situationalItemKeys: [
      `infinity-orb`,
      `oceanids-trident`,
      `morellonomicon`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `gargoyle`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `demolish`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `SCALING`,
      `DUELIST`,
      `SKIRMISH`,
      `SPLIT_PUSH`,
      `EXTENDED_FIGHT_CHAMPION`,
    ],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `SCALING_HEALTH`,
      `SUSTAIN`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
      `ANTI_SHIELD`,
    ],
    notes: `Solo lane AP skirmisher profile focused on scaling, extended duels, Hallowed Mist outplay windows, and percent-health magic damage. Rod of Ages, Psychic Projector, and Rabadon's Deathcap form the main health-scaling AP core. Infinity Orb improves execute pressure, Morellonomicon answers healing, Oceanid's Trident answers shielding, and Gargoyle adds durability when Gwen commits into fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // HECARIM
  {
    profileKey: `hecarim-jungle-speed`,
    championKey: `hecarim`,
    role: GameRole.JUNGLE,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.SURVIVE_DIVE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`trinity-force`, `manamune`, `seryldas-grudge`],
    situationalItemKeys: [
      `muramana`,
      `spear-of-shojin`,
      `deaths-dance`,
      `serpents-fang`,
      `ionian-boots-of-lucidity`,
      `glorious`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `phase-rush`,
      `axiom-arcanist`,
      `transcendence`,
      `nimbus-cloak`,
      `overgrowth`,
    ],
    recommendedSpellKeys: [`ghost`, `smite`],
    playStyleTags: [
      `MOBILITY`,
      `DIVE`,
      `JUNGLE_CLEAR`,
      `SKIRMISH`,
      `TEAMFIGHT`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `PHYSICAL_DAMAGE`,
      `SCALING_MANA`,
      `SPELLBLADE`,
      `ABILITY_HASTE`,
      `MOVEMENT_SPEED`,
      `ANTI_SHIELD`,
    ],
    notes: `Jungle speed-fighter profile focused on movement-speed scaling, fast engage, and backline disruption with Onslaught of Shadows. Trinity Force, Manamune, and Serylda's Grudge form the main damage, mana-scaling, and slow core. Spear of Shojin improves ability uptime, Death's Dance adds durability after diving, Serpent's Fang answers shielding, and Quicksilver helps into crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // HEIMERDINGER
  {
    profileKey: `heimerdinger-mid-zone-control`,
    championKey: `heimerdinger`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.BURST,
      GamePlan.SAFE,
      GamePlan.ANTI_HEAL,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`infinity-orb`, `awakened-soulstealer`, `rabadons-deathcap`],
    situationalItemKeys: [
      `oceanids-trident`,
      `crown-of-the-shattered-queen`,
      `morellonomicon`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `first-strike`,
      `cheap-shot`,
      `tyrant`,
      `eyeball-collector`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `ZONE_CONTROL`,
      `POKE`,
      `BURST`,
      `TEAMFIGHT`,
      `ABILITY_RELIANT_CHAMPION`,
    ],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MAGIC_PENETRATION`,
      `ULTIMATE_HASTE`,
      `ANTI_HEAL`,
      `ANTI_SHIELD`,
    ],
    notes: `Mid lane control mage profile focused on turret zones, poke pressure, grenade setup, and upgraded ability burst. Infinity Orb, Awakened Soulstealer, and Rabadon's Deathcap form the main AP burst core. Oceanid's Trident answers shielding, Morellonomicon answers healing, and Crown plus Stasis help Heimerdinger survive assassins or dive after setting up his turret field.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // IRELIA
  {
    profileKey: `irelia-top-duelist`,
    championKey: `irelia`,
    role: GameRole.TOP,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.ANTI_TANK,
      GamePlan.SURVIVE_DIVE,
    ],
    coreItemKeys: [`trinity-force`, `blade-of-the-ruined-king`, `hullbreaker`],
    situationalItemKeys: [
      `deaths-dance`,
      `guardian-angel`,
      `wits-end`,
      `gluttonous-greaves`,
      `stasis`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `demolish`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `barrier`],
    playStyleTags: [
      `DUELIST`,
      `SPLIT_PUSH`,
      `MOBILITY`,
      `SKIRMISH`,
      `HIGH_EXECUTION`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `ON_HIT`,
      `SPELLBLADE`,
      `SUSTAIN`,
      `ANTI_TANK`,
      `PHYSICAL_DAMAGE`,
    ],
    notes: `Solo lane duelist profile focused on Bladesurge resets, side-lane pressure, and extended fights with Ionian Fervor stacks. Trinity Force, Blade of the Ruined King, and Hullbreaker form the main split-push and dueling core. Death's Dance and Guardian Angel improve survivability, Wit's End helps into magic damage, and Quicksilver helps when crowd control stops her reset chain.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `irelia-mid-duelist`,
    championKey: `irelia`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.BURST,
      GamePlan.ANTI_TANK,
      GamePlan.SURVIVE_DIVE,
    ],
    coreItemKeys: [`trinity-force`, `blade-of-the-ruined-king`, `deaths-dance`],
    situationalItemKeys: [
      `terminus`,
      `guardian-angel`,
      `wits-end`,
      `gluttonous-greaves`,
      `stasis`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `brutal`,
      `last-stand`,
      `legend-bloodline`,
      `second-wind`,
    ],
    recommendedSpellKeys: [`flash`, `barrier`],
    playStyleTags: [
      `DUELIST`,
      `MOBILITY`,
      `DIVE`,
      `SKIRMISH`,
      `HIGH_EXECUTION`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `ON_HIT`,
      `SPELLBLADE`,
      `SUSTAIN`,
      `PHYSICAL_DAMAGE`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Mid lane fighter profile focused on punishing squishy targets, dashing through waves, and creating all-in windows with Vanguard's Edge. Trinity Force, Blade of the Ruined King, and Death's Dance form the main damage and survivability core. Terminus adds extended-fight value, Guardian Angel improves safety after diving, Wit's End helps into magic damage, and Quicksilver helps into crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JANNA
  {
    profileKey: `janna-support-enchanter`,
    championKey: `janna`,
    role: GameRole.SUPPORT,
    gamePlan: [GamePlan.SAFE, GamePlan.STANDARD, GamePlan.SURVIVE_DIVE],
    coreItemKeys: [`bulwark-of-the-mountain`, `harmonic-echo`, `ardent-censer`],
    situationalItemKeys: [
      `redemption`,
      `crown-of-the-shattered-queen`,
      `ionian-boots-of-lucidity`,
      `veil`,
    ],
    recommendedRuneKeys: [
      `aery`,
      `font-of-life`,
      `bone-plating`,
      `revitalize`,
      `ingenious-hunter`,
    ],
    recommendedSpellKeys: [`flash`, `heal`],
    playStyleTags: [
      `TEAM_SUPPORT`,
      `PEEL`,
      `SURVIVABILITY`,
      `LANE_SURVIVAL`,
      `DISENGAGE`,
    ],
    buildTags: [
      `SUPPORT`,
      `HEAL_SHIELD_POWER`,
      `SHIELD`,
      `MANA_REGEN`,
      `ABILITY_HASTE`,
      `DEFENSIVE`,
      `SPELL_SHIELD`,
    ],
    notes: `Support enchanter profile focused on peel, shielding, disengage, and protecting high-damage carries through extended fights. Bulwark of the Mountain, Harmonic Echo, and Ardent Censer form the main support utility core. Redemption adds teamwide sustain, Crown improves personal safety, and Veil helps protect allies from key crowd control or pick attempts.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JARVAN IV
  {
    profileKey: `jarvan-iv-jungle-engage`,
    championKey: `jarvan-iv`,
    role: GameRole.JUNGLE,
    gamePlan: [GamePlan.STANDARD, GamePlan.SURVIVE_DIVE, GamePlan.ANTI_HEAL],
    coreItemKeys: [`trinity-force`, `radiant-virtue`, `force-of-nature`],
    situationalItemKeys: [
      `frozen-heart`,
      `amaranths-twinguard`,
      `thornmail`,
      `randuins-omen`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `goredrinker`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `unshakeable`,
      `bone-plating`,
      `overgrowth`,
      `triumph`,
    ],
    recommendedSpellKeys: [`flash`, `smite`],
    playStyleTags: [`VANGUARD`, `JUNGLE_CLEAR`, `ENGAGE`, `DIVE`, `TEAMFIGHT`],
    buildTags: [
      `ATTACK_DAMAGE`,
      `HEALTH`,
      `DEFENSIVE`,
      `SPELLBLADE`,
      `SUSTAIN`,
      `ANTI_HEAL`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Jungle engage fighter profile focused on early ganks, Dragon Strike plus Demacian Standard knock-up setup, and Cataclysm lockdown. Trinity Force, Radiant Virtue, and Force of Nature form the main fighter-support durability core. Frozen Heart helps against attack speed users, Thornmail answers healing, Randuin's Omen helps into critical strike damage, and Goredrinker adds sustain after diving into fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JAX
  {
    profileKey: `jax-top-duelist`,
    championKey: `jax`,
    role: GameRole.TOP,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.ANTI_SHIELD,
      GamePlan.SURVIVE_DIVE,
    ],
    coreItemKeys: [`trinity-force`, `riftmaker`, `zekes-convergence`],
    situationalItemKeys: [
      `oceanids-trident`,
      `amaranths-twinguard`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `gargoyle`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `grasp-of-the-undying`,
      `demolish`,
      `second-wind`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `DUELIST`,
      `SPLIT_PUSH`,
      `SCALING`,
      `ON_HIT_CHAMPION`,
      `EXTENDED_FIGHT_CHAMPION`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ABILITY_POWER`,
      `SPELLBLADE`,
      `SUSTAIN`,
      `HYBRID_DAMAGE`,
      `ANTI_SHIELD`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Solo lane duelist profile focused on scaling side-lane pressure, Empower trades, Counter Strike outplays, and extended fights with Grandmaster-at-Arms. Trinity Force, Riftmaker, and Zeke's Convergence form the main hybrid bruiser core. Oceanid's Trident answers shielding, Amaranth's Twinguard improves durability, and Quicksilver helps when crowd control stops Jax from sticking to targets.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JAYCE
  {
    profileKey: `jayce-mid-poke`,
    championKey: `jayce`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.BURST,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`manamune`, `youmuus-ghostblade`, `seryldas-grudge`],
    situationalItemKeys: [
      `muramana`,
      `edge-of-night`,
      `guardian-angel`,
      `serpents-fang`,
      `boots-of-dynamism`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `first-strike`,
      `sudden-impact`,
      `chain-assault`,
      `eyeball-collector`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `POKE`,
      `BURST`,
      `FORM_SWAP`,
      `LANE_PRESSURE`,
      `ABILITY_RELIANT_CHAMPION`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `PHYSICAL_DAMAGE`,
      `SCALING_MANA`,
      `ABILITY_HASTE`,
      `ARMOR_REDUCTION`,
      `SPELL_SHIELD`,
      `ANTI_SHIELD`,
    ],
    notes: `Mid lane poke profile focused on Shock Blast pressure, form-swapping burst, and early lane control. Manamune, Youmuu's Ghostblade, and Serylda's Grudge form the main poke and armor-reduction core. Serpent's Fang answers shielding, Edge of Night adds spell shield safety, and Guardian Angel plus Stasis help Jayce survive after committing in hammer form.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `jayce-top-bruiser`,
    championKey: `jayce`,
    role: GameRole.TOP,
    gamePlan: [GamePlan.STANDARD, GamePlan.BURST, GamePlan.SURVIVE_DIVE],
    coreItemKeys: [`eclipse`, `trinity-force`, `seryldas-grudge`],
    situationalItemKeys: [
      `spear-of-shojin`,
      `guardian-angel`,
      `gluttonous-greaves`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `conqueror`,
      `demolish`,
      `bone-plating`,
      `overgrowth`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `POKE`,
      `DUELING`,
      `FORM_SWAP`,
      `LANE_PRESSURE`,
      `SIDE_LANE`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `PHYSICAL_DAMAGE`,
      `SPELLBLADE`,
      `ABILITY_HASTE`,
      `ARMOR_REDUCTION`,
      `SUSTAIN`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Solo lane Jayce profile focused on ranged lane pressure, hammer-form burst trades, and side-lane tempo. Eclipse, Trinity Force, and Serylda's Grudge form the main bruiser poke core. Spear of Shojin improves ability uptime, Guardian Angel adds safety after aggressive commits, and Stasis helps Jayce survive burst or dive windows.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JHIN
  {
    profileKey: `jhin-adc-execute`,
    championKey: `jhin`,
    role: GameRole.ADC,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.BURST,
      GamePlan.SAFE,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_HEAL,
    ],
    coreItemKeys: [`the-collector`, `magnetic-blaster`, `lord-dominiks-regard`],
    situationalItemKeys: [
      `infinity-edge`,
      `bloodthirster`,
      `mortal-reminder`,
      `guardian-angel`,
      `gluttonous-greaves`,
      `galeforce`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `dark-harvest`,
      `brutal`,
      `cut-down`,
      `legend-alacrity`,
      `celerity`,
    ],
    recommendedSpellKeys: [`flash`, `ghost`],
    playStyleTags: [
      `UTILITY_MARKSMAN`,
      `BURST`,
      `PICK`,
      `POKE`,
      `POSITIONING_RELIANT`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `PHYSICAL_DAMAGE`,
      `CRITICAL_STRIKE`,
      `BURST_DAMAGE`,
      `EXECUTE`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
    ],
    notes: `Duo lane utility marksman profile focused on pick setup, fourth-shot burst, long-range follow-up, and execute pressure with Curtain Call. The Collector, Magnetic Blaster, and Lord Dominik's Regard form the main physical damage and anti-tank core. Mortal Reminder answers healing, Guardian Angel improves safety against assassins, and Quicksilver helps into crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JINX
  {
    profileKey: `jinx-adc-hypercarry`,
    championKey: `jinx`,
    role: GameRole.ADC,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.SAFE,
      GamePlan.ANTI_TANK,
      GamePlan.ANTI_HEAL,
    ],
    coreItemKeys: [`bloodthirster`, `magnetic-blaster`, `lord-dominiks-regard`],
    situationalItemKeys: [
      `runaans-hurricane`,
      `infinity-edge`,
      `mortal-reminder`,
      `berserkers-greaves`,
      `galeforce`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `lethal-tempo`,
      `brutal`,
      `cut-down`,
      `legend-alacrity`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ghost`],
    playStyleTags: [
      `HYPERCARRY`,
      `AUTO_ATTACK_CHAMPION`,
      `DPS`,
      `SCALING`,
      `RESET_CHAMPION`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `PHYSICAL_DAMAGE`,
      `CRITICAL_STRIKE`,
      `SUSTAIN`,
      `ANTI_TANK`,
      `ANTI_HEAL`,
    ],
    notes: `Duo lane hypercarry profile focused on scaling DPS, rocket-form teamfight damage, and Get Excited! reset cleanup. Bloodthirster, Magnetic Blaster, and Lord Dominik's Regard form the main physical damage and anti-tank core. Runaan's Hurricane and Infinity Edge increase late-game teamfight damage, Mortal Reminder answers healing, and Quicksilver helps against crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // K'SANTE
  {
    profileKey: `ksante-top-tank`,
    championKey: `k-sante`,
    role: GameRole.TOP,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SURVIVE_DIVE,
      GamePlan.ANTI_HEAL,
      GamePlan.SCALING,
    ],
    coreItemKeys: [`iceborn-gauntlet`, `thornmail`, `unending-despair`],
    situationalItemKeys: [
      `mantle-of-the-twelfth-hour`,
      `amaranths-twinguard`,
      `randuins-omen`,
      `frozen-heart`,
      `plated-steelcaps`,
      `mercurys-treads`,
      `gargoyle`,
    ],
    recommendedRuneKeys: [
      `grasp-of-the-undying`,
      `unshakeable`,
      `second-wind`,
      `overgrowth`,
      `last-stand`,
    ],
    recommendedSpellKeys: [`flash`, `teleport`],
    playStyleTags: [
      `VANGUARD`,
      `DUELING`,
      `TEAMFIGHT`,
      `SURVIVABILITY`,
      `SIDE_LANE`,
    ],
    buildTags: [
      `DEFENSIVE`,
      `HEALTH`,
      `ARMOR_REDUCTION`,
      `ANTI_HEAL`,
      `ANTI_ATTACK_SPEED`,
      `DAMAGE_REDUCTION`,
      `SLOW`,
    ],
    notes: `Solo lane tank profile focused on durable trading, displacement control, side-lane pressure, and All Out target isolation. Iceborn Gauntlet, Thornmail, and Unending Despair form the main tank and anti-heal core. Randuin's Omen helps into critical strike damage, Frozen Heart helps against attack speed, Mercury's Treads helps into magic damage or crowd control, and Gargoyle adds frontline durability in teamfights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KAI'SA
  {
    profileKey: `kaisa-adc-on-hit`,
    championKey: `kaisa`,
    role: GameRole.ADC,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.ANTI_TANK,
      GamePlan.SAFE,
    ],
    coreItemKeys: [
      `kraken-slayer`,
      `guinsoos-rageblade`,
      `blade-of-the-ruined-king`,
    ],
    situationalItemKeys: [
      `terminus`,
      `runaans-hurricane`,
      `berserkers-greaves`,
      `stasis`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `lethal-tempo`,
      `brutal`,
      `cut-down`,
      `legend-alacrity`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `ghost`],
    playStyleTags: [
      `HYPERCARRY`,
      `ON_HIT_CHAMPION`,
      `AUTO_ATTACK_CHAMPION`,
      `DPS`,
      `MOBILITY`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `ON_HIT`,
      `HYBRID_DAMAGE`,
      `ANTI_TANK`,
      `SUSTAIN_DAMAGE`,
      `PHYSICAL_DAMAGE`,
    ],
    notes: `Duo lane on-hit hypercarry profile focused on scaling DPS, Plasma stacking, Supercharge repositioning, and Killer Instinct follow-up. Kraken Slayer, Guinsoo's Rageblade, and Blade of the Ruined King form the main on-hit damage core. Terminus and Runaan's Hurricane improve extended-fight and multi-target value, while Quicksilver helps into crowd control-heavy teams.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KALISTA
  {
    profileKey: `kalista-adc-on-hit`,
    championKey: `kalista`,
    role: GameRole.ADC,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.SCALING,
      GamePlan.ANTI_TANK,
      GamePlan.SAFE,
    ],
    coreItemKeys: [
      `blade-of-the-ruined-king`,
      `guinsoos-rageblade`,
      `runaans-hurricane`,
    ],
    situationalItemKeys: [
      `terminus`,
      `amaranths-twinguard`,
      `randuins-omen`,
      `guardian-angel`,
      `berserkers-greaves`,
      `quicksilver`,
    ],
    recommendedRuneKeys: [
      `lethal-tempo`,
      `brutal`,
      `cut-down`,
      `legend-alacrity`,
      `bone-plating`,
    ],
    recommendedSpellKeys: [`flash`, `barrier`],
    playStyleTags: [
      `ON_HIT_CHAMPION`,
      `AUTO_ATTACK_CHAMPION`,
      `DPS`,
      `MOBILITY`,
      `OATHSWORN_RELIANT`,
    ],
    buildTags: [
      `ATTACK_DAMAGE`,
      `ATTACK_SPEED`,
      `ON_HIT`,
      `PHYSICAL_DAMAGE`,
      `SUSTAIN_DAMAGE`,
      `ANTI_TANK`,
      `DAMAGE_REDUCTION`,
    ],
    notes: `Duo lane on-hit marksman profile focused on Martial Poise kiting, spear stacking, Rend execution, and Fate's Call engage or save plays with her Oathsworn ally. Blade of the Ruined King, Guinsoo's Rageblade, and Runaan's Hurricane form the main on-hit DPS core. Terminus improves extended-fight value, Randuin's Omen helps into critical strike damage, Guardian Angel helps into burst, and Quicksilver helps against crowd control that stops her movement pattern.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KARMA
  {
    profileKey: `karma-support-enchanter`,
    championKey: `karma`,
    role: GameRole.SUPPORT,
    gamePlan: [
      GamePlan.SAFE,
      GamePlan.STANDARD,
      GamePlan.ANTI_HEAL,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`bulwark-of-the-mountain`, `harmonic-echo`, `ardent-censer`],
    situationalItemKeys: [
      `redemption`,
      `frozen-heart`,
      `morellonomicon`,
      `oceanids-trident`,
      `ionian-boots-of-lucidity`,
      `veil`,
    ],
    recommendedRuneKeys: [
      `aery`,
      `font-of-life`,
      `bone-plating`,
      `revitalize`,
      `ingenious-hunter`,
    ],
    recommendedSpellKeys: [`flash`, `heal`],
    playStyleTags: [`TEAM_SUPPORT`, `PEEL`, `POKE`, `UTILITY`, `LANE_SURVIVAL`],
    buildTags: [
      `SUPPORT`,
      `HEAL_SHIELD_POWER`,
      `SHIELD`,
      `MANA_REGEN`,
      `ABILITY_HASTE`,
      `ANTI_HEAL`,
      `ANTI_SHIELD`,
    ],
    notes: `Support enchanter profile focused on poke, shielding, speed-up utility, and empowering carries with Inspire. Bulwark of the Mountain, Harmonic Echo, and Ardent Censer form the main support utility core. Redemption adds team sustain, Frozen Heart helps against attack speed, Morellonomicon answers healing, Oceanid's Trident answers shielding, and Veil adds protection against key pick tools.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    profileKey: `karma-mid-poke`,
    championKey: `karma`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.STANDARD,
      GamePlan.BURST,
      GamePlan.SAFE,
      GamePlan.ANTI_HEAL,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`ludens-echo`, `bandle-fantasy`, `rabadons-deathcap`],
    situationalItemKeys: [
      `malignance`,
      `horizon-focus`,
      `morellonomicon`,
      `oceanids-trident`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `arcane-comet`,
      `cheap-shot`,
      `tyrant`,
      `eyeball-collector`,
      `transcendence`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [`POKE`, `BURST`, `ZONE_CONTROL`, `TEAM_SUPPORT`, `UTILITY`],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MAGIC_PENETRATION`,
      `ABILITY_HASTE`,
      `ANTI_HEAL`,
      `ANTI_SHIELD`,
    ],
    notes: `Mid lane poke mage profile focused on Inner Flame pressure, Mantra burst, and utility shielding during skirmishes. Luden's Echo, Bandle Fantasy, and Rabadon's Deathcap form the main AP poke core. Malignance and Horizon Focus increase long-range damage value, Morellonomicon answers healing, Oceanid's Trident answers shielding, and Stasis improves safety against dive.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KASSADIN
  {
    profileKey: `kassadin-mid-scaling`,
    championKey: `kassadin`,
    role: GameRole.MID,
    gamePlan: [
      GamePlan.SCALING,
      GamePlan.STANDARD,
      GamePlan.SAFE,
      GamePlan.ANTI_SHIELD,
    ],
    coreItemKeys: [`rod-of-ages`, `archangels-staff`, `rabadons-deathcap`],
    situationalItemKeys: [
      `seraphs-embrace`,
      `malignance`,
      `infinity-orb`,
      `crown-of-the-shattered-queen`,
      `oceanids-trident`,
      `boots-of-mana`,
      `stasis`,
    ],
    recommendedRuneKeys: [
      `first-strike`,
      `botanist`,
      `transcendence`,
      `gathering-storm`,
      `sudden-impact`,
    ],
    recommendedSpellKeys: [`flash`, `ignite`],
    playStyleTags: [
      `SCALING`,
      `MOBILITY`,
      `BURST`,
      `ANTI_MAGE`,
      `ULTIMATE_RELIANT_CHAMPION`,
    ],
    buildTags: [
      `ABILITY_POWER`,
      `MAGIC_DAMAGE`,
      `SCALING_MANA`,
      `SCALING_HEALTH`,
      `BURST_DAMAGE`,
      `ULTIMATE_HASTE`,
      `ANTI_SHIELD`,
    ],
    notes: `Mid lane scaling AP assassin profile focused on surviving early lane, stacking Rod of Ages and Archangel's Staff, then taking over fights with Riftwalk mobility and burst. Rod of Ages, Archangel's Staff, and Rabadon's Deathcap form the main scaling core. Malignance improves ultimate pressure, Infinity Orb adds execute burst, Crown helps into crowd control or burst, and Oceanid's Trident answers shielding.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
];

export async function seedChampionBuildProfiles(
  prisma: PrismaClient,
  patchId: string,
) {
  console.log(`Seeding champion build profiles...`);

  for (const championBuildProfileSeed of championBuildProfileSeeds) {
    const champion = await prisma.champion.findUnique({
      where: {
        key: championBuildProfileSeed.championKey,
      },
    });

    if (!champion || champion.deletedAt) {
      throw new Error(
        `Champion not found or deleted: ${championBuildProfileSeed.championKey}`,
      );
    }

    await prisma.championBuildProfile.upsert({
      where: {
        championId_patchId_role_profileKey: {
          championId: champion.id,
          patchId,
          role: championBuildProfileSeed.role,
          profileKey: championBuildProfileSeed.profileKey,
        },
      },
      update: {
        gamePlan: championBuildProfileSeed.gamePlan,
        coreItemKeys: championBuildProfileSeed.coreItemKeys,
        situationalItemKeys: championBuildProfileSeed.situationalItemKeys,
        recommendedRuneKeys: championBuildProfileSeed.recommendedRuneKeys,
        recommendedSpellKeys: championBuildProfileSeed.recommendedSpellKeys,
        playStyleTags: championBuildProfileSeed.playStyleTags,
        buildTags: championBuildProfileSeed.buildTags,
        notes: championBuildProfileSeed.notes ?? null,
        dataQuality:
          championBuildProfileSeed.dataQuality ?? DataQualityLevel.MINIMAL,
        deletedAt: null,
      },
      create: {
        profileKey: championBuildProfileSeed.profileKey,
        championId: champion.id,
        patchId,
        role: championBuildProfileSeed.role,
        gamePlan: championBuildProfileSeed.gamePlan,
        coreItemKeys: championBuildProfileSeed.coreItemKeys,
        situationalItemKeys: championBuildProfileSeed.situationalItemKeys,
        recommendedRuneKeys: championBuildProfileSeed.recommendedRuneKeys,
        recommendedSpellKeys: championBuildProfileSeed.recommendedSpellKeys,
        playStyleTags: championBuildProfileSeed.playStyleTags,
        buildTags: championBuildProfileSeed.buildTags,
        notes: championBuildProfileSeed.notes ?? null,
        dataQuality:
          championBuildProfileSeed.dataQuality ?? DataQualityLevel.MINIMAL,
      },
    });

    console.log(`Seeded ${champion.name}'s build profile for patch ${patchId}`);
  }

  console.log(`SEEDED CHAMPIONS BUILD PROFILES`);
}
