import { Prisma, PrismaClient } from './../../src/generated/prisma/client.js';

type ChampionPatchStatSeed = {
  championKey: string;
  baseHealth?: number | null;
  baseArmor?: number | null;
  baseMana?: number | null;
  baseMagicResist: number;
  baseAttackDamage?: number | null;
  baseAbilityPower?: number | null;
  attackSpeed?: number | null;
  moveSpeed?: number | null;
  healthGrowth?: number | null;
  manaGrowth?: number | null;
  armorGrowth?: number | null;
  magicResistGrowth?: number | null;
  attackDamageGrowth?: number | null;
  attackSpeedGrowth?: number | null;
  scalingProfile?: Prisma.InputJsonValue;
  laneProfile?: Prisma.InputJsonValue;
  teamProfile?: Prisma.InputJsonValue;
  metaScore?: number | null;
};

const championPatchStatSeeds: ChampionPatchStatSeed[] = [
  // AATROX
  {
    championKey: `aatrox`,

    baseHealth: 630,
    baseArmor: 46,
    baseMagicResist: 40,
    baseAttackDamage: 62,
    baseAbilityPower: 0,
    attackSpeed: 0.73,
    moveSpeed: 355,

    healthGrowth: 136,
    armorGrowth: 4,
    magicResistGrowth: 2,
    attackDamageGrowth: 5,
    attackSpeedGrowth: 0.007857,

    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 6,
          armor: 46,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 62,
          attackSpeed: 0.73,
        },
        {
          level: 2,
          health: 766,
          healthRegenPer5s: 7,
          armor: 50,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 67,
          attackSpeed: 0.74,
        },
        {
          level: 3,
          health: 902,
          healthRegenPer5s: 8,
          armor: 54,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 72,
          attackSpeed: 0.75,
        },
        {
          level: 4,
          health: 1038,
          healthRegenPer5s: 9,
          armor: 58,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 77,
          attackSpeed: 0.75,
        },
        {
          level: 5,
          health: 1174,
          healthRegenPer5s: 10,
          armor: 62,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 82,
          attackSpeed: 0.76,
        },
        {
          level: 6,
          health: 1310,
          healthRegenPer5s: 11,
          armor: 66,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 87,
          attackSpeed: 0.77,
        },
        {
          level: 7,
          health: 1446,
          healthRegenPer5s: 12,
          armor: 70,
          magicResist: 52,
          moveSpeed: 355,
          attackDamage: 92,
          attackSpeed: 0.78,
        },
        {
          level: 8,
          health: 1582,
          healthRegenPer5s: 13,
          armor: 74,
          magicResist: 54,
          moveSpeed: 355,
          attackDamage: 97,
          attackSpeed: 0.79,
        },
        {
          level: 9,
          health: 1718,
          healthRegenPer5s: 14,
          armor: 78,
          magicResist: 56,
          moveSpeed: 355,
          attackDamage: 102,
          attackSpeed: 0.79,
        },
        {
          level: 10,
          health: 1854,
          healthRegenPer5s: 15,
          armor: 82,
          magicResist: 58,
          moveSpeed: 355,
          attackDamage: 107,
          attackSpeed: 0.8,
        },
        {
          level: 11,
          health: 1990,
          healthRegenPer5s: 16,
          armor: 86,
          magicResist: 60,
          moveSpeed: 355,
          attackDamage: 112,
          attackSpeed: 0.81,
        },
        {
          level: 12,
          health: 2126,
          healthRegenPer5s: 17,
          armor: 90,
          magicResist: 62,
          moveSpeed: 355,
          attackDamage: 117,
          attackSpeed: 0.82,
        },
        {
          level: 13,
          health: 2262,
          healthRegenPer5s: 18,
          armor: 94,
          magicResist: 64,
          moveSpeed: 355,
          attackDamage: 122,
          attackSpeed: 0.82,
        },
        {
          level: 14,
          health: 2398,
          healthRegenPer5s: 19,
          armor: 98,
          magicResist: 66,
          moveSpeed: 355,
          attackDamage: 127,
          attackSpeed: 0.83,
        },
        {
          level: 15,
          health: 2534,
          healthRegenPer5s: 20,
          armor: 102,
          magicResist: 68,
          moveSpeed: 355,
          attackDamage: 132,
          attackSpeed: 0.84,
        },
      ],
    },

    laneProfile: {
      preferredRoles: [`TOP`],
      tradingPattern: `skillshot_combo`,
      sustainLevel: `high`,
      allInThreat: `high`,
      waveClear: `medium`,
      mobility: `medium`,
    },

    teamProfile: {
      provides: [`FRONTLINE`, `AREA_DAMAGE`, `KNOCK_UP`, `SUSTAIN`],
      needs: [`ENGAGE_SETUP`, `ANTI_HEAL_PROTECTION`],
      weakAgainst: [`ANTI_HEAL`, `KITE`, `HIGH_MOBILITY`, `POINT_AND_CLICK_CC`],
    },
  },
  // AHRI
  {
    championKey: `ahri`,

    baseHealth: 630,
    baseMana: 435,
    baseArmor: 34,
    baseMagicResist: 36,
    baseAttackDamage: 52,
    baseAbilityPower: 0,
    attackSpeed: 0.75,
    moveSpeed: 355,

    healthGrowth: 120,
    manaGrowth: 37,
    armorGrowth: 4,
    magicResistGrowth: 1,
    attackDamageGrowth: 3,
    attackSpeedGrowth: 0,

    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 8,
          mana: 435,
          manaRegenPer5s: 18,
          armor: 34,
          magicResist: 36,
          moveSpeed: 355,
          attackDamage: 52,
          attackSpeed: 0.75,
        },
        {
          level: 2,
          health: 750,
          healthRegenPer5s: 9,
          mana: 472,
          manaRegenPer5s: 19,
          armor: 38,
          magicResist: 37,
          moveSpeed: 355,
          attackDamage: 55,
          attackSpeed: 0.75,
        },
        {
          level: 3,
          health: 870,
          healthRegenPer5s: 10,
          mana: 509,
          manaRegenPer5s: 20,
          armor: 42,
          magicResist: 38,
          moveSpeed: 355,
          attackDamage: 58,
          attackSpeed: 0.75,
        },
        {
          level: 4,
          health: 990,
          healthRegenPer5s: 11,
          mana: 546,
          manaRegenPer5s: 21,
          armor: 46,
          magicResist: 39,
          moveSpeed: 355,
          attackDamage: 61,
          attackSpeed: 0.75,
        },
        {
          level: 5,
          health: 1110,
          healthRegenPer5s: 12,
          mana: 583,
          manaRegenPer5s: 22,
          armor: 50,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 64,
          attackSpeed: 0.75,
        },
        {
          level: 6,
          health: 1230,
          healthRegenPer5s: 13,
          mana: 620,
          manaRegenPer5s: 23,
          armor: 54,
          magicResist: 41,
          moveSpeed: 355,
          attackDamage: 67,
          attackSpeed: 0.75,
        },
        {
          level: 7,
          health: 1350,
          healthRegenPer5s: 14,
          mana: 657,
          manaRegenPer5s: 24,
          armor: 58,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 70,
          attackSpeed: 0.75,
        },
        {
          level: 8,
          health: 1470,
          healthRegenPer5s: 15,
          mana: 694,
          manaRegenPer5s: 25,
          armor: 62,
          magicResist: 43,
          moveSpeed: 355,
          attackDamage: 73,
          attackSpeed: 0.75,
        },
        {
          level: 9,
          health: 1590,
          healthRegenPer5s: 16,
          mana: 731,
          manaRegenPer5s: 26,
          armor: 66,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 76,
          attackSpeed: 0.75,
        },
        {
          level: 10,
          health: 1710,
          healthRegenPer5s: 17,
          mana: 768,
          manaRegenPer5s: 27,
          armor: 70,
          magicResist: 45,
          moveSpeed: 355,
          attackDamage: 79,
          attackSpeed: 0.75,
        },
        {
          level: 11,
          health: 1830,
          healthRegenPer5s: 18,
          mana: 805,
          manaRegenPer5s: 28,
          armor: 74,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 82,
          attackSpeed: 0.75,
        },
        {
          level: 12,
          health: 1950,
          healthRegenPer5s: 19,
          mana: 842,
          manaRegenPer5s: 29,
          armor: 78,
          magicResist: 47,
          moveSpeed: 355,
          attackDamage: 85,
          attackSpeed: 0.75,
        },
        {
          level: 13,
          health: 2070,
          healthRegenPer5s: 20,
          mana: 879,
          manaRegenPer5s: 30,
          armor: 82,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 88,
          attackSpeed: 0.75,
        },
        {
          level: 14,
          health: 2190,
          healthRegenPer5s: 21,
          mana: 916,
          manaRegenPer5s: 31,
          armor: 86,
          magicResist: 49,
          moveSpeed: 355,
          attackDamage: 91,
          attackSpeed: 0.75,
        },
        {
          level: 15,
          health: 2310,
          healthRegenPer5s: 22,
          mana: 953,
          manaRegenPer5s: 32,
          armor: 90,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 94,
          attackSpeed: 0.75,
        },
      ],
    },

    laneProfile: {
      preferredRoles: [`MID`],
      tradingPattern: `poke_pick_combo`,
      sustainLevel: `medium`,
      allInThreat: `medium_high`,
      waveClear: `high`,
      mobility: `high`,
    },

    teamProfile: {
      provides: [`MAGIC_DAMAGE`, `CHARM`, `PICK_POTENTIAL`, `MOBILITY`],
      needs: [`FRONTLINE`, `ENGAGE_SETUP`, `DAMAGE_FOLLOWUP`],
      weakAgainst: [`POINT_AND_CLICK_CC`, `BURST_DAMAGE`, `HIGH_MOBILITY`],
    },
  },
  // AKALI
  {
    championKey: `akali`,

    baseHealth: 630,
    baseMana: 200,
    baseArmor: 34,
    baseMagicResist: 38,
    baseAttackDamage: 64,
    baseAbilityPower: 0,
    attackSpeed: 0.8,
    moveSpeed: 355,

    healthGrowth: 140,
    manaGrowth: 0,
    armorGrowth: 6,
    magicResistGrowth: 2,
    attackDamageGrowth: 4,
    attackSpeedGrowth: 0.015,

    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 10,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 34,
          magicResist: 38,
          moveSpeed: 355,
          attackDamage: 64,
          attackSpeed: 0.8,
        },
        {
          level: 2,
          health: 770,
          healthRegenPer5s: 11,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 40,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 68,
          attackSpeed: 0.82,
        },
        {
          level: 3,
          health: 910,
          healthRegenPer5s: 12,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 46,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 72,
          attackSpeed: 0.83,
        },
        {
          level: 4,
          health: 1050,
          healthRegenPer5s: 13,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 52,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 76,
          attackSpeed: 0.85,
        },
        {
          level: 5,
          health: 1190,
          healthRegenPer5s: 14,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 58,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 80,
          attackSpeed: 0.86,
        },
        {
          level: 6,
          health: 1330,
          healthRegenPer5s: 15,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 64,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 84,
          attackSpeed: 0.88,
        },
        {
          level: 7,
          health: 1470,
          healthRegenPer5s: 16,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 70,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 88,
          attackSpeed: 0.89,
        },
        {
          level: 8,
          health: 1610,
          healthRegenPer5s: 17,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 76,
          magicResist: 52,
          moveSpeed: 355,
          attackDamage: 92,
          attackSpeed: 0.91,
        },
        {
          level: 9,
          health: 1750,
          healthRegenPer5s: 18,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 82,
          magicResist: 54,
          moveSpeed: 355,
          attackDamage: 96,
          attackSpeed: 0.92,
        },
        {
          level: 10,
          health: 1890,
          healthRegenPer5s: 19,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 88,
          magicResist: 56,
          moveSpeed: 355,
          attackDamage: 100,
          attackSpeed: 0.94,
        },
        {
          level: 11,
          health: 2030,
          healthRegenPer5s: 20,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 94,
          magicResist: 58,
          moveSpeed: 355,
          attackDamage: 104,
          attackSpeed: 0.95,
        },
        {
          level: 12,
          health: 2170,
          healthRegenPer5s: 21,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 100,
          magicResist: 60,
          moveSpeed: 355,
          attackDamage: 108,
          attackSpeed: 0.97,
        },
        {
          level: 13,
          health: 2310,
          healthRegenPer5s: 22,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 106,
          magicResist: 62,
          moveSpeed: 355,
          attackDamage: 112,
          attackSpeed: 0.98,
        },
        {
          level: 14,
          health: 2450,
          healthRegenPer5s: 23,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 112,
          magicResist: 64,
          moveSpeed: 355,
          attackDamage: 116,
          attackSpeed: 1,
        },
        {
          level: 15,
          health: 2590,
          healthRegenPer5s: 24,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 118,
          magicResist: 66,
          moveSpeed: 355,
          attackDamage: 120,
          attackSpeed: 1.01,
        },
      ],
    },

    laneProfile: {
      preferredRoles: [`MID`, `TOP`],
      tradingPattern: `burst_assassin_combo`,
      sustainLevel: `low`,
      allInThreat: `high`,
      waveClear: `medium`,
      mobility: `very_high`,
    },

    teamProfile: {
      provides: [`MAGIC_DAMAGE`, `BURST_DAMAGE`, `MOBILITY`, `EXECUTE`],
      needs: [`DIVE_SETUP`, `FLANK_ACCESS`, `DAMAGE_FOLLOWUP`],
      weakAgainst: [`POINT_AND_CLICK_CC`, `REVEAL`, `ANTI_DIVE`, `LOCKDOWN`],
    },
  },
];

export async function seedChampionPatchStats(
  prisma: PrismaClient,
  patchId: string,
) {}
