import { PrismaClient } from '../../src/generated/prisma/client.js';
import {
  DataQualityLevel,
  GameRole,
} from '../../src/generated/prisma/enums.js';

type ChampionSynergyProfileSeed = {
  championKey: string;
  role: GameRole;
  goodWithTags: string[];
  providesTags: string[];
  needsTags: string[];
  teamRiskTags: string[];
  synergyNotes?: string | null;
  dataQuality?: DataQualityLevel;
};

const championSynergyProfileSeeds: ChampionSynergyProfileSeed[] = [
  // AATROX
  {
    championKey: `aatrox`,
    role: GameRole.TOP,
    goodWithTags: [
      `ENGAGE`,
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `TEAMFIGHT`,
      `FRONTLINE`,
    ],
    providesTags: [
      `FRONTLINE`,
      `SUSTAIN`,
      `AREA_DAMAGE`,
      `KNOCK_UP`,
      `EXTENDED_FIGHT`,
      `TEAMFIGHT_FOLLOWUP`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `ANTI_HEAL`,
      `BACKLINE_ACCESS`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `LOW_DURABILITY_TEAM`,
      `NO_HEALING_TEAM`,
    ],
    synergyNotes: `Aatrox works best with teammates that can start fights or hold enemies in place so he can land The Darkin Blade sweet spots. Jarvan IV, Rell, and Nautilus are strong examples because they provide reliable engage and crowd control setup. Aatrox adds frontline pressure, sustain, knock-up, and extended fight damage, but he can feel weak if the team lacks engage or follow-up damage.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `aatrox`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `CROWD_CONTROL_SETUP`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `TEAMFIGHT`,
      `OBJECTIVE_CONTROL`,
    ],
    providesTags: [
      `SUSTAIN`,
      `FRONTLINE`,
      `AREA_DAMAGE`,
      `KNOCK_UP`,
      `SKIRMISH`,
      `OBJECTIVE_CONTROL`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `ENGAGE_SETUP`,
    ],
    teamRiskTags: [`LOW_CC`, `LOW_KILL_PRESSURE`, `LOW_DURABILITY_TEAM`],
    synergyNotes: `Jungle Aatrox prefers lanes that can help lock targets down and fight early skirmishes. He contributes strong sustained fighting and frontline presence around objectives, but needs teammates with setup or reliable damage to make ganks and river fights consistent.`,
    dataQuality: DataQualityLevel.MINIMAL,
  },
  // AHRI
  {
    championKey: `ahri`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `PICK_COMPOSITION`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
    ],
    providesTags: [
      `CHARM`,
      `PICK_POTENTIAL`,
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MOBILITY`,
      `BACKLINE_ACCESS`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `LOW_KILL_PRESSURE`,
      `NO_HEALING_TEAM`,
    ],
    synergyNotes: `Ahri works best with teammates that can start fights or lock targets down so Charm becomes easier to land. Vi, Jarvan IV, and Nautilus are strong examples because they provide reliable engage and crowd control setup. Ahri adds pick pressure, magic burst, and backline access, but she needs frontline or engage support so she does not have to start every fight alone.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AKALI
  {
    championKey: `akali`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `DIVE`,
      `PICK_COMPOSITION`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MOBILITY`,
      `BACKLINE_ACCESS`,
      `PICK_POTENTIAL`,
      `DIVE`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `LOW_KILL_PRESSURE`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Akali works best with teammates that create reliable engage or chaos before she enters the fight. Amumu, Jarvan IV, and Nocturne are strong examples because they force enemies to group, burn cooldowns, or lose vision control. Akali provides magic burst, backline access, and cleanup pressure, but she needs setup so she does not have to start fights alone.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `akali`,
    role: GameRole.TOP,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `DIVE`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MOBILITY`,
      `SIDE_LANE`,
      `BACKLINE_ACCESS`,
      `SKIRMISH`,
    ],
    needsTags: [
      `FRONTLINE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `PEEL`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `NO_HEALING_TEAM`,
    ],
    synergyNotes: `Solo lane Akali adds AP side lane pressure and backline threat from a Baron lane slot. She pairs well with engage junglers and supports that can force grouped fights, letting her enter after key crowd control lands. The team should still draft frontline or reliable CC elsewhere because Akali does not provide stable engage or peel by herself.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AKSHAN
  {
    championKey: `akshan`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `PICK_COMPOSITION`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `PICK_POTENTIAL`,
      `MOBILITY`,
      `VISION_CONTROL`,
      `REVIVE`,
      `BACKLINE_ACCESS`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `PEEL`,
      `FOLLOW_UP_DAMAGE`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Akshan works best with teammates that can lock targets down so he can safely follow up with ranged damage and cleanup. Rakan, Leona, and Amumu are strong examples because they provide reliable engage and crowd control. Akshan adds physical damage, roaming pressure, pick potential, and revive value, but he needs frontline or peel because he is vulnerable when caught.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // ALISTAR
  {
    championKey: `alistar`,
    role: GameRole.SUPPORT,
    goodWithTags: [
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `RESET_WINDOW`,
      `TEAMFIGHT_CLEANUP`,
      `DIVE`,
      `CROWD_CONTROL_SETUP`,
    ],
    providesTags: [
      `FRONTLINE`,
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `KNOCK_UP`,
      `PEEL`,
      `DAMAGE_REDUCTION`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `LANE_PARTNER_DAMAGE`,
      `KILL_PRESSURE`,
      `TEAMFIGHT_CLEANUP`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [`LOW_KILL_PRESSURE`, `LOW_DURABILITY_TEAM`, `LOW_DAMAGE`],
    synergyNotes: `Alistar pairs best with carries that can immediately follow his engage or benefit from knock-up setup. Draven, Samira, and Yasuo are strong examples because they can convert his crowd control into kills or teamfight cleanup. Alistar provides reliable engage, frontline, peel, and durability, but he needs teammates with enough damage to punish the targets he locks down.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AMBESSA
  {
    championKey: `ambessa`,
    role: GameRole.TOP,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `DIVE`,
      `FOLLOW_UP_DAMAGE`,
      `TEAMFIGHT`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `MOBILITY`,
      `BACKLINE_ACCESS`,
      `DIVE`,
      `SKIRMISH`,
      `FOLLOW_UP_DAMAGE`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
      `LOW_KILL_PRESSURE`,
    ],
    synergyNotes: `Ambessa works best with teams that can start fights or hold targets in place before she commits. Nautilus, Leona, and Nocturne are strong examples because they create engage windows and force enemies into bad positions. Ambessa provides mobile physical damage, dive pressure, and follow-up threat, but she needs setup because she can be punished if she enters fights alone.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `ambessa`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `DIVE`,
      `TEAMFIGHT`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `MOBILITY`,
      `SKIRMISH`,
      `JUNGLE_CLEAR`,
      `BACKLINE_ACCESS`,
      `OBJECTIVE_CONTROL`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `PEEL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Jungle Ambessa pairs well with lanes that provide reliable crowd control or burst follow-up. Leona, Nautilus, and Lissandra are strong examples because they can lock enemies down long enough for Ambessa to finish the engage. She gives the team skirmish pressure, physical damage, and objective fighting, but needs allies to provide stable CC and damage confirmation.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AMUMU
  {
    championKey: `amumu`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `AREA_DAMAGE`,
      `TEAMFIGHT`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `MAGIC_DAMAGE`,
      `WOMBO_COMBO`,
    ],
    providesTags: [
      `FRONTLINE`,
      `HARD_ENGAGE`,
      `AREA_CC`,
      `CROWD_CONTROL_SETUP`,
      `MAGIC_DAMAGE`,
      `TEAMFIGHT_SETUP`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `AREA_DAMAGE`,
      `LANE_KILL_PRESSURE`,
      `OBJECTIVE_CONTROL`,
      `TEAMFIGHT_CLEANUP`,
    ],
    teamRiskTags: [
      `LOW_DAMAGE`,
      `LOW_KILL_PRESSURE`,
      `LOW_DURABILITY_TEAM`,
      `NO_HEALING_TEAM`,
    ],
    synergyNotes: `Amumu pairs best with champions that can layer heavy area damage over his crowd control. Miss Fortune, Kennen, and Rumble are strong examples because they can punish enemies locked by Curse of the Sad Mummy. Amumu provides frontline, engage, area crowd control, and teamfight setup, but he needs teammates with enough follow-up damage to finish fights after he starts them.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // ANNIE
  {
    championKey: `annie`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `AREA_DAMAGE`,
      `FOLLOW_UP_DAMAGE`,
      `TEAMFIGHT`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `STUN`,
      `AREA_DAMAGE`,
      `PICK_POTENTIAL`,
      `TEAMFIGHT_SETUP`,
    ],
    needsTags: [
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `OBJECTIVE_CONTROL`,
      `PEEL`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_KILL_PRESSURE`,
      `LOW_CC`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Annie works best with teammates that can start fights or force enemies into grouped positions before she uses Tibbers. Amumu, Jarvan IV, and Vi are strong examples because they provide reliable engage and crowd control setup. Annie contributes magic burst, stun threat, pick pressure, and teamfight initiation, but she needs frontline or engage help because her range is limited.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // ASHE
  {
    championKey: `ashe`,
    role: GameRole.ADC,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `PEEL`,
      `FRONTLINE`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `DPS`,
      `SLOW`,
      `GLOBAL_RANGE`,
      `PICK_POTENTIAL`,
      `VISION_CONTROL`,
    ],
    needsTags: [
      `PEEL`,
      `FRONTLINE`,
      `ENGAGE_SETUP`,
      `LANE_PARTNER_DAMAGE`,
      `TEAM_SUPPORT`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_KILL_PRESSURE`,
      `NO_SHIELD_TEAM`,
      `NO_HEALING_TEAM`,
    ],
    synergyNotes: `Ashe pairs best with supports that can either lock targets down after her slows or protect her during extended fights. Leona, Nautilus, and Braum are strong examples because they add reliable crowd control, peel, and lane kill pressure. Ashe provides sustained physical damage, slows, long-range pick setup, and vision utility, but she needs protection because she has no dash.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AURELION SOL
  {
    championKey: `aurelion-sol`,
    role: GameRole.MID,
    goodWithTags: [
      `FRONTLINE`,
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `AREA_DAMAGE`,
      `TEAMFIGHT`,
      `PEEL`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `AREA_DAMAGE`,
      `BURN_DAMAGE`,
      `ZONE_CONTROL`,
      `SCALING_DAMAGE`,
      `TEAMFIGHT_SETUP`,
    ],
    needsTags: [
      `FRONTLINE`,
      `PEEL`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `WEAK_EARLY_GAME`,
    ],
    synergyNotes: `Aurelion Sol works best with teammates that can protect his scaling and group enemies for his area damage. Amumu, Nautilus, and Bard are strong examples because they provide crowd control setup, engage control, or protective utility. Aurelion Sol provides scaling magic damage, zone control, and huge teamfight threat, but he needs frontline and peel so he can safely channel damage over time.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // AURORA
  {
    championKey: `aurora`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `AREA_DAMAGE`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MOBILITY`,
      `ZONE_CONTROL`,
      `TEAMFIGHT_SETUP`,
      `PICK_POTENTIAL`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Aurora works best with teammates that can force enemies into her fight zone or lock targets down before she commits. Viego, Amumu, and Jarvan IV are strong examples because they can create reset windows, grouped fights, or reliable engage setup. Aurora provides magic burst, mobility, zone control, and teamfight setup, but she needs frontline or engage support to avoid being the only champion starting fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BARD
  {
    championKey: `bard`,
    role: GameRole.SUPPORT,
    goodWithTags: [
      `LONG_RANGE_CHAMPION`,
      `FOLLOW_UP_DAMAGE`,
      `PICK_COMPOSITION`,
      `CROWD_CONTROL_SETUP`,
      `LANE_KILL_PRESSURE`,
      `SAFE_POSITIONING`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `PICK_POTENTIAL`,
      `ROAMING`,
      `VISION_CONTROL`,
      `STASIS`,
      `PORTAL`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `LANE_PARTNER_DAMAGE`,
      `SAFE_POSITIONING`,
      `OBJECTIVE_CONTROL`,
      `PEEL`,
    ],
    teamRiskTags: [
      `LOW_KILL_PRESSURE`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
      `LOW_DAMAGE`,
    ],
    synergyNotes: `Bard pairs well with long-range carries that can follow up his crowd control or punish targets caught by Tempered Fate. Jhin, Caitlyn, and Varus are strong examples because they can convert Bard's pick setup into lane kills or objective pressure. Bard provides roaming, pick potential, stasis utility, portal access, and vision control, but he needs teammates with reliable follow-up damage because his engages can be wasted without coordination.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BLITZCRANK
  {
    championKey: `blitzcrank`,
    role: GameRole.SUPPORT,
    goodWithTags: [
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `BURST_DAMAGE`,
      `PICK_COMPOSITION`,
      `CROWD_CONTROL_SETUP`,
      `EARLY_GAME_PRESSURE`,
    ],
    providesTags: [
      `PICK_POTENTIAL`,
      `PULL`,
      `KNOCK_UP`,
      `SILENCE`,
      `CROWD_CONTROL_SETUP`,
      `FRONTLINE`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `LANE_PARTNER_DAMAGE`,
      `BURST_DAMAGE`,
      `KILL_PRESSURE`,
      `VISION_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_KILL_PRESSURE`,
      `LOW_DAMAGE`,
      `TEAM_DEPENDENT`,
      `LOW_DURABILITY_TEAM`,
    ],
    synergyNotes: `Blitzcrank pairs best with lane partners that can instantly punish hooked targets. Miss Fortune, Draven, and Lucian are strong examples because they bring high lane damage and can convert Rocket Grab into kills. Blitzcrank provides pick pressure, pull, knock-up, silence, and frontline threat, but he needs follow-up damage because missed hooks can leave the lane with low pressure.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BRAND
  {
    championKey: `brand`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `AREA_DAMAGE`,
      `TEAMFIGHT`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURN_DAMAGE`,
      `AREA_DAMAGE`,
      `ZONE_CONTROL`,
      `TEAMFIGHT`,
      `ANTI_TANK`,
    ],
    needsTags: [
      `FRONTLINE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `PEEL`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `WEAK_EARLY_GAME`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Brand works best with champions that can group enemies or hold them inside his area damage. Amumu, Jarvan IV, and Leona are strong examples because their engage and crowd control let Brand land full burn combos. Brand provides magic damage, area damage, burn pressure, and anti-frontline teamfight value, but he needs frontline and peel because he is easy to punish when caught.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `brand`,
    role: GameRole.SUPPORT,
    goodWithTags: [
      `LONG_RANGE_CHAMPION`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `POKE_SETUP`,
      `CROWD_CONTROL_SETUP`,
      `SAFE_POSITIONING`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURN_DAMAGE`,
      `AREA_DAMAGE`,
      `POKE`,
      `ZONE_CONTROL`,
      `TEAMFIGHT`,
    ],
    needsTags: [
      `LANE_PARTNER_DAMAGE`,
      `SAFE_POSITIONING`,
      `PEEL`,
      `FOLLOW_UP_DAMAGE`,
      `VISION_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `NO_SHIELD_TEAM`,
      `NO_HEALING_TEAM`,
    ],
    synergyNotes: `Support Brand pairs well with carries that can safely add damage while enemies are slowed, stunned, or zoned by his spells. Jhin, Ashe, and Caitlyn are strong examples because they can follow up from range and punish poke-heavy lanes. Brand provides high magic damage and teamfight burn from support, but he does not provide reliable peel, so the team should still draft protection or frontline elsewhere.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // BRAUM
  {
    championKey: `braum`,
    role: GameRole.SUPPORT,
    goodWithTags: [
      `AUTO_ATTACK_CHAMPION`,
      `DPS`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `SAFE_POSITIONING`,
      `TEAMFIGHT`,
    ],
    providesTags: [
      `PEEL`,
      `ALLY_PROTECTION`,
      `PROJECTILE_BLOCK`,
      `STUN`,
      `KNOCK_UP`,
      `FRONTLINE`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `LANE_PARTNER_DAMAGE`,
      `DPS`,
      `SAFE_POSITIONING`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_DAMAGE`,
      `LOW_KILL_PRESSURE`,
      `NO_HEALING_TEAM`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Braum pairs best with carries that can quickly apply Concussive Blows stacks and benefit from strong peel. Ashe, Lucian, and Ezreal are strong examples because they can follow up his slows, passive stacks, and frontline protection. Braum provides peel, projectile blocking, frontline durability, stun setup, and anti-dive protection, but he needs teammates with enough damage to finish fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // CAITLYN
  {
    championKey: `caitlyn`,
    role: GameRole.ADC,
    goodWithTags: [
      `ENCHANTER`,
      `SHIELDING`,
      `PEEL`,
      `POKE_SETUP`,
      `CROWD_CONTROL_SETUP`,
      `SAFE_POSITIONING`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `DPS`,
      `LONG_RANGE_POKE`,
      `TRAP`,
      `ZONE_CONTROL`,
      `LONG_RANGE_EXECUTE`,
    ],
    needsTags: [
      `PEEL`,
      `TEAM_SUPPORT`,
      `FRONTLINE`,
      `LANE_PARTNER_DAMAGE`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `NO_SHIELD_TEAM`,
      `NO_HEALING_TEAM`,
    ],
    synergyNotes: `Caitlyn pairs best with supports that help her control lane space, protect her, or chain crowd control into traps. Nami, Milio, and Bard are strong examples because they improve her lane pressure, safety, or pick setup. Caitlyn provides long-range physical damage, poke, trap control, and execute threat, but she needs peel and frontline support because she is vulnerable when enemies reach her.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // CAMILLE
  {
    championKey: `camille`,
    role: GameRole.TOP,
    goodWithTags: [
      `HARD_ENGAGE`,
      `FOLLOW_UP_DAMAGE`,
      `CROWD_CONTROL_SETUP`,
      `DIVE`,
      `SIDE_LANE`,
      `GLOBAL_RANGE`,
    ],
    providesTags: [
      `TRUE_DAMAGE`,
      `MOBILITY`,
      `PICK_POTENTIAL`,
      `LOCKDOWN`,
      `BACKLINE_ACCESS`,
      `SPLIT_PUSH`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `LOW_KILL_PRESSURE`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Camille works well with teams that can follow her target lockdown and convert Hextech Ultimatum into kills. Vi, Jarvan IV, and Galio are strong examples because they add engage, follow-up crowd control, or global-style collapse. Camille provides side-lane pressure, true damage, pick threat, and backline access, but she needs teammates who can follow her dives or cover front-to-back fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `camille`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `CROWD_CONTROL_SETUP`,
      `DIVE`,
      `GLOBAL_RANGE`,
      `TEAMFIGHT_FOLLOWUP`,
    ],
    providesTags: [
      `TRUE_DAMAGE`,
      `PICK_POTENTIAL`,
      `MOBILITY`,
      `LOCKDOWN`,
      `BACKLINE_ACCESS`,
      `OBJECTIVE_CONTROL`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `PEEL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Jungle Camille pairs best with lanes that can follow up her long-range engage and guaranteed lockdown. Jarvan IV, Galio, and Shen-style team setups are strong because they can collapse with her and extend dives. Camille provides pick pressure, true damage, and strong target isolation, but she needs lane damage and reliable follow-up to make ganks consistent.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // CORKI
  {
    championKey: `corki`,
    role: GameRole.ADC,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `FRONTLINE`,
      `PEEL`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `HYBRID_DAMAGE`,
      `MAGIC_DAMAGE`,
      `PHYSICAL_DAMAGE`,
      `POKE`,
      `DPS`,
      `AREA_DAMAGE`,
    ],
    needsTags: [
      `FRONTLINE`,
      `PEEL`,
      `CROWD_CONTROL_SETUP`,
      `LANE_PARTNER_DAMAGE`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `NO_SHIELD_TEAM`,
      `NO_HEALING_TEAM`,
    ],
    synergyNotes: `Corki pairs best with engage supports that can lock enemies down while he follows up with mixed damage and poke. Nautilus, Alistar, and Leona are strong examples because they create reliable all-in windows and protect him during fights. Corki provides hybrid damage, poke, sustained DPS, and area damage, but he needs frontline and peel to keep dealing damage safely.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DARIUS
  {
    championKey: `darius`,
    role: GameRole.TOP,
    goodWithTags: [
      `SPEED_UP`,
      `CROWD_CONTROL_SETUP`,
      `HARD_ENGAGE`,
      `FRONTLINE`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `TRUE_DAMAGE`,
      `DRAIN_TANK`,
      `FRONTLINE`,
      `PULL`,
      `TEAMFIGHT_CLEANUP`,
    ],
    needsTags: [
      `SPEED_UP`,
      `ENGAGE_SETUP`,
      `CROWD_CONTROL_SETUP`,
      `PEEL`,
      `FOLLOW_UP_DAMAGE`,
    ],
    teamRiskTags: [`KITEABLE`, `LOW_MOBILITY`, `LOW_CC`, `LOW_DURABILITY_TEAM`],
    synergyNotes: `Darius pairs best with teammates that help him reach targets or keep enemies inside his extended fight range. Zilean, Rammus, and Amumu are strong examples because they provide speed-up, engage, or crowd control setup. Darius provides frontline pressure, physical damage, true damage execute threat, pull utility, and cleanup potential, but he needs help against teams that can kite him.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `darius`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `SPEED_UP`,
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `LANE_KILL_PRESSURE`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `TRUE_DAMAGE`,
      `DRAIN_TANK`,
      `FRONTLINE`,
      `PULL`,
      `TEAMFIGHT_CLEANUP`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `SPEED_UP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
    ],
    teamRiskTags: [`KITEABLE`, `LOW_MOBILITY`, `LOW_CC`, `LOW_KILL_PRESSURE`],
    synergyNotes: `Jungle Darius works best with lanes that can set up ganks or help him stay on targets long enough to stack Hemorrhage. Zilean, Alistar, and Malphite are strong examples because they provide speed-up, lockdown, or engage setup. Darius provides strong skirmishing, frontline pressure, pull utility, and execute cleanup, but he can feel weak if his lanes cannot help him start or extend fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DIANA
  {
    championKey: `diana`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `KNOCK_UP`,
      `AREA_DAMAGE`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `DIVE`,
      `AREA_DAMAGE`,
      `TEAMFIGHT_SETUP`,
      `BACKLINE_ACCESS`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `PEEL`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
      `LOW_CC`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Mid Diana works best with teammates that can start fights, extend her engage, or layer crowd control after Moonfall. Lee Sin, Rakan, and Galio are strong examples because they provide setup, follow-up, or dive support. Diana provides magic burst, backline access, area damage, and teamfight setup, but she needs follow-up because her engage is commit-heavy.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `diana`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `KNOCK_UP`,
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `AREA_DAMAGE`,
      `TEAMFIGHT_FOLLOWUP`,
      `SCALING_GAME`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `DIVE`,
      `AREA_DAMAGE`,
      `TEAMFIGHT_SETUP`,
      `JUNGLE_CLEAR`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Jungle Diana pairs well with champions that can capitalize on grouped enemies or add reliable engage around her Moonfall. Yasuo, Malphite, and Kayle are strong examples because they either chain with knock-up style setups, create teamfight openings, or scale with Diana's dive threat. Diana provides jungle magic damage, burst engage, area damage, and strong teamfight setup, but she needs lanes that can help her start or finish fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DR. MUNDO
  {
    championKey: `dr-mundo`,
    role: GameRole.TOP,
    goodWithTags: [
      `FOLLOW_UP_DAMAGE`,
      `SCALING_GAME`,
      `TEAMFIGHT`,
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `PEEL`,
    ],
    providesTags: [
      `FRONTLINE`,
      `DRAIN_TANK`,
      `SUSTAIN`,
      `HEALTH_REGEN`,
      `SPLIT_PUSH`,
      `SURVIVABILITY`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `ANTI_TANK`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `KITEABLE`,
      `ANTI_HEAL_VULNERABLE`,
    ],
    synergyNotes: `Dr. Mundo works best with teammates that add damage and crowd control while he absorbs pressure as the frontline. Ryze, Olaf, and Leona are useful examples because they add sustained damage, skirmish threat, or engage control around Mundo's durability. Dr. Mundo provides frontline presence, sustain, health scaling, and side-lane pressure, but he needs teammates to supply reliable lockdown and damage because he can be kited or weakened by anti-heal.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // DRAVEN
  {
    championKey: `draven`,
    role: GameRole.ADC,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `LANE_KILL_PRESSURE`,
      `PICK_COMPOSITION`,
      `FOLLOW_UP_DAMAGE`,
      `PEEL`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `RAW_DAMAGE`,
      `LANE_KILL_PRESSURE`,
      `SNOWBALL`,
      `BONUS_GOLD`,
      `EXECUTE`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `PEEL`,
      `FRONTLINE`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
      `CC_VULNERABLE`,
      `POSITIONING_RELIANT`,
    ],
    synergyNotes: `Draven pairs best with aggressive supports that can lock enemies down and create early kill windows. Nautilus, Pyke, and Thresh are strong examples because they provide engage, pick setup, and lane pressure that help Draven cash in Adoration stacks. Draven provides very high physical damage, snowball pressure, and execute threat, but he needs peel and crowd control setup because his damage depends heavily on positioning around Spinning Axe.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // EKKO
  {
    championKey: `ekko`,
    role: GameRole.MID,
    goodWithTags: [
      `CROWD_CONTROL_SETUP`,
      `HARD_ENGAGE`,
      `PEEL`,
      `FOLLOW_UP_DAMAGE`,
      `DIVE`,
      `GLOBAL_RANGE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MOBILITY`,
      `PICK_POTENTIAL`,
      `BACKLINE_ACCESS`,
      `TIME_REWIND`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `PEEL`,
      `FRONTLINE`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Mid Ekko pairs well with teammates that can lock enemies down or protect his reset windows. Amumu, Nami, and Shen are strong examples because they provide crowd control setup, peel, or global-style support for his dives. Ekko provides magic burst, mobility, pick pressure, and strong outplay safety with Chronobreak, but he needs setup to reliably reach priority targets.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `ekko`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `DIVE`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `SKIRMISH`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MOBILITY`,
      `PICK_POTENTIAL`,
      `BACKLINE_ACCESS`,
      `JUNGLE_CLEAR`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Jungle Ekko works best with lanes that can set up his ganks or fight with him during skirmishes. Camille, Nautilus, and Irelia are strong examples because they bring lockdown, dive threat, or lane kill pressure. Ekko provides jungle magic damage, burst access, pick threat, and reset safety, but he needs reliable setup and follow-up damage to make his ganks consistent.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // EVELYNN
  {
    championKey: `evelynn`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `GLOBAL_RANGE`,
      `CROWD_CONTROL_SETUP`,
      `PICK_COMPOSITION`,
      `FOLLOW_UP_DAMAGE`,
      `LANE_KILL_PRESSURE`,
      `BURST_DAMAGE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `PICK_POTENTIAL`,
      `CAMOUFLAGE`,
      `CHARM`,
      `LOW_HEALTH_EXECUTE`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `VISION_CONTROL`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `WEAK_EARLY_GAME`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Evelynn pairs best with lanes that can help set up picks or follow her burst from unexpected angles. Shen, Ahri, and Veigar are strong examples because they add protection, charm or cage setup, and reliable burst follow-up. Evelynn provides stealth pressure, magic burst, charm threat, and execute cleanup, but she needs lane pressure and vision control because her early game is punishable before she unlocks Demon Shade roaming.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // EZREAL
  {
    championKey: `ezreal`,
    role: GameRole.ADC,
    goodWithTags: [
      `ENCHANTER`,
      `PEEL`,
      `POKE_SETUP`,
      `CROWD_CONTROL_SETUP`,
      `ROAMING`,
      `SAFE_POSITIONING`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `POKE`,
      `MOBILITY`,
      `GLOBAL_RANGE`,
      `SKILL_SHOT`,
      `SAFE_POSITIONING`,
    ],
    needsTags: [
      `PEEL`,
      `TEAM_SUPPORT`,
      `LANE_PARTNER_DAMAGE`,
      `CROWD_CONTROL_SETUP`,
      `FRONTLINE`,
    ],
    teamRiskTags: [
      `LOW_KILL_PRESSURE`,
      `LOW_CC`,
      `NO_HEALING_TEAM`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Ezreal pairs best with supports that either protect his scaling or help him land poke and follow-up skillshots. Yuumi, Braum, and Bard are strong examples because they add sustain, peel, crowd control setup, or roaming pressure without forcing Ezreal into unsafe trades. Ezreal provides safe physical poke, mobility, global damage pressure, and consistent mid-game DPS, but he needs teammates to supply engage or peel because his lane kill pressure can be lower than aggressive marksmen.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // FIDDLESTICKS
  {
    championKey: `fiddlesticks`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `FRONTLINE`,
      `AREA_DAMAGE`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `AREA_DAMAGE`,
      `FEAR`,
      `SILENCE`,
      `TEAMFIGHT_SETUP`,
    ],
    needsTags: [
      `VISION_CONTROL`,
      `FRONTLINE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `WEAK_EARLY_GAME`,
      `TEAM_DEPENDENT`,
      `LOW_DURABILITY_TEAM`,
      `INTERRUPT_VULNERABLE`,
    ],
    synergyNotes: `Fiddlesticks pairs best with champions that can start fights, hold enemies in place, or create safe flanking windows for Crowstorm. Galio, Alistar, and Leona are strong examples because they provide engage, frontline, and crowd control setup. Fiddlesticks provides heavy magic burst, area damage, fear, silence, and teamfight setup, but he needs vision control and frontline help because his best fights depend on surprise angles and uninterrupted channels.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // FIORA
  {
    championKey: `fiora`,
    role: GameRole.TOP,
    goodWithTags: [
      `HEALING`,
      `SHIELDING`,
      `SPEED_UP`,
      `PEEL`,
      `SIDE_LANE`,
      `SCALING_GAME`,
    ],
    providesTags: [
      `TRUE_DAMAGE`,
      `DUELING`,
      `SPLIT_PUSH`,
      `SIDE_LANE`,
      `ANTI_TANK`,
      `SUSTAIN`,
    ],
    needsTags: [
      `TEAM_SUPPORT`,
      `PEEL`,
      `MAP_PRESSURE`,
      `MACRO`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `TEAM_DEPENDENT`,
      `LOW_KILL_PRESSURE`,
      `TEAMFIGHT_FOLLOWUP`,
    ],
    synergyNotes: `Fiora pairs best with teammates that keep her alive, speed her up, or enable side-lane pressure while the rest of the map plays safely. Soraka, Lulu, and Zilean are strong examples because they add healing, shielding, speed-up, or revive-style protection for her extended duels. Fiora provides true damage, anti-tank pressure, split-push threat, and strong side-lane control, but she needs her team to manage objectives and avoid forced 4v5 fights while she pressures sidelanes.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // FIZZ
  {
    championKey: `fizz`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `PICK_COMPOSITION`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `LANE_KILL_PRESSURE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `PICK_POTENTIAL`,
      `DIVE`,
      `BACKLINE_ACCESS`,
      `UNTARGETABLE`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `VISION_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Mid Fizz works best with teammates that can lock targets down or start fights before he commits with Chum the Waters. Nautilus, Leona, and Jarvan IV are strong examples because they provide engage and crowd control setup for his burst. Fizz provides magic burst, pick pressure, backline access, and untargetable outplay windows, but he needs setup and follow-up because missed engage can leave him vulnerable.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `fizz`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `HARD_ENGAGE`,
      `FOLLOW_UP_DAMAGE`,
      `DIVE`,
      `PICK_COMPOSITION`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `PICK_POTENTIAL`,
      `DIVE`,
      `BACKLINE_ACCESS`,
      `JUNGLE_CLEAR`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_KILL_PRESSURE`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Jungle Fizz pairs best with lanes that can set up ganks or chain crowd control after his ultimate lands. Nautilus, Leona, and Rakan are strong examples because they provide engage, lockdown, and follow-up pressure. Fizz provides AP burst, pick threat, dive access, and jungle skirmish pressure, but he needs lanes with crowd control or damage to make his ganks reliable.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GALIO
  {
    championKey: `galio`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `DIVE`,
      `CROWD_CONTROL_SETUP`,
      `BACKLINE_ACCESS`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `TAUNT`,
      `KNOCK_UP`,
      `TEAMFIGHT_SETUP`,
      `GLOBAL_RANGE`,
      `ALLY_PROTECTION`,
    ],
    needsTags: [
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `LANE_KILL_PRESSURE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_DAMAGE`,
      `LOW_KILL_PRESSURE`,
      `TEAM_DEPENDENT`,
      `KITEABLE`,
    ],
    synergyNotes: `Mid Galio pairs best with champions that dive or start fights so he can follow with Hero's Entrance and layer taunt or knock-up control. Amumu, Jarvan IV, and Camille are strong examples because they create reliable engage and lockdown zones for Galio to join. Galio provides magic damage, anti-dive protection, taunt, knock-up, and global-style follow-up, but he needs teammates with enough damage to finish targets after he controls them.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `galio`,
    role: GameRole.SUPPORT,
    goodWithTags: [
      `HARD_ENGAGE`,
      `DIVE`,
      `CROWD_CONTROL_SETUP`,
      `BACKLINE_ACCESS`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `FRONTLINE`,
      `TAUNT`,
      `KNOCK_UP`,
      `ALLY_PROTECTION`,
      `PEEL`,
      `TEAMFIGHT_SETUP`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `LANE_PARTNER_DAMAGE`,
      `ENGAGE_SETUP`,
      `OBJECTIVE_CONTROL`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DAMAGE`,
      `LOW_KILL_PRESSURE`,
      `TEAM_DEPENDENT`,
      `KITEABLE`,
    ],
    synergyNotes: `Support Galio works best with teammates that want to dive or force grouped fights around his taunt and Hero's Entrance follow-up. Amumu, Jarvan IV, and Camille are strong examples because they create reliable engage windows and let Galio layer protection or crowd control on top. Galio provides frontline, peel, taunt, knock-up, and teamfight setup, but he needs lane partner damage and follow-up because his support build is more utility-focused than carry-focused.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GAREN
  {
    championKey: `garen`,
    role: GameRole.TOP,
    goodWithTags: [
      `SPEED_UP`,
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
      `SIDE_LANE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `ARMOR_REDUCTION`,
      `SILENCE`,
      `LOW_HEALTH_EXECUTE`,
      `FRONTLINE`,
      `SPLIT_PUSH`,
    ],
    needsTags: [
      `SPEED_UP`,
      `ENGAGE_SETUP`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [`KITEABLE`, `LOW_CC`, `LOW_KILL_PRESSURE`, `TEAM_DEPENDENT`],
    synergyNotes: `Garen pairs best with teammates that help him reach targets or force enemies to stay inside his melee range. Zilean, Nocturne, and Wukong are strong examples because they provide speed-up, engage pressure, or teamfight setup. Garen provides frontline durability, silence, armor reduction, execute threat, and side-lane pressure, but he needs help against teams that can kite or disengage from him.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GNAR
  {
    championKey: `gnar`,
    role: GameRole.TOP,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `DIVE`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
      `AREA_DAMAGE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `KNOCK_UP`,
      `STUN`,
      `AREA_CC`,
      `TEAMFIGHT_SETUP`,
      `SPLIT_PUSH`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `OBJECTIVE_CONTROL`,
      `TEAM_COORDINATION`,
    ],
    teamRiskTags: [
      `FORM_RELIANT`,
      `TEAM_DEPENDENT`,
      `LOW_KILL_PRESSURE`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Gnar pairs best with teammates that can force fights when his Rage bar is ready or follow up on Mega Gnar crowd control. Jarvan IV, Nocturne, and Vi are strong examples because they add engage, dive threat, and lockdown for his teamfight windows. Gnar provides physical damage, area crowd control, knock-up, stun, split-push pressure, and teamfight setup, but his value depends heavily on form timing and team coordination.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GRAGAS
  {
    championKey: `gragas`,
    role: GameRole.MID,
    goodWithTags: [
      `KNOCK_UP`,
      `CROWD_CONTROL_SETUP`,
      `PICK_COMPOSITION`,
      `FOLLOW_UP_DAMAGE`,
      `ROAMING`,
      `TEAMFIGHT`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `DISPLACEMENT`,
      `KNOCK_UP`,
      `PICK_POTENTIAL`,
      `ZONE_CONTROL`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `CROWD_CONTROL_SETUP`,
      `FRONTLINE`,
      `VISION_CONTROL`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Mid Gragas pairs well with champions that can follow his displacement or convert his crowd control into kills. Yasuo, Bard, and Pyke are strong examples because they can capitalize on knock-up, pick setup, or displaced targets. Gragas provides magic burst, displacement, knock-up, pick pressure, and zone control, but he needs follow-up damage and reliable teammates to finish targets after his combo.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `gragas`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `KNOCK_UP`,
      `CROWD_CONTROL_SETUP`,
      `PICK_COMPOSITION`,
      `FOLLOW_UP_DAMAGE`,
      `LANE_KILL_PRESSURE`,
      `ROAMING`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `DISPLACEMENT`,
      `KNOCK_UP`,
      `PICK_POTENTIAL`,
      `JUNGLE_CLEAR`,
    ],
    needsTags: [
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `CROWD_CONTROL_SETUP`,
      `FRONTLINE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_KILL_PRESSURE`,
      `LOW_CC`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Jungle Gragas works best with lanes that can follow his Body Slam and Explosive Cask displacement. Yasuo, Bard, and Ryze are strong examples because they can chain crowd control, add pick pressure, or lock targets in place after Gragas starts the play. Gragas provides AP burst, displacement, knock-up, jungle gank pressure, and pick setup, but he needs lane follow-up to make his engages reliable.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GRAVES
  {
    championKey: `graves`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `PEEL`,
      `SHIELDING`,
      `HEALING`,
      `CROWD_CONTROL_SETUP`,
      `LANE_KILL_PRESSURE`,
      `FRONTLINE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `BURST_DAMAGE`,
      `DPS`,
      `JUNGLE_CLEAR`,
      `SMOKE_SCREEN`,
      `OBJECTIVE_CONTROL`,
    ],
    needsTags: [
      `FRONTLINE`,
      `CROWD_CONTROL_SETUP`,
      `PEEL`,
      `LANE_KILL_PRESSURE`,
      `TEAM_SUPPORT`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `NO_HEALING_TEAM`,
      `NO_SHIELD_TEAM`,
    ],
    synergyNotes: `Graves pairs best with teammates that can protect him during short-range skirmishes or lock enemies down so he can land close-range burst. Janna, Nami, and Nautilus are strong examples because they provide peel, healing, shielding, or reliable crowd control setup. Graves provides strong jungle clear, physical damage, burst, sustained DPS, and objective control, but he needs frontline or peel because he must play closer to enemies than most marksmen.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // GWEN
  {
    championKey: `gwen`,
    role: GameRole.TOP,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `FRONTLINE`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
      `PEEL`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `PERCENT_HEALTH_DAMAGE`,
      `SUSTAIN`,
      `DUELING`,
      `SPLIT_PUSH`,
      `ANTI_TANK`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `PEEL`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `WEAK_EARLY_GAME`,
      `TEAM_DEPENDENT`,
      `LOW_KILL_PRESSURE`,
    ],
    synergyNotes: `Gwen pairs best with teammates that can start fights or lock enemies in place while she scales and cuts through the frontline. Rell, Rakan, and Nautilus are strong examples because they provide reliable engage and crowd control setup for her Needlework and Snip Snip! damage. Gwen provides scaling magic damage, sustain, anti-tank pressure, dueling, and split-push threat, but she needs setup and frontline support to safely enter teamfights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // HECARIM
  {
    championKey: `hecarim`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `SPEED_UP`,
      `SHIELDING`,
      `CROWD_CONTROL_SETUP`,
      `HARD_ENGAGE`,
      `FOLLOW_UP_DAMAGE`,
      `TEAMFIGHT`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `DIVE`,
      `FEAR`,
      `BACKLINE_ACCESS`,
      `TEAMFIGHT_SETUP`,
      `JUNGLE_CLEAR`,
    ],
    needsTags: [
      `SPEED_UP`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `TEAM_DEPENDENT`,
      `LOW_DURABILITY_TEAM`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Hecarim pairs best with teammates that speed him up, shield him, or lock enemies down after his engage. Karma, Zilean, and Nautilus are strong examples because they help him reach targets, survive dives, or chain crowd control after Onslaught of Shadows. Hecarim provides jungle tempo, physical damage, fear-based engage, backline access, and teamfight setup, but he needs follow-up damage and protection because he commits deeply into fights.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // HEIMERDINGER
  {
    championKey: `heimerdinger`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `FRONTLINE`,
      `AREA_DAMAGE`,
      `TEAMFIGHT`,
      `OBJECTIVE_CONTROL`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `ZONE_CONTROL`,
      `POKE`,
      `DEPLOYABLE`,
      `OBJECTIVE_CONTROL`,
    ],
    needsTags: [
      `FRONTLINE`,
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `PEEL`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `TEAM_DEPENDENT`,
      `VULNERABLE_TO_DIVE`,
    ],
    synergyNotes: `Heimerdinger pairs best with teammates that can hold enemies inside his turret zones or protect him while he controls objectives. Amumu, Jarvan IV, and Leona are strong examples because they provide engage and crowd control setup for his upgraded abilities and area damage. Heimerdinger provides magic damage, poke, deployable zone control, and objective control, but he needs frontline and peel because mobile divers can punish him if they reach his backline setup.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // IRELIA
  {
    championKey: `irelia`,
    role: GameRole.TOP,
    goodWithTags: [
      `CROWD_CONTROL_SETUP`,
      `HARD_ENGAGE`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `DIVE`,
      `FRONTLINE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `MOBILITY`,
      `DIVE`,
      `BACKLINE_ACCESS`,
      `DUELING`,
      `SPLIT_PUSH`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
      `CC_VULNERABLE`,
    ],
    synergyNotes: `Solo lane Irelia pairs best with teammates that can start fights or lock targets down long enough for her to stack passive and chain resets. Xin Zhao, Jarvan IV, and Nautilus are strong examples because they provide engage, lockdown, and follow-up windows for her dive pattern. Irelia provides physical damage, mobility, side-lane dueling, and backline access, but she needs crowd control setup and frontline help because she is vulnerable when her reset chain is interrupted.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `irelia`,
    role: GameRole.MID,
    goodWithTags: [
      `CROWD_CONTROL_SETUP`,
      `HARD_ENGAGE`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `DIVE`,
      `FRONTLINE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `MOBILITY`,
      `DIVE`,
      `BACKLINE_ACCESS`,
      `PICK_POTENTIAL`,
      `DUELING`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `PEEL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
      `CC_VULNERABLE`,
    ],
    synergyNotes: `Mid Irelia works best with teams that can create lockdown or dive pressure so she can enter fights safely and chain Bladesurge resets. Xin Zhao, Jarvan IV, and Nautilus are strong examples because they bring reliable crowd control and frontline pressure. Irelia provides physical damage from mid, mobility, pick pressure, and backline access, but she needs setup and follow-up because missed Flawless Duet or interrupted resets can make her engage fail.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JANNA
  {
    championKey: `janna`,
    role: GameRole.SUPPORT,
    goodWithTags: [
      `AUTO_ATTACK_CHAMPION`,
      `DPS`,
      `LANE_KILL_PRESSURE`,
      `SAFE_POSITIONING`,
      `HYPERCARRY`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `PEEL`,
      `ALLY_SHIELD`,
      `ALLY_HEAL`,
      `DISENGAGE`,
      `SPEED_UP`,
      `ALLY_PROTECTION`,
    ],
    needsTags: [
      `LANE_PARTNER_DAMAGE`,
      `DPS`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_DAMAGE`,
      `LOW_KILL_PRESSURE`,
      `TEAM_DEPENDENT`,
      `LOW_DURABILITY_TEAM`,
    ],
    synergyNotes: `Janna pairs best with marksmen that can use her shield, speed-up, and peel to play aggressively while staying safe. Draven, Jhin, and Lucian are strong examples because they benefit from extra protection and can convert Janna's disengage into winning trades. Janna provides shielding, healing, peel, speed-up, and strong anti-dive protection, but she needs teammates with enough damage because her own kill pressure is limited.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JARVAN IV
  {
    championKey: `jarvan-iv`,
    role: GameRole.JUNGLE,
    goodWithTags: [
      `AREA_DAMAGE`,
      `CROWD_CONTROL_SETUP`,
      `TEAMFIGHT`,
      `FOLLOW_UP_DAMAGE`,
      `HARD_ENGAGE`,
      `LANE_KILL_PRESSURE`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `KNOCK_UP`,
      `DIVE`,
      `LOCKDOWN`,
      `TEAMFIGHT_SETUP`,
      `FRONTLINE`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `AREA_DAMAGE`,
      `LANE_KILL_PRESSURE`,
      `OBJECTIVE_CONTROL`,
      `PEEL`,
    ],
    teamRiskTags: [
      `LOW_DAMAGE`,
      `TEAM_DEPENDENT`,
      `LOW_DURABILITY_TEAM`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Jarvan IV pairs best with champions that can layer damage or crowd control on top of his Cataclysm and knock-up engage. Orianna, Lissandra, and Miss Fortune are strong examples because they can punish enemies trapped in his lockdown zone. Jarvan IV provides engage, knock-up setup, frontline pressure, physical damage, and teamfight lockdown, but he needs follow-up damage because his engage can trap enemies without finishing them.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JAX
  {
    championKey: `jax`,
    role: GameRole.TOP,
    goodWithTags: [
      `SHIELDING`,
      `HEALING`,
      `SPEED_UP`,
      `PEEL`,
      `SIDE_LANE`,
      `SCALING_GAME`,
    ],
    providesTags: [
      `HYBRID_DAMAGE`,
      `DUELING`,
      `SPLIT_PUSH`,
      `COUNTER_STRIKE`,
      `STUN`,
      `SCALING_DAMAGE`,
    ],
    needsTags: [
      `TEAM_SUPPORT`,
      `PEEL`,
      `MAP_PRESSURE`,
      `OBJECTIVE_CONTROL`,
      `CROWD_CONTROL_SETUP`,
    ],
    teamRiskTags: [`LOW_CC`, `TEAM_DEPENDENT`, `KITEABLE`, `WEAK_EARLY_GAME`],
    synergyNotes: `Jax pairs best with teammates that can protect or speed him up while he scales into side-lane and teamfight threat. Lulu, Janna, and Zilean are strong examples because they add shielding, peel, speed-up, or revive-style protection for his extended fights. Jax provides hybrid damage, split-push pressure, dueling, stun threat, and scaling carry potential, but he needs support against kiting and coordinated crowd control.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JAYCE
  {
    championKey: `jayce`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `POKE_SETUP`,
      `SKIRMISH`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `POKE`,
      `BURST_DAMAGE`,
      `FORM_SWAP`,
      `ARMOR_REDUCTION`,
      `LANE_PRESSURE`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Mid Jayce pairs best with junglers and divers that can lock enemies down after his poke or help him convert early lane pressure into kills. Jarvan IV, Vi, and Lee Sin are strong examples because they provide engage, crowd control setup, and skirmish tempo. Jayce provides physical poke, burst damage, armor reduction, and lane pressure, but he needs frontline or engage help so his poke can turn into objectives.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `jayce`,
    role: GameRole.TOP,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `SIDE_LANE`,
      `SKIRMISH`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `POKE`,
      `BURST_DAMAGE`,
      `FORM_SWAP`,
      `ARMOR_REDUCTION`,
      `SIDE_LANE`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `ENGAGE_SETUP`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Solo lane Jayce works best with teammates that can start fights after he softens enemies with poke or help him snowball lane pressure. Jarvan IV, Vi, and Lee Sin are strong examples because they bring early skirmish pressure and reliable engage setup. Jayce provides physical poke, burst, armor reduction, form-swap flexibility, and side-lane pressure, but he needs teammates who can create lockdown because his own crowd control is limited.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JHIN
  {
    championKey: `jhin`,
    role: GameRole.ADC,
    goodWithTags: [
      `CROWD_CONTROL_SETUP`,
      `POKE_SETUP`,
      `PICK_COMPOSITION`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
      `SAFE_POSITIONING`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `BURST_DAMAGE`,
      `PICK_POTENTIAL`,
      `ROOT`,
      `TRAP`,
      `LONG_RANGE_EXECUTE`,
    ],
    needsTags: [
      `CROWD_CONTROL_SETUP`,
      `PEEL`,
      `FRONTLINE`,
      `LANE_PARTNER_DAMAGE`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DPS`,
      `POSITIONING_RELIANT`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Jhin pairs best with supports that can poke, root, knock up, or force enemies into predictable positions for Deadly Flourish and Curtain Call. Zyra, Karma, and Rakan are strong examples because they add lane control, crowd control setup, and follow-up pressure. Jhin provides physical burst, pick potential, root follow-up, trap control, and long-range execute threat, but he needs peel and setup because his sustained DPS is lower than traditional hypercarry marksmen.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // JINX
  {
    championKey: `jinx`,
    role: GameRole.ADC,
    goodWithTags: [
      `ENCHANTER`,
      `SHIELDING`,
      `HEALING`,
      `PEEL`,
      `SAFE_POSITIONING`,
      `TEAMFIGHT`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `DPS`,
      `AREA_DAMAGE`,
      `GLOBAL_RANGE`,
      `TAKEDOWN_RESET`,
      `RESET_CARRY`,
    ],
    needsTags: [
      `PEEL`,
      `FRONTLINE`,
      `TEAM_SUPPORT`,
      `CROWD_CONTROL_SETUP`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `WEAK_EARLY_GAME`,
      `POSITIONING_RELIANT`,
    ],
    synergyNotes: `Jinx pairs best with enchanters and peel supports that help her survive lane and stay alive long enough to trigger Get Excited! resets. Lulu, Janna, and Milio are strong examples because they provide shielding, healing, peel, and safety for her scaling teamfight pattern. Jinx provides high physical DPS, area damage, global execute pressure, and reset carry potential, but she needs protection because she is vulnerable before fights start snowballing in her favor.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // K'SANTE
  {
    championKey: `k-sante`,
    role: GameRole.TOP,
    goodWithTags: [
      `FOLLOW_UP_DAMAGE`,
      `DPS`,
      `TEAMFIGHT_CLEANUP`,
      `CROWD_CONTROL_SETUP`,
      `OBJECTIVE_CONTROL`,
      `SCALING_GAME`,
    ],
    providesTags: [
      `FRONTLINE`,
      `DAMAGE_REDUCTION`,
      `KNOCK_UP`,
      `DISPLACEMENT`,
      `ALLY_PROTECTION`,
      `PICK_POTENTIAL`,
    ],
    needsTags: [
      `FOLLOW_UP_DAMAGE`,
      `DPS`,
      `LANE_KILL_PRESSURE`,
      `OBJECTIVE_CONTROL`,
      `TEAMFIGHT_CLEANUP`,
    ],
    teamRiskTags: [
      `LOW_DAMAGE`,
      `LOW_KILL_PRESSURE`,
      `KITEABLE`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `K'Sante pairs best with damage-heavy teammates that benefit from his frontline control and target displacement. Shyvana, Master Yi, and Warwick are strong examples because they add sustained damage, cleanup threat, or skirmish pressure while K'Sante absorbs pressure and disrupts enemies. K'Sante provides frontline durability, knock-up, displacement, ally protection, and pick potential, but he needs teammates with enough damage to finish fights after he creates space.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KAI'SA
  {
    championKey: `kaisa`,
    role: GameRole.ADC,
    goodWithTags: [
      `SHIELDING`,
      `PEEL`,
      `CROWD_CONTROL_SETUP`,
      `HARD_ENGAGE`,
      `LANE_KILL_PRESSURE`,
      `FOLLOW_UP_DAMAGE`,
    ],
    providesTags: [
      `HYBRID_DAMAGE`,
      `DPS`,
      `ON_HIT_EFFECTS`,
      `PLASMA`,
      `BACKLINE_ACCESS`,
      `SCALING_DAMAGE`,
    ],
    needsTags: [
      `PEEL`,
      `CROWD_CONTROL_SETUP`,
      `FRONTLINE`,
      `LANE_PARTNER_DAMAGE`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `LOW_DURABILITY_TEAM`,
      `LOW_CC`,
      `WEAK_EARLY_GAME`,
      `POSITIONING_RELIANT`,
    ],
    synergyNotes: `Kai'Sa pairs best with supports that either protect her scaling or provide crowd control for Plasma setup and Killer Instinct follow-up. Lulu, Nautilus, and Alistar are strong examples because they offer shielding, peel, engage, or lockdown. Kai'Sa provides hybrid DPS, on-hit damage, Plasma pressure, backline access, and scaling carry threat, but she needs protection and reliable setup because her early range can be punished.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KALISTA
  {
    championKey: `kalista`,
    role: GameRole.ADC,
    goodWithTags: [
      `HARD_ENGAGE`,
      `FRONTLINE`,
      `CROWD_CONTROL_SETUP`,
      `ALLY_ENGAGE`,
      `LANE_KILL_PRESSURE`,
      `OATHSWORN_SETUP`,
    ],
    providesTags: [
      `PHYSICAL_DAMAGE`,
      `DPS`,
      `MOBILITY`,
      `OATHSWORN`,
      `ALLY_PROTECTION`,
      `OBJECTIVE_CONTROL`,
    ],
    needsTags: [
      `FRONTLINE`,
      `CROWD_CONTROL_SETUP`,
      `LANE_PARTNER_DAMAGE`,
      `PEEL`,
      `SAFE_POSITIONING`,
    ],
    teamRiskTags: [
      `OATHSWORN_RELIANT`,
      `POSITIONING_RELIANT`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Kalista pairs best with engage supports that can become her Oathsworn and use Fate's Call to start fights or re-enter safely. Alistar, Nautilus, and Thresh are strong examples because they provide frontline, lockdown, and lane kill pressure. Kalista provides sustained physical DPS, mobility, Oathsworn utility, ally protection, and strong objective control through Rend, but she needs reliable engage and protection because slows or crowd control can heavily punish her movement-based damage pattern.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KARMA
  {
    championKey: `karma`,
    role: GameRole.SUPPORT,
    goodWithTags: [
      `AUTO_ATTACK_CHAMPION`,
      `DPS`,
      `LANE_KILL_PRESSURE`,
      `POKE_SETUP`,
      `SAFE_POSITIONING`,
      `SPEED_UP`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `POKE`,
      `ALLY_SHIELD`,
      `SPEED_UP`,
      `PEEL`,
      `TEAM_SUPPORT`,
    ],
    needsTags: [
      `LANE_PARTNER_DAMAGE`,
      `DPS`,
      `FOLLOW_UP_DAMAGE`,
      `FRONTLINE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `LOW_DAMAGE`,
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
    ],
    synergyNotes: `Support Karma pairs best with aggressive carries that can use her shield, speed-up, and poke pressure to win trades early. Lucian, Ezreal, and Draven are strong examples because they can convert Karma's lane control into damage advantages. Karma provides poke, shielding, speed-up, peel, and team utility, but she needs teammates with enough damage because her support build is not a primary carry source.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  {
    championKey: `karma`,
    role: GameRole.MID,
    goodWithTags: [
      `HYPERCARRY`,
      `DIVE`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `SPEED_UP`,
      `EXTENDED_FIGHT`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `POKE`,
      `BURST_DAMAGE`,
      `ALLY_SHIELD`,
      `SPEED_UP`,
      `TEAM_SUPPORT`,
    ],
    needsTags: [
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `DPS`,
      `OBJECTIVE_CONTROL`,
      `PEEL`,
    ],
    teamRiskTags: [
      `LOW_CC`,
      `LOW_DURABILITY_TEAM`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Mid Karma works best with carries or bruisers that benefit from speed-up and shielding while she adds poke and utility from mid lane. Master Yi, Kindred, and Aatrox are strong examples because they can use Karma's shields and movement speed to stay on targets or survive extended fights. Karma provides magic poke, burst windows, shielding, and team support, but she needs frontline and sustained damage around her because she does not always replace a dedicated carry mage.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
  // KASSADIN
  {
    championKey: `kassadin`,
    role: GameRole.MID,
    goodWithTags: [
      `HARD_ENGAGE`,
      `CROWD_CONTROL_SETUP`,
      `DIVE`,
      `FRONTLINE`,
      `FOLLOW_UP_DAMAGE`,
      `SCALING_GAME`,
    ],
    providesTags: [
      `MAGIC_DAMAGE`,
      `BURST_DAMAGE`,
      `MOBILITY`,
      `BACKLINE_ACCESS`,
      `ANTI_MAGIC`,
      `SCALING_DAMAGE`,
    ],
    needsTags: [
      `FRONTLINE`,
      `ENGAGE_SETUP`,
      `CROWD_CONTROL_SETUP`,
      `FOLLOW_UP_DAMAGE`,
      `OBJECTIVE_CONTROL`,
    ],
    teamRiskTags: [
      `WEAK_EARLY_GAME`,
      `LOW_CC`,
      `TEAM_DEPENDENT`,
      `WEAK_WHEN_BEHIND`,
    ],
    synergyNotes: `Kassadin pairs best with teammates that can create engage windows and hold the game stable while he scales. Jarvan IV, Nocturne, and Vi are strong examples because they provide dive pressure, lockdown, and target access that let Kassadin follow up with Riftwalk burst. Kassadin provides scaling magic damage, backline access, anti-magic value, and late-game cleanup threat, but he needs frontline and early-game stability because his first few levels can be punishable.`,
    dataQuality: DataQualityLevel.PARTIAL,
  },
];

export async function seedChampionSynergyProfiles(
  prisma: PrismaClient,
  patchId: string,
) {
  console.log(`Seeding champion synergy profiles...`);

  for (const championSynergyProfileSeed of championSynergyProfileSeeds) {
    const champion = await prisma.champion.findUnique({
      where: {
        key: championSynergyProfileSeed.championKey,
      },
    });

    if (!champion || champion.deletedAt) {
      throw new Error(
        `Champion not found or deleted: ${championSynergyProfileSeed.championKey}`,
      );
    }

    await prisma.championSynergyProfile.upsert({
      where: {
        championId_patchId_role: {
          championId: champion.id,
          patchId,
          role: championSynergyProfileSeed.role,
        },
      },
      update: {
        goodWithTags: championSynergyProfileSeed.goodWithTags,
        providesTags: championSynergyProfileSeed.providesTags,
        needsTags: championSynergyProfileSeed.needsTags,
        teamRiskTags: championSynergyProfileSeed.teamRiskTags,
        synergyNotes: championSynergyProfileSeed.synergyNotes ?? null,
        dataQuality:
          championSynergyProfileSeed.dataQuality ?? DataQualityLevel.MINIMAL,
        deletedAt: null,
      },
      create: {
        championId: champion.id,
        patchId,
        role: championSynergyProfileSeed.role,
        goodWithTags: championSynergyProfileSeed.goodWithTags,
        providesTags: championSynergyProfileSeed.providesTags,
        needsTags: championSynergyProfileSeed.needsTags,
        teamRiskTags: championSynergyProfileSeed.teamRiskTags,
        synergyNotes: championSynergyProfileSeed.synergyNotes ?? null,
        dataQuality:
          championSynergyProfileSeed.dataQuality ?? DataQualityLevel.MINIMAL,
      },
    });

    console.log(
      `Seeded ${champion.name}'s synergy profile for patch ${patchId}`,
    );
  }

  console.log(`SEEDED CHAMPIONS SYNERGY PROFILES`);
}
