import { Prisma, PrismaClient } from './../../src/generated/prisma/client.js';

type ChampionPatchStatSeed = {
  championKey: string;
  baseHealth?: number | null;
  baseArmor?: number | null;
  baseResource?: number | null;
  baseMagicResist?: number | null;
  baseAttackDamage?: number | null;
  baseAbilityPower?: number | null;
  attackSpeed?: number | null;
  moveSpeed?: number | null;
  healthGrowth?: number | null;
  resourceGrowth?: number | null;
  armorGrowth?: number | null;
  magicResistGrowth?: number | null;
  attackDamageGrowth?: number | null;
  attackSpeedGrowth?: number | null;
  scalingProfile?: Prisma.InputJsonValue | null;
  laneProfile?: Prisma.InputJsonValue | null;
  teamProfile?: Prisma.InputJsonValue | null;
  metaScore?: number | null;
};

const championPatchStatSeeds: ChampionPatchStatSeed[] = [
  // AATROX
  {
    championKey: `aatrox`,

    baseHealth: 630,
    baseResource: null,
    baseArmor: 46,
    baseMagicResist: 40,
    baseAttackDamage: 62,
    baseAbilityPower: 0,
    attackSpeed: 0.73,
    moveSpeed: 355,

    healthGrowth: 136,
    resourceGrowth: null,
    armorGrowth: 4,
    magicResistGrowth: 2,
    attackDamageGrowth: 5,
    attackSpeedGrowth: 0.007857,

    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 6,
          armor: 46,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 62,
          attackSpeed: 0.73,
        },
        {
          level: 2,
          health: 766,
          healthRegenPer5s: 7,
          armor: 50,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 67,
          attackSpeed: 0.74,
        },
        {
          level: 3,
          health: 902,
          healthRegenPer5s: 8,
          armor: 54,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 72,
          attackSpeed: 0.75,
        },
        {
          level: 4,
          health: 1038,
          healthRegenPer5s: 9,
          armor: 58,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 77,
          attackSpeed: 0.75,
        },
        {
          level: 5,
          health: 1174,
          healthRegenPer5s: 10,
          armor: 62,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 82,
          attackSpeed: 0.76,
        },
        {
          level: 6,
          health: 1310,
          healthRegenPer5s: 11,
          armor: 66,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 87,
          attackSpeed: 0.77,
        },
        {
          level: 7,
          health: 1446,
          healthRegenPer5s: 12,
          armor: 70,
          magicResist: 52,
          moveSpeed: 355,
          attackDamage: 92,
          attackSpeed: 0.78,
        },
        {
          level: 8,
          health: 1582,
          healthRegenPer5s: 13,
          armor: 74,
          magicResist: 54,
          moveSpeed: 355,
          attackDamage: 97,
          attackSpeed: 0.79,
        },
        {
          level: 9,
          health: 1718,
          healthRegenPer5s: 14,
          armor: 78,
          magicResist: 56,
          moveSpeed: 355,
          attackDamage: 102,
          attackSpeed: 0.79,
        },
        {
          level: 10,
          health: 1854,
          healthRegenPer5s: 15,
          armor: 82,
          magicResist: 58,
          moveSpeed: 355,
          attackDamage: 107,
          attackSpeed: 0.8,
        },
        {
          level: 11,
          health: 1990,
          healthRegenPer5s: 16,
          armor: 86,
          magicResist: 60,
          moveSpeed: 355,
          attackDamage: 112,
          attackSpeed: 0.81,
        },
        {
          level: 12,
          health: 2126,
          healthRegenPer5s: 17,
          armor: 90,
          magicResist: 62,
          moveSpeed: 355,
          attackDamage: 117,
          attackSpeed: 0.82,
        },
        {
          level: 13,
          health: 2262,
          healthRegenPer5s: 18,
          armor: 94,
          magicResist: 64,
          moveSpeed: 355,
          attackDamage: 122,
          attackSpeed: 0.82,
        },
        {
          level: 14,
          health: 2398,
          healthRegenPer5s: 19,
          armor: 98,
          magicResist: 66,
          moveSpeed: 355,
          attackDamage: 127,
          attackSpeed: 0.83,
        },
        {
          level: 15,
          health: 2534,
          healthRegenPer5s: 20,
          armor: 102,
          magicResist: 68,
          moveSpeed: 355,
          attackDamage: 132,
          attackSpeed: 0.84,
        },
      ],
    },

    laneProfile: {
      preferredRoles: [`TOP`],
      tradingPattern: `skillshot_combo`,
      sustainLevel: `high`,
      allInThreat: `high`,
      waveClear: `medium`,
      mobility: `medium`,
    },

    teamProfile: {
      provides: [`FRONTLINE`, `AREA_DAMAGE`, `KNOCK_UP`, `SUSTAIN`],
      needs: [`ENGAGE_SETUP`, `ANTI_HEAL_PROTECTION`],
      weakAgainst: [`ANTI_HEAL`, `KITE`, `HIGH_MOBILITY`, `POINT_AND_CLICK_CC`],
    },
  },
  // AHRI
  {
    championKey: `ahri`,
    baseHealth: 630,
    baseResource: 435,
    baseArmor: 34,
    baseMagicResist: 36,
    baseAttackDamage: 52,
    baseAbilityPower: 0,
    attackSpeed: 0.75,
    moveSpeed: 355,
    healthGrowth: 120,
    resourceGrowth: 37,
    armorGrowth: 4,
    magicResistGrowth: 1,
    attackDamageGrowth: 3,
    attackSpeedGrowth: 0,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 8,
          mana: 435,
          manaRegenPer5s: 18,
          armor: 34,
          magicResist: 36,
          moveSpeed: 355,
          attackDamage: 52,
          attackSpeed: 0.75,
        },
        {
          level: 2,
          health: 750,
          healthRegenPer5s: 9,
          mana: 472,
          manaRegenPer5s: 19,
          armor: 38,
          magicResist: 37,
          moveSpeed: 355,
          attackDamage: 55,
          attackSpeed: 0.75,
        },
        {
          level: 3,
          health: 870,
          healthRegenPer5s: 10,
          mana: 509,
          manaRegenPer5s: 20,
          armor: 42,
          magicResist: 38,
          moveSpeed: 355,
          attackDamage: 58,
          attackSpeed: 0.75,
        },
        {
          level: 4,
          health: 990,
          healthRegenPer5s: 11,
          mana: 546,
          manaRegenPer5s: 21,
          armor: 46,
          magicResist: 39,
          moveSpeed: 355,
          attackDamage: 61,
          attackSpeed: 0.75,
        },
        {
          level: 5,
          health: 1110,
          healthRegenPer5s: 12,
          mana: 583,
          manaRegenPer5s: 22,
          armor: 50,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 64,
          attackSpeed: 0.75,
        },
        {
          level: 6,
          health: 1230,
          healthRegenPer5s: 13,
          mana: 620,
          manaRegenPer5s: 23,
          armor: 54,
          magicResist: 41,
          moveSpeed: 355,
          attackDamage: 67,
          attackSpeed: 0.75,
        },
        {
          level: 7,
          health: 1350,
          healthRegenPer5s: 14,
          mana: 657,
          manaRegenPer5s: 24,
          armor: 58,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 70,
          attackSpeed: 0.75,
        },
        {
          level: 8,
          health: 1470,
          healthRegenPer5s: 15,
          mana: 694,
          manaRegenPer5s: 25,
          armor: 62,
          magicResist: 43,
          moveSpeed: 355,
          attackDamage: 73,
          attackSpeed: 0.75,
        },
        {
          level: 9,
          health: 1590,
          healthRegenPer5s: 16,
          mana: 731,
          manaRegenPer5s: 26,
          armor: 66,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 76,
          attackSpeed: 0.75,
        },
        {
          level: 10,
          health: 1710,
          healthRegenPer5s: 17,
          mana: 768,
          manaRegenPer5s: 27,
          armor: 70,
          magicResist: 45,
          moveSpeed: 355,
          attackDamage: 79,
          attackSpeed: 0.75,
        },
        {
          level: 11,
          health: 1830,
          healthRegenPer5s: 18,
          mana: 805,
          manaRegenPer5s: 28,
          armor: 74,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 82,
          attackSpeed: 0.75,
        },
        {
          level: 12,
          health: 1950,
          healthRegenPer5s: 19,
          mana: 842,
          manaRegenPer5s: 29,
          armor: 78,
          magicResist: 47,
          moveSpeed: 355,
          attackDamage: 85,
          attackSpeed: 0.75,
        },
        {
          level: 13,
          health: 2070,
          healthRegenPer5s: 20,
          mana: 879,
          manaRegenPer5s: 30,
          armor: 82,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 88,
          attackSpeed: 0.75,
        },
        {
          level: 14,
          health: 2190,
          healthRegenPer5s: 21,
          mana: 916,
          manaRegenPer5s: 31,
          armor: 86,
          magicResist: 49,
          moveSpeed: 355,
          attackDamage: 91,
          attackSpeed: 0.75,
        },
        {
          level: 15,
          health: 2310,
          healthRegenPer5s: 22,
          mana: 953,
          manaRegenPer5s: 32,
          armor: 90,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 94,
          attackSpeed: 0.75,
        },
      ],
    },
    laneProfile: {
      lanePressure: `MEDIUM`,
      roamThreat: `HIGH`,
      tradePattern: `SHORT_TRADES_AND_PICK_SETUP`,
      notes: `Ranged magic mid laner with charm pick threat, mobility, sustain from passive, and strong roam/skirmish potential after level 5.`,
    },
    teamProfile: {
      teamfightRole: `MOBILE_PICK_MAGE`,
      pickPotential: `HIGH`,
      mobility: `HIGH`,
      utility: [`CHARM`, `DASH`, `SUSTAIN`],
    },
    metaScore: null,
  },
  // AKALI
  {
    championKey: `akali`,
    baseHealth: 630,
    baseResource: 200,
    baseArmor: 34,
    baseMagicResist: 38,
    baseAttackDamage: 64,
    baseAbilityPower: 0,
    attackSpeed: 0.8,
    moveSpeed: 355,
    healthGrowth: 140,
    resourceGrowth: 0,
    armorGrowth: 6,
    magicResistGrowth: 2,
    attackDamageGrowth: 4,
    attackSpeedGrowth: 0.015,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 10,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 34,
          magicResist: 38,
          moveSpeed: 355,
          attackDamage: 64,
          attackSpeed: 0.8,
        },
        {
          level: 2,
          health: 770,
          healthRegenPer5s: 11,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 40,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 68,
          attackSpeed: 0.82,
        },
        {
          level: 3,
          health: 910,
          healthRegenPer5s: 12,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 46,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 72,
          attackSpeed: 0.83,
        },
        {
          level: 4,
          health: 1050,
          healthRegenPer5s: 13,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 52,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 76,
          attackSpeed: 0.85,
        },
        {
          level: 5,
          health: 1190,
          healthRegenPer5s: 14,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 58,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 80,
          attackSpeed: 0.86,
        },
        {
          level: 6,
          health: 1330,
          healthRegenPer5s: 15,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 64,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 84,
          attackSpeed: 0.88,
        },
        {
          level: 7,
          health: 1470,
          healthRegenPer5s: 16,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 70,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 88,
          attackSpeed: 0.89,
        },
        {
          level: 8,
          health: 1610,
          healthRegenPer5s: 17,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 76,
          magicResist: 52,
          moveSpeed: 355,
          attackDamage: 92,
          attackSpeed: 0.91,
        },
        {
          level: 9,
          health: 1750,
          healthRegenPer5s: 18,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 82,
          magicResist: 54,
          moveSpeed: 355,
          attackDamage: 96,
          attackSpeed: 0.92,
        },
        {
          level: 10,
          health: 1890,
          healthRegenPer5s: 19,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 88,
          magicResist: 56,
          moveSpeed: 355,
          attackDamage: 100,
          attackSpeed: 0.94,
        },
        {
          level: 11,
          health: 2030,
          healthRegenPer5s: 20,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 94,
          magicResist: 58,
          moveSpeed: 355,
          attackDamage: 104,
          attackSpeed: 0.95,
        },
        {
          level: 12,
          health: 2170,
          healthRegenPer5s: 21,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 100,
          magicResist: 60,
          moveSpeed: 355,
          attackDamage: 108,
          attackSpeed: 0.97,
        },
        {
          level: 13,
          health: 2310,
          healthRegenPer5s: 22,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 106,
          magicResist: 62,
          moveSpeed: 355,
          attackDamage: 112,
          attackSpeed: 0.98,
        },
        {
          level: 14,
          health: 2450,
          healthRegenPer5s: 23,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 112,
          magicResist: 64,
          moveSpeed: 355,
          attackDamage: 116,
          attackSpeed: 1,
        },
        {
          level: 15,
          health: 2590,
          healthRegenPer5s: 24,
          mana: 200,
          manaRegenPer5s: 50,
          armor: 118,
          magicResist: 66,
          moveSpeed: 355,
          attackDamage: 120,
          attackSpeed: 1.01,
        },
      ],
    },
    laneProfile: {
      lanePressure: `MEDIUM`,
      roamThreat: `HIGH`,
      tradePattern: `BURST_TRADES_AND_ALL_IN`,
      notes: `Melee energy-based assassin with high mobility, strong all-in threat, stealth safety, and execute pressure after level 5.`,
    },
    teamProfile: {
      teamfightRole: `MOBILE_ASSASSIN`,
      pickPotential: `HIGH`,
      mobility: `VERY_HIGH`,
      utility: [`STEALTH`, `DASH`, `EXECUTE`, `SLOW`],
    },
    metaScore: null,
  },
  // AKSHAN
  {
    championKey: `akshan`,
    baseHealth: 630,
    baseResource: 390,
    baseArmor: 35,
    baseMagicResist: 30,
    baseAttackDamage: 52,
    baseAbilityPower: 0,
    attackSpeed: 0.7,
    moveSpeed: 340,
    healthGrowth: 128,
    resourceGrowth: 37,
    armorGrowth: 5,
    magicResistGrowth: 1,
    attackDamageGrowth: 5,
    attackSpeedGrowth: 0.00357,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 9,
          mana: 390,
          manaRegenPer5s: 15,
          armor: 35,
          magicResist: 30,
          moveSpeed: 340,
          attackDamage: 52,
          attackSpeed: 0.7,
        },
        {
          level: 2,
          health: 758,
          healthRegenPer5s: 10,
          mana: 427,
          manaRegenPer5s: 16,
          armor: 40,
          magicResist: 31,
          moveSpeed: 340,
          attackDamage: 57,
          attackSpeed: 0.7,
        },
        {
          level: 3,
          health: 886,
          healthRegenPer5s: 11,
          mana: 464,
          manaRegenPer5s: 17,
          armor: 45,
          magicResist: 32,
          moveSpeed: 340,
          attackDamage: 62,
          attackSpeed: 0.71,
        },
        {
          level: 4,
          health: 1014,
          healthRegenPer5s: 12,
          mana: 501,
          manaRegenPer5s: 18,
          armor: 50,
          magicResist: 33,
          moveSpeed: 340,
          attackDamage: 67,
          attackSpeed: 0.71,
        },
        {
          level: 5,
          health: 1142,
          healthRegenPer5s: 13,
          mana: 538,
          manaRegenPer5s: 19,
          armor: 55,
          magicResist: 34,
          moveSpeed: 340,
          attackDamage: 72,
          attackSpeed: 0.71,
        },
        {
          level: 6,
          health: 1270,
          healthRegenPer5s: 14,
          mana: 575,
          manaRegenPer5s: 20,
          armor: 60,
          magicResist: 35,
          moveSpeed: 340,
          attackDamage: 77,
          attackSpeed: 0.72,
        },
        {
          level: 7,
          health: 1398,
          healthRegenPer5s: 15,
          mana: 612,
          manaRegenPer5s: 21,
          armor: 65,
          magicResist: 36,
          moveSpeed: 340,
          attackDamage: 82,
          attackSpeed: 0.72,
        },
        {
          level: 8,
          health: 1526,
          healthRegenPer5s: 16,
          mana: 649,
          manaRegenPer5s: 22,
          armor: 70,
          magicResist: 37,
          moveSpeed: 340,
          attackDamage: 87,
          attackSpeed: 0.73,
        },
        {
          level: 9,
          health: 1654,
          healthRegenPer5s: 17,
          mana: 686,
          manaRegenPer5s: 23,
          armor: 75,
          magicResist: 38,
          moveSpeed: 340,
          attackDamage: 92,
          attackSpeed: 0.73,
        },
        {
          level: 10,
          health: 1782,
          healthRegenPer5s: 18,
          mana: 723,
          manaRegenPer5s: 24,
          armor: 80,
          magicResist: 39,
          moveSpeed: 340,
          attackDamage: 97,
          attackSpeed: 0.73,
        },
        {
          level: 11,
          health: 1910,
          healthRegenPer5s: 19,
          mana: 760,
          manaRegenPer5s: 25,
          armor: 85,
          magicResist: 40,
          moveSpeed: 340,
          attackDamage: 102,
          attackSpeed: 0.74,
        },
        {
          level: 12,
          health: 2038,
          healthRegenPer5s: 20,
          mana: 797,
          manaRegenPer5s: 26,
          armor: 90,
          magicResist: 41,
          moveSpeed: 340,
          attackDamage: 107,
          attackSpeed: 0.74,
        },
        {
          level: 13,
          health: 2166,
          healthRegenPer5s: 21,
          mana: 834,
          manaRegenPer5s: 27,
          armor: 95,
          magicResist: 42,
          moveSpeed: 340,
          attackDamage: 112,
          attackSpeed: 0.74,
        },
        {
          level: 14,
          health: 2294,
          healthRegenPer5s: 22,
          mana: 871,
          manaRegenPer5s: 28,
          armor: 100,
          magicResist: 43,
          moveSpeed: 340,
          attackDamage: 117,
          attackSpeed: 0.75,
        },
        {
          level: 15,
          health: 2422,
          healthRegenPer5s: 23,
          mana: 908,
          manaRegenPer5s: 29,
          armor: 105,
          magicResist: 44,
          moveSpeed: 340,
          attackDamage: 122,
          attackSpeed: 0.75,
        },
      ],
    },
    laneProfile: {
      lanePressure: `MEDIUM`,
      roamThreat: `HIGH`,
      tradePattern: `SHORT_TRADES_AND_ROAMS`,
      notes: `Ranged AD mid/marksman with strong roaming, reveal, mobility, and pick potential.`,
    },
    teamProfile: {
      teamfightRole: `BACKLINE_SKIRMISHER`,
      pickPotential: `HIGH`,
      mobility: `HIGH`,
      utility: [`REVIVE`, `REVEAL`, `EXECUTE`],
    },
    metaScore: null,
  },
  // ALISTAR
  {
    championKey: `alistar`,
    baseHealth: 720,
    baseResource: 345,
    baseArmor: 52,
    baseMagicResist: 38,
    baseAttackDamage: 58,
    baseAbilityPower: 0,
    attackSpeed: 0.8,
    moveSpeed: 340,
    healthGrowth: 144,
    resourceGrowth: 31,
    armorGrowth: 4,
    magicResistGrowth: 2,
    attackDamageGrowth: 3,
    attackSpeedGrowth: 0.015,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 720,
          healthRegenPer5s: 9,
          mana: 345,
          manaRegenPer5s: 12,
          armor: 52,
          magicResist: 38,
          moveSpeed: 340,
          attackDamage: 58,
          attackSpeed: 0.8,
        },
        {
          level: 2,
          health: 864,
          healthRegenPer5s: 10,
          mana: 376,
          manaRegenPer5s: 13,
          armor: 56,
          magicResist: 40,
          moveSpeed: 340,
          attackDamage: 61,
          attackSpeed: 0.82,
        },
        {
          level: 3,
          health: 1008,
          healthRegenPer5s: 11,
          mana: 407,
          manaRegenPer5s: 14,
          armor: 60,
          magicResist: 42,
          moveSpeed: 340,
          attackDamage: 64,
          attackSpeed: 0.83,
        },
        {
          level: 4,
          health: 1152,
          healthRegenPer5s: 12,
          mana: 438,
          manaRegenPer5s: 15,
          armor: 64,
          magicResist: 44,
          moveSpeed: 340,
          attackDamage: 67,
          attackSpeed: 0.85,
        },
        {
          level: 5,
          health: 1296,
          healthRegenPer5s: 13,
          mana: 469,
          manaRegenPer5s: 16,
          armor: 68,
          magicResist: 46,
          moveSpeed: 340,
          attackDamage: 70,
          attackSpeed: 0.86,
        },
        {
          level: 6,
          health: 1440,
          healthRegenPer5s: 14,
          mana: 500,
          manaRegenPer5s: 17,
          armor: 72,
          magicResist: 48,
          moveSpeed: 340,
          attackDamage: 73,
          attackSpeed: 0.88,
        },
        {
          level: 7,
          health: 1584,
          healthRegenPer5s: 15,
          mana: 531,
          manaRegenPer5s: 18,
          armor: 76,
          magicResist: 50,
          moveSpeed: 340,
          attackDamage: 76,
          attackSpeed: 0.89,
        },
        {
          level: 8,
          health: 1728,
          healthRegenPer5s: 16,
          mana: 562,
          manaRegenPer5s: 19,
          armor: 80,
          magicResist: 52,
          moveSpeed: 340,
          attackDamage: 79,
          attackSpeed: 0.91,
        },
        {
          level: 9,
          health: 1872,
          healthRegenPer5s: 17,
          mana: 593,
          manaRegenPer5s: 20,
          armor: 84,
          magicResist: 54,
          moveSpeed: 340,
          attackDamage: 82,
          attackSpeed: 0.92,
        },
        {
          level: 10,
          health: 2016,
          healthRegenPer5s: 18,
          mana: 624,
          manaRegenPer5s: 21,
          armor: 88,
          magicResist: 56,
          moveSpeed: 340,
          attackDamage: 85,
          attackSpeed: 0.94,
        },
        {
          level: 11,
          health: 2160,
          healthRegenPer5s: 19,
          mana: 655,
          manaRegenPer5s: 22,
          armor: 92,
          magicResist: 58,
          moveSpeed: 340,
          attackDamage: 88,
          attackSpeed: 0.95,
        },
        {
          level: 12,
          health: 2304,
          healthRegenPer5s: 20,
          mana: 686,
          manaRegenPer5s: 23,
          armor: 96,
          magicResist: 60,
          moveSpeed: 340,
          attackDamage: 91,
          attackSpeed: 0.97,
        },
        {
          level: 13,
          health: 2448,
          healthRegenPer5s: 21,
          mana: 717,
          manaRegenPer5s: 24,
          armor: 100,
          magicResist: 62,
          moveSpeed: 340,
          attackDamage: 94,
          attackSpeed: 0.98,
        },
        {
          level: 14,
          health: 2592,
          healthRegenPer5s: 22,
          mana: 748,
          manaRegenPer5s: 25,
          armor: 104,
          magicResist: 64,
          moveSpeed: 340,
          attackDamage: 97,
          attackSpeed: 1,
        },
        {
          level: 15,
          health: 2736,
          healthRegenPer5s: 23,
          mana: 779,
          manaRegenPer5s: 26,
          armor: 108,
          magicResist: 66,
          moveSpeed: 340,
          attackDamage: 100,
          attackSpeed: 1.01,
        },
      ],
    },
    laneProfile: {
      preferredRoles: [`SUPPORT`],
      tradingPattern: `engage_combo`,
      sustainLevel: `medium`,
      allInThreat: `high`,
      waveClear: `low`,
      mobility: `low`,
      notes: `Tank support with strong engage, knock-up, displacement, peel, and high durability after ultimate.`,
    },
    teamProfile: {
      provides: [`FRONTLINE`, `ENGAGE`, `PEEL`, `KNOCK_UP`, `DAMAGE_REDUCTION`],
      needs: [`FOLLOW_UP_DAMAGE`, `LANE_PARTNER_DAMAGE`],
      weakAgainst: [`POKE_COMPOSITION`, `DISENGAGE`, `KITE`],
    },
    metaScore: null,
  },
  // AMBESSA
  {
    championKey: `ambessa`,
    baseHealth: 660,
    baseResource: 200,
    baseArmor: 43,
    baseMagicResist: 36,
    baseAttackDamage: 58,
    baseAbilityPower: 0,
    attackSpeed: 0.8,
    moveSpeed: 355,
    healthGrowth: 120,
    resourceGrowth: 0,
    armorGrowth: 4,
    magicResistGrowth: 2,
    attackDamageGrowth: 4,
    attackSpeedGrowth: 0.015,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 660,
          healthRegenPer5s: 8,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 43,
          magicResist: 36,
          moveSpeed: 355,
          attackDamage: 58,
          attackSpeed: 0.8,
        },
        {
          level: 2,
          health: 780,
          healthRegenPer5s: 9,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 47,
          magicResist: 38,
          moveSpeed: 355,
          attackDamage: 62,
          attackSpeed: 0.82,
        },
        {
          level: 3,
          health: 900,
          healthRegenPer5s: 10,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 51,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 66,
          attackSpeed: 0.83,
        },
        {
          level: 4,
          health: 1020,
          healthRegenPer5s: 11,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 55,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 70,
          attackSpeed: 0.85,
        },
        {
          level: 5,
          health: 1140,
          healthRegenPer5s: 12,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 59,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 74,
          attackSpeed: 0.86,
        },
        {
          level: 6,
          health: 1260,
          healthRegenPer5s: 13,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 63,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 78,
          attackSpeed: 0.88,
        },
        {
          level: 7,
          health: 1380,
          healthRegenPer5s: 14,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 67,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 82,
          attackSpeed: 0.89,
        },
        {
          level: 8,
          health: 1500,
          healthRegenPer5s: 15,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 71,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 86,
          attackSpeed: 0.91,
        },
        {
          level: 9,
          health: 1620,
          healthRegenPer5s: 16,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 75,
          magicResist: 52,
          moveSpeed: 355,
          attackDamage: 90,
          attackSpeed: 0.92,
        },
        {
          level: 10,
          health: 1740,
          healthRegenPer5s: 17,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 79,
          magicResist: 54,
          moveSpeed: 355,
          attackDamage: 94,
          attackSpeed: 0.94,
        },
        {
          level: 11,
          health: 1860,
          healthRegenPer5s: 18,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 83,
          magicResist: 56,
          moveSpeed: 355,
          attackDamage: 98,
          attackSpeed: 0.95,
        },
        {
          level: 12,
          health: 1980,
          healthRegenPer5s: 19,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 87,
          magicResist: 58,
          moveSpeed: 355,
          attackDamage: 102,
          attackSpeed: 0.97,
        },
        {
          level: 13,
          health: 2100,
          healthRegenPer5s: 20,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 91,
          magicResist: 60,
          moveSpeed: 355,
          attackDamage: 106,
          attackSpeed: 0.98,
        },
        {
          level: 14,
          health: 2220,
          healthRegenPer5s: 21,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 95,
          magicResist: 62,
          moveSpeed: 355,
          attackDamage: 110,
          attackSpeed: 1,
        },
        {
          level: 15,
          health: 2340,
          healthRegenPer5s: 22,
          resource: 200,
          resourceRegenPer5s: 50,
          armor: 99,
          magicResist: 64,
          moveSpeed: 355,
          attackDamage: 114,
          attackSpeed: 1.01,
        },
      ],
    },
    laneProfile: {
      preferredRoles: [`TOP`],
      tradingPattern: `mobile_extended_trade`,
      sustainLevel: `high_after_level_5`,
      allInThreat: `high`,
      waveClear: `medium`,
      mobility: `very_high`,
      notes: `Energy-based bruiser with repeated dash windows, percent-health damage, shielding, sustain after ultimate, and strong dive threat.`,
    },
    teamProfile: {
      provides: [
        `DIVE`,
        `SUSTAIN`,
        `PERCENT_HEALTH_DAMAGE`,
        `DAMAGE_REDUCTION`,
      ],
      needs: [`ENGAGE_SETUP`, `FOLLOW_UP_DAMAGE`],
      weakAgainst: [`ANTI_HEAL`, `POINT_AND_CLICK_CC`, `KITE`],
    },
    metaScore: null,
  },
  // AMUMU
  {
    championKey: `amumu`,
    baseHealth: 690,
    baseResource: 390,
    baseArmor: 40,
    baseMagicResist: 38,
    baseAttackDamage: 52,
    baseAbilityPower: 0,
    attackSpeed: 0.8,
    moveSpeed: 345,
    healthGrowth: 104,
    resourceGrowth: 49,
    armorGrowth: 4,
    magicResistGrowth: 2,
    attackDamageGrowth: 3,
    attackSpeedGrowth: 0.015,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 690,
          healthRegenPer5s: 9,
          resource: 390,
          resourceRegenPer5s: 15,
          armor: 40,
          magicResist: 38,
          moveSpeed: 345,
          attackDamage: 52,
          attackSpeed: 0.8,
        },
        {
          level: 2,
          health: 794,
          healthRegenPer5s: 10,
          resource: 439,
          resourceRegenPer5s: 16,
          armor: 44,
          magicResist: 40,
          moveSpeed: 345,
          attackDamage: 55,
          attackSpeed: 0.82,
        },
        {
          level: 3,
          health: 898,
          healthRegenPer5s: 11,
          resource: 488,
          resourceRegenPer5s: 17,
          armor: 48,
          magicResist: 42,
          moveSpeed: 345,
          attackDamage: 58,
          attackSpeed: 0.83,
        },
        {
          level: 4,
          health: 1002,
          healthRegenPer5s: 11,
          resource: 537,
          resourceRegenPer5s: 18,
          armor: 52,
          magicResist: 44,
          moveSpeed: 345,
          attackDamage: 61,
          attackSpeed: 0.85,
        },
        {
          level: 5,
          health: 1106,
          healthRegenPer5s: 12,
          resource: 586,
          resourceRegenPer5s: 19,
          armor: 56,
          magicResist: 46,
          moveSpeed: 345,
          attackDamage: 64,
          attackSpeed: 0.86,
        },
        {
          level: 6,
          health: 1210,
          healthRegenPer5s: 13,
          resource: 635,
          resourceRegenPer5s: 20,
          armor: 60,
          magicResist: 48,
          moveSpeed: 345,
          attackDamage: 67,
          attackSpeed: 0.88,
        },
        {
          level: 7,
          health: 1314,
          healthRegenPer5s: 14,
          resource: 684,
          resourceRegenPer5s: 21,
          armor: 64,
          magicResist: 50,
          moveSpeed: 345,
          attackDamage: 70,
          attackSpeed: 0.89,
        },
        {
          level: 8,
          health: 1418,
          healthRegenPer5s: 14,
          resource: 733,
          resourceRegenPer5s: 22,
          armor: 68,
          magicResist: 52,
          moveSpeed: 345,
          attackDamage: 73,
          attackSpeed: 0.91,
        },
        {
          level: 9,
          health: 1522,
          healthRegenPer5s: 15,
          resource: 782,
          resourceRegenPer5s: 23,
          armor: 72,
          magicResist: 54,
          moveSpeed: 345,
          attackDamage: 76,
          attackSpeed: 0.92,
        },
        {
          level: 10,
          health: 1626,
          healthRegenPer5s: 16,
          resource: 831,
          resourceRegenPer5s: 24,
          armor: 76,
          magicResist: 56,
          moveSpeed: 345,
          attackDamage: 79,
          attackSpeed: 0.94,
        },
        {
          level: 11,
          health: 1730,
          healthRegenPer5s: 17,
          resource: 880,
          resourceRegenPer5s: 25,
          armor: 80,
          magicResist: 58,
          moveSpeed: 345,
          attackDamage: 82,
          attackSpeed: 0.95,
        },
        {
          level: 12,
          health: 1834,
          healthRegenPer5s: 18,
          resource: 929,
          resourceRegenPer5s: 26,
          armor: 84,
          magicResist: 60,
          moveSpeed: 345,
          attackDamage: 85,
          attackSpeed: 0.97,
        },
        {
          level: 13,
          health: 1938,
          healthRegenPer5s: 19,
          resource: 978,
          resourceRegenPer5s: 27,
          armor: 88,
          magicResist: 62,
          moveSpeed: 345,
          attackDamage: 88,
          attackSpeed: 0.98,
        },
        {
          level: 14,
          health: 2042,
          healthRegenPer5s: 20,
          resource: 1027,
          resourceRegenPer5s: 28,
          armor: 92,
          magicResist: 64,
          moveSpeed: 345,
          attackDamage: 91,
          attackSpeed: 1,
        },
        {
          level: 15,
          health: 2146,
          healthRegenPer5s: 21,
          resource: 1076,
          resourceRegenPer5s: 29,
          armor: 96,
          magicResist: 66,
          moveSpeed: 345,
          attackDamage: 94,
          attackSpeed: 1.01,
        },
      ],
    },
    laneProfile: {
      preferredRoles: [`JUNGLE`, `SUPPORT`],
      tradingPattern: `engage_and_area_control`,
      sustainLevel: `medium`,
      allInThreat: `high`,
      waveClear: `medium`,
      mobility: `low`,
      notes: `Magic damage tank with strong area crowd control, anti-tank magic synergy, and reliable teamfight engage through Bandage Toss and ultimate.`,
    },
    teamProfile: {
      provides: [`ENGAGE`, `CROWD_CONTROL`, `AREA_DAMAGE`, `ANTI_TANK`],
      needs: [`FOLLOW_UP_DAMAGE`, `MAGIC_DAMAGE`],
      weakAgainst: [`KITE`, `DISENGAGE`, `HIGH_MOBILITY`],
    },
    metaScore: null,
  },
  // ANNIE
  {
    championKey: `annie`,
    baseHealth: 600,
    baseResource: 435,
    baseArmor: 34,
    baseMagicResist: 36,
    baseAttackDamage: 52,
    baseAbilityPower: 0,
    attackSpeed: 0.75,
    moveSpeed: 355,
    healthGrowth: 120,
    resourceGrowth: 43,
    armorGrowth: 4,
    magicResistGrowth: 1,
    attackDamageGrowth: 2,
    attackSpeedGrowth: 0,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 600,
          healthRegenPer5s: 8,
          resource: 435,
          resourceRegenPer5s: 12,
          armor: 34,
          magicResist: 36,
          moveSpeed: 355,
          attackDamage: 52,
          attackSpeed: 0.75,
        },
        {
          level: 2,
          health: 720,
          healthRegenPer5s: 8,
          resource: 478,
          resourceRegenPer5s: 13,
          armor: 38,
          magicResist: 37,
          moveSpeed: 355,
          attackDamage: 54,
          attackSpeed: 0.75,
        },
        {
          level: 3,
          health: 840,
          healthRegenPer5s: 8,
          resource: 521,
          resourceRegenPer5s: 14,
          armor: 42,
          magicResist: 38,
          moveSpeed: 355,
          attackDamage: 56,
          attackSpeed: 0.75,
        },
        {
          level: 4,
          health: 960,
          healthRegenPer5s: 8,
          resource: 564,
          resourceRegenPer5s: 15,
          armor: 46,
          magicResist: 39,
          moveSpeed: 355,
          attackDamage: 58,
          attackSpeed: 0.75,
        },
        {
          level: 5,
          health: 1080,
          healthRegenPer5s: 8,
          resource: 607,
          resourceRegenPer5s: 16,
          armor: 50,
          magicResist: 40,
          moveSpeed: 355,
          attackDamage: 60,
          attackSpeed: 0.75,
        },
        {
          level: 6,
          health: 1200,
          healthRegenPer5s: 8,
          resource: 650,
          resourceRegenPer5s: 17,
          armor: 54,
          magicResist: 41,
          moveSpeed: 355,
          attackDamage: 62,
          attackSpeed: 0.75,
        },
        {
          level: 7,
          health: 1320,
          healthRegenPer5s: 8,
          resource: 693,
          resourceRegenPer5s: 18,
          armor: 58,
          magicResist: 42,
          moveSpeed: 355,
          attackDamage: 64,
          attackSpeed: 0.75,
        },
        {
          level: 8,
          health: 1440,
          healthRegenPer5s: 8,
          resource: 736,
          resourceRegenPer5s: 19,
          armor: 62,
          magicResist: 43,
          moveSpeed: 355,
          attackDamage: 66,
          attackSpeed: 0.75,
        },
        {
          level: 9,
          health: 1560,
          healthRegenPer5s: 8,
          resource: 779,
          resourceRegenPer5s: 20,
          armor: 66,
          magicResist: 44,
          moveSpeed: 355,
          attackDamage: 68,
          attackSpeed: 0.75,
        },
        {
          level: 10,
          health: 1680,
          healthRegenPer5s: 8,
          resource: 822,
          resourceRegenPer5s: 21,
          armor: 70,
          magicResist: 45,
          moveSpeed: 355,
          attackDamage: 70,
          attackSpeed: 0.75,
        },
        {
          level: 11,
          health: 1800,
          healthRegenPer5s: 8,
          resource: 865,
          resourceRegenPer5s: 22,
          armor: 74,
          magicResist: 46,
          moveSpeed: 355,
          attackDamage: 72,
          attackSpeed: 0.75,
        },
        {
          level: 12,
          health: 1920,
          healthRegenPer5s: 8,
          resource: 908,
          resourceRegenPer5s: 23,
          armor: 78,
          magicResist: 47,
          moveSpeed: 355,
          attackDamage: 74,
          attackSpeed: 0.75,
        },
        {
          level: 13,
          health: 2040,
          healthRegenPer5s: 8,
          resource: 951,
          resourceRegenPer5s: 24,
          armor: 82,
          magicResist: 48,
          moveSpeed: 355,
          attackDamage: 76,
          attackSpeed: 0.75,
        },
        {
          level: 14,
          health: 2160,
          healthRegenPer5s: 8,
          resource: 994,
          resourceRegenPer5s: 25,
          armor: 86,
          magicResist: 49,
          moveSpeed: 355,
          attackDamage: 78,
          attackSpeed: 0.75,
        },
        {
          level: 15,
          health: 2280,
          healthRegenPer5s: 8,
          resource: 1037,
          resourceRegenPer5s: 26,
          armor: 90,
          magicResist: 50,
          moveSpeed: 355,
          attackDamage: 80,
          attackSpeed: 0.75,
        },
      ],
    },
    laneProfile: {
      preferredRoles: [`MID`, `SUPPORT`],
      tradingPattern: `burst_combo_with_stun_setup`,
      sustainLevel: `low`,
      allInThreat: `high`,
      waveClear: `medium`,
      mobility: `low`,
      notes: `Burst mage with reliable stun setup after 4 ability casts, strong pick potential, and high teamfight threat with Tibbers.`,
    },
    teamProfile: {
      provides: [
        `BURST_DAMAGE`,
        `CROWD_CONTROL`,
        `PICK_POTENTIAL`,
        `TEAMFIGHT`,
      ],
      needs: [`ENGAGE_SETUP`, `POSITIONING`, `COOLDOWN_WINDOW`],
      weakAgainst: [`POKE_COMPOSITION`, `HIGH_MOBILITY`, `LONG_RANGE_CHAMPION`],
    },
    metaScore: null,
  },
  // ASHE
  {
    championKey: `ashe`,
    baseHealth: 630,
    baseResource: 345,
    baseArmor: 35,
    baseMagicResist: 30,
    baseAttackDamage: 58,
    baseAbilityPower: 0,
    attackSpeed: 0.83,
    moveSpeed: 335,
    healthGrowth: 128,
    resourceGrowth: 30,
    armorGrowth: 4,
    magicResistGrowth: 1,
    attackDamageGrowth: 2,
    attackSpeedGrowth: 0.02,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 6,
          resource: 345,
          resourceRegenPer5s: 9,
          armor: 35,
          magicResist: 30,
          moveSpeed: 335,
          attackDamage: 58,
          attackSpeed: 0.83,
        },
        {
          level: 2,
          health: 758,
          healthRegenPer5s: 7,
          resource: 375,
          resourceRegenPer5s: 10,
          armor: 39,
          magicResist: 31,
          moveSpeed: 335,
          attackDamage: 60,
          attackSpeed: 0.85,
        },
        {
          level: 3,
          health: 886,
          healthRegenPer5s: 8,
          resource: 405,
          resourceRegenPer5s: 11,
          armor: 43,
          magicResist: 32,
          moveSpeed: 335,
          attackDamage: 62,
          attackSpeed: 0.87,
        },
        {
          level: 4,
          health: 1014,
          healthRegenPer5s: 9,
          resource: 435,
          resourceRegenPer5s: 12,
          armor: 47,
          magicResist: 33,
          moveSpeed: 335,
          attackDamage: 64,
          attackSpeed: 0.89,
        },
        {
          level: 5,
          health: 1142,
          healthRegenPer5s: 10,
          resource: 465,
          resourceRegenPer5s: 13,
          armor: 51,
          magicResist: 34,
          moveSpeed: 335,
          attackDamage: 66,
          attackSpeed: 0.91,
        },
        {
          level: 6,
          health: 1270,
          healthRegenPer5s: 11,
          resource: 495,
          resourceRegenPer5s: 14,
          armor: 55,
          magicResist: 35,
          moveSpeed: 335,
          attackDamage: 68,
          attackSpeed: 0.93,
        },
        {
          level: 7,
          health: 1398,
          healthRegenPer5s: 12,
          resource: 525,
          resourceRegenPer5s: 15,
          armor: 59,
          magicResist: 36,
          moveSpeed: 335,
          attackDamage: 70,
          attackSpeed: 0.95,
        },
        {
          level: 8,
          health: 1526,
          healthRegenPer5s: 13,
          resource: 555,
          resourceRegenPer5s: 16,
          armor: 63,
          magicResist: 37,
          moveSpeed: 335,
          attackDamage: 72,
          attackSpeed: 0.97,
        },
        {
          level: 9,
          health: 1654,
          healthRegenPer5s: 14,
          resource: 585,
          resourceRegenPer5s: 17,
          armor: 67,
          magicResist: 38,
          moveSpeed: 335,
          attackDamage: 74,
          attackSpeed: 0.99,
        },
        {
          level: 10,
          health: 1782,
          healthRegenPer5s: 15,
          resource: 615,
          resourceRegenPer5s: 18,
          armor: 71,
          magicResist: 39,
          moveSpeed: 335,
          attackDamage: 76,
          attackSpeed: 1.01,
        },
        {
          level: 11,
          health: 1910,
          healthRegenPer5s: 16,
          resource: 645,
          resourceRegenPer5s: 19,
          armor: 75,
          magicResist: 40,
          moveSpeed: 335,
          attackDamage: 78,
          attackSpeed: 1.03,
        },
        {
          level: 12,
          health: 2038,
          healthRegenPer5s: 17,
          resource: 675,
          resourceRegenPer5s: 20,
          armor: 79,
          magicResist: 41,
          moveSpeed: 335,
          attackDamage: 80,
          attackSpeed: 1.05,
        },
        {
          level: 13,
          health: 2166,
          healthRegenPer5s: 18,
          resource: 705,
          resourceRegenPer5s: 21,
          armor: 83,
          magicResist: 42,
          moveSpeed: 335,
          attackDamage: 82,
          attackSpeed: 1.07,
        },
        {
          level: 14,
          health: 2294,
          healthRegenPer5s: 19,
          resource: 735,
          resourceRegenPer5s: 22,
          armor: 87,
          magicResist: 43,
          moveSpeed: 335,
          attackDamage: 84,
          attackSpeed: 1.09,
        },
        {
          level: 15,
          health: 2422,
          healthRegenPer5s: 20,
          resource: 765,
          resourceRegenPer5s: 23,
          armor: 91,
          magicResist: 44,
          moveSpeed: 335,
          attackDamage: 86,
          attackSpeed: 1.11,
        },
      ],
    },
    laneProfile: {
      preferredRoles: [`ADC`, `SUPPORT`],
      tradingPattern: `poke_and_kite`,
      sustainLevel: `low`,
      allInThreat: `medium`,
      waveClear: `medium`,
      mobility: `low`,
      notes: `Utility marksman with constant slows, strong lane poke, global pick threat, and vision control through Hawkshot.`,
    },
    teamProfile: {
      provides: [
        `KITE`,
        `PICK_POTENTIAL`,
        `VISION_CONTROL`,
        `UTILITY_MARKSMAN`,
      ],
      needs: [`PEEL`, `FRONTLINE`, `POSITIONING`],
      weakAgainst: [`DIVE`, `ASSASSIN`, `HIGH_MOBILITY`],
    },
    metaScore: null,
  },
  // AURELION SOL
  {
    championKey: `aurelion-sol`,
    baseHealth: 630,
    baseResource: 435,
    baseArmor: 34,
    baseMagicResist: 36,
    baseAttackDamage: 52,
    baseAbilityPower: 0,
    attackSpeed: 0.75,
    moveSpeed: 345,
    healthGrowth: 128,
    resourceGrowth: 43,
    armorGrowth: 4,
    magicResistGrowth: 1,
    attackDamageGrowth: 2,
    attackSpeedGrowth: 0,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 8,
          resource: 435,
          resourceRegenPer5s: 9,
          armor: 34,
          magicResist: 36,
          moveSpeed: 345,
          attackDamage: 52,
          attackSpeed: 0.75,
        },
        {
          level: 2,
          health: 758,
          healthRegenPer5s: 9,
          resource: 478,
          resourceRegenPer5s: 10,
          armor: 38,
          magicResist: 37,
          moveSpeed: 345,
          attackDamage: 54,
          attackSpeed: 0.75,
        },
        {
          level: 3,
          health: 886,
          healthRegenPer5s: 10,
          resource: 521,
          resourceRegenPer5s: 11,
          armor: 42,
          magicResist: 38,
          moveSpeed: 345,
          attackDamage: 56,
          attackSpeed: 0.75,
        },
        {
          level: 4,
          health: 1014,
          healthRegenPer5s: 11,
          resource: 564,
          resourceRegenPer5s: 12,
          armor: 46,
          magicResist: 39,
          moveSpeed: 345,
          attackDamage: 58,
          attackSpeed: 0.75,
        },
        {
          level: 5,
          health: 1142,
          healthRegenPer5s: 12,
          resource: 607,
          resourceRegenPer5s: 13,
          armor: 50,
          magicResist: 40,
          moveSpeed: 345,
          attackDamage: 60,
          attackSpeed: 0.75,
        },
        {
          level: 6,
          health: 1270,
          healthRegenPer5s: 13,
          resource: 650,
          resourceRegenPer5s: 14,
          armor: 54,
          magicResist: 41,
          moveSpeed: 345,
          attackDamage: 62,
          attackSpeed: 0.75,
        },
        {
          level: 7,
          health: 1398,
          healthRegenPer5s: 14,
          resource: 693,
          resourceRegenPer5s: 15,
          armor: 58,
          magicResist: 42,
          moveSpeed: 345,
          attackDamage: 64,
          attackSpeed: 0.75,
        },
        {
          level: 8,
          health: 1526,
          healthRegenPer5s: 15,
          resource: 736,
          resourceRegenPer5s: 16,
          armor: 62,
          magicResist: 43,
          moveSpeed: 345,
          attackDamage: 66,
          attackSpeed: 0.75,
        },
        {
          level: 9,
          health: 1654,
          healthRegenPer5s: 16,
          resource: 779,
          resourceRegenPer5s: 17,
          armor: 66,
          magicResist: 44,
          moveSpeed: 345,
          attackDamage: 68,
          attackSpeed: 0.75,
        },
        {
          level: 10,
          health: 1782,
          healthRegenPer5s: 17,
          resource: 822,
          resourceRegenPer5s: 18,
          armor: 70,
          magicResist: 45,
          moveSpeed: 345,
          attackDamage: 70,
          attackSpeed: 0.75,
        },
        {
          level: 11,
          health: 1910,
          healthRegenPer5s: 18,
          resource: 865,
          resourceRegenPer5s: 19,
          armor: 74,
          magicResist: 46,
          moveSpeed: 345,
          attackDamage: 72,
          attackSpeed: 0.75,
        },
        {
          level: 12,
          health: 2038,
          healthRegenPer5s: 19,
          resource: 908,
          resourceRegenPer5s: 20,
          armor: 78,
          magicResist: 47,
          moveSpeed: 345,
          attackDamage: 74,
          attackSpeed: 0.75,
        },
        {
          level: 13,
          health: 2166,
          healthRegenPer5s: 20,
          resource: 951,
          resourceRegenPer5s: 21,
          armor: 82,
          magicResist: 48,
          moveSpeed: 345,
          attackDamage: 76,
          attackSpeed: 0.75,
        },
        {
          level: 14,
          health: 2294,
          healthRegenPer5s: 21,
          resource: 994,
          resourceRegenPer5s: 22,
          armor: 86,
          magicResist: 49,
          moveSpeed: 345,
          attackDamage: 78,
          attackSpeed: 0.75,
        },
        {
          level: 15,
          health: 2422,
          healthRegenPer5s: 22,
          resource: 1037,
          resourceRegenPer5s: 23,
          armor: 90,
          magicResist: 50,
          moveSpeed: 345,
          attackDamage: 80,
          attackSpeed: 0.75,
        },
      ],
    },
    laneProfile: {
      preferredRoles: [`MID`],
      tradingPattern: `scaling_zone_control`,
      sustainLevel: `low`,
      allInThreat: `medium`,
      waveClear: `high_after_scaling`,
      mobility: `medium`,
      notes: `Scaling control mage that stacks Stardust to increase ability size, execute threshold, flight range, and max-health damage.`,
    },
    teamProfile: {
      provides: [`SCALING_GAME`, `AREA_DAMAGE`, `ZONE_CONTROL`, `TEAMFIGHT`],
      needs: [`EARLY_GAME_COVER`, `PEEL`, `FRONTLINE`],
      weakAgainst: [`ASSASSIN`, `POINT_AND_CLICK_CC`, `EARLY_GAME_PRESSURE`],
    },
    metaScore: null,
  },
  // AURORA
  {
    championKey: `aurora`,
    baseHealth: 630,
    baseResource: 420,
    baseArmor: 34,
    baseMagicResist: 36,
    baseAttackDamage: 54,
    baseAbilityPower: 0,
    attackSpeed: 0.75,
    moveSpeed: 350,
    healthGrowth: 89,
    resourceGrowth: 37,
    armorGrowth: 4,
    magicResistGrowth: 2,
    attackDamageGrowth: 3,
    attackSpeedGrowth: 0.014,
    scalingProfile: {
      levelStats: [
        {
          level: 1,
          health: 630,
          healthRegenPer5s: 8,
          resource: 420,
          resourceRegenPer5s: 14,
          armor: 34,
          magicResist: 36,
          moveSpeed: 350,
          attackDamage: 54,
          attackSpeed: 0.75,
        },
        {
          level: 2,
          health: 719,
          healthRegenPer5s: 9,
          resource: 457,
          resourceRegenPer5s: 15,
          armor: 38,
          magicResist: 38,
          moveSpeed: 350,
          attackDamage: 57,
          attackSpeed: 0.76,
        },
        {
          level: 3,
          health: 808,
          healthRegenPer5s: 10,
          resource: 494,
          resourceRegenPer5s: 16,
          armor: 42,
          magicResist: 40,
          moveSpeed: 350,
          attackDamage: 60,
          attackSpeed: 0.78,
        },
        {
          level: 4,
          health: 897,
          healthRegenPer5s: 11,
          resource: 531,
          resourceRegenPer5s: 17,
          armor: 46,
          magicResist: 42,
          moveSpeed: 350,
          attackDamage: 63,
          attackSpeed: 0.79,
        },
        {
          level: 5,
          health: 986,
          healthRegenPer5s: 12,
          resource: 568,
          resourceRegenPer5s: 18,
          armor: 50,
          magicResist: 44,
          moveSpeed: 350,
          attackDamage: 66,
          attackSpeed: 0.8,
        },
        {
          level: 6,
          health: 1075,
          healthRegenPer5s: 13,
          resource: 605,
          resourceRegenPer5s: 19,
          armor: 54,
          magicResist: 46,
          moveSpeed: 350,
          attackDamage: 69,
          attackSpeed: 0.82,
        },
        {
          level: 7,
          health: 1164,
          healthRegenPer5s: 14,
          resource: 642,
          resourceRegenPer5s: 20,
          armor: 58,
          magicResist: 48,
          moveSpeed: 350,
          attackDamage: 72,
          attackSpeed: 0.83,
        },
        {
          level: 8,
          health: 1253,
          healthRegenPer5s: 15,
          resource: 679,
          resourceRegenPer5s: 21,
          armor: 62,
          magicResist: 50,
          moveSpeed: 350,
          attackDamage: 75,
          attackSpeed: 0.85,
        },
        {
          level: 9,
          health: 1342,
          healthRegenPer5s: 16,
          resource: 716,
          resourceRegenPer5s: 22,
          armor: 66,
          magicResist: 52,
          moveSpeed: 350,
          attackDamage: 78,
          attackSpeed: 0.86,
        },
        {
          level: 10,
          health: 1431,
          healthRegenPer5s: 17,
          resource: 753,
          resourceRegenPer5s: 23,
          armor: 70,
          magicResist: 54,
          moveSpeed: 350,
          attackDamage: 81,
          attackSpeed: 0.87,
        },
        {
          level: 11,
          health: 1520,
          healthRegenPer5s: 18,
          resource: 790,
          resourceRegenPer5s: 24,
          armor: 74,
          magicResist: 56,
          moveSpeed: 350,
          attackDamage: 84,
          attackSpeed: 0.89,
        },
        {
          level: 12,
          health: 1609,
          healthRegenPer5s: 19,
          resource: 827,
          resourceRegenPer5s: 25,
          armor: 78,
          magicResist: 58,
          moveSpeed: 350,
          attackDamage: 87,
          attackSpeed: 0.9,
        },
        {
          level: 13,
          health: 1698,
          healthRegenPer5s: 20,
          resource: 864,
          resourceRegenPer5s: 26,
          armor: 82,
          magicResist: 60,
          moveSpeed: 350,
          attackDamage: 90,
          attackSpeed: 0.91,
        },
        {
          level: 14,
          health: 1787,
          healthRegenPer5s: 21,
          resource: 901,
          resourceRegenPer5s: 27,
          armor: 86,
          magicResist: 62,
          moveSpeed: 350,
          attackDamage: 93,
          attackSpeed: 0.93,
        },
        {
          level: 15,
          health: 1876,
          healthRegenPer5s: 22,
          resource: 938,
          resourceRegenPer5s: 28,
          armor: 90,
          magicResist: 64,
          moveSpeed: 350,
          attackDamage: 96,
          attackSpeed: 0.94,
        },
      ],
    },
    laneProfile: {
      preferredRoles: [`MID`, `TOP`],
      tradingPattern: `poke_recast_and_mobility_trade`,
      sustainLevel: `medium`,
      allInThreat: `medium`,
      waveClear: `medium`,
      mobility: `high`,
      notes: `Mobile mage skirmisher with curse detonation, percent-health damage, invisibility windows, backward hops, and strong area control with ultimate.`,
    },
    teamProfile: {
      provides: [`ZONE_CONTROL`, `MOBILITY`, `SLOW`, `PERCENT_HEALTH_DAMAGE`],
      needs: [`FRONTLINE`, `ENGAGE_SETUP`, `POSITIONING`],
      weakAgainst: [
        `POINT_AND_CLICK_CC`,
        `BURST_DAMAGE`,
        `LONG_RANGE_CHAMPION`,
      ],
    },
    metaScore: null,
  },
];

export async function seedChampionPatchStats(
  prisma: PrismaClient,
  patchId: string,
) {
  for (const championPatchStatSeed of championPatchStatSeeds) {
    const champion = await prisma.champion.findUnique({
      where: {
        key: championPatchStatSeed.championKey,
      },
    });

    if (!champion || champion.deletedAt) {
      throw new Error(
        `Champion not found or deleted: ${championPatchStatSeed.championKey}`,
      );
    }

    await prisma.championPatchStat.upsert({
      where: {
        championId_patchId: {
          championId: champion.id,
          patchId,
        },
      },
      update: {
        baseHealth: championPatchStatSeed.baseHealth ?? null,
        baseResource: championPatchStatSeed.baseResource ?? null,
        baseArmor: championPatchStatSeed.baseArmor ?? null,
        baseMagicResist: championPatchStatSeed.baseMagicResist ?? null,
        baseAttackDamage: championPatchStatSeed.baseAttackDamage ?? null,
        baseAbilityPower: championPatchStatSeed.baseAbilityPower ?? null,
        attackSpeed: championPatchStatSeed.attackSpeed ?? null,
        moveSpeed: championPatchStatSeed.moveSpeed ?? null,
        healthGrowth: championPatchStatSeed.healthGrowth ?? null,
        resourceGrowth: championPatchStatSeed.resourceGrowth ?? null,
        armorGrowth: championPatchStatSeed.armorGrowth ?? null,
        magicResistGrowth: championPatchStatSeed.magicResistGrowth ?? null,
        attackDamageGrowth: championPatchStatSeed.attackDamageGrowth ?? null,
        attackSpeedGrowth: championPatchStatSeed.attackSpeedGrowth ?? null,
        scalingProfile: championPatchStatSeed.scalingProfile ?? Prisma.DbNull,
        laneProfile: championPatchStatSeed.laneProfile ?? Prisma.DbNull,
        teamProfile: championPatchStatSeed.teamProfile ?? Prisma.DbNull,
        metaScore: championPatchStatSeed.metaScore ?? null,
        deletedAt: null,
      },
      create: {
        championId: champion.id,
        patchId,
        baseHealth: championPatchStatSeed.baseHealth ?? null,
        baseResource: championPatchStatSeed.baseResource ?? null,
        baseArmor: championPatchStatSeed.baseArmor ?? null,
        baseMagicResist: championPatchStatSeed.baseMagicResist ?? null,
        baseAttackDamage: championPatchStatSeed.baseAttackDamage ?? null,
        baseAbilityPower: championPatchStatSeed.baseAbilityPower ?? null,
        attackSpeed: championPatchStatSeed.attackSpeed ?? null,
        moveSpeed: championPatchStatSeed.moveSpeed ?? null,
        healthGrowth: championPatchStatSeed.healthGrowth ?? null,
        resourceGrowth: championPatchStatSeed.resourceGrowth ?? null,
        armorGrowth: championPatchStatSeed.armorGrowth ?? null,
        magicResistGrowth: championPatchStatSeed.magicResistGrowth ?? null,
        attackDamageGrowth: championPatchStatSeed.attackDamageGrowth ?? null,
        attackSpeedGrowth: championPatchStatSeed.attackSpeedGrowth ?? null,
        scalingProfile: championPatchStatSeed.scalingProfile ?? Prisma.DbNull,
        laneProfile: championPatchStatSeed.laneProfile ?? Prisma.DbNull,
        teamProfile: championPatchStatSeed.teamProfile ?? Prisma.DbNull,
        metaScore: championPatchStatSeed.metaScore ?? null,
      },
    });

    console.log(`Seeded champion ${champion.name} for patch ${patchId}`);
  }

  console.log(`SEEDED CHAMPIONS PATCH STATS`);
}
