import { PrismaClient } from '../../src/generated/prisma/client.js';
import { GameTagCategory } from '../../src/generated/prisma/enums.js';

type GameTagSeed = {
  key: string;
  name: string;
  nameVi: string;
  description: string;
  descriptionVi: string;
  category: GameTagCategory;
};

function createTag(
  key: string,
  name: string,
  nameVi: string,
  category: GameTagCategory,
): GameTagSeed {
  return {
    key,
    name,
    nameVi,
    description: `Tag used for ${name.toLowerCase()} classification`,
    descriptionVi: `Tag dùng để phân loại ${nameVi.toLowerCase()}`,
    category,
  };
}

const gameTagSeeds: GameTagSeed[] = [
  // ITEM CATEGORIES
  createTag('LOW_TIER', 'Low Tier', 'Trang bị bậc thấp', GameTagCategory.ITEM),
  createTag(
    'MIDDLE_TIER',
    'Middle Tier',
    'Trang bị bậc trung',
    GameTagCategory.ITEM,
  ),
  createTag('HIGH_TIER', 'High Tier', 'Trang bị bậc cao', GameTagCategory.ITEM),
  createTag(
    'COMPONENT',
    'Component',
    'Trang bị thành phần',
    GameTagCategory.ITEM,
  ),
  createTag('MAGIC', 'Magic', 'Trang bị phép thuật', GameTagCategory.ITEM),
  createTag('SUPPORT', 'Support', 'Trang bị hỗ trợ', GameTagCategory.ITEM),
  createTag(
    'DEFENSIVE',
    'Defensive',
    'Trang bị phòng thủ',
    GameTagCategory.ITEM,
  ),
  createTag('HYBRID', 'Hybrid', 'Trang bị lai', GameTagCategory.ITEM),
  createTag('ON_HIT', 'On Hit', 'Hiệu ứng đòn đánh', GameTagCategory.ITEM),

  // ITEM STATS
  createTag(
    'ABILITY_POWER',
    'Ability Power',
    'Sức mạnh phép thuật',
    GameTagCategory.ITEM,
  ),
  createTag(
    'ATTACK_DAMAGE',
    'Attack Damage',
    'Sức mạnh công kích',
    GameTagCategory.ITEM,
  ),
  createTag('HEALTH', 'Health', 'Máu', GameTagCategory.ITEM),
  createTag('MANA', 'Mana', 'Năng lượng', GameTagCategory.ITEM),
  createTag(
    'ABILITY_HASTE',
    'Ability Haste',
    'Điểm hồi kỹ năng',
    GameTagCategory.ITEM,
  ),
  createTag(
    'ATTACK_SPEED',
    'Attack Speed',
    'Tốc độ đánh',
    GameTagCategory.ITEM,
  ),
  createTag(
    'MAGIC_PENETRATION',
    'Magic Penetration',
    'Xuyên kháng phép',
    GameTagCategory.ITEM,
  ),
  createTag(
    'MOVEMENT_SPEED',
    'Movement Speed',
    'Tốc độ di chuyển',
    GameTagCategory.ITEM,
  ),
  createTag('MAGIC_VAMP', 'Magic Vamp', 'Hút máu phép', GameTagCategory.ITEM),
  createTag('MANA_REGEN', 'Mana Regen', 'Hồi năng lượng', GameTagCategory.ITEM),
  createTag(
    'HEAL_SHIELD_POWER',
    'Heal and Shield Power',
    'Sức mạnh hồi máu và lá chắn',
    GameTagCategory.ITEM,
  ),

  // DAMAGE / SCORING TAGS
  createTag(
    'MAGIC_DAMAGE',
    'Magic Damage',
    'Sát thương phép',
    GameTagCategory.SCORING,
  ),
  createTag(
    'PHYSICAL_DAMAGE',
    'Physical Damage',
    'Sát thương vật lý',
    GameTagCategory.SCORING,
  ),
  createTag(
    'TRUE_DAMAGE',
    'True Damage',
    'Sát thương chuẩn',
    GameTagCategory.SCORING,
  ),
  createTag(
    'HYBRID_DAMAGE',
    'Hybrid Damage',
    'Sát thương lai',
    GameTagCategory.SCORING,
  ),
  createTag(
    'ADAPTIVE_DAMAGE',
    'Adaptive Damage',
    'Sát thương thích ứng',
    GameTagCategory.SCORING,
  ),
  createTag(
    'BURST_DAMAGE',
    'Burst Damage',
    'Sát thương dồn',
    GameTagCategory.SCORING,
  ),
  createTag(
    'SUSTAIN_DAMAGE',
    'Sustained Damage',
    'Sát thương duy trì',
    GameTagCategory.SCORING,
  ),
  createTag(
    'BURN_DAMAGE',
    'Burn Damage',
    'Sát thương đốt',
    GameTagCategory.SCORING,
  ),
  createTag(
    'AREA_DAMAGE',
    'Area Damage',
    'Sát thương diện rộng',
    GameTagCategory.SCORING,
  ),
  createTag(
    'DAMAGE_AMP',
    'Damage Amplification',
    'Khuếch đại sát thương',
    GameTagCategory.SCORING,
  ),
  createTag(
    'MAGIC_RESIST_REDUCTION',
    'Magic Resist Reduction',
    'Giảm kháng phép',
    GameTagCategory.SCORING,
  ),

  // ITEM EFFECT TAGS
  createTag(
    'SCALING_MANA',
    'Mana Scaling',
    'Tăng tiến theo năng lượng',
    GameTagCategory.BUILD,
  ),
  createTag(
    'SCALING_HEALTH',
    'Health Scaling',
    'Tăng tiến theo máu',
    GameTagCategory.BUILD,
  ),
  createTag('SNOWBALL', 'Snowball', 'Lăn cầu tuyết', GameTagCategory.BUILD),
  createTag('SPELLBLADE', 'Spellblade', 'Kiếm phép', GameTagCategory.BUILD),
  createTag(
    'ULTIMATE_HASTE',
    'Ultimate Haste',
    'Hồi chiêu cuối',
    GameTagCategory.BUILD,
  ),
  createTag(
    'SPELL_SHIELD',
    'Spell Shield',
    'Khiên phép',
    GameTagCategory.BUILD,
  ),
  createTag('EXECUTE', 'Execute', 'Kết liễu', GameTagCategory.BUILD),
  createTag('REVEAL', 'Reveal', 'Lộ diện', GameTagCategory.BUILD),
  createTag('SLOW', 'Slow', 'Làm chậm', GameTagCategory.BUILD),
  createTag('SUSTAIN', 'Sustain', 'Hồi phục duy trì', GameTagCategory.BUILD),
  createTag('KITE', 'Kite', 'Thả diều', GameTagCategory.BUILD),

  // COUNTER TAGS
  createTag(
    'ANTI_TANK',
    'Anti Tank',
    'Chống chống chịu',
    GameTagCategory.COUNTER,
  ),
  createTag('ANTI_HEAL', 'Anti Heal', 'Giảm hồi máu', GameTagCategory.COUNTER),
  createTag(
    'ANTI_SHIELD',
    'Anti Shield',
    'Chống lá chắn',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'ANTI_BURST',
    'Anti Burst',
    'Chống dồn sát thương',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'ANTI_ATTACK_SPEED',
    'Anti Attack Speed',
    'Khắc chế tốc độ đánh',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'PERCENT_HEALTH_DAMAGE',
    'Percent Health Damage',
    'Sát thương theo phần trăm máu',
    GameTagCategory.COUNTER,
  ),

  // MATCHUP / ENEMY TEAM TAGS
  createTag('TANK', 'Tank', 'Chống chịu', GameTagCategory.MATCHUP),
  createTag('HIGH_HEALTH', 'High Health', 'Nhiều máu', GameTagCategory.MATCHUP),
  createTag('FRONTLINE', 'Frontline', 'Tuyến trước', GameTagCategory.MATCHUP),
  createTag(
    'SQUISHY_CHAMPION',
    'Squishy Champion',
    'Tướng mỏng',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_HEALTH_TARGET',
    'Low Health Target',
    'Mục tiêu thấp máu',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_MAGIC_RESIST',
    'Low Magic Resist',
    'Ít kháng phép',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'HIGH_MAGIC_RESIST',
    'High Magic Resist',
    'Nhiều kháng phép',
    GameTagCategory.MATCHUP,
  ),
  createTag('HEALING', 'Healing', 'Hồi máu', GameTagCategory.MATCHUP),
  createTag('ENCHANTER', 'Enchanter', 'Hỗ trợ buff', GameTagCategory.MATCHUP),
  createTag('SHIELDING', 'Shielding', 'Tạo lá chắn', GameTagCategory.MATCHUP),
  createTag(
    'NO_HEALING_TEAM',
    'No Healing Team',
    'Đội hình không hồi máu',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'NO_SHIELD_TEAM',
    'No Shield Team',
    'Đội hình không lá chắn',
    GameTagCategory.MATCHUP,
  ),
  createTag('ASSASSIN', 'Assassin', 'Sát thủ', GameTagCategory.MATCHUP),
  createTag('BRUISER', 'Bruiser', 'Đấu sĩ', GameTagCategory.MATCHUP),
  createTag('ENGAGE', 'Engage', 'Mở giao tranh', GameTagCategory.MATCHUP),
  createTag(
    'DISENGAGE',
    'Disengage',
    'Thoát giao tranh',
    GameTagCategory.MATCHUP,
  ),
  createTag('DIVE', 'Dive', 'Lao vào', GameTagCategory.MATCHUP),
  createTag(
    'MELEE_CHAMPION',
    'Melee Champion',
    'Tướng cận chiến',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_RANGE_CHAMPION',
    'Low Range Champion',
    'Tướng tầm đánh ngắn',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LONG_RANGE_CHAMPION',
    'Long Range Champion',
    'Tướng tầm xa',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'HIGH_MOBILITY',
    'High Mobility',
    'Độ cơ động cao',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'POINT_AND_CLICK_CC',
    'Point and Click CC',
    'Khống chế chỉ định',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_CC',
    'Low Crowd Control',
    'Ít khống chế',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_BURST',
    'Low Burst',
    'Ít sát thương dồn',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'PICK_COMPOSITION',
    'Pick Composition',
    'Đội hình bắt lẻ',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'POKE_COMPOSITION',
    'Poke Composition',
    'Đội hình cấu rỉa',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'GROUPED_ENEMIES',
    'Grouped Enemies',
    'Kẻ địch đứng gần nhau',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'FOG_OF_WAR',
    'Fog of War',
    'Tầm nhìn khuất',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'MELEE_TRADING',
    'Melee Trading',
    'Trao đổi chiêu cận chiến',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_COOLDOWN_HARASS',
    'Low Cooldown Harass',
    'Cấu rỉa hồi chiêu thấp',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_ULTIMATE_VALUE',
    'Low Ultimate Value',
    'Giá trị chiêu cuối thấp',
    GameTagCategory.MATCHUP,
  ),

  // GAME PLAN / CONTEXT TAGS
  createTag(
    `FORM_SELECTION`,
    `Form selection`,
    `Chọn dạng biến đổi`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `INVULNERABILITY`,
    `Invulnerability`,
    `Bất tử`,
    GameTagCategory.TEAM_COMP,
  ),

  createTag(
    `TEAMFIGHT_CLEANUP`,
    `Teamfight cleanup`,
    `Dọn giao tranh`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `CROWD_CONTROL_SETUP`,
    `Crowd control setup`,
    `Thiết lập khống chế`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `RESET_WINDOW`,
    `Reset window`,
    `Cửa sổ hồi chiêu theo hạ gục`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `OATHSWORN_SETUP`,
    `Oathsworn setup`,
    `Thiết lập Thệ Ước`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `PLASMA_SETUP`,
    `Plasma setup`,
    `Thiết lập Plasma`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LONG_FIGHT',
    'Long Fight',
    'Giao tranh dài',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'EXTENDED_FIGHT',
    'Extended Fight',
    'Giao tranh kéo dài',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'TEAMFIGHT',
    'Teamfight',
    'Giao tranh tổng',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'SCALING_GAME',
    'Scaling Game',
    'Trận đấu kéo dài',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'SNOWBALL_GAME',
    'Snowball Game',
    'Trận đấu lăn cầu tuyết',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'FAST_SNOWBALL',
    'Fast Snowball',
    'Lăn cầu tuyết nhanh',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'FOLLOW_UP_DAMAGE',
    'Follow Up Damage',
    'Sát thương theo sau mở giao tranh',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LANE_PARTNER_DAMAGE',
    'Lane Partner Damage',
    'Sát thương từ đồng đội đi đường',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'EARLY_GAME_PRESSURE',
    'Early Game Pressure',
    'Áp lực đầu trận',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'EARLY_BURST',
    'Early Burst',
    'Dồn sát thương sớm',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LOW_DURABILITY_TEAM',
    'Low Durability Team',
    'Đội hình mỏng',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LOW_KILL_PRESSURE',
    'Low Kill Pressure',
    'Ít áp lực hạ gục',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'MIXED_DAMAGE',
    'Mixed Damage',
    'Sát thương hỗn hợp',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'SUSTAIN_TEAM',
    'Sustain Team',
    'Đội hình hồi phục',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'TEAM_COORDINATION',
    'Team Coordination',
    'Cần phối hợp đội',
    GameTagCategory.TEAM_COMP,
  ),

  // SPELL / SUMMONER SPELL TAGS
  createTag('CHASE', 'Chase', 'Truy đuổi', GameTagCategory.SPELL),
  createTag('ESCAPE', 'Escape', 'Thoát thân', GameTagCategory.SPELL),
  createTag('UTILITY', 'Utility', 'Đa dụng', GameTagCategory.SPELL),
  createTag('SHIELD', 'Shield', 'Lá chắn', GameTagCategory.SPELL),
  createTag('DEFENSE', 'Defense', 'Phòng thủ', GameTagCategory.SPELL),
  createTag('CLEANSE', 'Cleanse', 'Thanh tẩy', GameTagCategory.SPELL),
  createTag('JUNGLE', 'Jungle', 'Đi rừng', GameTagCategory.SPELL),
  createTag('PLAYMAKING', 'Playmaking', 'Tạo đột biến', GameTagCategory.SPELL),

  createTag('ROAMING', 'Roaming', 'Đảo đường', GameTagCategory.TEAM_COMP),
  createTag('DUO_LANE', 'Duo Lane', 'Đường đôi', GameTagCategory.TEAM_COMP),
  createTag(
    'SURVIVABILITY',
    'Survivability',
    'Khả năng sống sót',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'TEAM_SUPPORT',
    'Team Support',
    'Hỗ trợ đồng đội',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LANE_SURVIVAL',
    'Lane Survival',
    'Sống sót khi đi đường',
    GameTagCategory.TEAM_COMP,
  ),
  createTag('PEEL', 'Peel', 'Bảo kê', GameTagCategory.TEAM_COMP),
  createTag(
    'KILL_PRESSURE',
    'Kill Pressure',
    'Áp lực hạ gục',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LANE_KILL_PRESSURE',
    'Lane Kill Pressure',
    'Áp lực hạ gục khi đi đường',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'OBJECTIVE_CONTROL',
    'Objective Control',
    'Kiểm soát mục tiêu',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'JUNGLE_CLEAR',
    'Jungle Clear',
    'Dọn rừng',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'NON_JUNGLE_ROLE',
    'Non Jungle Role',
    'Không phải vai trò đi rừng',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'MAP_PRESSURE',
    'Map Pressure',
    'Áp lực bản đồ',
    GameTagCategory.TEAM_COMP,
  ),
  createTag('MACRO', 'Macro', 'Tư duy bản đồ', GameTagCategory.TEAM_COMP),
  createTag('SIDE_LANE', 'Side Lane', 'Đường cánh', GameTagCategory.TEAM_COMP),
  createTag(
    'EARLY_COMBAT',
    'Early Combat',
    'Giao tranh sớm',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'DAMAGE_REDUCTION',
    'Damage Reduction',
    'Giảm sát thương',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'ANTI_ASSASSIN',
    'Anti Assassin',
    'Khắc chế sát thủ',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'ANTI_CC',
    'Anti Crowd Control',
    'Chống khống chế',
    GameTagCategory.COUNTER,
  ),

  createTag(
    'LONG_RANGE_POKE',
    'Long Range Poke',
    'Cấu rỉa tầm xa',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'CROWD_CONTROL',
    'Crowd Control',
    'Khống chế',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LONG_RANGE_SAFE_PLAY',
    'Long Range Safe Play',
    'Chơi an toàn tầm xa',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'EPIC_MONSTER',
    'Epic Monster',
    'Quái khủng',
    GameTagCategory.MATCHUP,
  ),

  createTag(
    'RAW_DAMAGE',
    'Raw Damage',
    'Sát thương thuần',
    GameTagCategory.SCORING,
  ),

  // CHAMPION CLASS TAGS
  createTag(
    `JUGGERNAUT`,
    `Juggernaut`,
    `Đấu sĩ chống chịu kém cơ động`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `VANGUARD`,
    `Vanguard`,
    `Tiên phong mở giao tranh`,
    GameTagCategory.CHAMPION,
  ),
  createTag('MAGE', 'Mage', 'Pháp sư', GameTagCategory.CHAMPION),
  createTag('FIGHTER', 'Fighter', 'Đấu sĩ', GameTagCategory.CHAMPION),
  createTag(
    'SKIRMISHER',
    'Skirmisher',
    'Đấu sĩ cơ động',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'CONTROL_MAGE',
    'Control Mage',
    'Pháp sư kiểm soát',
    GameTagCategory.CHAMPION,
  ),
  createTag('MARKSMAN', 'Marksman', 'Xạ thủ', GameTagCategory.CHAMPION),

  // CHAMPION PLAYSTYLE TAGS
  createTag(
    `FALLS_OFF_LATE`,
    `Falls off late`,
    `Yếu dần về cuối trận`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `ARTILLERY`,
    `Artillery`,
    `Pháo kích tầm xa`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    `STACKING_RELIANT`,
    `Stacking reliant`,
    `Phụ thuộc cộng dồn`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    `ISOLATION_RELIANT`,
    `Isolation reliant`,
    `Phụ thuộc mục tiêu cô lập`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    `FORM_CHANGE`,
    `Form change`,
    `Biến đổi dạng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `HYPERCARRY`,
    `Hypercarry`,
    `Chủ lực siêu cuối trận`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `RESET_CHAMPION`,
    `Reset champion`,
    `Tướng hồi chiêu theo hạ gục`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `ANTI_MAGE`,
    `Anti-mage`,
    `Khắc chế pháp sư`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`FORM_SWAP`, `Form Swap`, `Chuyển dạng`, GameTagCategory.PLAYSTYLE),
  createTag(
    `LANE_PRESSURE`,
    `Lane Pressure`,
    `Áp lực đi đường`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(`ANTI_DIVE`, `Anti-Dive`, `Chống lao vào`, GameTagCategory.COUNTER),
  createTag(
    `TRANSFORMATION_RELIANT`,
    `Transformation Reliant`,
    `Phụ thuộc biến hình`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    `TIMING_RELIANT`,
    `Timing Reliant`,
    `Phụ thuộc căn thời điểm`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(`DUELIST`, `Duelist`, `Đấu sĩ tay đôi`, GameTagCategory.PLAYSTYLE),
  createTag(
    `THREE_HIT_PASSIVE`,
    `Three-Hit Passive`,
    `Nội tại ba đòn`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag('BURST', 'Burst', 'Dồn sát thương', GameTagCategory.PLAYSTYLE),
  createTag('PICK', 'Pick', 'Bắt lẻ', GameTagCategory.PLAYSTYLE),
  createTag('MOBILITY', 'Mobility', 'Cơ động', GameTagCategory.PLAYSTYLE),
  createTag(
    'DPS',
    'DPS',
    'Sát thương theo thời gian',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'SCALING',
    'Scaling',
    'Tăng tiến sức mạnh',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag('POKE', 'Poke', 'Cấu rỉa', GameTagCategory.PLAYSTYLE),
  createTag(
    'ZONE_CONTROL',
    'Zone Control',
    'Kiểm soát khu vực',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'ON_HIT_CHAMPION',
    'On Hit Champion',
    'Tướng đánh theo hiệu ứng đòn đánh',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'AUTO_ATTACK_CHAMPION',
    'Auto Attack Champion',
    'Tướng đánh thường nhiều',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'SPELLBLADE_CHAMPION',
    'Spellblade Champion',
    'Tướng tận dụng Kiếm Phép',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'ABILITY_RELIANT_CHAMPION',
    'Ability Reliant Champion',
    'Tướng phụ thuộc kỹ năng',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'MANA_HUNGRY_CHAMPION',
    'Mana Hungry Champion',
    'Tướng tốn nhiều năng lượng',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    `ENERGY_RELIANT`,
    `Energy reliant`,
    `Phụ thuộc nội năng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'ULTIMATE_RELIANT_CHAMPION',
    'Ultimate Reliant Champion',
    'Tướng phụ thuộc chiêu cuối',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'EXTENDED_FIGHT_CHAMPION',
    'Extended Fight Champion',
    'Tướng mạnh trong giao tranh kéo dài',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'UTILITY_MARKSMAN',
    'Utility Marksman',
    'Xạ thủ thiên về tiện ích',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'VISION_CONTROL',
    'Vision Control',
    'Kiểm soát tầm nhìn',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'SKIRMISH',
    'Skirmish',
    'Giao tranh nhỏ lẻ',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(`SPLIT_PUSH`, `Split Push`, `Đẩy Lẻ`, GameTagCategory.PLAYSTYLE),
  createTag(
    `DRAIN_TANK`,
    `Drain Tank`,
    `Đấu Sĩ Hồi Phục`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(`ADORATION`, `Adoration`, `Ngưỡng Mộ`, GameTagCategory.PLAYSTYLE),
  createTag(
    `BONUS_GOLD`,
    `Bonus Gold`,
    `Vàng thưởng`,
    GameTagCategory.PLAYSTYLE,
  ),

  // CHAMPION UTILITY TAGS
  createTag(`POLYMORPH`, `Polymorph`, `Biến hóa`, GameTagCategory.CHAMPION),
  createTag(`SLEEP`, `Sleep`, `Ngủ`, GameTagCategory.CHAMPION),
  createTag(
    `UNTARGETABLE`,
    `Untargetable`,
    `Không thể bị chọn làm mục tiêu`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `TERRAIN_WALK`,
    `Terrain walk`,
    `Đi xuyên địa hình`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `VISION_DENIAL`,
    `Vision Denial`,
    `Che khuất tầm nhìn`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`TAUNT`, `Taunt`, `Khiêu khích`, GameTagCategory.CHAMPION),
  createTag(`FEAR`, `Fear`, `Hoảng sợ`, GameTagCategory.CHAMPION),
  createTag(
    `COOLDOWN_REDUCTION`,
    `Cooldown Reduction`,
    `Giảm hồi chiêu`,
    GameTagCategory.CHAMPION,
  ),
  createTag('CHARM', 'Charm', 'Hôn gió', GameTagCategory.CHAMPION),
  createTag('DASH', 'Dash', 'Lướt', GameTagCategory.CHAMPION),
  createTag('KNOCK_UP', 'Knock Up', 'Hất tung', GameTagCategory.CHAMPION),
  createTag('WIND_WALL', 'Wind Wall', 'Tường gió', GameTagCategory.CHAMPION),
  createTag('REVIVE', 'Revive', 'Hồi sinh đồng minh', GameTagCategory.CHAMPION),

  // CHAMPION RISK TAGS
  createTag(`IMMOBILE`, `Immobile`, `Kém cơ động`, GameTagCategory.CHAMPION),
  createTag(
    `MELEE_RANGE`,
    `Melee range`,
    `Tầm đánh cận chiến`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `FORM_RELIANT`,
    `Form reliant`,
    `Phụ thuộc dạng biến đổi`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `SCALING_RELIANT`,
    `Scaling reliant`,
    `Phụ thuộc tăng tiến sức mạnh`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `RESET_RELIANT`,
    `Reset reliant`,
    `Phụ thuộc hồi chiêu theo hạ gục`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `MANA_RELIANT`,
    `Mana reliant`,
    `Phụ thuộc năng lượng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `OATHSWORN_RELIANT`,
    `Oathsworn reliant`,
    `Phụ thuộc Thệ Ước`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `SHORT_RANGE_MARKSMAN`,
    `Short-range marksman`,
    `Xạ thủ tầm ngắn`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `RELOAD_RELIANT`,
    `Reload Reliant`,
    `Phụ thuộc nạp đạn`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `FORM_DEPENDENT`,
    `Form Dependent`,
    `Phụ thuộc dạng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `COMMIT_HEAVY`,
    `Commit Heavy`,
    `Dễ phải lao vào sâu`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'SKILLSHOT_RELIANT',
    'Skillshot Reliant',
    'Phụ thuộc kỹ năng định hướng',
    GameTagCategory.CHAMPION,
  ),
  createTag('SQUISHY', 'Squishy', 'Mỏng máu', GameTagCategory.CHAMPION),
  createTag(
    'MELEE_MID',
    'Melee Mid',
    'Đường giữa cận chiến',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'HIGH_EXECUTION',
    'High Execution',
    'Yêu cầu kỹ năng cao',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'CC_VULNERABLE',
    'CC Vulnerable',
    'Dễ bị khống chế',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'LOW_MOBILITY',
    'Low Mobility',
    'Kém cơ động',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'POSITIONING_RELIANT',
    'Positioning Reliant',
    'Phụ thuộc vị trí đứng',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'WEAK_EARLY_GAME',
    'Weak Early Game',
    'Yếu đầu trận',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'INTERRUPT_VULNERABLE',
    'Interrupt Vulnerable',
    'Dễ bị ngắt kỹ năng',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'SHORT_RANGE_MAGE',
    'Short Range Mage',
    'Pháp sư tầm ngắn',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'FLASH_RELIANT',
    'Flash Reliant',
    'Phụ thuộc Tốc Biến',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'COOLDOWN_RELIANT',
    'Cooldown Reliant',
    'Phụ thuộc hồi chiêu',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'PUNISHABLE_WHEN_MISSED',
    'Punishable When Missed',
    'Dễ bị trừng phạt khi dùng hụt',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'MISS_DEPENDENT',
    'Miss Dependent',
    'Phụ thuộc dùng trúng kỹ năng',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `TEAM_DEPENDENT`,
    `Team Dependent`,
    `Phụ Thuộc Đồng Đội`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `LOW_DAMAGE`,
    `Low Damage`,
    `Ít Sát Thương`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`KITEABLE`, `Kiteable`, `Dễ Bị Thả Diều`, GameTagCategory.CHAMPION),
  createTag(
    `ANTI_HEAL_VULNERABLE`,
    `Anti-heal Vulnerable`,
    `Yếu Trước Giảm Hồi Máu`,
    GameTagCategory.CHAMPION,
  ),

  // CHAMPION STRENGTH / WEAKNESS TAGS
  createTag(
    `HIGH_RANGE_CHAMPION`,
    `High-range champion`,
    `Tướng tầm đánh xa`,
    GameTagCategory.MATCHUP,
  ),
  createTag(
    `LOCKDOWN`,
    `Lockdown`,
    `Khống chế khóa mục tiêu`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `STACKING_RANGE`,
    `Stacking range`,
    `Tăng tầm đánh theo cộng dồn`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `ISOLATED_TARGET`,
    `Isolated target`,
    `Mục tiêu cô lập`,
    GameTagCategory.MATCHUP,
  ),
  createTag(
    `ANTI_MAGIC`,
    `Anti-magic`,
    `Chống sát thương phép`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `RESET_CARRY`,
    `Reset Carry`,
    `Chủ lực snowball theo hạ gục`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `SAFE_POSITIONING`,
    `Safe Positioning`,
    `Giữ vị trí an toàn`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `POKE_SETUP`,
    `Poke Setup`,
    `Thiết lập cấu rỉa`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `HARD_ENGAGE`,
    `Hard Engage`,
    `Mở giao tranh mạnh`,
    GameTagCategory.MATCHUP,
  ),
  createTag(
    `TERRAIN_CONTROL`,
    `Terrain Control`,
    `Kiểm soát địa hình`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `ARMOR_REDUCTION`,
    `Armor Reduction`,
    `Giảm giáp`,
    GameTagCategory.SCORING,
  ),
  createTag(
    `COOLDOWN_MANAGEMENT`,
    `Cooldown Management`,
    `Quản lý hồi chiêu`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `RAGE_MANAGEMENT`,
    `Rage Management`,
    `Quản lý Cuồng Nộ`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`TOWER_DIVE`, `Tower Dive`, `Băng trụ`, GameTagCategory.CHAMPION),
  createTag(`DUELING`, `Dueling`, `Đấu tay đôi`, GameTagCategory.CHAMPION),
  createTag(
    `AREA_CC`,
    `Area Crowd Control`,
    `Khống chế diện rộng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `FLANK_ANGLE`,
    `Flank Angle`,
    `Góc đánh bọc hậu`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`INTERRUPT`, `Interrupt`, `Ngắt kỹ năng`, GameTagCategory.CHAMPION),
  createTag(
    `SKILL_SHOT_ACCURACY`,
    `Skill Shot Accuracy`,
    `Độ chính xác kỹ năng định hướng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'PICK_POTENTIAL',
    'Pick Potential',
    'Khả năng bắt lẻ',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'SCALING_DAMAGE',
    'Scaling Damage',
    'Sát thương tăng tiến',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'TEAMFIGHT_FOLLOWUP',
    'Teamfight Follow Up',
    'Theo giao tranh tốt',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'WAVE_CLEAR',
    'Wave Clear',
    'Dọn lính nhanh',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'WEAK_WHEN_BEHIND',
    'Weak When Behind',
    'Yếu khi bị thọt',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'HARD_TO_PLAY',
    'Hard To Play',
    'Khó chơi',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'WEAK_INTO_POINT_CLICK_CC',
    'Weak Into Point Click CC',
    'Yếu trước khống chế chỉ định',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'VULNERABLE_TO_DIVE',
    'Vulnerable To Dive',
    'Dễ bị lao vào',
    GameTagCategory.CHAMPION,
  ),

  // SKILL TAGS
  createTag(
    `OVERHEAL_SHIELD`,
    `Overheal shield`,
    `Lá chắn từ hồi máu vượt mức`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ANTI_MARKSMAN`,
    `Anti marksman`,
    `Khắc chế xạ thủ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DAMAGE_STORAGE`,
    `Damage storage`,
    `Tích trữ sát thương`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DEATH_REALM`,
    `Death Realm`,
    `Vương Quốc Tử Vong`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STAT_STEAL`,
    `Stat steal`,
    `Đánh cắp chỉ số`,
    GameTagCategory.SKILL,
  ),
  createTag(`OVERWHELM`, `Overwhelm`, `Áp Đảo`, GameTagCategory.SKILL),
  createTag(
    `PROJECTILE_REFLECTION`,
    `Projectile reflection`,
    `Phản lại đường đạn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LINGERING_ZONE`,
    `Lingering zone`,
    `Vùng hiệu ứng kéo dài`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ARMOR_SCALING`,
    `Armor scaling`,
    `Tỉ lệ theo Giáp`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TRUE_SIGHT`,
    `True sight`,
    `Tầm nhìn chuẩn`,
    GameTagCategory.SKILL,
  ),
  createTag(`ENLARGE`, `Enlarge`, `Phóng to`, GameTagCategory.SKILL),
  createTag(
    `ALLY_BUFF_SYNERGY`,
    `Ally buff synergy`,
    `Tương tác cường hóa từ đồng minh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `IMMOBILIZE_SYNERGY`,
    `Immobilize synergy`,
    `Tương tác bất động`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LINE_DAMAGE`,
    `Line damage`,
    `Sát thương đường thẳng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SPELL_WEAVING`,
    `Spell weaving`,
    `Đan xen kỹ năng và đòn đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(`REPOSITION`, `Reposition`, `Tái định vị`, GameTagCategory.SKILL),
  createTag(
    `DIRECTIONAL_FIRE`,
    `Directional fire`,
    `Bắn theo hướng chỉ định`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DEATH_TRIGGER`,
    `Death trigger`,
    `Kích hoạt khi chết`,
    GameTagCategory.SKILL,
  ),
  createTag(`ICE_SHARD`, `Ice Shard`, `Mảnh Băng`, GameTagCategory.SKILL),
  createTag(
    `SELF_CENTERED_AREA`,
    `Self-centered area`,
    `Vùng quanh bản thân`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TELEPORT`,
    `Teleport`,
    `Dịch chuyển tức thời`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SELF_CAST`,
    `Self-cast`,
    `Tự dùng lên bản thân`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TARGETED_STUN`,
    `Targeted stun`,
    `Làm choáng chỉ định`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MISSING_HEALTH_HEAL`,
    `Missing Health heal`,
    `Hồi máu theo Máu đã mất`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `AREA_SLOW`,
    `Area slow`,
    `Làm chậm diện rộng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `JUNGLE_SUSTAIN`,
    `Jungle sustain`,
    `Hồi phục khi đi rừng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MOVEMENT_SPEED_STACKS`,
    `Movement Speed stacks`,
    `Cộng dồn Tốc Độ Di Chuyển`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MONSTER_DAMAGE_BONUS`,
    `Monster damage bonus`,
    `Tăng sát thương lên quái`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CENTER_BONUS_DAMAGE`,
    `Center bonus damage`,
    `Tăng sát thương vùng trung tâm`,
    GameTagCategory.SKILL,
  ),
  createTag(`DROWSY`, `Drowsy`, `Lơ Mơ`, GameTagCategory.SKILL),
  createTag(
    `GLOBAL_CC`,
    `Global crowd control`,
    `Khống chế toàn bản đồ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TEAMFIGHT_SETUP`,
    `Teamfight setup`,
    `Mở giao tranh tổng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BONUS_MAGIC_DAMAGE`,
    `Bonus magic damage`,
    `Sát thương phép cộng thêm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BONUS_MAGIC_RESIST`,
    `Bonus Magic Resist`,
    `Tăng Kháng Phép`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DAMAGE_RESISTANCE`,
    `Damage resistance`,
    `Chống chịu sát thương`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DEFENSIVE_STEROID`,
    `Defensive steroid`,
    `Cường hóa phòng thủ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CENTER_STUN`,
    `Center stun`,
    `Làm choáng vùng trung tâm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DECAYING_SLOW`,
    `Decaying slow`,
    `Làm chậm giảm dần`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `COLLISION_DAMAGE`,
    `Collision damage`,
    `Sát thương va chạm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DISPLACEMENT`,
    `Displacement`,
    `Dịch chuyển vị trí mục tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `AFTER_DEATH_EFFECT`,
    `After-death effect`,
    `Hiệu ứng sau khi chết`,
    GameTagCategory.SKILL,
  ),
  createTag(`EXPLOSION`, `Explosion`, `Phát nổ`, GameTagCategory.SKILL),
  createTag(
    `RESIST_SHRED`,
    `Resist shred`,
    `Giảm chống chịu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ATTACK_RANGE_BUFF`,
    `Attack range buff`,
    `Tăng tầm đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TRAIL_ZONE`,
    `Trail zone`,
    `Vùng vệt kéo dài`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `AREA_REVEAL`,
    `Area reveal`,
    `Lộ diện khu vực`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MANA_COST_RAMP`,
    `Mana cost ramp`,
    `Tăng tiêu hao năng lượng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ABILITY_SCALING_STACKS`,
    `Ability scaling stacks`,
    `Cộng dồn tăng sức mạnh kỹ năng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MULTI_TARGET`,
    `Multi-target`,
    `Đa mục tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MARK_SCALING`,
    `Mark scaling`,
    `Tăng sức mạnh theo dấu ấn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MONSTER_DAMAGE_CAP`,
    `Monster damage cap`,
    `Giới hạn sát thương lên quái`,
    GameTagCategory.SKILL,
  ),
  createTag(`THIRD_HIT`, `Third hit`, `Đòn đánh thứ ba`, GameTagCategory.SKILL),
  createTag(
    `LOW_HEALTH_EXECUTE`,
    `Low-health execute`,
    `Kết liễu mục tiêu thấp máu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CANNOT_DIE_ZONE`,
    `Cannot-die zone`,
    `Vùng không thể bị hạ gục`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `AREA_PROTECTION`,
    `Area protection`,
    `Bảo vệ diện rộng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ANTI_EXECUTE`,
    `Anti-execute`,
    `Chống kết liễu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STEALTH_SYNERGY`,
    `Stealth synergy`,
    `Tương tác tàng hình`,
    GameTagCategory.SKILL,
  ),
  createTag(`ISOLATION`, `Isolation`, `Cô lập`, GameTagCategory.SKILL),
  createTag(
    `COOLDOWN_REFUND`,
    `Cooldown refund`,
    `Hoàn lại hồi chiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SINGLE_TARGET_BURST`,
    `Single-target burst`,
    `Dồn sát thương đơn mục tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LINE_SKILLSHOT`,
    `Line skillshot`,
    `Kỹ năng định hướng đường thẳng`,
    GameTagCategory.SKILL,
  ),
  createTag(`SELF_HEAL`, `Self heal`, `Tự hồi máu`, GameTagCategory.SKILL),
  createTag(`LEAP`, `Leap`, `Nhảy`, GameTagCategory.SKILL),
  createTag(
    `TAKEDOWN_RESET`,
    `Takedown reset`,
    `Hồi lại khi tham gia hạ gục`,
    GameTagCategory.SKILL,
  ),
  createTag(`INVISIBILITY`, `Invisibility`, `Vô hình`, GameTagCategory.SKILL),
  createTag(
    `OUT_OF_COMBAT_BURST`,
    `Out-of-combat burst`,
    `Dồn sát thương sau khi rời giao tranh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DOUBLE_HIT`,
    `Double hit`,
    `Hai lần gây sát thương`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LINE_ATTACK`,
    `Line attack`,
    `Đòn đánh theo đường thẳng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SLOW_IMMUNITY`,
    `Slow immunity`,
    `Miễn nhiễm làm chậm`,
    GameTagCategory.SKILL,
  ),
  createTag(`INFEST`, `Infest`, `Nhập vào mục tiêu`, GameTagCategory.SKILL),
  createTag(
    `LEVEL_SCALING`,
    `Level scaling`,
    `Tăng tiến theo cấp`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `RANGE_SCALING`,
    `Range scaling`,
    `Tăng tầm đánh theo cấp`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `RESISTANCE_REDUCTION`,
    `Resistance reduction`,
    `Giảm chống chịu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `AOE_ON_HIT`,
    `AoE on-hit`,
    `Đòn đánh lan diện rộng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_PROTECTION`,
    `Ally protection`,
    `Bảo vệ đồng minh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `COOLDOWN_RESET`,
    `Cooldown reset`,
    `Làm mới hồi chiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `GRIEVOUS_WOUNDS`,
    `Grievous Wounds`,
    `Vết Thương Sâu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SELF_SHIELD`,
    `Self shield`,
    `Tự tạo lá chắn`,
    GameTagCategory.SKILL,
  ),
  createTag(`BLINK`, `Blink`, `Dịch chuyển tức thời`, GameTagCategory.SKILL),
  createTag(
    `MANA_SCALING`,
    `Mana scaling`,
    `Tỉ lệ theo năng lượng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STACKING_DAMAGE`,
    `Stacking damage`,
    `Sát thương cộng dồn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `EMPOWERED_ABILITY`,
    `Empowered ability`,
    `Kỹ năng cường hóa`,
    GameTagCategory.SKILL,
  ),
  createTag(`TETHER`, `Tether`, `Liên kết`, GameTagCategory.SKILL),
  createTag(
    `ULTIMATE_EMPOWER`,
    `Ultimate empower`,
    `Chiêu cuối cường hóa`,
    GameTagCategory.SKILL,
  ),
  createTag(`OATHSWORN`, `Oathsworn`, `Thệ Ước`, GameTagCategory.SKILL),
  createTag(
    `BOOT_SCALING`,
    `Boot scaling`,
    `Tỉ lệ theo bậc giày`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_ENGAGE`,
    `Ally engage`,
    `Đồng minh mở giao tranh`,
    GameTagCategory.SKILL,
  ),
  createTag(`PLASMA`, `Plasma`, `Plasma`, GameTagCategory.SKILL),
  createTag(`MULTI_HIT`, `Multi-hit`, `Đa lần trúng`, GameTagCategory.SKILL),
  createTag(
    `BACKLINE_ACCESS`,
    `Backline access`,
    `Tiếp cận tuyến sau`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MAX_HEALTH_DAMAGE`,
    `Max Health Damage`,
    `Sát thương theo máu tối đa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STACKING_ABILITY`,
    `Stacking Ability`,
    `Kỹ năng cộng dồn`,
    GameTagCategory.SKILL,
  ),
  createTag(`PULL`, `Pull`, `Kéo`, GameTagCategory.SKILL),
  createTag(`PATH_MAKER`, `Path Maker`, `Mở đường`, GameTagCategory.SKILL),
  createTag(
    `ALLY_SHIELD`,
    `Ally Shield`,
    `Lá chắn đồng minh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BONUS_HEALTH_SCALING`,
    `Bonus Health Scaling`,
    `Tỉ lệ theo máu cộng thêm`,
    GameTagCategory.SKILL,
  ),
  createTag(`OMNIVAMP`, `Omnivamp`, `Hút máu toàn phần`, GameTagCategory.SKILL),
  createTag(`TRAP`, `Trap`, `Bẫy`, GameTagCategory.SKILL),
  createTag(
    `DASH_INTERRUPT`,
    `Dash Interrupt`,
    `Ngắt lướt`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LONG_RANGE_EXECUTE`,
    `Long Range Execute`,
    `Kết liễu tầm xa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `FOURTH_SHOT`,
    `Fourth Shot`,
    `Viên đạn thứ tư`,
    GameTagCategory.SKILL,
  ),
  createTag(`RELOAD`, `Reload`, `Nạp đạn`, GameTagCategory.SKILL),
  createTag(
    `INVISIBLE_TRAP`,
    `Invisible Trap`,
    `Bẫy vô hình`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MANA_RESTORE`,
    `Mana Restore`,
    `Hồi năng lượng`,
    GameTagCategory.SKILL,
  ),
  createTag(`EMPOWER`, `Empower`, `Vận sức`, GameTagCategory.SKILL),
  createTag(
    `ATTACK_RESET`,
    `Attack Reset`,
    `Tái tạo đòn đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MONSTER_DAMAGE_MODIFIER`,
    `Monster Damage Modifier`,
    `Điều chỉnh sát thương lên quái`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `COUNTER_STRIKE`,
    `Counter Strike`,
    `Phản công`,
    GameTagCategory.SKILL,
  ),
  createTag(`DODGE`, `Dodge`, `Né đòn`, GameTagCategory.SKILL),
  createTag(
    `ATTACK_DODGE`,
    `Attack Dodge`,
    `Né đòn đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `EVERY_THIRD_ATTACK`,
    `Every Third Attack`,
    `Mỗi đòn thứ ba`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SIZE_INCREASE`,
    `Size Increase`,
    `Tăng kích cỡ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BASIC_ATTACK_MODIFIER`,
    `Basic Attack Modifier`,
    `Biến đổi đòn đánh thường`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MAX_HEALTH_SCALING`,
    `Max Health Scaling`,
    `Tỉ lệ theo máu tối đa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `NEARBY_ENEMY_SCALING`,
    `Nearby Enemy Scaling`,
    `Tỉ lệ theo kẻ địch gần đó`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STORED_CHARGES`,
    `Stored Charges`,
    `Điểm dùng tích trữ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `AUTO_TARGET`,
    `Auto Target`,
    `Tự chọn mục tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_BUFF`,
    `Ally Buff`,
    `Cường hóa đồng minh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ATTACK_DAMAGE_BUFF`,
    `Attack Damage Buff`,
    `Tăng sức mạnh công kích`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LOW_HEALTH_ALLY_TARGETING`,
    `Low Health Ally Targeting`,
    `Chọn đồng minh thấp máu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TURRET_SHIELD`,
    `Turret Shield`,
    `Lá chắn cho trụ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ON_HIT_DAMAGE`,
    `On-Hit Damage`,
    `Sát thương trên đòn đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MARK_CONSUME`,
    `Mark Consume`,
    `Tiêu thụ đánh dấu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MINION_DAMAGE_MODIFIER`,
    `Minion Damage Modifier`,
    `Điều chỉnh sát thương lên lính`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CHARGED_RELEASE`,
    `Charged Release`,
    `Tung chiêu sau khi tích lực`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `UNINTERRUPTIBLE`,
    `Uninterruptible`,
    `Không thể bị ngắt`,
    GameTagCategory.SKILL,
  ),
  createTag(`MARK`, `Mark`, `Đánh dấu`, GameTagCategory.SKILL),
  createTag(
    `DEPLOYABLE`,
    `Deployable`,
    `Đơn vị triển khai`,
    GameTagCategory.SKILL,
  ),
  createTag(`UPGRADE`, `Upgrade`, `Nâng cấp`, GameTagCategory.SKILL),
  createTag(
    `ABILITY_UPGRADE`,
    `Ability Upgrade`,
    `Nâng cấp kỹ năng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MOVEMENT_SPEED_SCALING`,
    `Movement Speed Scaling`,
    `Tỉ lệ theo Tốc Độ Di Chuyển`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BONUS_ATTACK_DAMAGE`,
    `Bonus Attack Damage`,
    `Sức Mạnh Công Kích cộng thêm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LONG_RANGE_ENGAGE`,
    `Long-Range Engage`,
    `Mở giao tranh tầm xa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STACK_CONSUME`,
    `Stack Consume`,
    `Tiêu thụ cộng dồn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TERRAIN_INTERACTION`,
    `Terrain Interaction`,
    `Tương tác địa hình`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BONUS_ARMOR`,
    `Bonus Armor`,
    `Giáp cộng thêm`,
    GameTagCategory.SKILL,
  ),
  createTag(`RAGE`, `Rage`, `Cuồng Nộ`, GameTagCategory.SKILL),
  createTag(
    `TRANSFORMATION`,
    `Transformation`,
    `Biến hình`,
    GameTagCategory.SKILL,
  ),
  createTag(`HYPER`, `Hyper`, `Quá Khích`, GameTagCategory.SKILL),
  createTag(`TENACITY`, `Tenacity`, `Kháng hiệu ứng`, GameTagCategory.SKILL),
  createTag(
    `MAGIC_RESIST_SCALING`,
    `Magic Resist Scaling`,
    `Tỉ lệ theo Kháng Phép`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MAGIC_SHIELD`,
    `Magic Shield`,
    `Lá chắn phép`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `COLLISION_DASH`,
    `Collision Dash`,
    `Lướt va chạm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ATTACHED_PROJECTILE`,
    `Attached Projectile`,
    `Đạn bám mục tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(`VITAL`, `Vital`, `Điểm Yếu`, GameTagCategory.SKILL),
  createTag(`PARRY`, `Parry`, `Chặn đòn`, GameTagCategory.SKILL),
  createTag(`DRAIN`, `Drain`, `Hút máu`, GameTagCategory.SKILL),
  createTag(
    `MARK_DETONATION`,
    `Mark Detonation`,
    `Kích nổ dấu ấn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MANA_REFUND`,
    `Mana Refund`,
    `Hoàn lại năng lượng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ON_HIT_EFFECTS`,
    `On-Hit Effects`,
    `Hiệu ứng đòn đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BACKWARD_WARP`,
    `Backward Warp`,
    `Dịch chuyển lùi`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TIME_REWIND`,
    `Time Rewind`,
    `Quay ngược thời gian`,
    GameTagCategory.SKILL,
  ),
  createTag(
    'SKILL_SHOT',
    'Skill Shot',
    'Kỹ năng định hướng',
    GameTagCategory.SKILL,
  ),
  createTag('KNOCK_BACK', 'Knock Back', 'Đẩy lùi', GameTagCategory.SKILL),
  createTag('STUN', 'Stun', 'Làm choáng', GameTagCategory.SKILL),
  createTag('CAMOUFLAGE', 'Camouflage', 'Ngụy trang', GameTagCategory.SKILL),
  createTag(
    'DOUBLE_SHOT',
    'Double Shot',
    'Bắn thêm phát thứ hai',
    GameTagCategory.SKILL,
  ),
  createTag(
    'CRITICAL_SCALING',
    'Critical Scaling',
    'Tăng sức mạnh theo tỉ lệ chí mạng',
    GameTagCategory.SKILL,
  ),
  createTag(
    'MISSING_HEALTH_DAMAGE',
    'Missing Health Damage',
    'Sát thương theo máu đã mất',
    GameTagCategory.SKILL,
  ),
  createTag('LOCK_ON', 'Lock On', 'Khóa mục tiêu', GameTagCategory.SKILL),
  createTag(
    'MULTI_CAST',
    'Multi Cast',
    'Kỹ năng có nhiều lần sử dụng',
    GameTagCategory.SKILL,
  ),
  createTag(
    'ARMOR_PENETRATION',
    'Armor Penetration',
    'Xuyên giáp',
    GameTagCategory.SKILL,
  ),
  createTag('SUPPRESS', 'Suppress', 'Áp chế', GameTagCategory.SKILL),
  createTag(
    'UNSTOPPABLE',
    'Unstoppable',
    'Không thể bị cản phá',
    GameTagCategory.SKILL,
  ),
  createTag(
    'PHYSICAL_VAMP',
    'Physical Vamp',
    'Hút máu vật lý',
    GameTagCategory.SKILL,
  ),
  createTag('ROOT', 'Root', 'Trói chân', GameTagCategory.SKILL),
  createTag('TOGGLE', 'Toggle', 'Kỹ năng bật tắt', GameTagCategory.SKILL),
  createTag(
    'STACKING_PASSIVE',
    'Stacking Passive',
    'Nội tại tích cộng dồn',
    GameTagCategory.SKILL,
  ),
  createTag(
    'BURST_SETUP',
    'Burst Setup',
    'Thiết lập dồn sát thương',
    GameTagCategory.SKILL,
  ),
  createTag(
    'LAST_HIT_REFUND',
    'Last Hit Refund',
    'Hoàn trả tài nguyên khi kết liễu',
    GameTagCategory.SKILL,
  ),
  createTag(
    'CONE_DAMAGE',
    'Cone Damage',
    'Sát thương hình nón',
    GameTagCategory.SKILL,
  ),
  createTag(
    'SELF_BUFF',
    'Self Buff',
    'Tự cường hóa bản thân',
    GameTagCategory.SKILL,
  ),
  createTag(
    'SUMMON_SUPPORT',
    'Summon Support',
    'Hỗ trợ đơn vị triệu hồi',
    GameTagCategory.SKILL,
  ),
  createTag('SUMMON', 'Summon', 'Triệu hồi', GameTagCategory.SKILL),
  createTag(
    'ATTACK_SPEED_STEROID',
    'Attack Speed Steroid',
    'Tăng mạnh tốc độ đánh',
    GameTagCategory.SKILL,
  ),
  createTag('VISION', 'Vision', 'Cung cấp tầm nhìn', GameTagCategory.SKILL),
  createTag(
    'GLOBAL_RANGE',
    'Global Range',
    'Tầm sử dụng toàn bản đồ',
    GameTagCategory.SKILL,
  ),
  createTag(
    'STEERABLE_PROJECTILE',
    'Steerable Projectile',
    'Đạn có thể điều khiển hướng bay',
    GameTagCategory.SKILL,
  ),
  createTag(
    'ABILITY_EVOLUTION',
    'Ability Evolution',
    'Kỹ năng tiến hóa theo cộng dồn',
    GameTagCategory.SKILL,
  ),
  createTag(
    'CHANNEL',
    'Channel',
    'Vận sức duy trì kỹ năng',
    GameTagCategory.SKILL,
  ),
  createTag(
    'FLIGHT',
    'Flight',
    'Bay theo hướng chỉ định',
    GameTagCategory.SKILL,
  ),
  createTag(
    'REALM_HOPPER',
    'Realm Hopper',
    'Nhảy giữa các vùng linh giới',
    GameTagCategory.SKILL,
  ),
  createTag(
    'SELF_DISPLACEMENT',
    'Self Displacement',
    'Tự dịch chuyển vị trí',
    GameTagCategory.SKILL,
  ),
  createTag(
    'BOUNDARY_CONTROL',
    'Boundary Control',
    'Kiểm soát ranh giới vùng',
    GameTagCategory.SKILL,
  ),
  createTag('RECAST', 'Recast', 'Tái kích hoạt', GameTagCategory.SKILL),
  createTag('STEALTH', 'Stealth', 'Tàng hình', GameTagCategory.SKILL),
  createTag('SPEED_UP', 'Speed Up', 'Tăng tốc', GameTagCategory.SKILL),
  createTag(
    'ENERGY_RESTORE',
    'Energy Restore',
    'Hồi nội năng',
    GameTagCategory.SKILL,
  ),
  createTag('STASIS', 'Stasis', 'Ngưng đọng', GameTagCategory.SKILL),
  createTag(
    'AOE_STASIS',
    'Area Stasis',
    'Ngưng đọng diện rộng',
    GameTagCategory.SKILL,
  ),
  createTag('PORTAL', 'Portal', 'Cổng dịch chuyển', GameTagCategory.SKILL),
  createTag(
    'TERRAIN_TRAVEL',
    'Terrain Travel',
    'Di chuyển xuyên địa hình',
    GameTagCategory.SKILL,
  ),
  createTag(
    'ALLY_HEAL',
    'Ally Heal',
    'Hồi máu cho đồng minh',
    GameTagCategory.SKILL,
  ),
  createTag(
    'EMPOWERED_ATTACK',
    'Empowered Attack',
    'Đòn đánh cường hóa',
    GameTagCategory.SKILL,
  ),
  createTag('HOOK', 'Hook', 'Kéo móc', GameTagCategory.SKILL),
  createTag(
    'LOW_HEALTH_TRIGGER',
    'Low Health Trigger',
    'Kích hoạt khi thấp máu',
    GameTagCategory.SKILL,
  ),
  createTag(
    'DECAYING_MOVEMENT_SPEED',
    'Decaying Movement Speed',
    'Tốc độ di chuyển giảm dần',
    GameTagCategory.SKILL,
  ),
  createTag(
    'SELF_SLOW',
    'Self Slow',
    'Tự làm chậm bản thân',
    GameTagCategory.SKILL,
  ),
  createTag(
    'CRITICAL_STRIKE',
    'Critical Strike',
    'Chí mạng',
    GameTagCategory.SKILL,
  ),
  createTag(
    'PASSIVE_DAMAGE',
    'Passive Damage',
    'Sát thương nội tại',
    GameTagCategory.SKILL,
  ),
  createTag('SILENCE', 'Silence', 'Câm lặng', GameTagCategory.SKILL),
  createTag(
    'AUTO_ATTACK_RESET',
    'Auto Attack Reset',
    'Tái tạo đòn đánh thường',
    GameTagCategory.SKILL,
  ),
  createTag(
    `DAMAGE_OVER_TIME`,
    `Damage Over Time`,
    `Sát Thương Theo Thời Gian`,
    GameTagCategory.SKILL,
  ),
  createTag(`DETONATION`, `Detonation`, `Phát Nổ`, GameTagCategory.SKILL),
  createTag(
    `DELAYED_AREA`,
    `Delayed Area`,
    `Vùng Trì Hoãn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SPREAD_DAMAGE`,
    `Spread Damage`,
    `Sát Thương Lan`,
    GameTagCategory.SKILL,
  ),
  createTag(`BOUNCE`, `Bounce`, `Nảy Mục Tiêu`, GameTagCategory.SKILL),
  createTag(
    `ALLY_FOLLOW_UP`,
    `Ally Follow-up`,
    `Đồng Minh Bồi Tiếp`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_DASH`,
    `Ally Dash`,
    `Lướt Tới Đồng Minh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BONUS_RESISTANCES`,
    `Bonus Resistances`,
    `Tăng Chống Chịu`,
    GameTagCategory.SKILL,
  ),
  createTag(`PROTECTION`, `Protection`, `Bảo Vệ`, GameTagCategory.SKILL),
  createTag(
    `PROJECTILE_BLOCK`,
    `Projectile Block`,
    `Chặn Đường Đạn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DAMAGE_NEGATION`,
    `Damage Negation`,
    `Vô Hiệu Sát Thương`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `PIERCING_PROJECTILE`,
    `Piercing Projectile`,
    `Đạn Xuyên Mục Tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ADAPTIVE_SHIELD`,
    `Adaptive Shield`,
    `Lá Chắn Thích Ứng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TRADING_TOOL`,
    `Trading Tool`,
    `Công Cụ Trao Đổi Chiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LOCKDOWN_ZONE`,
    `Lockdown Zone`,
    `Vùng Khóa Chân`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CURRENT_HEALTH_DAMAGE`,
    `Current Health Damage`,
    `Sát Thương Theo Máu Hiện Tại`,
    GameTagCategory.SKILL,
  ),
  createTag(`ARMOR_SHRED`, `Armor Shred`, `Giảm Giáp`, GameTagCategory.SKILL),
  createTag(
    `CHARGE_SYSTEM`,
    `Charge System`,
    `Cơ Chế Tích Trữ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ORBITING_SPHERES`,
    `Orbiting Spheres`,
    `Quả Cầu Xoay Quanh`,
    GameTagCategory.SKILL,
  ),
  createTag(`CHARGE`, `Charge`, `Tích Tụ`, GameTagCategory.SKILL),
  createTag(
    `CC_RESIST`,
    `Crowd Control Resist`,
    `Kháng Khống Chế`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HEALTH_REGEN`,
    `Health Regeneration`,
    `Hồi Máu Theo Thời Gian`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HEALTH_COST`,
    `Health Cost`,
    `Tiêu Hao Máu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HEALTH_SCALING`,
    `Health Scaling`,
    `Tỉ Lệ Theo Máu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MISSING_HEALTH_SCALING`,
    `Missing Health Scaling`,
    `Tỉ Lệ Theo Máu Đã Mất`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `COOLDOWN_REFRESH`,
    `Cooldown Refresh`,
    `Làm mới hồi chiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DAMAGE_FALLOFF`,
    `Damage Falloff`,
    `Sát thương giảm dần`,
    GameTagCategory.SKILL,
  ),
];

export async function seedGameTags(prisma: PrismaClient) {
  console.log('Seeding game tags...');

  for (const gameTagSeed of gameTagSeeds) {
    await prisma.gameTag.upsert({
      where: {
        key: gameTagSeed.key,
      },
      update: {
        name: gameTagSeed.name,
        nameVi: gameTagSeed.nameVi,
        description: gameTagSeed.description,
        descriptionVi: gameTagSeed.descriptionVi,
        category: gameTagSeed.category,
        deletedAt: null,
      },
      create: gameTagSeed,
    });

    console.log(`Seeded game tag: ${gameTagSeed.key}`);
  }

  console.log('Seeded game tags');
}
