import { PrismaClient } from '../../src/generated/prisma/client.js';
import { GameTagCategory } from '../../src/generated/prisma/enums.js';

type GameTagSeed = {
  key: string;
  name: string;
  nameVi: string;
  description: string;
  descriptionVi: string;
  category: GameTagCategory;
};

function createTag(
  key: string,
  name: string,
  nameVi: string,
  category: GameTagCategory,
): GameTagSeed {
  return {
    key,
    name,
    nameVi,
    description: `Tag used for ${name.toLowerCase()} classification`,
    descriptionVi: `Tag dùng để phân loại ${nameVi.toLowerCase()}`,
    category,
  };
}

const gameTagSeeds: GameTagSeed[] = [
  // ITEM CATEGORIES
  createTag('LOW_TIER', 'Low Tier', 'Trang bị bậc thấp', GameTagCategory.ITEM),
  createTag(
    'MIDDLE_TIER',
    'Middle Tier',
    'Trang bị bậc trung',
    GameTagCategory.ITEM,
  ),
  createTag('HIGH_TIER', 'High Tier', 'Trang bị bậc cao', GameTagCategory.ITEM),
  createTag(
    'COMPONENT',
    'Component',
    'Trang bị thành phần',
    GameTagCategory.ITEM,
  ),
  createTag('MAGIC', 'Magic', 'Trang bị phép thuật', GameTagCategory.ITEM),
  createTag('SUPPORT', 'Support', 'Trang bị hỗ trợ', GameTagCategory.ITEM),
  createTag(
    'DEFENSIVE',
    'Defensive',
    'Trang bị phòng thủ',
    GameTagCategory.ITEM,
  ),
  createTag('HYBRID', 'Hybrid', 'Trang bị lai', GameTagCategory.ITEM),
  createTag('ON_HIT', 'On Hit', 'Hiệu ứng đòn đánh', GameTagCategory.ITEM),

  // ITEM STATS
  createTag(
    'ABILITY_POWER',
    'Ability Power',
    'Sức mạnh phép thuật',
    GameTagCategory.ITEM,
  ),
  createTag(
    'ATTACK_DAMAGE',
    'Attack Damage',
    'Sức mạnh công kích',
    GameTagCategory.ITEM,
  ),
  createTag('HEALTH', 'Health', 'Máu', GameTagCategory.ITEM),
  createTag('MANA', 'Mana', 'Năng lượng', GameTagCategory.ITEM),
  createTag(
    'ABILITY_HASTE',
    'Ability Haste',
    'Điểm hồi kỹ năng',
    GameTagCategory.ITEM,
  ),
  createTag(
    'ATTACK_SPEED',
    'Attack Speed',
    'Tốc độ đánh',
    GameTagCategory.ITEM,
  ),
  createTag(
    'MAGIC_PENETRATION',
    'Magic Penetration',
    'Xuyên kháng phép',
    GameTagCategory.ITEM,
  ),
  createTag(
    'MOVEMENT_SPEED',
    'Movement Speed',
    'Tốc độ di chuyển',
    GameTagCategory.ITEM,
  ),
  createTag('MAGIC_VAMP', 'Magic Vamp', 'Hút máu phép', GameTagCategory.ITEM),
  createTag('MANA_REGEN', 'Mana Regen', 'Hồi năng lượng', GameTagCategory.ITEM),
  createTag(
    'HEAL_SHIELD_POWER',
    'Heal and Shield Power',
    'Sức mạnh hồi máu và lá chắn',
    GameTagCategory.ITEM,
  ),

  // DAMAGE / SCORING TAGS
  createTag(
    'MAGIC_DAMAGE',
    'Magic Damage',
    'Sát thương phép',
    GameTagCategory.SCORING,
  ),
  createTag(
    'PHYSICAL_DAMAGE',
    'Physical Damage',
    'Sát thương vật lý',
    GameTagCategory.SCORING,
  ),
  createTag(
    'TRUE_DAMAGE',
    'True Damage',
    'Sát thương chuẩn',
    GameTagCategory.SCORING,
  ),
  createTag(
    'HYBRID_DAMAGE',
    'Hybrid Damage',
    'Sát thương lai',
    GameTagCategory.SCORING,
  ),
  createTag(
    'ADAPTIVE_DAMAGE',
    'Adaptive Damage',
    'Sát thương thích ứng',
    GameTagCategory.SCORING,
  ),
  createTag(
    'BURST_DAMAGE',
    'Burst Damage',
    'Sát thương dồn',
    GameTagCategory.SCORING,
  ),
  createTag(
    'SUSTAIN_DAMAGE',
    'Sustained Damage',
    'Sát thương duy trì',
    GameTagCategory.SCORING,
  ),
  createTag(
    'BURN_DAMAGE',
    'Burn Damage',
    'Sát thương đốt',
    GameTagCategory.SCORING,
  ),
  createTag(
    'AREA_DAMAGE',
    'Area Damage',
    'Sát thương diện rộng',
    GameTagCategory.SCORING,
  ),
  createTag(
    'DAMAGE_AMP',
    'Damage Amplification',
    'Khuếch đại sát thương',
    GameTagCategory.SCORING,
  ),
  createTag(
    'MAGIC_RESIST_REDUCTION',
    'Magic Resist Reduction',
    'Giảm kháng phép',
    GameTagCategory.SCORING,
  ),

  // ITEM EFFECT TAGS
  createTag(
    'SCALING_MANA',
    'Mana Scaling',
    'Tăng tiến theo năng lượng',
    GameTagCategory.BUILD,
  ),
  createTag(
    'SCALING_HEALTH',
    'Health Scaling',
    'Tăng tiến theo máu',
    GameTagCategory.BUILD,
  ),
  createTag('SNOWBALL', 'Snowball', 'Lăn cầu tuyết', GameTagCategory.BUILD),
  createTag('SPELLBLADE', 'Spellblade', 'Kiếm phép', GameTagCategory.BUILD),
  createTag(
    'ULTIMATE_HASTE',
    'Ultimate Haste',
    'Hồi chiêu cuối',
    GameTagCategory.BUILD,
  ),
  createTag(
    'SPELL_SHIELD',
    'Spell Shield',
    'Khiên phép',
    GameTagCategory.BUILD,
  ),
  createTag('EXECUTE', 'Execute', 'Kết liễu', GameTagCategory.BUILD),
  createTag('REVEAL', 'Reveal', 'Lộ diện', GameTagCategory.BUILD),
  createTag('SLOW', 'Slow', 'Làm chậm', GameTagCategory.BUILD),
  createTag('SUSTAIN', 'Sustain', 'Hồi phục duy trì', GameTagCategory.BUILD),
  createTag('KITE', 'Kite', 'Thả diều', GameTagCategory.BUILD),

  // COUNTER TAGS
  createTag(
    'ANTI_TANK',
    'Anti Tank',
    'Chống chống chịu',
    GameTagCategory.COUNTER,
  ),
  createTag('ANTI_HEAL', 'Anti Heal', 'Giảm hồi máu', GameTagCategory.COUNTER),
  createTag(
    'ANTI_SHIELD',
    'Anti Shield',
    'Chống lá chắn',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'ANTI_BURST',
    'Anti Burst',
    'Chống dồn sát thương',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'ANTI_ATTACK_SPEED',
    'Anti Attack Speed',
    'Khắc chế tốc độ đánh',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'PERCENT_HEALTH_DAMAGE',
    'Percent Health Damage',
    'Sát thương theo phần trăm máu',
    GameTagCategory.COUNTER,
  ),

  // MATCHUP / ENEMY TEAM TAGS
  createTag('TANK', 'Tank', 'Chống chịu', GameTagCategory.MATCHUP),
  createTag('HIGH_HEALTH', 'High Health', 'Nhiều máu', GameTagCategory.MATCHUP),
  createTag('FRONTLINE', 'Frontline', 'Tuyến trước', GameTagCategory.MATCHUP),
  createTag(
    'SQUISHY_CHAMPION',
    'Squishy Champion',
    'Tướng mỏng',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_HEALTH_TARGET',
    'Low Health Target',
    'Mục tiêu thấp máu',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_MAGIC_RESIST',
    'Low Magic Resist',
    'Ít kháng phép',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'HIGH_MAGIC_RESIST',
    'High Magic Resist',
    'Nhiều kháng phép',
    GameTagCategory.MATCHUP,
  ),
  createTag('HEALING', 'Healing', 'Hồi máu', GameTagCategory.MATCHUP),
  createTag('ENCHANTER', 'Enchanter', 'Hỗ trợ buff', GameTagCategory.MATCHUP),
  createTag('SHIELDING', 'Shielding', 'Tạo lá chắn', GameTagCategory.MATCHUP),
  createTag(
    'NO_HEALING_TEAM',
    'No Healing Team',
    'Đội hình không hồi máu',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'NO_SHIELD_TEAM',
    'No Shield Team',
    'Đội hình không lá chắn',
    GameTagCategory.MATCHUP,
  ),
  createTag('ASSASSIN', 'Assassin', 'Sát thủ', GameTagCategory.MATCHUP),
  createTag('BRUISER', 'Bruiser', 'Đấu sĩ', GameTagCategory.MATCHUP),
  createTag('ENGAGE', 'Engage', 'Mở giao tranh', GameTagCategory.MATCHUP),
  createTag(
    'DISENGAGE',
    'Disengage',
    'Thoát giao tranh',
    GameTagCategory.MATCHUP,
  ),
  createTag('DIVE', 'Dive', 'Lao vào', GameTagCategory.MATCHUP),
  createTag(
    'MELEE_CHAMPION',
    'Melee Champion',
    'Tướng cận chiến',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_RANGE_CHAMPION',
    'Low Range Champion',
    'Tướng tầm đánh ngắn',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LONG_RANGE_CHAMPION',
    'Long Range Champion',
    'Tướng tầm xa',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'HIGH_MOBILITY',
    'High Mobility',
    'Độ cơ động cao',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'POINT_AND_CLICK_CC',
    'Point and Click CC',
    'Khống chế chỉ định',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_CC',
    'Low Crowd Control',
    'Ít khống chế',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_BURST',
    'Low Burst',
    'Ít sát thương dồn',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'PICK_COMPOSITION',
    'Pick Composition',
    'Đội hình bắt lẻ',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'POKE_COMPOSITION',
    'Poke Composition',
    'Đội hình cấu rỉa',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'GROUPED_ENEMIES',
    'Grouped Enemies',
    'Kẻ địch đứng gần nhau',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'FOG_OF_WAR',
    'Fog of War',
    'Tầm nhìn khuất',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'MELEE_TRADING',
    'Melee Trading',
    'Trao đổi chiêu cận chiến',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_COOLDOWN_HARASS',
    'Low Cooldown Harass',
    'Cấu rỉa hồi chiêu thấp',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LOW_ULTIMATE_VALUE',
    'Low Ultimate Value',
    'Giá trị chiêu cuối thấp',
    GameTagCategory.MATCHUP,
  ),

  // GAME PLAN / CONTEXT TAGS
  createTag(
    `FORM_SELECTION`,
    `Form selection`,
    `Chọn dạng biến đổi`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `INVULNERABILITY`,
    `Invulnerability`,
    `Bất tử`,
    GameTagCategory.TEAM_COMP,
  ),

  createTag(
    `TEAMFIGHT_CLEANUP`,
    `Teamfight cleanup`,
    `Dọn giao tranh`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `CROWD_CONTROL_SETUP`,
    `Crowd control setup`,
    `Thiết lập khống chế`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `RESET_WINDOW`,
    `Reset window`,
    `Cửa sổ hồi chiêu theo hạ gục`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `OATHSWORN_SETUP`,
    `Oathsworn setup`,
    `Thiết lập Thệ Ước`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `PLASMA_SETUP`,
    `Plasma setup`,
    `Thiết lập Plasma`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LONG_FIGHT',
    'Long Fight',
    'Giao tranh dài',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'EXTENDED_FIGHT',
    'Extended Fight',
    'Giao tranh kéo dài',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'TEAMFIGHT',
    'Teamfight',
    'Giao tranh tổng',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'SCALING_GAME',
    'Scaling Game',
    'Trận đấu kéo dài',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'SNOWBALL_GAME',
    'Snowball Game',
    'Trận đấu lăn cầu tuyết',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'FAST_SNOWBALL',
    'Fast Snowball',
    'Lăn cầu tuyết nhanh',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'FOLLOW_UP_DAMAGE',
    'Follow Up Damage',
    'Sát thương theo sau mở giao tranh',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LANE_PARTNER_DAMAGE',
    'Lane Partner Damage',
    'Sát thương từ đồng đội đi đường',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'EARLY_GAME_PRESSURE',
    'Early Game Pressure',
    'Áp lực đầu trận',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'EARLY_BURST',
    'Early Burst',
    'Dồn sát thương sớm',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LOW_DURABILITY_TEAM',
    'Low Durability Team',
    'Đội hình mỏng',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LOW_KILL_PRESSURE',
    'Low Kill Pressure',
    'Ít áp lực hạ gục',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'MIXED_DAMAGE',
    'Mixed Damage',
    'Sát thương hỗn hợp',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'SUSTAIN_TEAM',
    'Sustain Team',
    'Đội hình hồi phục',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'TEAM_COORDINATION',
    'Team Coordination',
    'Cần phối hợp đội',
    GameTagCategory.TEAM_COMP,
  ),

  // SPELL / SUMMONER SPELL TAGS
  createTag('CHASE', 'Chase', 'Truy đuổi', GameTagCategory.SPELL),
  createTag('ESCAPE', 'Escape', 'Thoát thân', GameTagCategory.SPELL),
  createTag('UTILITY', 'Utility', 'Đa dụng', GameTagCategory.SPELL),
  createTag('SHIELD', 'Shield', 'Lá chắn', GameTagCategory.SPELL),
  createTag('DEFENSE', 'Defense', 'Phòng thủ', GameTagCategory.SPELL),
  createTag('CLEANSE', 'Cleanse', 'Thanh tẩy', GameTagCategory.SPELL),
  createTag('JUNGLE', 'Jungle', 'Đi rừng', GameTagCategory.SPELL),
  createTag('PLAYMAKING', 'Playmaking', 'Tạo đột biến', GameTagCategory.SPELL),

  createTag('ROAMING', 'Roaming', 'Đảo đường', GameTagCategory.TEAM_COMP),
  createTag('DUO_LANE', 'Duo Lane', 'Đường đôi', GameTagCategory.TEAM_COMP),
  createTag(
    'SURVIVABILITY',
    'Survivability',
    'Khả năng sống sót',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'TEAM_SUPPORT',
    'Team Support',
    'Hỗ trợ đồng đội',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LANE_SURVIVAL',
    'Lane Survival',
    'Sống sót khi đi đường',
    GameTagCategory.TEAM_COMP,
  ),
  createTag('PEEL', 'Peel', 'Bảo kê', GameTagCategory.TEAM_COMP),
  createTag(
    'KILL_PRESSURE',
    'Kill Pressure',
    'Áp lực hạ gục',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'LANE_KILL_PRESSURE',
    'Lane Kill Pressure',
    'Áp lực hạ gục khi đi đường',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'OBJECTIVE_CONTROL',
    'Objective Control',
    'Kiểm soát mục tiêu',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'JUNGLE_CLEAR',
    'Jungle Clear',
    'Dọn rừng',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'NON_JUNGLE_ROLE',
    'Non Jungle Role',
    'Không phải vai trò đi rừng',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'MAP_PRESSURE',
    'Map Pressure',
    'Áp lực bản đồ',
    GameTagCategory.TEAM_COMP,
  ),
  createTag('MACRO', 'Macro', 'Tư duy bản đồ', GameTagCategory.TEAM_COMP),
  createTag('SIDE_LANE', 'Side Lane', 'Đường cánh', GameTagCategory.TEAM_COMP),
  createTag(
    'EARLY_COMBAT',
    'Early Combat',
    'Giao tranh sớm',
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    'DAMAGE_REDUCTION',
    'Damage Reduction',
    'Giảm sát thương',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'ANTI_ASSASSIN',
    'Anti Assassin',
    'Khắc chế sát thủ',
    GameTagCategory.COUNTER,
  ),
  createTag(
    'ANTI_CC',
    'Anti Crowd Control',
    'Chống khống chế',
    GameTagCategory.COUNTER,
  ),

  createTag(
    'LONG_RANGE_POKE',
    'Long Range Poke',
    'Cấu rỉa tầm xa',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'CROWD_CONTROL',
    'Crowd Control',
    'Khống chế',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'LONG_RANGE_SAFE_PLAY',
    'Long Range Safe Play',
    'Chơi an toàn tầm xa',
    GameTagCategory.MATCHUP,
  ),
  createTag(
    'EPIC_MONSTER',
    'Epic Monster',
    'Quái khủng',
    GameTagCategory.MATCHUP,
  ),

  createTag(
    'RAW_DAMAGE',
    'Raw Damage',
    'Sát thương thuần',
    GameTagCategory.SCORING,
  ),

  // CHAMPION CLASS TAGS
  createTag('MAGE', 'Mage', 'Pháp sư', GameTagCategory.CHAMPION),
  createTag('FIGHTER', 'Fighter', 'Đấu sĩ', GameTagCategory.CHAMPION),
  createTag(
    'SKIRMISHER',
    'Skirmisher',
    'Đấu sĩ cơ động',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'CONTROL_MAGE',
    'Control Mage',
    'Pháp sư kiểm soát',
    GameTagCategory.CHAMPION,
  ),
  createTag('MARKSMAN', 'Marksman', 'Xạ thủ', GameTagCategory.CHAMPION),

  // CHAMPION PLAYSTYLE TAGS
  createTag(
    `FORM_CHANGE`,
    `Form change`,
    `Biến đổi dạng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `HYPERCARRY`,
    `Hypercarry`,
    `Chủ lực siêu cuối trận`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `RESET_CHAMPION`,
    `Reset champion`,
    `Tướng hồi chiêu theo hạ gục`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `ANTI_MAGE`,
    `Anti-mage`,
    `Khắc chế pháp sư`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`FORM_SWAP`, `Form Swap`, `Chuyển dạng`, GameTagCategory.PLAYSTYLE),
  createTag(
    `LANE_PRESSURE`,
    `Lane Pressure`,
    `Áp lực đi đường`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(`ANTI_DIVE`, `Anti-Dive`, `Chống lao vào`, GameTagCategory.COUNTER),
  createTag(
    `TRANSFORMATION_RELIANT`,
    `Transformation Reliant`,
    `Phụ thuộc biến hình`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    `TIMING_RELIANT`,
    `Timing Reliant`,
    `Phụ thuộc căn thời điểm`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(`DUELIST`, `Duelist`, `Đấu sĩ tay đôi`, GameTagCategory.PLAYSTYLE),
  createTag(
    `THREE_HIT_PASSIVE`,
    `Three-Hit Passive`,
    `Nội tại ba đòn`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag('BURST', 'Burst', 'Dồn sát thương', GameTagCategory.PLAYSTYLE),
  createTag('PICK', 'Pick', 'Bắt lẻ', GameTagCategory.PLAYSTYLE),
  createTag('MOBILITY', 'Mobility', 'Cơ động', GameTagCategory.PLAYSTYLE),
  createTag(
    'DPS',
    'DPS',
    'Sát thương theo thời gian',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'SCALING',
    'Scaling',
    'Tăng tiến sức mạnh',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag('POKE', 'Poke', 'Cấu rỉa', GameTagCategory.PLAYSTYLE),
  createTag(
    'ZONE_CONTROL',
    'Zone Control',
    'Kiểm soát khu vực',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'ON_HIT_CHAMPION',
    'On Hit Champion',
    'Tướng đánh theo hiệu ứng đòn đánh',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'AUTO_ATTACK_CHAMPION',
    'Auto Attack Champion',
    'Tướng đánh thường nhiều',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'SPELLBLADE_CHAMPION',
    'Spellblade Champion',
    'Tướng tận dụng Kiếm Phép',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'ABILITY_RELIANT_CHAMPION',
    'Ability Reliant Champion',
    'Tướng phụ thuộc kỹ năng',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'MANA_HUNGRY_CHAMPION',
    'Mana Hungry Champion',
    'Tướng tốn nhiều năng lượng',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    `ENERGY_RELIANT`,
    `Energy reliant`,
    `Phụ thuộc nội năng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'ULTIMATE_RELIANT_CHAMPION',
    'Ultimate Reliant Champion',
    'Tướng phụ thuộc chiêu cuối',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'EXTENDED_FIGHT_CHAMPION',
    'Extended Fight Champion',
    'Tướng mạnh trong giao tranh kéo dài',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'UTILITY_MARKSMAN',
    'Utility Marksman',
    'Xạ thủ thiên về tiện ích',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'VISION_CONTROL',
    'Vision Control',
    'Kiểm soát tầm nhìn',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(
    'SKIRMISH',
    'Skirmish',
    'Giao tranh nhỏ lẻ',
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(`SPLIT_PUSH`, `Split Push`, `Đẩy Lẻ`, GameTagCategory.PLAYSTYLE),
  createTag(
    `DRAIN_TANK`,
    `Drain Tank`,
    `Đấu Sĩ Hồi Phục`,
    GameTagCategory.PLAYSTYLE,
  ),
  createTag(`ADORATION`, `Adoration`, `Ngưỡng Mộ`, GameTagCategory.PLAYSTYLE),
  createTag(
    `BONUS_GOLD`,
    `Bonus Gold`,
    `Vàng thưởng`,
    GameTagCategory.PLAYSTYLE,
  ),

  // CHAMPION UTILITY TAGS
  createTag(
    `UNTARGETABLE`,
    `Untargetable`,
    `Không thể bị chọn làm mục tiêu`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `TERRAIN_WALK`,
    `Terrain walk`,
    `Đi xuyên địa hình`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `VISION_DENIAL`,
    `Vision Denial`,
    `Che khuất tầm nhìn`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`TAUNT`, `Taunt`, `Khiêu khích`, GameTagCategory.CHAMPION),
  createTag(`FEAR`, `Fear`, `Hoảng sợ`, GameTagCategory.CHAMPION),
  createTag(
    `COOLDOWN_REDUCTION`,
    `Cooldown Reduction`,
    `Giảm hồi chiêu`,
    GameTagCategory.CHAMPION,
  ),
  createTag('CHARM', 'Charm', 'Hôn gió', GameTagCategory.CHAMPION),
  createTag('DASH', 'Dash', 'Lướt', GameTagCategory.CHAMPION),
  createTag('KNOCK_UP', 'Knock Up', 'Hất tung', GameTagCategory.CHAMPION),
  createTag('WIND_WALL', 'Wind Wall', 'Tường gió', GameTagCategory.CHAMPION),
  createTag('REVIVE', 'Revive', 'Hồi sinh đồng minh', GameTagCategory.CHAMPION),

  // CHAMPION RISK TAGS
  createTag(
    `FORM_RELIANT`,
    `Form reliant`,
    `Phụ thuộc dạng biến đổi`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `SCALING_RELIANT`,
    `Scaling reliant`,
    `Phụ thuộc tăng tiến sức mạnh`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `RESET_RELIANT`,
    `Reset reliant`,
    `Phụ thuộc hồi chiêu theo hạ gục`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `MANA_RELIANT`,
    `Mana reliant`,
    `Phụ thuộc năng lượng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `OATHSWORN_RELIANT`,
    `Oathsworn reliant`,
    `Phụ thuộc Thệ Ước`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `SHORT_RANGE_MARKSMAN`,
    `Short-range marksman`,
    `Xạ thủ tầm ngắn`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `RELOAD_RELIANT`,
    `Reload Reliant`,
    `Phụ thuộc nạp đạn`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `FORM_DEPENDENT`,
    `Form Dependent`,
    `Phụ thuộc dạng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `COMMIT_HEAVY`,
    `Commit Heavy`,
    `Dễ phải lao vào sâu`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'SKILLSHOT_RELIANT',
    'Skillshot Reliant',
    'Phụ thuộc kỹ năng định hướng',
    GameTagCategory.CHAMPION,
  ),
  createTag('SQUISHY', 'Squishy', 'Mỏng máu', GameTagCategory.CHAMPION),
  createTag(
    'MELEE_MID',
    'Melee Mid',
    'Đường giữa cận chiến',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'HIGH_EXECUTION',
    'High Execution',
    'Yêu cầu kỹ năng cao',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'CC_VULNERABLE',
    'CC Vulnerable',
    'Dễ bị khống chế',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'LOW_MOBILITY',
    'Low Mobility',
    'Kém cơ động',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'POSITIONING_RELIANT',
    'Positioning Reliant',
    'Phụ thuộc vị trí đứng',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'WEAK_EARLY_GAME',
    'Weak Early Game',
    'Yếu đầu trận',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'INTERRUPT_VULNERABLE',
    'Interrupt Vulnerable',
    'Dễ bị ngắt kỹ năng',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'SHORT_RANGE_MAGE',
    'Short Range Mage',
    'Pháp sư tầm ngắn',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'FLASH_RELIANT',
    'Flash Reliant',
    'Phụ thuộc Tốc Biến',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'COOLDOWN_RELIANT',
    'Cooldown Reliant',
    'Phụ thuộc hồi chiêu',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'PUNISHABLE_WHEN_MISSED',
    'Punishable When Missed',
    'Dễ bị trừng phạt khi dùng hụt',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'MISS_DEPENDENT',
    'Miss Dependent',
    'Phụ thuộc dùng trúng kỹ năng',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `TEAM_DEPENDENT`,
    `Team Dependent`,
    `Phụ Thuộc Đồng Đội`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `LOW_DAMAGE`,
    `Low Damage`,
    `Ít Sát Thương`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`KITEABLE`, `Kiteable`, `Dễ Bị Thả Diều`, GameTagCategory.CHAMPION),
  createTag(
    `ANTI_HEAL_VULNERABLE`,
    `Anti-heal Vulnerable`,
    `Yếu Trước Giảm Hồi Máu`,
    GameTagCategory.CHAMPION,
  ),

  // CHAMPION STRENGTH / WEAKNESS TAGS
  createTag(
    `ANTI_MAGIC`,
    `Anti-magic`,
    `Chống sát thương phép`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `DISPLACEMENT`,
    `Displacement`,
    `Dịch chuyển vị trí kẻ địch`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `RESET_CARRY`,
    `Reset Carry`,
    `Chủ lực snowball theo hạ gục`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `SAFE_POSITIONING`,
    `Safe Positioning`,
    `Giữ vị trí an toàn`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `POKE_SETUP`,
    `Poke Setup`,
    `Thiết lập cấu rỉa`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `HARD_ENGAGE`,
    `Hard Engage`,
    `Mở giao tranh mạnh`,
    GameTagCategory.MATCHUP,
  ),
  createTag(
    `TERRAIN_CONTROL`,
    `Terrain Control`,
    `Kiểm soát địa hình`,
    GameTagCategory.TEAM_COMP,
  ),
  createTag(
    `ARMOR_REDUCTION`,
    `Armor Reduction`,
    `Giảm giáp`,
    GameTagCategory.SCORING,
  ),
  createTag(
    `COOLDOWN_MANAGEMENT`,
    `Cooldown Management`,
    `Quản lý hồi chiêu`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `RAGE_MANAGEMENT`,
    `Rage Management`,
    `Quản lý Cuồng Nộ`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`TOWER_DIVE`, `Tower Dive`, `Băng trụ`, GameTagCategory.CHAMPION),
  createTag(`DUELING`, `Dueling`, `Đấu tay đôi`, GameTagCategory.CHAMPION),
  createTag(
    `AREA_CC`,
    `Area Crowd Control`,
    `Khống chế diện rộng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    `FLANK_ANGLE`,
    `Flank Angle`,
    `Góc đánh bọc hậu`,
    GameTagCategory.CHAMPION,
  ),
  createTag(`INTERRUPT`, `Interrupt`, `Ngắt kỹ năng`, GameTagCategory.CHAMPION),
  createTag(
    `SKILL_SHOT_ACCURACY`,
    `Skill Shot Accuracy`,
    `Độ chính xác kỹ năng định hướng`,
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'PICK_POTENTIAL',
    'Pick Potential',
    'Khả năng bắt lẻ',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'SCALING_DAMAGE',
    'Scaling Damage',
    'Sát thương tăng tiến',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'TEAMFIGHT_FOLLOWUP',
    'Teamfight Follow Up',
    'Theo giao tranh tốt',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'WAVE_CLEAR',
    'Wave Clear',
    'Dọn lính nhanh',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'WEAK_WHEN_BEHIND',
    'Weak When Behind',
    'Yếu khi bị thọt',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'HARD_TO_PLAY',
    'Hard To Play',
    'Khó chơi',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'WEAK_INTO_POINT_CLICK_CC',
    'Weak Into Point Click CC',
    'Yếu trước khống chế chỉ định',
    GameTagCategory.CHAMPION,
  ),
  createTag(
    'VULNERABLE_TO_DIVE',
    'Vulnerable To Dive',
    'Dễ bị lao vào',
    GameTagCategory.CHAMPION,
  ),

  // SKILL TAGS
  createTag(
    `MARK_OF_THE_STORM`,
    `Mark of the Storm`,
    `Dấu Ấn Sấm Sét`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `THUNDERING_SHURIKEN`,
    `Thundering Shuriken`,
    `Phi Tiêu Sấm Sét`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ELECTRICAL_SURGE`,
    `Electrical Surge`,
    `Giật Sét`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LIGHTNING_RUSH`,
    `Lightning Rush`,
    `Tốc Độ Sấm Sét`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SLICING_MAELSTROM`,
    `Slicing Maelstrom`,
    `Bão Sấm Sét`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DARKIN_SCYTHE`,
    `The Darkin Scythe`,
    `Lưỡi Hái Darkin`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SHADOW_ASSASSIN`,
    `Shadow Assassin`,
    `Sát Thủ Bóng Tối`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DARKIN_SLAYER`,
    `Darkin Slayer`,
    `Darkin Đoạt Mệnh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `OUT_OF_COMBAT_BURST`,
    `Out-of-combat burst`,
    `Dồn sát thương sau khi rời giao tranh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `REAPING_SLASH`,
    `Reaping Slash`,
    `Trảm Quét`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DOUBLE_HIT`,
    `Double hit`,
    `Hai lần gây sát thương`,
    GameTagCategory.SKILL,
  ),
  createTag(`BLADES_REACH`, `Blade's Reach`, `Phá`, GameTagCategory.SKILL),
  createTag(
    `LINE_ATTACK`,
    `Line attack`,
    `Đòn đánh theo đường thẳng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DECAYING_SLOW`,
    `Decaying slow`,
    `Làm chậm giảm dần`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SHADOW_STEP`,
    `Shadow Step`,
    `Bộ Pháp Bóng Tối`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SLOW_IMMUNITY`,
    `Slow immunity`,
    `Miễn nhiễm làm chậm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `UMBRAL_TRESPASS`,
    `Umbral Trespass`,
    `Nhập Hồn`,
    GameTagCategory.SKILL,
  ),
  createTag(`INFEST`, `Infest`, `Nhập vào mục tiêu`, GameTagCategory.SKILL),
  createTag(
    `DIVINE_ASCENT`,
    `Divine Ascent`,
    `Thượng Nhân Cảnh Giới`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LEVEL_SCALING`,
    `Level scaling`,
    `Tăng tiến theo cấp`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `RANGE_SCALING`,
    `Range scaling`,
    `Tăng tầm đánh theo cấp`,
    GameTagCategory.SKILL,
  ),
  createTag(`FLAME_WAVE`, `Flame wave`, `Sóng lửa`, GameTagCategory.SKILL),
  createTag(
    `RADIANT_BLAST`,
    `Radiant Blast`,
    `Hào Quang Trừng Phạt`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `RESISTANCE_REDUCTION`,
    `Resistance reduction`,
    `Giảm chống chịu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CELESTIAL_BLESSING`,
    `Celestial Blessing`,
    `Thiên Giới Ban Phước`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STARFIRE_SPELLBLADE`,
    `Starfire Spellblade`,
    `Kiếm Tinh Hỏa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `AOE_ON_HIT`,
    `AoE on-hit`,
    `Đòn đánh lan diện rộng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DIVINE_JUDGMENT`,
    `Divine Judgment`,
    `Thần Linh Định Đoạt`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_PROTECTION`,
    `Ally protection`,
    `Bảo vệ đồng minh`,
    GameTagCategory.SKILL,
  ),
  createTag(`VORACITY`, `Voracity`, `Tham Lam`, GameTagCategory.SKILL),
  createTag(`DAGGER`, `Dagger`, `Dao Găm`, GameTagCategory.SKILL),
  createTag(
    `COOLDOWN_RESET`,
    `Cooldown reset`,
    `Làm mới hồi chiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DAGGER_SETUP`,
    `Dagger setup`,
    `Thiết lập Dao Găm`,
    GameTagCategory.SKILL,
  ),
  createTag(`SHUNPO`, `Shunpo`, `Ám Sát`, GameTagCategory.SKILL),
  createTag(
    `DAGGER_PICKUP`,
    `Dagger pickup`,
    `Nhặt Dao Găm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DEATH_LOTUS`,
    `Death Lotus`,
    `Bông Sen Tử Thần`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `GRIEVOUS_WOUNDS`,
    `Grievous Wounds`,
    `Vết Thương Sâu`,
    GameTagCategory.SKILL,
  ),
  createTag(`VOID_STONE`, `Void Stone`, `Đá Hư Không`, GameTagCategory.SKILL),
  createTag(
    `SELF_SHIELD`,
    `Self shield`,
    `Tự tạo lá chắn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `NULL_SPHERE`,
    `Null Sphere`,
    `Quả Cầu Hư Không`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `NETHER_BLADE`,
    `Nether Blade`,
    `Lưỡi Kiếm Âm Ti`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `FORCE_PULSE`,
    `Force Pulse`,
    `Áp Suất Hư Không`,
    GameTagCategory.SKILL,
  ),
  createTag(`RIFTWALK`, `Riftwalk`, `Hư Vô Bộ Pháp`, GameTagCategory.SKILL),
  createTag(`BLINK`, `Blink`, `Dịch chuyển tức thời`, GameTagCategory.SKILL),
  createTag(
    `MANA_SCALING`,
    `Mana scaling`,
    `Tỉ lệ theo năng lượng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STACKING_DAMAGE`,
    `Stacking damage`,
    `Sát thương cộng dồn`,
    GameTagCategory.SKILL,
  ),
  createTag(`MANTRA`, `Mantra`, `Mantra`, GameTagCategory.SKILL),
  createTag(
    `EMPOWERED_ABILITY`,
    `Empowered ability`,
    `Kỹ năng cường hóa`,
    GameTagCategory.SKILL,
  ),
  createTag(`TETHER`, `Tether`, `Liên kết`, GameTagCategory.SKILL),
  createTag(
    `ULTIMATE_EMPOWER`,
    `Ultimate empower`,
    `Chiêu cuối cường hóa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MARTIAL_POISE`,
    `Martial Poise`,
    `Phong Thái Quân Nhân`,
    GameTagCategory.SKILL,
  ),
  createTag(`OATHSWORN`, `Oathsworn`, `Thệ Ước`, GameTagCategory.SKILL),
  createTag(
    `BOOT_SCALING`,
    `Boot scaling`,
    `Tỉ lệ theo bậc giày`,
    GameTagCategory.SKILL,
  ),
  createTag(`SPEAR`, `Spear`, `Lao`, GameTagCategory.SKILL),
  createTag(
    `REND_STACK_TRANSFER`,
    `Rend stack transfer`,
    `Chuyển cộng dồn Giày Vò`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SOUL_SENTINEL`,
    `Soul Sentinel`,
    `Lính Canh Linh Hồn`,
    GameTagCategory.SKILL,
  ),
  createTag(`PATROL`, `Patrol`, `Tuần tra`, GameTagCategory.SKILL),
  createTag(`REND`, `Rend`, `Giày Vò`, GameTagCategory.SKILL),
  createTag(
    `FATES_CALL`,
    `Fate's Call`,
    `Định Mệnh Vẫy Gọi`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_ENGAGE`,
    `Ally engage`,
    `Đồng minh mở giao tranh`,
    GameTagCategory.SKILL,
  ),
  createTag(`PLASMA`, `Plasma`, `Plasma`, GameTagCategory.SKILL),
  createTag(
    `LIVING_WEAPON`,
    `Living Weapon`,
    `Vũ Khí Sống`,
    GameTagCategory.SKILL,
  ),
  createTag(`MULTI_HIT`, `Multi-hit`, `Đa lần trúng`, GameTagCategory.SKILL),
  createTag(
    `BACKLINE_ACCESS`,
    `Backline access`,
    `Tiếp cận tuyến sau`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `KILLER_INSTINCT`,
    `Killer Instinct`,
    `Bản Năng Sát Thủ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DAUNTLESS_INSTINCT`,
    `Dauntless Instinct`,
    `Bản năng bất khuất`,
    GameTagCategory.SKILL,
  ),
  createTag(`ALL_OUT`, `All Out`, `Khô máu`, GameTagCategory.SKILL),
  createTag(
    `MAX_HEALTH_DAMAGE`,
    `Max Health Damage`,
    `Sát thương theo máu tối đa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `NTOFO_STRIKES`,
    `Ntofo Strikes`,
    `Ntofo công phá`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STACKING_ABILITY`,
    `Stacking Ability`,
    `Kỹ năng cộng dồn`,
    GameTagCategory.SKILL,
  ),
  createTag(`SHOCKWAVE`, `Shockwave`, `Sóng xung kích`, GameTagCategory.SKILL),
  createTag(`PULL`, `Pull`, `Kéo`, GameTagCategory.SKILL),
  createTag(`PATH_MAKER`, `Path Maker`, `Mở đường`, GameTagCategory.SKILL),
  createTag(
    `CHARGED_DASH`,
    `Charged Dash`,
    `Lướt tụ lực`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `FOOTWORK`,
    `Footwork`,
    `Bước chân dũng mãnh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_SHIELD`,
    `Ally Shield`,
    `Lá chắn đồng minh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BONUS_HEALTH_SCALING`,
    `Bonus Health Scaling`,
    `Tỉ lệ theo máu cộng thêm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DEMOLISHING_STRIKE`,
    `Demolishing Strike`,
    `Cú đánh phá hủy`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `WALL_COLLISION`,
    `Wall Collision`,
    `Va chạm tường`,
    GameTagCategory.SKILL,
  ),
  createTag(`OMNIVAMP`, `Omnivamp`, `Hút máu toàn phần`, GameTagCategory.SKILL),
  createTag(`GET_EXCITED`, `Get Excited!`, `Hưng phấn`, GameTagCategory.SKILL),
  createTag(
    `TAKEDOWN_RESET`,
    `Takedown Reset`,
    `Kích hoạt khi tham gia hạ gục`,
    GameTagCategory.SKILL,
  ),
  createTag(`SWITCHEROO`, `Switcheroo!`, `Tráo hàng`, GameTagCategory.SKILL),
  createTag(`WEAPON_SWAP`, `Weapon Swap`, `Đổi vũ khí`, GameTagCategory.SKILL),
  createTag(
    `ROCKET_LAUNCHER`,
    `Rocket Launcher`,
    `Súng phóng lựu`,
    GameTagCategory.SKILL,
  ),
  createTag(`MINIGUN`, `Minigun`, `Súng nhỏ`, GameTagCategory.SKILL),
  createTag(`ZAP`, `Zap!`, `Giật bắn`, GameTagCategory.SKILL),
  createTag(
    `FLAME_CHOMPERS`,
    `Flame Chompers!`,
    `Lựu đạn ma hỏa`,
    GameTagCategory.SKILL,
  ),
  createTag(`TRAP`, `Trap`, `Bẫy`, GameTagCategory.SKILL),
  createTag(
    `DASH_INTERRUPT`,
    `Dash Interrupt`,
    `Ngắt lướt`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SUPER_MEGA_DEATH_ROCKET`,
    `Super Mega Death Rocket!`,
    `Tên lửa đạn đạo siêu khủng khiếp`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LONG_RANGE_EXECUTE`,
    `Long Range Execute`,
    `Kết liễu tầm xa`,
    GameTagCategory.SKILL,
  ),
  createTag(`WHISPER`, `Whisper`, `Lời thì thầm`, GameTagCategory.SKILL),
  createTag(
    `FOURTH_SHOT`,
    `Fourth Shot`,
    `Viên đạn thứ tư`,
    GameTagCategory.SKILL,
  ),
  createTag(`RELOAD`, `Reload`, `Nạp đạn`, GameTagCategory.SKILL),
  createTag(
    `DANCING_GRENADE`,
    `Dancing Grenade`,
    `Lựu đạn nhảy múa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `EXECUTE_CHAIN`,
    `Execute Chain`,
    `Chuỗi kết liễu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MULTI_TARGET`,
    `Multi Target`,
    `Đa mục tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DEADLY_FLOURISH`,
    `Deadly Flourish`,
    `Nét vẽ chết chóc`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CAPTIVE_AUDIENCE`,
    `Captive Audience`,
    `Cạm bẫy nghệ thuật`,
    GameTagCategory.SKILL,
  ),
  createTag(`LOTUS_TRAP`, `Lotus Trap`, `Bẫy hoa sen`, GameTagCategory.SKILL),
  createTag(
    `INVISIBLE_TRAP`,
    `Invisible Trap`,
    `Bẫy vô hình`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CURTAIN_CALL`,
    `Curtain Call`,
    `Sân khấu tử thần`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HEXTECH_CAPACITOR`,
    `Hextech Capacitor`,
    `Tụ điện Hextech`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TO_THE_SKIES`,
    `To The Skies!`,
    `Chỉ thiên`,
    GameTagCategory.SKILL,
  ),
  createTag(`SHOCK_BLAST`, `Shock Blast`, `Cầu sấm`, GameTagCategory.SKILL),
  createTag(
    `ACCELERATION_GATE_SYNERGY`,
    `Acceleration Gate Synergy`,
    `Tương tác cổng tăng tốc`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LIGHTNING_FIELD`,
    `Lightning Field`,
    `Tích tụ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HYPER_CHARGE`,
    `Hyper Charge`,
    `Sạc siêu tốc`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MANA_RESTORE`,
    `Mana Restore`,
    `Hồi năng lượng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `THUNDERING_BLOW`,
    `Thundering Blow`,
    `Lôi phạt`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ACCELERATION_GATE`,
    `Acceleration Gate`,
    `Cổng tăng tốc`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MERCURY_CANNON`,
    `Mercury Cannon`,
    `Pháo thủy ngân`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MERCURY_HAMMER`,
    `Mercury Hammer`,
    `Búa thủy ngân`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `STANCE_CHANGE`,
    `Stance Change`,
    `Đổi thế chiến đấu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `RELENTLESS_ASSAULT`,
    `Relentless Assault`,
    `Không khoan nhượng`,
    GameTagCategory.SKILL,
  ),
  createTag(`LEAP_STRIKE`, `Leap Strike`, `Nhảy và nện`, GameTagCategory.SKILL),
  createTag(
    `TARGETED_LEAP`,
    `Targeted Leap`,
    `Nhảy chọn mục tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(`EMPOWER`, `Empower`, `Vận sức`, GameTagCategory.SKILL),
  createTag(
    `ATTACK_RESET`,
    `Attack Reset`,
    `Tái tạo đòn đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MONSTER_DAMAGE_MODIFIER`,
    `Monster Damage Modifier`,
    `Điều chỉnh sát thương lên quái`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `COUNTER_STRIKE`,
    `Counter Strike`,
    `Phản công`,
    GameTagCategory.SKILL,
  ),
  createTag(`DODGE`, `Dodge`, `Né đòn`, GameTagCategory.SKILL),
  createTag(
    `ATTACK_DODGE`,
    `Attack Dodge`,
    `Né đòn đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `GRANDMASTER_AT_ARMS`,
    `Grandmaster-at-Arms`,
    `Sức mạnh bậc thầy`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `EVERY_THIRD_ATTACK`,
    `Every Third Attack`,
    `Mỗi đòn thứ ba`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SIZE_INCREASE`,
    `Size Increase`,
    `Tăng kích cỡ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MARTIAL_CADENCE`,
    `Martial Cadence`,
    `Thương thuật`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BASIC_ATTACK_MODIFIER`,
    `Basic Attack Modifier`,
    `Biến đổi đòn đánh thường`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DRAGON_STRIKE`,
    `Dragon Strike`,
    `Giáng long kích`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `FLAG_AND_DRAG`,
    `Flag and Drag`,
    `Combo cắm cờ kéo người`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `GOLDEN_AEGIS`,
    `Golden Aegis`,
    `Hoàng kim giáp`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MAX_HEALTH_SCALING`,
    `Max Health Scaling`,
    `Tỉ lệ theo máu tối đa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `NEARBY_ENEMY_SCALING`,
    `Nearby Enemy Scaling`,
    `Tỉ lệ theo kẻ địch gần đó`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DEMACIAN_STANDARD`,
    `Demacian Standard`,
    `Hoàng kỳ Demacia`,
    GameTagCategory.SKILL,
  ),
  createTag(`CATACLYSM`, `Cataclysm`, `Đại địa chấn`, GameTagCategory.SKILL),
  createTag(`ARENA`, `Arena`, `Đấu trường`, GameTagCategory.SKILL),
  createTag(`TAILWIND`, `Tailwind`, `Thuận gió`, GameTagCategory.SKILL),
  createTag(`AURA`, `Aura`, `Hào quang`, GameTagCategory.SKILL),
  createTag(`HOWLING_GALE`, `Howling Gale`, `Gió lốc`, GameTagCategory.SKILL),
  createTag(
    `STORED_CHARGES`,
    `Stored Charges`,
    `Điểm dùng tích trữ`,
    GameTagCategory.SKILL,
  ),
  createTag(`ZEPHYR`, `Zephyr`, `Gió tây`, GameTagCategory.SKILL),
  createTag(
    `AUTO_TARGET`,
    `Auto Target`,
    `Tự chọn mục tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_BUFF`,
    `Ally Buff`,
    `Cường hóa đồng minh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `EYE_OF_THE_STORM`,
    `Eye Of The Storm`,
    `Mắt bão`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ATTACK_DAMAGE_BUFF`,
    `Attack Damage Buff`,
    `Tăng sức mạnh công kích`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LOW_HEALTH_ALLY_TARGETING`,
    `Low Health Ally Targeting`,
    `Chọn đồng minh thấp máu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TURRET_SHIELD`,
    `Turret Shield`,
    `Lá chắn cho trụ`,
    GameTagCategory.SKILL,
  ),
  createTag(`MONSOON`, `Monsoon`, `Gió mùa`, GameTagCategory.SKILL),
  createTag(
    `IONIAN_FERVOR`,
    `Ionian Fervor`,
    `Tinh Thần Ionia`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ON_HIT_DAMAGE`,
    `On-Hit Damage`,
    `Sát thương trên đòn đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(`BLADESURGE`, `Bladesurge`, `Đâm kiếm`, GameTagCategory.SKILL),
  createTag(
    `MARK_CONSUME`,
    `Mark Consume`,
    `Tiêu thụ đánh dấu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MINION_DAMAGE_MODIFIER`,
    `Minion Damage Modifier`,
    `Điều chỉnh sát thương lên lính`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DEFIANT_DANCE`,
    `Defiant Dance`,
    `Vũ điệu thách thức`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CHARGED_RELEASE`,
    `Charged Release`,
    `Tung chiêu sau khi tích lực`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `UNINTERRUPTIBLE`,
    `Uninterruptible`,
    `Không thể bị ngắt`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `FLAWLESS_DUET`,
    `Flawless Duet`,
    `Bước nhảy hoàn vũ`,
    GameTagCategory.SKILL,
  ),
  createTag(`MARK`, `Mark`, `Đánh dấu`, GameTagCategory.SKILL),
  createTag(
    `BLADE_CONVERGE`,
    `Blade Converge`,
    `Kiếm hội tụ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `VANGUARDS_EDGE`,
    `Vanguard's Edge`,
    `Thanh kiếm tiên phong`,
    GameTagCategory.SKILL,
  ),
  createTag(`BLADE_WALL`, `Blade Wall`, `Tường kiếm`, GameTagCategory.SKILL),
  createTag(
    `HEXTECH_AFFINITY`,
    `Hextech Affinity`,
    `Ái Lực Hextech`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TURRET_SYNERGY`,
    `Turret Synergy`,
    `Tương Tác Với Ụ Súng`,
    GameTagCategory.SKILL,
  ),
  createTag(`TURRET`, `Turret`, `Ụ súng`, GameTagCategory.SKILL),
  createTag(
    `DEPLOYABLE`,
    `Deployable`,
    `Đơn vị triển khai`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `UPGRADE_SYNERGY`,
    `Upgrade Synergy`,
    `Tương tác nâng cấp`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MICRO_ROCKETS`,
    `Micro-Rockets`,
    `Tên lửa cỡ nhỏ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TURRET_CHARGE`,
    `Turret Charge`,
    `Nạp năng lượng ụ súng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ELECTRON_STORM_GRENADE`,
    `Electron Storm Grenade`,
    `Lựu đạn bão điện tử`,
    GameTagCategory.SKILL,
  ),
  createTag(`GRENADE`, `Grenade`, `Lựu đạn`, GameTagCategory.SKILL),
  createTag(`UPGRADE`, `Upgrade`, `Nâng cấp`, GameTagCategory.SKILL),
  createTag(
    `ABILITY_UPGRADE`,
    `Ability Upgrade`,
    `Nâng cấp kỹ năng`,
    GameTagCategory.SKILL,
  ),
  createTag(`WARPATH`, `Warpath`, `Đường Ra Trận`, GameTagCategory.SKILL),
  createTag(
    `MOVEMENT_SPEED_SCALING`,
    `Movement Speed Scaling`,
    `Tỉ lệ theo Tốc Độ Di Chuyển`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BONUS_ATTACK_DAMAGE`,
    `Bonus Attack Damage`,
    `Sức Mạnh Công Kích cộng thêm`,
    GameTagCategory.SKILL,
  ),
  createTag(`RAMPAGE`, `Rampage`, `Càn Quét`, GameTagCategory.SKILL),
  createTag(
    `SPIRIT_OF_DREAD`,
    `Spirit of Dread`,
    `Nhiếp Hồn Trận`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DEVASTATING_CHARGE`,
    `Devastating Charge`,
    `Vó Ngựa Hủy Diệt`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ONSLAUGHT_OF_SHADOWS`,
    `Onslaught of Shadows`,
    `Bóng Ma Kị Sĩ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LONG_RANGE_ENGAGE`,
    `Long-Range Engage`,
    `Mở giao tranh tầm xa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `THOUSAND_CUTS`,
    `Thousand Cuts`,
    `Ngàn Nhát Cắt`,
    GameTagCategory.SKILL,
  ),
  createTag(`SNIP_SNIP`, `Snip Snip!`, `Xoẹt Xoẹt!`, GameTagCategory.SKILL),
  createTag(
    `STACK_CONSUME`,
    `Stack Consume`,
    `Tiêu thụ cộng dồn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HALLOWED_MIST`,
    `Hallowed Mist`,
    `Sương Lam Bất Bại`,
    GameTagCategory.SKILL,
  ),
  createTag(`SKIP_N_SLASH`, `Skip 'n Slash`, `Xén Xén`, GameTagCategory.SKILL),
  createTag(
    `NEEDLEWORK`,
    `Needlework`,
    `Xe Chỉ Luồn Kim`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `NEW_DESTINY`,
    `New Destiny`,
    `Vận Mệnh Thay Đổi`,
    GameTagCategory.SKILL,
  ),
  createTag(`SHOTGUN`, `Shotgun`, `Súng shotgun`, GameTagCategory.SKILL),
  createTag(
    `DELAYED_DETONATION`,
    `Delayed Detonation`,
    `Phát nổ trễ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TERRAIN_INTERACTION`,
    `Terrain Interaction`,
    `Tương tác địa hình`,
    GameTagCategory.SKILL,
  ),
  createTag(`SMOKE_SCREEN`, `Smoke Screen`, `Bom Mù`, GameTagCategory.SKILL),
  createTag(`QUICKDRAW`, `Quickdraw`, `Rút Súng Nhanh`, GameTagCategory.SKILL),
  createTag(`TRUE_GRIT`, `True Grit`, `Lì Đòn`, GameTagCategory.SKILL),
  createTag(
    `BONUS_ARMOR`,
    `Bonus Armor`,
    `Giáp cộng thêm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `COLLATERAL_DAMAGE`,
    `Collateral Damage`,
    `Đạn Nổ Thần Công`,
    GameTagCategory.SKILL,
  ),
  createTag(`RECOIL`, `Recoil`, `Lực giật`, GameTagCategory.SKILL),
  createTag(
    `HAPPY_HOUR`,
    `Happy Hour`,
    `Giờ Khuyến Mãi`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BARREL_ROLL`,
    `Barrel Roll`,
    `Lăn Thùng Rượu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DRUNKEN_RAGE`,
    `Drunken Rage`,
    `Say Quá Hóa Cuồng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BODY_SLAM`,
    `Body Slam`,
    `Lấy Thịt Đè Người`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `EXPLOSIVE_CASK`,
    `Explosive Cask`,
    `Thùng Rượu Nổ`,
    GameTagCategory.SKILL,
  ),
  createTag(`RAGE_GENE`, `Rage Gene`, `Gien Cuồng Nộ`, GameTagCategory.SKILL),
  createTag(`RAGE`, `Rage`, `Cuồng Nộ`, GameTagCategory.SKILL),
  createTag(
    `TRANSFORMATION`,
    `Transformation`,
    `Biến hình`,
    GameTagCategory.SKILL,
  ),
  createTag(`MEGA_GNAR`, `Mega Gnar`, `Gnar Khổng Lồ`, GameTagCategory.SKILL),
  createTag(`MINI_GNAR`, `Mini Gnar`, `Gnar Tí Nị`, GameTagCategory.SKILL),
  createTag(
    `BOOMERANG_THROW`,
    `Boomerang Throw`,
    `Ném Boomerang`,
    GameTagCategory.SKILL,
  ),
  createTag(`BOULDER_TOSS`, `Boulder Toss`, `Ném Đá`, GameTagCategory.SKILL),
  createTag(`HYPER`, `Hyper`, `Quá Khích`, GameTagCategory.SKILL),
  createTag(`WALLOP`, `Wallop`, `Đập Phá`, GameTagCategory.SKILL),
  createTag(`HOP`, `Hop`, `Nhún Nhảy`, GameTagCategory.SKILL),
  createTag(`CRUNCH`, `Crunch`, `Nghiền Nát`, GameTagCategory.SKILL),
  createTag(`GNAR_ULTIMATE`, `GNAR!`, `GNAR!`, GameTagCategory.SKILL),
  createTag(
    `WALL_STUN`,
    `Wall Stun`,
    `Choáng khi va tường`,
    GameTagCategory.SKILL,
  ),
  createTag(`PERSEVERANCE`, `Perseverance`, `Bền Bỉ`, GameTagCategory.SKILL),
  createTag(
    `DECISIVE_STRIKE`,
    `Decisive Strike`,
    `Đòn Quyết Định`,
    GameTagCategory.SKILL,
  ),
  createTag(`COURAGE`, `Courage`, `Can Đảm`, GameTagCategory.SKILL),
  createTag(`TENACITY`, `Tenacity`, `Kháng hiệu ứng`, GameTagCategory.SKILL),
  createTag(`JUDGMENT`, `Judgment`, `Phán Quyết`, GameTagCategory.SKILL),
  createTag(`SPIN`, `Spin`, `Xoay kiếm`, GameTagCategory.SKILL),
  createTag(
    `DEMACIAN_JUSTICE`,
    `Demacian Justice`,
    `Công Lý Demacia`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `COLOSSAL_SMASH`,
    `Colossal Smash`,
    `Cú Nện Khổng Lồ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MAGIC_RESIST_SCALING`,
    `Magic Resist Scaling`,
    `Tỉ lệ theo Kháng Phép`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SHIELD_OF_DURAND`,
    `Shield of Durand`,
    `Lá Chắn Durand`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MAGIC_SHIELD`,
    `Magic Shield`,
    `Lá chắn phép`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `COLLISION_DASH`,
    `Collision Dash`,
    `Lướt va chạm`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HEROS_ENTRANCE`,
    `Hero's Entrance`,
    `Siêu Hùng Giáng Thế`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SEASTONE_TRIDENT`,
    `Seastone Trident`,
    `Đinh Ba Hải Thạch`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `RENDING_WAVE`,
    `Rending Wave`,
    `Sóng Xé Toạc`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `PLAYFUL_TRICKSTER`,
    `Playful / Trickster`,
    `Tung Tăng / Nhảy Múa`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CHUM_THE_WATERS`,
    `Chum the Waters`,
    `Triệu Hồi Thủy Quái`,
    GameTagCategory.SKILL,
  ),
  createTag(`SHARK`, `Shark`, `Cá mập`, GameTagCategory.SKILL),
  createTag(
    `ATTACHED_PROJECTILE`,
    `Attached Projectile`,
    `Đạn bám mục tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(`VITAL`, `Vital`, `Điểm Yếu`, GameTagCategory.SKILL),
  createTag(`RIPOSTE`, `Riposte`, `Phản đòn`, GameTagCategory.SKILL),
  createTag(`PARRY`, `Parry`, `Chặn đòn`, GameTagCategory.SKILL),
  createTag(
    `SCARECROW_EFFIGY`,
    `Scarecrow Effigy`,
    `Hình Nhân Bù Nhìn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `EFFIGY_IMPERSONATION`,
    `Effigy Impersonation`,
    `Giả dạng hình nhân`,
    GameTagCategory.SKILL,
  ),
  createTag(`DRAIN`, `Drain`, `Hút máu`, GameTagCategory.SKILL),
  createTag(`CROWSTORM`, `Crowstorm`, `Bão Quạ`, GameTagCategory.SKILL),
  createTag(
    `ESSENCE_FLUX`,
    `Essence Flux`,
    `Tinh Hoa Tuôn Chảy`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MARK_DETONATION`,
    `Mark Detonation`,
    `Kích nổ dấu ấn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MANA_REFUND`,
    `Mana Refund`,
    `Hoàn lại năng lượng`,
    GameTagCategory.SKILL,
  ),
  createTag(`DEMON_SHADE`, `Demon Shade`, `Yêu Ảnh`, GameTagCategory.SKILL),
  createTag(`CURSE`, `Curse`, `Nguyền rủa`, GameTagCategory.SKILL),
  createTag(
    `ON_HIT_EFFECTS`,
    `On-Hit Effects`,
    `Hiệu ứng đòn đánh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BACKWARD_WARP`,
    `Backward Warp`,
    `Dịch chuyển lùi`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CHRONOSPHERE`,
    `Chronosphere`,
    `Vùng thời không`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TIME_REWIND`,
    `Time Rewind`,
    `Quay ngược thời gian`,
    GameTagCategory.SKILL,
  ),
  createTag(
    'SKILL_SHOT',
    'Skill Shot',
    'Kỹ năng định hướng',
    GameTagCategory.SKILL,
  ),
  createTag('KNOCK_BACK', 'Knock Back', 'Đẩy lùi', GameTagCategory.SKILL),
  createTag('STUN', 'Stun', 'Làm choáng', GameTagCategory.SKILL),
  createTag('CAMOUFLAGE', 'Camouflage', 'Ngụy trang', GameTagCategory.SKILL),
  createTag(
    'DOUBLE_SHOT',
    'Double Shot',
    'Bắn thêm phát thứ hai',
    GameTagCategory.SKILL,
  ),
  createTag(
    'CRITICAL_SCALING',
    'Critical Scaling',
    'Tăng sức mạnh theo tỉ lệ chí mạng',
    GameTagCategory.SKILL,
  ),
  createTag(
    'MISSING_HEALTH_DAMAGE',
    'Missing Health Damage',
    'Sát thương theo máu đã mất',
    GameTagCategory.SKILL,
  ),
  createTag('LOCK_ON', 'Lock On', 'Khóa mục tiêu', GameTagCategory.SKILL),
  createTag(
    'MULTI_CAST',
    'Multi Cast',
    'Kỹ năng có nhiều lần sử dụng',
    GameTagCategory.SKILL,
  ),
  createTag(
    'ARMOR_PENETRATION',
    'Armor Penetration',
    'Xuyên giáp',
    GameTagCategory.SKILL,
  ),
  createTag('SUPPRESS', 'Suppress', 'Áp chế', GameTagCategory.SKILL),
  createTag(
    'UNSTOPPABLE',
    'Unstoppable',
    'Không thể bị cản phá',
    GameTagCategory.SKILL,
  ),
  createTag(
    'PHYSICAL_VAMP',
    'Physical Vamp',
    'Hút máu vật lý',
    GameTagCategory.SKILL,
  ),
  createTag('ROOT', 'Root', 'Trói chân', GameTagCategory.SKILL),
  createTag('TOGGLE', 'Toggle', 'Kỹ năng bật tắt', GameTagCategory.SKILL),
  createTag(
    'STACKING_PASSIVE',
    'Stacking Passive',
    'Nội tại tích cộng dồn',
    GameTagCategory.SKILL,
  ),
  createTag(
    'BURST_SETUP',
    'Burst Setup',
    'Thiết lập dồn sát thương',
    GameTagCategory.SKILL,
  ),
  createTag(
    'LAST_HIT_REFUND',
    'Last Hit Refund',
    'Hoàn trả tài nguyên khi kết liễu',
    GameTagCategory.SKILL,
  ),
  createTag(
    'CONE_DAMAGE',
    'Cone Damage',
    'Sát thương hình nón',
    GameTagCategory.SKILL,
  ),
  createTag(
    'SELF_BUFF',
    'Self Buff',
    'Tự cường hóa bản thân',
    GameTagCategory.SKILL,
  ),
  createTag(
    'SUMMON_SUPPORT',
    'Summon Support',
    'Hỗ trợ đơn vị triệu hồi',
    GameTagCategory.SKILL,
  ),
  createTag('SUMMON', 'Summon', 'Triệu hồi', GameTagCategory.SKILL),
  createTag(
    'ATTACK_SPEED_STEROID',
    'Attack Speed Steroid',
    'Tăng mạnh tốc độ đánh',
    GameTagCategory.SKILL,
  ),
  createTag('VISION', 'Vision', 'Cung cấp tầm nhìn', GameTagCategory.SKILL),
  createTag(
    'GLOBAL_RANGE',
    'Global Range',
    'Tầm sử dụng toàn bản đồ',
    GameTagCategory.SKILL,
  ),
  createTag(
    'STEERABLE_PROJECTILE',
    'Steerable Projectile',
    'Đạn có thể điều khiển hướng bay',
    GameTagCategory.SKILL,
  ),
  createTag(
    'ABILITY_EVOLUTION',
    'Ability Evolution',
    'Kỹ năng tiến hóa theo cộng dồn',
    GameTagCategory.SKILL,
  ),
  createTag(
    'CHANNEL',
    'Channel',
    'Vận sức duy trì kỹ năng',
    GameTagCategory.SKILL,
  ),
  createTag(
    'FLIGHT',
    'Flight',
    'Bay theo hướng chỉ định',
    GameTagCategory.SKILL,
  ),
  createTag(
    'COOLDOWN_REFUND',
    'Cooldown Refund',
    'Hoàn trả hồi chiêu',
    GameTagCategory.SKILL,
  ),
  createTag(
    'REALM_HOPPER',
    'Realm Hopper',
    'Nhảy giữa các vùng linh giới',
    GameTagCategory.SKILL,
  ),
  createTag(
    'SELF_DISPLACEMENT',
    'Self Displacement',
    'Tự dịch chuyển vị trí',
    GameTagCategory.SKILL,
  ),
  createTag(
    'BOUNDARY_CONTROL',
    'Boundary Control',
    'Kiểm soát ranh giới vùng',
    GameTagCategory.SKILL,
  ),
  createTag('RECAST', 'Recast', 'Tái kích hoạt', GameTagCategory.SKILL),
  createTag('STEALTH', 'Stealth', 'Tàng hình', GameTagCategory.SKILL),
  createTag('SPEED_UP', 'Speed Up', 'Tăng tốc', GameTagCategory.SKILL),
  createTag(
    'ENERGY_RESTORE',
    'Energy Restore',
    'Hồi nội năng',
    GameTagCategory.SKILL,
  ),
  createTag('STASIS', 'Stasis', 'Ngưng đọng', GameTagCategory.SKILL),
  createTag(
    'AOE_STASIS',
    'Area Stasis',
    'Ngưng đọng diện rộng',
    GameTagCategory.SKILL,
  ),
  createTag('PORTAL', 'Portal', 'Cổng dịch chuyển', GameTagCategory.SKILL),
  createTag(
    'TERRAIN_TRAVEL',
    'Terrain Travel',
    'Di chuyển xuyên địa hình',
    GameTagCategory.SKILL,
  ),
  createTag('SHRINE', 'Shrine', 'Điện hồi phục', GameTagCategory.SKILL),
  createTag('CHIME', 'Chime', 'Chuông ma thuật', GameTagCategory.SKILL),
  createTag('MEEP', 'Meep', 'Meep hỗ trợ', GameTagCategory.SKILL),
  createTag(
    'ALLY_HEAL',
    'Ally Heal',
    'Hồi máu cho đồng minh',
    GameTagCategory.SKILL,
  ),
  createTag(
    'EMPOWERED_ATTACK',
    'Empowered Attack',
    'Đòn đánh cường hóa',
    GameTagCategory.SKILL,
  ),
  createTag('HOOK', 'Hook', 'Kéo móc', GameTagCategory.SKILL),
  createTag(
    'LOW_HEALTH_TRIGGER',
    'Low Health Trigger',
    'Kích hoạt khi thấp máu',
    GameTagCategory.SKILL,
  ),
  createTag(
    'DECAYING_MOVEMENT_SPEED',
    'Decaying Movement Speed',
    'Tốc độ di chuyển giảm dần',
    GameTagCategory.SKILL,
  ),
  createTag(
    'SELF_SLOW',
    'Self Slow',
    'Tự làm chậm bản thân',
    GameTagCategory.SKILL,
  ),
  createTag(
    'CRITICAL_STRIKE',
    'Critical Strike',
    'Chí mạng',
    GameTagCategory.SKILL,
  ),
  createTag(
    'PASSIVE_DAMAGE',
    'Passive Damage',
    'Sát thương nội tại',
    GameTagCategory.SKILL,
  ),
  createTag('SILENCE', 'Silence', 'Câm lặng', GameTagCategory.SKILL),
  createTag(
    'AUTO_ATTACK_RESET',
    'Auto Attack Reset',
    'Tái tạo đòn đánh thường',
    GameTagCategory.SKILL,
  ),
  createTag(`BLAZE`, `Blaze`, `Bỏng Cháy`, GameTagCategory.SKILL),
  createTag(
    `DAMAGE_OVER_TIME`,
    `Damage Over Time`,
    `Sát Thương Theo Thời Gian`,
    GameTagCategory.SKILL,
  ),
  createTag(`DETONATION`, `Detonation`, `Phát Nổ`, GameTagCategory.SKILL),
  createTag(
    `BLAZE_SYNERGY`,
    `Blaze Synergy`,
    `Tương Tác Bỏng Cháy`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DELAYED_AREA`,
    `Delayed Area`,
    `Vùng Trì Hoãn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `SPREAD_DAMAGE`,
    `Spread Damage`,
    `Sát Thương Lan`,
    GameTagCategory.SKILL,
  ),
  createTag(`BOUNCE`, `Bounce`, `Nảy Mục Tiêu`, GameTagCategory.SKILL),
  createTag(
    `CONCUSSIVE_BLOWS`,
    `Concussive Blows`,
    `Đánh Ngất Ngư`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_FOLLOW_UP`,
    `Ally Follow-up`,
    `Đồng Minh Bồi Tiếp`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ALLY_DASH`,
    `Ally Dash`,
    `Lướt Tới Đồng Minh`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `BONUS_RESISTANCES`,
    `Bonus Resistances`,
    `Tăng Chống Chịu`,
    GameTagCategory.SKILL,
  ),
  createTag(`PROTECTION`, `Protection`, `Bảo Vệ`, GameTagCategory.SKILL),
  createTag(
    `PROJECTILE_BLOCK`,
    `Projectile Block`,
    `Chặn Đường Đạn`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DAMAGE_NEGATION`,
    `Damage Negation`,
    `Vô Hiệu Sát Thương`,
    GameTagCategory.SKILL,
  ),
  createTag(`FISSURE`, `Fissure`, `Khe Nứt`, GameTagCategory.SKILL),
  createTag(`HEADSHOT`, `Headshot`, `Thiện Xạ`, GameTagCategory.SKILL),
  createTag(
    `TRAP_SYNERGY`,
    `Trap Synergy`,
    `Tương Tác Bẫy`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `PIERCING_PROJECTILE`,
    `Piercing Projectile`,
    `Đạn Xuyên Mục Tiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HEADSHOT_SETUP`,
    `Headshot Setup`,
    `Thiết Lập Thiện Xạ`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ADAPTIVE_SHIELD`,
    `Adaptive Shield`,
    `Lá Chắn Thích Ứng`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `TRADING_TOOL`,
    `Trading Tool`,
    `Công Cụ Trao Đổi Chiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(`HOOKSHOT`, `Hookshot`, `Bắn Dây Móc`, GameTagCategory.SKILL),
  createTag(
    `TERRAIN_HOOK`,
    `Terrain Hook`,
    `Móc Địa Hình`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `LOCKDOWN_ZONE`,
    `Lockdown Zone`,
    `Vùng Khóa Chân`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CURRENT_HEALTH_DAMAGE`,
    `Current Health Damage`,
    `Sát Thương Theo Máu Hiện Tại`,
    GameTagCategory.SKILL,
  ),
  createTag(`PACKAGE`, `Package`, `Gói Hàng`, GameTagCategory.SKILL),
  createTag(`BIG_ONE`, `Big One`, `Quả Đại Bác`, GameTagCategory.SKILL),
  createTag(`ARMOR_SHRED`, `Armor Shred`, `Giảm Giáp`, GameTagCategory.SKILL),
  createTag(`MISSILE`, `Missile`, `Tên Lửa`, GameTagCategory.SKILL),
  createTag(
    `CHARGE_SYSTEM`,
    `Charge System`,
    `Cơ Chế Tích Trữ`,
    GameTagCategory.SKILL,
  ),
  createTag(`HEMORRHAGE`, `Hemorrhage`, `Xuất Huyết`, GameTagCategory.SKILL),
  createTag(`BLEED`, `Bleed`, `Chảy Máu`, GameTagCategory.SKILL),
  createTag(
    `NOXIAN_MIGHT`,
    `Noxian Might`,
    `Sức Mạnh Noxus`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `OUTER_EDGE_BONUS`,
    `Outer Edge Bonus`,
    `Thưởng Rìa Ngoài`,
    GameTagCategory.SKILL,
  ),
  createTag(`MOONLIGHT`, `Moonlight`, `Ánh Trăng`, GameTagCategory.SKILL),
  createTag(
    `DASH_SETUP`,
    `Dash Setup`,
    `Thiết Lập Lướt`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `ORBITING_SPHERES`,
    `Orbiting Spheres`,
    `Quả Cầu Xoay Quanh`,
    GameTagCategory.SKILL,
  ),
  createTag(`CHARGE`, `Charge`, `Tích Tụ`, GameTagCategory.SKILL),
  createTag(
    `MOONFALL_GLOW`,
    `Moonfall Glow`,
    `Ánh Trăng Rơi`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CC_RESIST`,
    `Crowd Control Resist`,
    `Kháng Khống Chế`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `CHEMICAL_CANISTER`,
    `Chemical Canister`,
    `Bình Hóa Chất`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HEALTH_REGEN`,
    `Health Regeneration`,
    `Hồi Máu Theo Thời Gian`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HEALTH_COST`,
    `Health Cost`,
    `Tiêu Hao Máu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `HEALTH_SCALING`,
    `Health Scaling`,
    `Tỉ Lệ Theo Máu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `MISSING_HEALTH_SCALING`,
    `Missing Health Scaling`,
    `Tỉ Lệ Theo Máu Đã Mất`,
    GameTagCategory.SKILL,
  ),
  createTag(`SPINNING_AXE`, `Spinning Axe`, `Rìu xoay`, GameTagCategory.SKILL),
  createTag(`AXE_CATCH`, `Axe Catch`, `Bắt rìu`, GameTagCategory.SKILL),
  createTag(
    `COOLDOWN_REFRESH`,
    `Cooldown Refresh`,
    `Làm mới hồi chiêu`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `RETURNING_PROJECTILE`,
    `Returning Projectile`,
    `Đạn bay quay lại`,
    GameTagCategory.SKILL,
  ),
  createTag(
    `DAMAGE_FALLOFF`,
    `Damage Falloff`,
    `Sát thương giảm dần`,
    GameTagCategory.SKILL,
  ),
];

export async function seedGameTags(prisma: PrismaClient) {
  console.log('Seeding game tags...');

  for (const gameTagSeed of gameTagSeeds) {
    await prisma.gameTag.upsert({
      where: {
        key: gameTagSeed.key,
      },
      update: {
        name: gameTagSeed.name,
        nameVi: gameTagSeed.nameVi,
        description: gameTagSeed.description,
        descriptionVi: gameTagSeed.descriptionVi,
        category: gameTagSeed.category,
        deletedAt: null,
      },
      create: gameTagSeed,
    });

    console.log(`Seeded game tag: ${gameTagSeed.key}`);
  }

  console.log('Seeded game tags');
}
