import { Prisma, PrismaClient } from '../../src/generated/prisma/client.js';
import {
  RuneEffectType,
  RuneStatType,
  RuneTriggerType,
  TargetType,
} from '../../src/generated/prisma/enums.js';

type RunePatchStatSeed = {
  key: string;
  isAvailable?: boolean;
  shortDescription?: string | null;
  fullDescription?: string | null;
  effectTypes: RuneEffectType[];
  triggerTypes: RuneTriggerType[];
  targetTypes: TargetType[];
  baseValue?: number | null;
  scalingValue?: number | null;
  cooldown?: number | null;
  duration?: number | null;
  maxStacks?: number | null;
  statTypes: RuneStatType[];
  statBonuses?: Prisma.InputJsonValue;
  notes?: string | null;
};

const runePatchStatSeeds: RunePatchStatSeed[] = [
  {
    key: `electrocute`,
    shortDescription: `Apply 3 stacks to the same champion within 3 seconds to deal adaptive damage.`,
    fullDescription: `Đòn đánh thường và kỹ năng trúng tướng địch sẽ tạo một cộng dồn Sốc Điện, tối đa một cộng dồn cho mỗi đòn đánh hoặc lần sử dụng kỹ năng. Khi đặt đủ 3 cộng dồn lên cùng một mục tiêu trong vòng 3 giây, mục tiêu bị sét đánh và nhận 40 - 210 sát thương thích ứng theo cấp độ, cộng thêm 10% Sức Mạnh Công Kích cộng thêm và 5% Sức Mạnh Phép Thuật. Hồi chiêu: 20 - 13 giây theo cấp độ.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [
      RuneTriggerType.ON_ATTACK,
      RuneTriggerType.ON_ABILITY_HIT,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 40,
    scalingValue: 210,
    cooldown: 20,
    maxStacks: 3,
    statTypes: [],
    statBonuses: {
      activationWindowSeconds: 3,
      requiredStacks: 3,
      maximumStacksPerAttackOrCast: 1,
      damage: {
        minimum: 40,
        maximum: 210,
        scaling: `LEVEL`,
        damageType: `ADAPTIVE`,
      },
      bonusAttackDamageRatio: 0.1,
      abilityPowerRatio: 0.05,
      cooldownSeconds: {
        minimum: 13,
        maximum: 20,
        scaling: `LEVEL`,
      },
    },
  },
  {
    key: `dark-harvest`,
    shortDescription: `Damage a champion below 50% Health to deal adaptive damage and harvest their soul.`,
    fullDescription: `Gây sát thương lên tướng địch còn dưới 50% Máu sẽ gây sát thương thích ứng và thu hoạch linh hồn của chúng, tăng vĩnh viễn sát thương của Thu Thập Hắc Ám. Sát thương cơ bản là 35, cộng thêm sát thương theo số linh hồn đã thu hoạch, 10% Sức Mạnh Công Kích cộng thêm và 5% Sức Mạnh Phép Thuật. Hồi chiêu: 20 giây. Khi tham gia hạ gục, thời gian hồi chiêu được đặt lại còn 1 giây.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.STACKING,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [
      RuneTriggerType.ON_TARGET_LOW_HEALTH,
      RuneTriggerType.ON_TAKEDOWN,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 35,
    cooldown: 20,
    statTypes: [],
    statBonuses: {
      healthThresholdPercent: 50,
      damage: {
        base: 35,
        damageType: `ADAPTIVE`,
        bonusAttackDamageRatio: 0.1,
        abilityPowerRatio: 0.05,
      },
      soulDamageIncrease: {
        descriptionValue: 10,
        formulaValue: 11,
        verificationStatus: `SOURCE_INCONSISTENT`,
      },
      cooldownSeconds: 20,
      takedownResetCooldownSeconds: 1,
      soulStacksUnlimited: true,
    },
    notes: `The source description says each soul increases damage by 10, while the displayed damage formula says 11 damage per soul. This discrepancy requires verification.`,
  },
  {
    key: `empowerment`,
    shortDescription: `Hit a champion with 3 consecutive basic attacks to deal adaptive damage and increase your damage dealt.`,
    fullDescription: `Đánh trúng một tướng địch bằng 3 đòn đánh thường liên tiếp sẽ gây thêm 40 - 165 sát thương thích ứng theo cấp độ và tăng 8% toàn bộ sát thương bạn gây ra. Hiệu ứng khuếch đại sát thương kéo dài cho đến khi bạn rời khỏi giao tranh với tướng.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.DAMAGE_AMPLIFICATION,
      RuneEffectType.STACKING,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [RuneTriggerType.ON_ATTACK, RuneTriggerType.STACK_BASED],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 40,
    scalingValue: 165,
    maxStacks: 3,
    statTypes: [],
    statBonuses: {
      requiredConsecutiveBasicAttacks: 3,
      damage: {
        minimum: 40,
        maximum: 165,
        scaling: `LEVEL`,
        damageType: `ADAPTIVE`,
      },
      damageAmplificationPercent: 8,
      damageAmplificationEndsOnChampionCombatExit: true,
    },
  },
  {
    key: `lethal-tempo`,
    shortDescription: `Attack enemy champions to stack Attack Speed. At maximum stacks, gain attack range and exceed the Attack Speed cap.`,
    fullDescription: `Tấn công tướng địch sẽ nhận một cộng dồn Tốc Độ Đánh, tối đa 6 cộng dồn. Mỗi cộng dồn tồn tại trong 6 giây và tăng 6% - 14% Tốc Độ Đánh đối với tướng cận chiến hoặc 3.5% - 8% đối với tướng đánh xa. Khi đạt tối đa cộng dồn, tướng cận chiến nhận thêm 25 tầm đánh, còn tướng đánh xa nhận thêm 50 tầm đánh và có thể vượt qua giới hạn Tốc Độ Đánh.`,
    effectTypes: [
      RuneEffectType.ATTACK_SPEED,
      RuneEffectType.ATTACK_RANGE,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [RuneTriggerType.ON_ATTACK, RuneTriggerType.STACK_BASED],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    duration: 6,
    maxStacks: 6,
    statTypes: [RuneStatType.ATTACK_SPEED, RuneStatType.ATTACK_RANGE],
    statBonuses: {
      attackSpeedPerStackPercent: {
        melee: {
          minimum: 6,
          maximum: 14,
          scaling: `LEVEL`,
        },
        ranged: {
          minimum: 3.5,
          maximum: 8,
          scaling: `LEVEL`,
        },
      },
      maximumStacks: 6,
      stackDurationSeconds: 6,
      attackDistanceAtMaximumStacks: {
        melee: 25,
        ranged: 50,
      },
      exceedsAttackSpeedCapAtMaximumStacks: true,
    },
  },
  {
    key: `fleet-footwork`,
    shortDescription: `Build 100 Energy through movement, attacks, and abilities to empower your next attack with healing, Movement Speed, and resource restoration.`,
    fullDescription: `Di chuyển, tấn công và sử dụng kỹ năng sẽ tích lũy Năng Lượng. Khi đạt 100 cộng dồn Năng Lượng, đòn đánh kế tiếp nhận thêm 40% Tốc Độ Đánh, hồi 15 - 110 Máu theo cấp độ cộng 15% Sức Mạnh Công Kích cộng thêm và 10% Sức Mạnh Phép Thuật, đồng thời tăng 20% Tốc Độ Di Chuyển trong 1 giây. Nếu đòn đánh trúng tướng địch, hồi 8% Năng Lượng hoặc Mana đã mất. Khi tấn công lính hoặc quái, lượng hồi máu chỉ còn 35% đối với tướng cận chiến hoặc 15% đối với tướng đánh xa.`,
    effectTypes: [
      RuneEffectType.HEAL,
      RuneEffectType.ATTACK_SPEED,
      RuneEffectType.MOVEMENT_SPEED,
      RuneEffectType.RESOURCE_RESTORE,
      RuneEffectType.STACKING,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [RuneTriggerType.ON_ATTACK, RuneTriggerType.STACK_BASED],
    targetTypes: [
      TargetType.SELF,
      TargetType.CHAMPION,
      TargetType.MINION,
      TargetType.MONSTER,
    ],
    baseValue: 15,
    scalingValue: 110,
    duration: 1,
    maxStacks: 100,
    statTypes: [RuneStatType.ATTACK_SPEED, RuneStatType.MOVEMENT_SPEED],
    statBonuses: {
      maximumEnergyStacks: 100,
      energyGeneratedBy: [`MOVEMENT`, `BASIC_ATTACK`, `ABILITY_CAST`],
      empoweredAttackSpeedPercent: 40,
      heal: {
        minimum: 15,
        maximum: 110,
        scaling: `LEVEL`,
        bonusAttackDamageRatio: 0.15,
        abilityPowerRatio: 0.1,
      },
      movementSpeedPercent: 20,
      movementSpeedDurationSeconds: 1,
      championResourceRestore: {
        missingManaPercent: 8,
        missingEnergyPercent: 8,
      },
      nonChampionHealMultiplier: {
        melee: 0.35,
        ranged: 0.15,
        targetTypes: [`MINION`, `MONSTER`],
      },
    },
  },
  {
    key: `conqueror`,
    shortDescription: `Stack adaptive force by hitting enemy champions. At maximum stacks, gain physical and magical vamp.`,
    fullDescription: `Đòn đánh thường và kỹ năng trúng tướng địch sẽ tạo một cộng dồn Chinh Phục, tối đa một cộng dồn cho mỗi đòn đánh hoặc lần sử dụng kỹ năng. Mỗi cộng dồn tồn tại trong 6 giây và cho 3 - 5 Sức Mạnh Công Kích cộng thêm hoặc 4 - 12 Sức Mạnh Phép Thuật thích ứng, cộng dồn tối đa 6 lần. Khi đạt tối đa cộng dồn, nhận 8% Hút Máu Vật Lý và Hút Máu Phép đối với tướng cận chiến, hoặc 5% đối với tướng đánh xa.`,
    effectTypes: [
      RuneEffectType.ADAPTIVE_FORCE,
      RuneEffectType.PHYSICAL_VAMP,
      RuneEffectType.MAGIC_VAMP,
      RuneEffectType.STACKING,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [
      RuneTriggerType.ON_ATTACK,
      RuneTriggerType.ON_ABILITY_HIT,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    duration: 6,
    maxStacks: 6,
    statTypes: [
      RuneStatType.ADAPTIVE_FORCE,
      RuneStatType.PHYSICAL_VAMP,
      RuneStatType.MAGIC_VAMP,
    ],
    statBonuses: {
      attackDamagePerStack: {
        minimum: 3,
        maximum: 5,
        scaling: `LEVEL`,
      },
      abilityPowerPerStack: {
        minimum: 4,
        maximum: 12,
        scaling: `LEVEL`,
      },
      meleePhysicalVampPercent: 8,
      meleeMagicalVampPercent: 8,
      rangedPhysicalVampPercent: 5,
      rangedMagicalVampPercent: 5,
    },
  },
  {
    key: `grasp-of-the-undying`,
    shortDescription: `Build 4 stacks in combat to empower your next basic attack against a champion.`,
    fullDescription: `Khi bước vào giao tranh, nhận 1 cộng dồn mỗi giây trong 3 giây tiếp theo. Có thể tiếp tục tạo cộng dồn bằng cách tái bước vào giao tranh sau 2 giây. Khi đạt 4 cộng dồn, đòn đánh thường kế tiếp trong vòng 6 giây lên tướng địch sẽ tiêu thụ toàn bộ cộng dồn, gây thêm sát thương phép bằng 3.3% Máu tối đa, hồi lại 1.3% Máu tối đa và tăng vĩnh viễn 10 Máu cộng thêm. Thời gian duy trì đòn đánh cường hóa được làm mới mỗi khi bước vào giao tranh. Đối với tướng đánh xa, tất cả hiệu ứng bị giảm 40%.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.HEAL,
      RuneEffectType.HEALTH,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [
      RuneTriggerType.ON_COMBAT_START,
      RuneTriggerType.ON_ATTACK,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    duration: 6,
    maxStacks: 4,
    statTypes: [RuneStatType.HEALTH],
    statBonuses: {
      bonusMagicDamagePercentMaxHealth: 3.3,
      healPercentMaxHealth: 1.3,
      permanentBonusHealth: 10,
      rangedEffectMultiplier: 0.6,
      stackGenerationIntervalSeconds: 1,
      initialStackGenerationDurationSeconds: 3,
      reentryDelaySeconds: 2,
    },
  },
  {
    key: `guardian`,
    shortDescription: `Guard nearby or ability-targeted allies, shielding both of you after enough incoming damage.`,
    fullDescription: `Bảo hộ đồng minh trong phạm vi 350 đơn vị và đồng minh được bạn nhắm đến bằng kỹ năng trong 2.5 giây. Trong lúc bảo hộ, nếu bạn hoặc đồng minh nhận vượt một ngưỡng sát thương nhất định, cả hai nhận lá chắn hấp thụ 45 - 165 sát thương theo cấp độ, cộng 6% Máu cộng thêm và 15% Sức Mạnh Phép Thuật trong 2 giây. Hồi chiêu: 55 - 25 giây.`,
    effectTypes: [
      RuneEffectType.SHIELD,
      RuneEffectType.SCALING,
      RuneEffectType.UTILITY,
    ],
    triggerTypes: [
      RuneTriggerType.ON_ABILITY_HIT,
      RuneTriggerType.ON_CHAMPION_DAMAGE_TAKEN,
    ],
    targetTypes: [TargetType.SELF, TargetType.ALLY],
    duration: 2,
    statTypes: [],
    statBonuses: {
      guarding: {
        nearbyAllyRange: 350,
        abilityTargetedAllyGuardDurationSeconds: 2.5,
        guardsNearbyAllies: true,
        guardsAbilityTargetedAllies: true,
      },
      activationCondition: {
        triggerWhenOwnerOrGuardedAllyTakesEnoughDamage: true,
        damageThreshold: `UNSPECIFIED`,
      },
      shield: {
        minimum: 45,
        maximum: 165,
        scaling: `LEVEL`,
        bonusHealthRatio: 0.06,
        abilityPowerRatio: 0.15,
        durationSeconds: 2,
        appliesToOwner: true,
        appliesToGuardedAlly: true,
      },
      cooldown: {
        minimumSeconds: 25,
        maximumSeconds: 55,
        scaling: `LEVEL`,
      },
    },
    notes: `ON_ABILITY_HIT represents guarding an ally targeted by an ability. ON_CHAMPION_DAMAGE_TAKEN represents the owner or guarded ally taking enough damage to activate the shield. The source does not provide the exact incoming-damage threshold required to activate the shield.`,
  },
  {
    key: `aery`,
    shortDescription: `Damage enemy champions or protect allies with Aery. Aery must return before she can be sent again.`,
    fullDescription: `Đòn đánh thường và kỹ năng lên tướng địch sẽ đưa Aery đến mục tiêu, gây 15 - 70 sát thương thích ứng theo cấp độ, cộng thêm 10% Sức Mạnh Công Kích cộng thêm và 5% Sức Mạnh Phép Thuật. Hồi máu, tạo lá chắn hoặc cường hóa đồng minh sẽ đưa Aery đến tạo lá chắn hấp thụ 25 - 120 sát thương theo cấp độ, cộng thêm 10% Sức Mạnh Công Kích cộng thêm và 5% Sức Mạnh Phép Thuật trong 2 giây. Aery ở lại mục tiêu trong 2 giây trước khi bay trở lại và không thể được triệu hồi lại cho tới khi quay về. Ban đầu Aery bay chậm nhưng sẽ tăng tốc dần và có thể được thu hồi sớm bằng cách di chuyển đến gần Aery.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.SHIELD,
      RuneEffectType.UTILITY,
    ],
    triggerTypes: [
      RuneTriggerType.ON_ATTACK,
      RuneTriggerType.ON_ABILITY_HIT,
      RuneTriggerType.ON_HEAL,
      RuneTriggerType.ON_SHIELD,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION, TargetType.ALLY],
    duration: 2,
    statTypes: [],
    statBonuses: {
      damage: {
        minimum: 15,
        maximum: 70,
        scaling: `LEVEL`,
        damageType: `ADAPTIVE`,
        bonusAttackDamageRatio: 0.1,
        abilityPowerRatio: 0.05,
      },
      shield: {
        minimum: 25,
        maximum: 120,
        scaling: `LEVEL`,
        bonusAttackDamageRatio: 0.1,
        abilityPowerRatio: 0.05,
        durationSeconds: 2,
      },
      targetLingerDurationSeconds: 2,
      requiresReturnBeforeRetrigger: true,
      canBePickedUpByOwner: true,
      returnSpeedAccelerates: true,
    },
  },
  {
    key: `arcane-comet`,
    shortDescription: `Ability damage launches a comet at the target's location. Champion hits increase future comet damage.`,
    fullDescription: `Gây sát thương lên tướng địch bằng kỹ năng sẽ phóng một thiên thạch tới vị trí của chúng. Khi thiên thạch trúng tướng địch, sát thương của những thiên thạch tiếp theo sẽ tăng thêm. Thiên thạch gây 15 - 100 sát thương theo cấp độ, cộng 2 sát thương cho mỗi lần thiên thạch đã trúng tướng địch, cộng thêm 10% Sức Mạnh Công Kích cộng thêm và 5% Sức Mạnh Phép Thuật. Hồi chiêu: 16 - 8 giây theo cấp độ.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.SCALING,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [RuneTriggerType.ON_ABILITY_HIT, RuneTriggerType.STACK_BASED],
    targetTypes: [TargetType.CHAMPION, TargetType.AREA],
    baseValue: 15,
    scalingValue: 100,
    cooldown: 16,
    statTypes: [],
    statBonuses: {
      damage: {
        minimum: 15,
        maximum: 100,
        scaling: `LEVEL`,
      },
      damagePerChampionHit: 2,
      championHitStacksUnlimited: true,
      bonusAttackDamageRatio: 0.1,
      abilityPowerRatio: 0.05,
      cooldownSeconds: {
        minimum: 8,
        maximum: 16,
        scaling: `LEVEL`,
      },
    },
  },
  {
    key: `phase-rush`,
    shortDescription: `Hit a champion 3 times within 3 seconds to gain Movement Speed and Ability Haste and reduce current basic ability cooldowns.`,
    fullDescription: `Đánh trúng một tướng địch bằng 3 đòn đánh thường hoặc kỹ năng riêng biệt trong vòng 3 giây sẽ cho Tốc Độ Di Chuyển, 10 Điểm Hồi Kỹ Năng và giảm 20% thời gian hồi chiêu hiện tại của các kỹ năng cơ bản. Tướng cận chiến nhận 40% - 60% Tốc Độ Di Chuyển, còn tướng đánh xa nhận 20% - 35%. Hồi chiêu: 21 - 7 giây theo cấp độ.`,
    effectTypes: [
      RuneEffectType.MOVEMENT_SPEED,
      RuneEffectType.ABILITY_HASTE,
      RuneEffectType.COOLDOWN_REDUCTION,
    ],
    triggerTypes: [
      RuneTriggerType.ON_CHAMPION_HIT,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    cooldown: 21,
    maxStacks: 3,
    statTypes: [RuneStatType.MOVEMENT_SPEED, RuneStatType.ABILITY_HASTE],
    statBonuses: {
      activationWindowSeconds: 3,
      requiredSeparateHits: 3,
      movementSpeedPercent: {
        melee: {
          minimum: 40,
          maximum: 60,
          scaling: `LEVEL`,
        },
        ranged: {
          minimum: 20,
          maximum: 35,
          scaling: `LEVEL`,
        },
      },
      abilityHaste: 10,
      currentBasicAbilityCooldownReductionPercent: 20,
      cooldownSeconds: {
        minimum: 7,
        maximum: 21,
        scaling: `LEVEL`,
      },
    },
  },
  {
    key: `first-strike`,
    shortDescription: `Damage a champion shortly after entering combat to gain gold and deal bonus true damage.`,
    fullDescription: `Trong vòng 0.25 giây sau khi bước vào giao tranh với tướng địch, gây sát thương lên chúng sẽ cho 10 vàng và kích hoạt Đòn Phủ Đầu trong 3 giây. Trong thời gian này, bạn gây thêm 7% sát thương chuẩn lên tướng địch. Khi hiệu ứng kết thúc, nhận thêm vàng bằng 60% lượng sát thương cộng thêm đã gây ra nếu là tướng cận chiến hoặc 45% nếu là tướng đánh xa. Hồi chiêu: 20 - 13 giây theo cấp độ.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.GOLD],
    triggerTypes: [
      RuneTriggerType.ON_COMBAT_START,
      RuneTriggerType.ON_CHAMPION_HIT,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    cooldown: 20,
    duration: 3,
    statTypes: [RuneStatType.GOLD],
    statBonuses: {
      activationWindowSeconds: 0.25,
      initialGold: 10,
      effectDurationSeconds: 3,
      bonusTrueDamagePercent: 7,
      bonusGoldFromDamagePercent: {
        melee: 60,
        ranged: 45,
      },
      cooldownSeconds: {
        minimum: 13,
        maximum: 20,
        scaling: `LEVEL`,
      },
    },
  },
  {
    key: `ice-overlord`,
    shortDescription: `Immobilizing a champion creates an ice zone, grants defenses, and causes a delayed explosion around you.`,
    fullDescription: `Làm bất động một tướng địch sẽ tạo ra 3 luồng băng quanh mục tiêu, hình thành một vùng băng bên dưới chúng trong 3 giây. Kẻ địch bên trong vùng băng bị làm chậm 15% cộng thêm một lượng dựa trên Máu cộng thêm của bạn. Hiệu ứng làm chậm duy trì thêm 1.5 giây sau khi kẻ địch rời vùng băng. Đồng thời, bạn nhận một lớp băng bảo vệ, tăng Giáp và Kháng Phép thêm 35 cộng 70% Giáp cộng thêm và Kháng Phép cộng thêm. Sau 2.5 giây, lớp băng phát nổ quanh bạn, gây 15 - 100 cộng 5% Máu cộng thêm sát thương phép.`,
    effectTypes: [
      RuneEffectType.CROWD_CONTROL,
      RuneEffectType.ARMOR,
      RuneEffectType.MAGIC_RESIST,
      RuneEffectType.DAMAGE,
    ],
    triggerTypes: [RuneTriggerType.ON_IMMOBILIZE_APPLIED],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION, TargetType.AREA],
    baseValue: 15,
    scalingValue: 100,
    duration: 3,
    statTypes: [RuneStatType.ARMOR, RuneStatType.MAGIC_RESIST],
    statBonuses: {
      beamCount: 3,
      iceZoneDurationSeconds: 3,
      slowPercent: 15,
      slowBonusHealthScaling: 1,
      slowLingerDurationSeconds: 1.5,
      explosionDelaySeconds: 2.5,
      bonusArmorBase: 35,
      bonusArmorRatio: 0.7,
      bonusMagicResistBase: 35,
      bonusMagicResistRatio: 0.7,
      explosionDamageMinimum: 15,
      explosionDamageMaximum: 100,
      explosionBonusHealthRatio: 0.05,
    },
  },

  // For non-keystone runes, MVP stores detail in fullDescription and keeps numeric fields only when simple.
  {
    key: `cheap-shot`,
    shortDescription: `Deal bonus true damage to movement-impaired enemies.`,
    fullDescription: `Gây thêm 10 - 45 sát thương chuẩn theo cấp độ lên kẻ địch đang bị hạn chế di chuyển. Hồi chiêu: 7 giây.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_MOVEMENT_IMPAIRED_TARGET],
    targetTypes: [TargetType.ENEMY],
    baseValue: 10,
    scalingValue: 45,
    cooldown: 7,
    statTypes: [],
    statBonuses: {
      bonusTrueDamage: {
        minimum: 10,
        maximum: 45,
        scaling: `LEVEL`,
      },
      targetCondition: `MOVEMENT_IMPAIRED`,
      cooldownSeconds: 7,
    },
    notes: null,
  },
  {
    key: `sudden-impact`,
    shortDescription: `After using mobility or exiting stealth, damage a champion within 4 seconds to deal bonus true damage.`,
    fullDescription: `Sau khi lướt, nhảy, dịch chuyển tức thời, dịch chuyển hoặc thoát khỏi trạng thái tàng hình, bạn có 4 giây để gây sát thương lên tướng địch. Đòn đánh hoặc kỹ năng gây sát thương sẽ gây thêm 15 - 65 sát thương chuẩn theo cấp độ. Ở cấp 5, gây thêm 5 sát thương chuẩn. Ở cấp 9, gây thêm 5 sát thương chuẩn nữa và nhận 10% Tốc Độ Di Chuyển trong 1.5 giây sau khi gây sát thương. Hồi chiêu: 10 giây.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.MOBILITY,
      RuneEffectType.MOVEMENT_SPEED,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 15,
    scalingValue: 65,
    cooldown: 10,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
    statBonuses: {
      activationWindowSeconds: 4,
      activationSources: [`DASH`, `LEAP`, `BLINK`, `TELEPORT`, `EXIT_STEALTH`],
      bonusTrueDamage: {
        minimum: 15,
        maximum: 65,
        scaling: `LEVEL`,
      },
      levelBonuses: [
        {
          level: 5,
          additionalTrueDamage: 5,
        },
        {
          level: 9,
          additionalTrueDamage: 5,
          movementSpeedPercent: 10,
          movementSpeedDurationSeconds: 1.5,
        },
      ],
      cooldownSeconds: 10,
    },
  },
  {
    key: `empowered-attack`,
    shortDescription: `Every 8 seconds, empower your next attack to deal bonus adaptive damage.`,
    fullDescription: `Sau mỗi 8 giây, đòn đánh kế tiếp được cường hóa, gây thêm 20 - 60 sát thương thích ứng theo cấp độ. Đối với tướng đánh xa, sát thương cộng thêm chỉ còn 80%.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.SCALING],
    triggerTypes: [RuneTriggerType.PERIODIC, RuneTriggerType.ON_ATTACK],
    targetTypes: [TargetType.ENEMY],
    baseValue: 20,
    scalingValue: 60,
    cooldown: 8,
    statTypes: [],
    statBonuses: {
      bonusAdaptiveDamage: {
        minimum: 20,
        maximum: 60,
        scaling: `LEVEL`,
      },
      rangedDamageMultiplier: 0.8,
      empowermentIntervalSeconds: 8,
      empowersNextBasicAttack: true,
    },
  },
  {
    key: `chain-assault`,
    shortDescription: `Mark a champion with an active ability, then deal bonus adaptive damage with your next 2 attacks or active ability casts against them.`,
    fullDescription: `Kỹ năng kích hoạt trúng tướng địch sẽ đặt dấu ấn lên chúng. Hai đòn đánh hoặc lần sử dụng kỹ năng kích hoạt kế tiếp lên cùng mục tiêu sẽ gây thêm 12 - 38 sát thương thích ứng theo cấp độ, cộng 3% Sức Mạnh Công Kích cộng thêm và 1.5% Sức Mạnh Phép Thuật. Hồi chiêu: 15 giây.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.STACKING,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [
      RuneTriggerType.ON_ACTIVE_ABILITY_HIT,
      RuneTriggerType.ON_ATTACK,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 12,
    scalingValue: 38,
    cooldown: 15,
    maxStacks: 2,
    statTypes: [],
    statBonuses: {
      markApplication: {
        requiresActiveAbilityHit: true,
        targetType: `ENEMY_CHAMPION`,
      },
      empoweredHitCount: 2,
      empoweredSources: [`BASIC_ATTACK`, `ACTIVE_ABILITY_CAST`],
      requiresSameMarkedTarget: true,
      bonusAdaptiveDamage: {
        minimum: 12,
        maximum: 38,
        scaling: `LEVEL`,
        bonusAttackDamageRatio: 0.03,
        abilityPowerRatio: 0.015,
      },
      cooldownSeconds: 15,
    },
  },
  {
    key: `tyrant`,
    shortDescription: `Damage champions below 50% Health to deal bonus adaptive damage.`,
    fullDescription: `Gây sát thương lên tướng địch còn dưới 50% Máu sẽ gây thêm 20 - 70 sát thương thích ứng theo cấp độ, cộng 6% Sức Mạnh Công Kích cộng thêm và 3% Sức Mạnh Phép Thuật. Hồi chiêu: 10 giây.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.SCALING],
    triggerTypes: [RuneTriggerType.ON_TARGET_LOW_HEALTH],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 20,
    scalingValue: 70,
    cooldown: 10,
    statTypes: [],
    statBonuses: {
      targetHealthThresholdPercent: 50,
      healthThresholdCondition: `BELOW`,
      bonusAdaptiveDamage: {
        minimum: 20,
        maximum: 70,
        scaling: `LEVEL`,
        bonusAttackDamageRatio: 0.06,
        abilityPowerRatio: 0.03,
      },
      cooldownSeconds: 10,
    },
  },
  {
    key: `hubris`,
    shortDescription: `Takedown a champion within 3 seconds of damaging them to gain temporary Adaptive Force.`,
    fullDescription: `Khi tham gia hạ gục một tướng địch trong vòng 3 giây sau khi gây sát thương lên chúng, nhận Sức Mạnh Thích Ứng bằng 5 cộng thêm 1 cho mỗi mạng hạ gục tướng mà bạn đã có. Hiệu ứng kéo dài 30 giây.`,
    effectTypes: [RuneEffectType.ADAPTIVE_FORCE, RuneEffectType.SCALING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    duration: 30,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
    statBonuses: {
      takedownWindowSeconds: 3,
      adaptiveForce: {
        baseAmount: 5,
        amountPerChampionKill: 1,
        scalingSource: `OWNER_CHAMPION_KILLS`,
      },
      buffDurationSeconds: 30,
      requiresPriorDamageToTarget: true,
      requiresTakedownOnDamagedChampion: true,
    },
  },
  {
    key: `eyeball-collector`,
    shortDescription: `Champion and epic monster takedowns grant stacking Attack Damage or Ability Power.`,
    fullDescription: `Sau khi tham gia hạ tướng địch hoặc quái khủng, nhận 1.5 Sức Mạnh Công Kích hoặc 3 Sức Mạnh Phép Thuật cho mỗi cộng dồn, tối đa 8 cộng dồn. Khi đạt tối đa cộng dồn, nhận tổng cộng 12 Sức Mạnh Công Kích hoặc 24 Sức Mạnh Phép Thuật.`,
    effectTypes: [RuneEffectType.ADAPTIVE_FORCE, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [
      TargetType.SELF,
      TargetType.CHAMPION,
      TargetType.EPIC_MONSTER,
    ],
    maxStacks: 8,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
    statBonuses: {
      adaptiveBonusPerStack: {
        attackDamage: 1.5,
        abilityPower: 3,
      },
      maximumStacks: 8,
      maximumAdaptiveBonus: {
        attackDamage: 12,
        abilityPower: 24,
      },
      progressionSources: [`CHAMPION_TAKEDOWN`, `EPIC_MONSTER_TAKEDOWN`],
      permanentProgression: true,
    },
  },
  {
    key: `ingenious-hunter`,
    shortDescription: `Gain Item Ability Haste and increase it through champion or epic monster takedowns.`,
    fullDescription: `Nhận 20 Điểm Hồi Kỹ Năng Trang Bị. Mỗi lần tham gia hạ gục tướng địch hoặc quái khủng sẽ nhận thêm vĩnh viễn 5 Điểm Hồi Kỹ Năng Trang Bị, tối đa 5 cộng dồn.`,
    effectTypes: [RuneEffectType.ITEM_ABILITY_HASTE, RuneEffectType.STACKING],
    triggerTypes: [
      RuneTriggerType.ALWAYS_ACTIVE,
      RuneTriggerType.ON_TAKEDOWN,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [
      TargetType.SELF,
      TargetType.CHAMPION,
      TargetType.EPIC_MONSTER,
    ],
    maxStacks: 5,
    statTypes: [RuneStatType.ITEM_ABILITY_HASTE],
    statBonuses: {
      itemAbilityHaste: {
        baseAmount: 20,
        amountPerStack: 5,
        maximumStacks: 5,
        maximumAmount: 45,
        permanent: true,
      },
      validTakedownTargets: [`ENEMY_CHAMPION`, `EPIC_MONSTER`],
    },
    notes: `ABILITY_HASTE is used as the closest available effect because the current enums do not separately represent Item Ability Haste. This rune affects item abilities rather than champion ability cooldowns.`,
  },
  {
    key: `relentless-hunter`,
    shortDescription: `Gain out-of-combat Movement Speed and increase it through champion or epic monster takedowns.`,
    fullDescription: `Nhận 10 Tốc Độ Di Chuyển ngoài giao tranh. Mỗi lần tham gia hạ gục tướng địch hoặc quái khủng sẽ nhận thêm vĩnh viễn 2 Tốc Độ Di Chuyển ngoài giao tranh, tối đa 5 cộng dồn.`,
    effectTypes: [RuneEffectType.MOVEMENT_SPEED, RuneEffectType.STACKING],
    triggerTypes: [
      RuneTriggerType.WHILE_OUT_OF_COMBAT,
      RuneTriggerType.ON_TAKEDOWN,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [
      TargetType.SELF,
      TargetType.CHAMPION,
      TargetType.EPIC_MONSTER,
    ],
    maxStacks: 5,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
    statBonuses: {
      outOfCombatMovementSpeed: {
        baseAmount: 10,
        amountPerStack: 2,
        maximumStacks: 5,
        maximumAmount: 20,
        permanent: true,
      },
      validTakedownTargets: [`ENEMY_CHAMPION`, `EPIC_MONSTER`],
      activationCondition: `OUT_OF_COMBAT`,
    },
    notes: `The Movement Speed bonus applies only while out of combat. Champion and epic monster takedowns permanently increase the bonus up to 5 stacks.`,
  },
  {
    key: `zombie-ward`,
    shortDescription: `Enemy ward takedowns spawn a Zombie Ward and grant stacking Attack Damage or Ability Power.`,
    fullDescription: `Hạ hoặc hỗ trợ hạ mắt địch sẽ tạo một Mắt Thây Ma tại vị trí của mắt đã bị phá, cung cấp tầm nhìn khu vực xung quanh trong 120 giây. Đồng thời, nhận 3 Sức Mạnh Công Kích hoặc 6 Sức Mạnh Phép Thuật cho mỗi cộng dồn, tối đa 5 cộng dồn. Khi đạt tối đa cộng dồn, nhận tổng cộng 15 Sức Mạnh Công Kích hoặc 30 Sức Mạnh Phép Thuật.`,
    effectTypes: [
      RuneEffectType.ADAPTIVE_FORCE,
      RuneEffectType.VISION,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [RuneTriggerType.ON_WARD_DESTROYED],
    targetTypes: [TargetType.SELF, TargetType.WARD, TargetType.AREA],
    duration: 120,
    maxStacks: 5,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
    statBonuses: {
      adaptiveBonusPerStack: {
        attackDamage: 3,
        abilityPower: 6,
      },
      maximumAdaptiveBonus: {
        attackDamage: 15,
        abilityPower: 30,
      },
      maximumStacks: 5,
      zombieWard: {
        spawnsAtDestroyedEnemyWardLocation: true,
        visionDurationSeconds: 120,
        triggeredByWardTakedown: true,
        triggeredByWardAssist: true,
      },
      permanentProgression: true,
    },
    notes: `ON_TAKEDOWN is used as the closest available trigger for enemy ward takedowns and assists. The current target enums do not represent wards or vision objects, so the ward interaction is stored in statBonuses.`,
  },
  {
    key: `brutal`,
    shortDescription: `Attacks deal bonus adaptive damage to enemy champions.`,
    fullDescription: `Đòn đánh lên tướng địch gây thêm 5 sát thương thích ứng, cộng 6% Sức Mạnh Công Kích cộng thêm và 3% Sức Mạnh Phép Thuật.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_ATTACK],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 5,
    statTypes: [],
    statBonuses: {
      bonusAdaptiveDamage: {
        base: 5,
        bonusAttackDamageRatio: 0.06,
        abilityPowerRatio: 0.03,
      },
    },
  },
  {
    key: `triumph`,
    shortDescription: `Champion takedowns restore Health and resources, then grant temporary Movement Speed.`,
    fullDescription: `Tham gia hạ gục tướng địch sẽ hồi 10% Máu đã mất, 10% Mana tối đa và 10% Nội Năng tối đa, đồng thời cho 35 Tốc Độ Di Chuyển trong 2 giây.`,
    effectTypes: [
      RuneEffectType.HEAL,
      RuneEffectType.RESOURCE_RESTORE,
      RuneEffectType.MOVEMENT_SPEED,
    ],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    duration: 2,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
    statBonuses: {
      championTakedownRestoration: {
        missingHealthPercent: 10,
        maximumManaPercent: 10,
        maximumEnergyPercent: 10,
      },
      movementSpeed: {
        flatAmount: 35,
        durationSeconds: 2,
      },
    },
  },
  {
    key: `battle-zeal`,
    shortDescription: `While fighting a champion, gain increasing basic ability damage against them.`,
    fullDescription: `Khi đang giao tranh với một tướng địch, cứ mỗi 1 giây tăng 1.4% sát thương kỹ năng cơ bản gây lên tướng đó, tối đa 6%.`,
    effectTypes: [
      RuneEffectType.DAMAGE_AMPLIFICATION,
      RuneEffectType.STACKING,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [
      RuneTriggerType.WHILE_IN_COMBAT,
      RuneTriggerType.PERIODIC,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    statTypes: [],
    statBonuses: {
      basicAbilityDamageAmplification: {
        percentPerInterval: 1.4,
        intervalSeconds: 1,
        maximumPercent: 6,
      },
      activationCondition: `IN_COMBAT_WITH_ENEMY_CHAMPION`,
      appliesAgainstCurrentCombatTarget: true,
    },
    notes: `The source states that the amplification increases by 1.4% every second up to 6%. Because 6 is not evenly divisible by 1.4, the final increase may be capped at 6% rather than representing an exact whole-number stack count.`,
  },
  {
    key: `last-stand`,
    shortDescription: `While below 60% Health, attacks against enemy champions deal bonus adaptive damage.`,
    fullDescription: `Khi còn dưới 60% Máu, các đòn đánh lên tướng địch gây thêm 5% - 11% sát thương thích ứng.`,
    effectTypes: [RuneEffectType.DAMAGE_AMPLIFICATION],
    triggerTypes: [RuneTriggerType.ON_ATTACK, RuneTriggerType.ON_LOW_HEALTH],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    statTypes: [],
    statBonuses: {
      ownerHealthThresholdPercent: 60,
      healthThresholdCondition: `BELOW`,
      bonusAdaptiveDamagePercent: {
        minimum: 5,
        maximum: 11,
      },
    },
    notes: `The source confirms a 5% - 11% bonus damage range while below 60% Health, but does not explain how the value scales within that range.`,
  },
  {
    key: `cut-down`,
    shortDescription: `Attacks deal bonus adaptive damage to champions above 60% Health.`,
    fullDescription: `Đòn đánh của bạn gây thêm 6.57% sát thương thích ứng lên tướng địch còn trên 60% Máu.`,
    effectTypes: [RuneEffectType.DAMAGE_AMPLIFICATION],
    triggerTypes: [
      RuneTriggerType.ON_ATTACK,
      RuneTriggerType.ON_TARGET_HIGH_HEALTH,
    ],
    targetTypes: [TargetType.CHAMPION],
    statTypes: [],
    statBonuses: {
      targetHealthThresholdPercent: 60,
      healthThresholdCondition: `ABOVE`,
      bonusAdaptiveDamagePercent: 6.57,
    },
    notes: `The target-above-60%-Health condition is stored in statBonuses because the current trigger enums do not represent this condition directly.`,
  },
  {
    key: `coup-de-grace`,
    shortDescription: `Deal bonus adaptive damage to champions below 40% Health.`,
    fullDescription: `Khi tướng địch còn dưới 40% Máu, bạn gây thêm 8% sát thương thích ứng lên chúng.`,
    effectTypes: [RuneEffectType.DAMAGE_AMPLIFICATION],
    triggerTypes: [RuneTriggerType.ON_TARGET_LOW_HEALTH],
    targetTypes: [TargetType.CHAMPION],
    statTypes: [],
    statBonuses: {
      targetHealthThresholdPercent: 40,
      healthThresholdCondition: `BELOW`,
      bonusAdaptiveDamagePercent: 8,
    },
  },
  {
    key: `legend-alacrity`,
    shortDescription: `Gain stacking Attack Speed through monster, champion, and minion takedowns.`,
    fullDescription: `Khi tham gia hạ quái, tướng địch và lính, nhận thêm 3% Tốc Độ Đánh cho mỗi cộng dồn, tối đa 6 cộng dồn và đạt tổng cộng 18% Tốc Độ Đánh.`,
    effectTypes: [RuneEffectType.ATTACK_SPEED, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    maxStacks: 6,
    statTypes: [RuneStatType.ATTACK_SPEED],
    statBonuses: {
      attackSpeedPercentPerStack: 3,
      maximumBonusAttackSpeedPercent: 18,
      progressionSources: [
        `MONSTER_TAKEDOWN`,
        `CHAMPION_TAKEDOWN`,
        `MINION_TAKEDOWN`,
      ],
      permanentProgression: true,
    },
  },
  {
    key: `legend-tenacity`,
    shortDescription: `Gain Tenacity and Slow Resistance, increasing through takedowns.`,
    fullDescription: `Nhận 3% Kháng Hiệu Ứng và 3% Kháng Làm Chậm. Khi tham gia hạ quái, tướng địch hoặc lính, các chỉ số này tăng dần, tối đa 15% Kháng Hiệu Ứng và 20% Kháng Làm Chậm.`,
    effectTypes: [
      RuneEffectType.TENACITY,
      RuneEffectType.SLOW_RESISTANCE,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [
      RuneTriggerType.ALWAYS_ACTIVE,
      RuneTriggerType.ON_TAKEDOWN,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF],
    statTypes: [RuneStatType.TENACITY, RuneStatType.SLOW_RESISTANCE],
    statBonuses: {
      tenacity: {
        basePercent: 3,
        maximumPercent: 15,
      },
      slowResistance: {
        basePercent: 3,
        maximumPercent: 20,
      },
      validTakedownTargets: [`MONSTER`, `ENEMY_CHAMPION`, `MINION`],
      permanentProgression: true,
    },
    notes: null,
  },
  {
    key: `legend-bloodline`,
    shortDescription: `Gain Omnivamp and increase it through monster, champion, and minion takedowns.`,
    fullDescription: `Nhận 1% Hút Máu Toàn Phần. Khi tham gia hạ quái, tướng địch và lính, tăng thêm Hút Máu Toàn Phần vĩnh viễn, tối đa thêm 7%, đạt tổng cộng 8% Hút Máu Toàn Phần.`,
    effectTypes: [RuneEffectType.OMNIVAMP, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    statTypes: [RuneStatType.OMNIVAMP],
    statBonuses: {
      baseOmnivampPercent: 1,
      maximumBonusOmnivampPercent: 7,
      maximumTotalOmnivampPercent: 8,
      progressionSources: [
        `MONSTER_TAKEDOWN`,
        `CHAMPION_TAKEDOWN`,
        `MINION_TAKEDOWN`,
      ],
      permanentProgression: true,
    },
  },

  {
    key: `demolish`,
    shortDescription: `Charge near an enemy turret to empower your next attack against it.`,
    fullDescription: `Khi đứng trong phạm vi 550 của trụ địch, nhận 1 cộng dồn mỗi 0.5 giây, tối đa 6 cộng dồn. Khi đạt tối đa cộng dồn, đòn đánh kế tiếp lên trụ gây thêm 100 cộng 22% Máu tối đa của bạn dưới dạng sát thương vật lý. Hồi chiêu: 30 giây.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_ATTACK, RuneTriggerType.STACK_BASED],
    targetTypes: [TargetType.SELF, TargetType.TURRET],
    cooldown: 30,
    maxStacks: 6,
    statTypes: [],
    statBonuses: {
      activationRange: 550,
      chargeIntervalSeconds: 0.5,
      requiredCharges: 6,
      minimumFullChargeTimeSeconds: 3,
      empoweredAttack: {
        targetType: `ENEMY_TURRET`,
        flatPhysicalDamage: 100,
        ownerMaximumHealthRatio: 0.22,
      },
      cooldownSeconds: 30,
    },
    notes: `TargetType.ENEMY is used as the closest available target because the current target enums do not include turrets or structures.`,
  },
  {
    key: `font-of-life`,
    shortDescription: `Attacks and abilities against champions heal you and the lowest-Health nearby ally.`,
    fullDescription: `Khi đòn đánh hoặc kỹ năng của bạn trúng tướng địch, hồi máu cho bản thân và tướng đồng minh gần đó có lượng Máu thấp nhất. Đồng minh được hồi bằng 1.5% Máu tối đa của bạn cộng 5% Sức Mạnh Phép Thuật của bạn. Bạn được hồi bằng 1% Máu tối đa cộng 5% Sức Mạnh Phép Thuật. Hồi chiêu: 15 giây. Đối với tướng cận chiến, hiệu ứng hồi máu đạt 130% hiệu quả.`,
    effectTypes: [RuneEffectType.HEAL],
    triggerTypes: [RuneTriggerType.ON_ATTACK, RuneTriggerType.ON_ABILITY_HIT],
    targetTypes: [TargetType.SELF, TargetType.ALLY, TargetType.CHAMPION],
    cooldown: 15,
    statTypes: [],
    statBonuses: {
      selfHeal: {
        ownerMaximumHealthRatio: 0.01,
        ownerAbilityPowerRatio: 0.05,
      },
      allyHeal: {
        ownerMaximumHealthRatio: 0.015,
        ownerAbilityPowerRatio: 0.05,
        targetSelection: `LOWEST_HEALTH_NEARBY_ALLIED_CHAMPION`,
      },
      meleeEffectMultiplier: 1.3,
      cooldownSeconds: 15,
    },
  },
  {
    key: `courage-of-the-colossus`,
    shortDescription: `Immobilizing an enemy grants a temporary shield based on maximum Health.`,
    fullDescription: `Khi làm bất động một kẻ địch, nhận một lá chắn hấp thụ 25 - 45 sát thương theo cấp độ cộng 1% Máu tối đa của bạn trong 3 giây. Hồi chiêu: 18 giây.`,
    effectTypes: [RuneEffectType.SHIELD],
    triggerTypes: [RuneTriggerType.ON_IMMOBILIZE_APPLIED],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    cooldown: 18,
    duration: 3,
    statTypes: [],
    statBonuses: {
      shield: {
        minimum: 25,
        maximum: 45,
        scaling: `LEVEL`,
        ownerMaximumHealthRatio: 0.01,
        durationSeconds: 3,
      },
      activationCondition: `IMMOBILIZE_ENEMY`,
      cooldownSeconds: 18,
    },
    notes: null,
  },
  {
    key: `unshakeable`,
    shortDescription: `Gain Armor and Magic Resistance based on the number of nearby enemy champions.`,
    fullDescription: `Nhận thêm 3% Giáp và 3% Kháng Phép. Với mỗi tướng địch ở gần, nhận thêm 2% Giáp và 2% Kháng Phép, tính tối đa 3 tướng địch. Khi có đủ 3 tướng địch ở gần, nhận tổng cộng 9% Giáp, 9% Kháng Phép và thêm 20% Kháng Làm Chậm.`,
    effectTypes: [
      RuneEffectType.ARMOR,
      RuneEffectType.MAGIC_RESIST,
      RuneEffectType.SLOW_RESISTANCE,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE],
    targetTypes: [TargetType.SELF],
    maxStacks: 3,
    statTypes: [
      RuneStatType.ARMOR,
      RuneStatType.MAGIC_RESIST,
      RuneStatType.SLOW_RESISTANCE,
    ],
    statBonuses: {
      baseArmorPercent: 3,
      baseMagicResistancePercent: 3,
      nearbyEnemyChampionBonusPerStack: {
        armorPercent: 2,
        magicResistancePercent: 2,
      },
      maximumNearbyEnemyChampionCount: 3,
      maximumArmorPercent: 9,
      maximumMagicResistancePercent: 9,
      maximumStackBonus: {
        slowResistancePercent: 20,
        requiresMaximumNearbyEnemies: true,
      },
    },
    notes: `UTILITY stores the Slow Resistance effect because the current effect and stat enums do not represent Slow Resistance. ALWAYS_ACTIVE is used because the rune continuously scales with nearby enemy champions.`,
  },
  {
    key: `second-wind`,
    shortDescription: `Gain passive health regeneration and regenerate additional health after taking champion damage.`,
    fullDescription: `Hồi 5 Máu mỗi 5 giây. Sau khi nhận sát thương từ tướng địch, hồi thêm 3 Máu cộng 1.5% lượng Máu đã mất trong 5 giây tiếp theo. Hiệu ứng được tăng gấp đôi đối với tướng cận chiến.`,
    effectTypes: [RuneEffectType.HEAL],
    triggerTypes: [
      RuneTriggerType.PERIODIC,
      RuneTriggerType.ON_CHAMPION_DAMAGE_TAKEN,
    ],
    targetTypes: [TargetType.SELF],
    duration: 5,
    statTypes: [],
    statBonuses: {
      passiveHealthRegen: {
        amount: 5,
        intervalSeconds: 5,
      },
      postChampionDamageRegeneration: {
        flatAmount: 3,
        missingHealthRatio: 0.015,
        durationSeconds: 5,
      },
      meleeEffectMultiplier: 2,
    },
  },
  {
    key: `nullifying-orb`,
    shortDescription: `Gain a shield when champion damage drops you below 35% Health.`,
    fullDescription: `Khi nhận sát thương từ tướng địch khiến Máu tụt xuống dưới 35%, nhận một lá chắn hấp thụ 60 - 180 sát thương theo cấp độ trong 4 giây. Hồi chiêu: 60 giây.`,
    effectTypes: [RuneEffectType.SHIELD, RuneEffectType.SCALING],
    triggerTypes: [
      RuneTriggerType.ON_CHAMPION_DAMAGE_TAKEN,
      RuneTriggerType.ON_HEALTH_THRESHOLD_CROSSED,
    ],
    targetTypes: [TargetType.SELF],
    baseValue: 60,
    scalingValue: 180,
    cooldown: 60,
    duration: 4,
    statTypes: [],
    statBonuses: {
      activationCondition: {
        damageSource: `ENEMY_CHAMPION`,
        ownerHealthThresholdPercent: 35,
        healthThresholdCondition: `FALL_BELOW`,
        requiresDamageToCrossThreshold: true,
      },
      shield: {
        minimum: 60,
        maximum: 180,
        scaling: `LEVEL`,
        durationSeconds: 4,
      },
      cooldownSeconds: 60,
    },
    notes: `The shield activates only when enemy champion damage causes the owner's Health to cross below 35%.`,
  },
  {
    key: `bone-plating`,
    shortDescription: `Reduce damage from a triggering champion attack and the next two champion attacks.`,
    fullDescription: `Khi nhận một đòn đánh kích hoạt từ tướng địch, giảm sát thương của đòn đánh đó và 2 đòn đánh từ tướng tiếp theo. Hồi chiêu: 40 giây.`,
    effectTypes: [RuneEffectType.DAMAGE_REDUCTION],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_DAMAGE_TAKEN],
    targetTypes: [TargetType.SELF],
    cooldown: 40,
    maxStacks: 3,
    statTypes: [],
    statBonuses: {
      protectedChampionAttackCount: 3,
      includesTriggeringAttack: true,
      additionalProtectedChampionAttacks: 2,
      cooldownSeconds: 40,
    },
    notes: `The source does not specify the exact amount of damage reduced.`,
  },
  {
    key: `overgrowth`,
    shortDescription: `Nearby minion and monster deaths permanently increase maximum Health.`,
    fullDescription: `Mỗi khi có 3 lính hoặc 3 quái bị tiêu diệt gần đó, nhận vĩnh viễn 3 Máu tối đa. Máu tối đa có thể tiếp tục tăng không giới hạn. Khi đạt 30 cộng dồn, nhận thêm 3% Máu tối đa.`,
    effectTypes: [
      RuneEffectType.HEALTH,
      RuneEffectType.STACKING,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [
      RuneTriggerType.ON_NEARBY_UNIT_DEATH,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF, TargetType.MINION, TargetType.MONSTER],
    statTypes: [RuneStatType.HEALTH],
    statBonuses: {
      nearbyUnitDeathsPerStack: 3,
      validNearbyUnitTypes: [`MINION`, `MONSTER`],
      maximumHealthPerStack: 3,
      permanent: true,
      uncappedMaximumHealthScaling: true,
      milestoneBonus: {
        requiredStacks: 30,
        maximumHealthPercent: 3,
      },
    },
    notes: `Each stack is granted after 3 nearby minion or monster deaths. The flat maximum Health gain is uncapped. The 3% maximum Health bonus is unlocked once at 30 stacks.`,
  },
  {
    key: `revitalize`,
    shortDescription: `Amplify healing and shields, with an additional bonus on targets below 40% Health.`,
    fullDescription: `Tăng 5% hiệu quả hồi máu và lá chắn bạn cung cấp. Nếu mục tiêu còn dưới 40% Máu, hiệu quả được tăng thêm 10%, đạt tổng cộng 15%.`,
    effectTypes: [
      RuneEffectType.HEAL,
      RuneEffectType.SHIELD,
      RuneEffectType.UTILITY,
    ],
    triggerTypes: [RuneTriggerType.ON_HEAL, RuneTriggerType.ON_SHIELD],
    targetTypes: [TargetType.SELF, TargetType.ALLY],
    statTypes: [],
    statBonuses: {
      baseHealingAmplificationPercent: 5,
      baseShieldAmplificationPercent: 5,
      lowHealthThresholdPercent: 40,
      lowHealthAdditionalAmplificationPercent: 10,
      maximumHealingAmplificationPercent: 15,
      maximumShieldAmplificationPercent: 15,
      appliesWhenTargetHealthBelowThreshold: true,
    },
  },
  {
    key: `perseverance`,
    shortDescription: `Gain Tenacity and temporary defenses while immobilized.`,
    fullDescription: `Nhận 10% Kháng Hiệu Ứng. Khi bị bất động, nhận thêm 10 - 15 Giáp và 10 - 15 Kháng Phép theo cấp độ trong 1.5 giây. Thời gian hiệu lực được làm mới mỗi khi tiếp tục bị bất động.`,
    effectTypes: [
      RuneEffectType.TENACITY,
      RuneEffectType.ARMOR,
      RuneEffectType.MAGIC_RESIST,
    ],
    triggerTypes: [
      RuneTriggerType.ALWAYS_ACTIVE,
      RuneTriggerType.ON_IMMOBILIZED,
    ],
    targetTypes: [TargetType.SELF],
    duration: 1.5,
    statTypes: [
      RuneStatType.TENACITY,
      RuneStatType.ARMOR,
      RuneStatType.MAGIC_RESIST,
    ],
    statBonuses: {
      tenacityPercent: 10,
      armorWhileImmobilized: {
        minimum: 10,
        maximum: 15,
        scaling: `LEVEL`,
      },
      magicResistanceWhileImmobilized: {
        minimum: 10,
        maximum: 15,
        scaling: `LEVEL`,
      },
      defensiveBuffDurationSeconds: 1.5,
      refreshesOnRepeatedImmobilization: true,
    },
    notes: `UTILITY stores the Tenacity effect because the current effect and stat enums do not include Tenacity. ON_CHAMPION_HIT is the closest available trigger, although the defensive effect actually activates when the rune owner is immobilized.`,
  },
  {
    key: `axiom-arcanist`,
    shortDescription: `Empower your ultimate and reduce its remaining cooldown on champion takedowns.`,
    fullDescription: `Chiêu cuối gây thêm 10% sát thương, hồi thêm 10% Máu và tạo thêm 10% lá chắn. Sát thương diện rộng của chiêu cuối chỉ được tăng 5%. Khi tham gia hạ gục tướng địch, giảm 7% thời gian hồi chiêu còn lại của chiêu cuối.`,
    effectTypes: [
      RuneEffectType.DAMAGE_AMPLIFICATION,
      RuneEffectType.HEAL,
      RuneEffectType.SHIELD,
      RuneEffectType.COOLDOWN_REDUCTION,
    ],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE, RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [
      TargetType.SELF,
      TargetType.CHAMPION,
      TargetType.ALLY,
      TargetType.ENEMY,
      TargetType.AREA,
    ],
    statTypes: [],
    statBonuses: {
      ultimateAmplification: {
        damagePercent: 10,
        areaOfEffectDamagePercent: 5,
        healingPercent: 10,
        shieldingPercent: 10,
      },
      championTakedownEffect: {
        remainingUltimateCooldownReductionPercent: 7,
      },
    },
    notes: `The 5% modifier applies specifically to area-of-effect ultimate damage. Champion takedowns reduce the ultimate's remaining cooldown by 7%, not its total or maximum cooldown.`,
  },
  {
    key: `manaflow-band`,
    shortDescription: `Hitting a champion with an ability or empowered attack permanently increases maximum Mana.`,
    fullDescription: `Đánh trúng tướng địch bằng kỹ năng hoặc đòn đánh cường hóa sẽ tăng vĩnh viễn 30 Mana tối đa, cộng dồn tối đa 300 Mana.`,
    effectTypes: [RuneEffectType.MANA, RuneEffectType.STACKING],
    triggerTypes: [
      RuneTriggerType.ON_ABILITY_HIT,
      RuneTriggerType.ON_EMPOWERED_ATTACK,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    maxStacks: 10,
    statTypes: [RuneStatType.MANA],
    statBonuses: {
      maximumManaPerStack: 30,
      maximumManaBonus: 300,
      requiredStacksForMaximum: 10,
      validHitSources: [`ABILITY`, `EMPOWERED_ATTACK`],
      permanent: true,
    },
    notes: `ON_ATTACK is included as the closest available trigger for an empowered attack. Normal basic attacks do not activate Manaflow Band unless they are empowered.`,
  },
  {
    key: `botanist`,
    shortDescription: `Destroy plants to gain gold and empower their effects.`,
    fullDescription: `Khi phá hủy một cây, nhận 10 vàng và cường hóa hiệu ứng của cây đó. Quả Hồi Phục tăng 20% lượng hồi máu khi được sử dụng. Hoa Soi Sáng cung cấp tầm nhìn lâu hơn 20% khi bị phá hủy. Hạt Nổ cho 40% Tốc Độ Di Chuyển trong 2.5 giây sau khi bị hất văng.`,
    effectTypes: [
      RuneEffectType.GOLD,
      RuneEffectType.HEAL,
      RuneEffectType.MOVEMENT_SPEED,
      RuneEffectType.VISION,
    ],
    triggerTypes: [RuneTriggerType.ON_PLANT_DESTROYED],
    targetTypes: [TargetType.SELF, TargetType.PLANT],
    duration: 2.5,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
    statBonuses: {
      goldPerPlantDestroyed: 10,
      honeyfruit: {
        healingAmplificationPercent: 20,
      },
      scryersBloom: {
        visionDurationAmplificationPercent: 20,
      },
      blastCone: {
        movementSpeedPercent: 40,
        movementSpeedDurationSeconds: 2.5,
        activatesAfterKnockback: true,
      },
    },
    notes: `The 2.5-second duration applies only to the Blast Cone Movement Speed effect.`,
  },
  {
    key: `hexflash`,
    shortDescription: `While Flash is on cooldown, channel Hex Flash to blink to a new location.`,
    fullDescription: `Khi Tốc Biến đang hồi chiêu, nó được thay thế bằng Tốc Biến Ma Thuật. Vận sức trong tối đa 2 giây để dịch chuyển đến vị trí mới. Nếu vận sức dưới 1 giây, bạn vẫn di chuyển quãng đường tương ứng với 1 giây vận sức. Hồi chiêu: 18 giây.`,
    effectTypes: [RuneEffectType.MOBILITY],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE],
    targetTypes: [TargetType.SELF],
    cooldown: 18,
    statTypes: [],
    statBonuses: {
      requiresFlashOnCooldown: true,
      replacesFlashWhileOnCooldown: true,
      maximumChannelDurationSeconds: 2,
      minimumEffectiveChannelDurationSeconds: 1,
      usesMinimumDistanceWhenReleasedEarly: true,
      movementType: `BLINK`,
      cooldownSeconds: 18,
    },
    notes: `The rune replaces Flash with a channelled blink while Flash is on cooldown.`,
  },
  {
    key: `transcendence`,
    shortDescription: `Gain Ability Haste at levels 1 and 5. At level 9, basic ability hits reduce that ability's cooldown.`,
    fullDescription: `Ở cấp 1, nhận 5 Điểm Hồi Kỹ Năng. Ở cấp 5, nhận thêm 5 Điểm Hồi Kỹ Năng. Từ cấp 9, khi một kỹ năng cơ bản đánh trúng mục tiêu, giảm 8% thời gian hồi chiêu của chính kỹ năng đó. Hiệu ứng giảm hồi chiêu có hồi chiêu 8 giây.`,
    effectTypes: [
      RuneEffectType.ABILITY_HASTE,
      RuneEffectType.COOLDOWN_REDUCTION,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [RuneTriggerType.ON_ABILITY_HIT],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    cooldown: 8,
    statTypes: [RuneStatType.ABILITY_HASTE],
    statBonuses: {
      abilityHasteMilestones: [
        {
          level: 1,
          amount: 5,
        },
        {
          level: 5,
          amount: 5,
        },
      ],
      totalAbilityHasteAtLevel5: 10,
      basicAbilityCooldownReduction: {
        unlockLevel: 9,
        reductionPercent: 8,
        cooldownSeconds: 8,
        appliesToTriggeringAbility: true,
      },
    },
  },
  {
    key: `celerity`,
    shortDescription: `Gain Movement Speed and increase all bonus Movement Speed effects applied to you.`,
    fullDescription: `Nhận thêm 2% Tốc Độ Di Chuyển. Mọi hiệu ứng Tốc Độ Di Chuyển cộng thêm tác dụng lên bạn được tăng thêm 7%.`,
    effectTypes: [RuneEffectType.MOVEMENT_SPEED, RuneEffectType.SCALING],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE],
    targetTypes: [TargetType.SELF],
    statTypes: [RuneStatType.MOVEMENT_SPEED],
    statBonuses: {
      movementSpeedPercent: 2,
      bonusMovementSpeedAmplificationPercent: 7,
    },
  },
  {
    key: `absolute-focus`,
    shortDescription: `Gain adaptive Attack Damage or Ability Power while above 65% Health.`,
    fullDescription: `Khi còn trên 65% Máu, nhận thêm 2 - 20 Sức Mạnh Công Kích hoặc 2 - 30 Sức Mạnh Phép Thuật thích ứng theo cấp độ.`,
    effectTypes: [RuneEffectType.ADAPTIVE_FORCE, RuneEffectType.SCALING],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE],
    targetTypes: [TargetType.SELF],
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
    statBonuses: {
      healthThresholdPercent: 65,
      requiresHealthAboveThreshold: true,
      adaptiveBonus: {
        attackDamage: {
          minimum: 2,
          maximum: 20,
          scaling: `LEVEL`,
        },
        abilityPower: {
          minimum: 2,
          maximum: 30,
          scaling: `LEVEL`,
        },
      },
    },
    notes: `ALWAYS_ACTIVE is used because the current trigger enums do not directly represent a self-health-above-threshold condition.`,
  },
  {
    key: `scorch`,
    shortDescription: `Ability damage against champions deals bonus magic damage after 1 second.`,
    fullDescription: `Gây sát thương lên tướng địch bằng kỹ năng sẽ gây thêm 21 - 49 sát thương phép sau 1 giây. Hồi chiêu: 8 giây.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.SCALING],
    triggerTypes: [RuneTriggerType.ON_ABILITY_HIT],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 21,
    scalingValue: 49,
    cooldown: 8,
    statTypes: [],
    statBonuses: {
      bonusMagicDamage: {
        minimum: 21,
        maximum: 49,
        scaling: `LEVEL`,
      },
      damageDelaySeconds: 1,
      cooldownSeconds: 8,
    },
  },
  {
    key: `nimbus-cloak`,
    shortDescription: `Casting a Summoner Spell grants Movement Speed based on the spell's cooldown.`,
    fullDescription: `Sau khi sử dụng Phép Bổ Trợ, nhận thêm 10% - 40% Tốc Độ Di Chuyển trong 3 giây. Lượng Tốc Độ Di Chuyển nhận được phụ thuộc vào thời gian hồi chiêu của Phép Bổ Trợ đã sử dụng.`,
    effectTypes: [RuneEffectType.MOVEMENT_SPEED],
    triggerTypes: [RuneTriggerType.ON_SUMMONER_SPELL_CAST],
    targetTypes: [TargetType.SELF],
    duration: 3,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
    statBonuses: {
      movementSpeedPercent: {
        minimum: 10,
        maximum: 40,
        scalingSource: `SUMMONER_SPELL_COOLDOWN`,
      },
      durationSeconds: 3,
      activatesAfterSummonerSpellCast: true,
    },
    notes: null,
  },
  {
    key: `gathering-storm`,
    shortDescription: `Starting at 6 minutes, gain increasing adaptive Attack Damage or Ability Power every 3 minutes.`,
    fullDescription: `Bắt đầu từ phút thứ 6 của trận đấu, cứ mỗi 3 phút nhận thêm Sức Mạnh Công Kích hoặc Sức Mạnh Phép Thuật thích ứng. Tổng chỉ số nhận được tăng theo thời gian: 2 / 5 / 9 / 14 / ... Sức Mạnh Công Kích hoặc 4 / 10 / 18 / 28 / ... Sức Mạnh Phép Thuật.`,
    effectTypes: [
      RuneEffectType.ADAPTIVE_FORCE,
      RuneEffectType.SCALING,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [
      RuneTriggerType.AFTER_TIME,
      RuneTriggerType.PERIODIC,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF],
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
    statBonuses: {
      firstActivationMinute: 6,
      activationIntervalMinutes: 3,
      scalingSource: `GAME_TIME`,
      cumulativeAdaptiveForceMilestones: {
        attackDamage: [2, 5, 9, 14],
        abilityPower: [4, 10, 18, 28],
      },
      continuesScalingAfterListedMilestones: true,
    },
    notes: `The listed values are cumulative totals at successive 3-minute milestones beginning at 6 minutes. The source confirms that the progression continues beyond the listed values but does not state a maximum.`,
  },
  {
    key: `ixtali-seedjar`,
    shortDescription: `Destroy plants to collect temporary seeds that can be planted later.`,
    fullDescription: `Sau khi phá hủy một cây, lập tức nhận một hạt giống thay thế phụ kiện trong 60 giây. Hạt giống có thể được gieo tại vị trí chỉ định, sau đó sẽ trưởng thành và tự hủy không lâu sau đó. Hạt giống có thể nhặt cũng sẽ rơi ra khi đồng minh phá cây. Hạt bắt đầu xuất hiện từ phút thứ 2 của trận đấu. Mỗi loại cây có hồi chiêu riêng 30 giây.`,
    effectTypes: [RuneEffectType.UTILITY],
    triggerTypes: [
      RuneTriggerType.AFTER_TIME,
      RuneTriggerType.ON_PLANT_DESTROYED,
    ],
    targetTypes: [
      TargetType.SELF,
      TargetType.ALLY,
      TargetType.PLANT,
      TargetType.LOCATION,
    ],
    cooldown: 30,
    duration: 60,
    statTypes: [],
    statBonuses: {
      seedAvailability: {
        unlockGameTimeSeconds: 120,
        unlockGameTimeMinutes: 2,
      },
      seedAcquisition: {
        grantedAfterOwnerDestroysPlant: true,
        dropsWhenAllyDestroysPlant: true,
        allyDroppedSeedRequiresPickup: true,
      },
      trinketReplacement: {
        replacesTrinket: true,
        durationSeconds: 60,
      },
      planting: {
        canPlantAtTargetLocation: true,
        seedMaturesAfterPlanting: true,
        seedSelfDestructsAfterMaturing: true,
      },
      plantCooldown: {
        cooldownSeconds: 30,
        trackedSeparatelyPerPlantType: true,
      },
    },
    notes: `The source does not provide the exact maturation time or self-destruction delay after planting. The 60-second duration applies to the seed replacing the trinket before it is used or expires.`,
  },
];

export async function seedRunesPatchStats(
  prisma: PrismaClient,
  patchId: string,
) {
  console.log(`SEEDING RUNES PATCH STATS...`);

  for (const runePatchStatSeed of runePatchStatSeeds) {
    const rune = await prisma.rune.findUnique({
      where: {
        key: runePatchStatSeed.key,
      },
    });

    if (!rune) {
      throw new Error(
        `Cannot seed rune patch stat. Missing rune: ${runePatchStatSeed.key}`,
      );
    }

    await prisma.runePatchStat.upsert({
      where: {
        runeId_patchId: {
          runeId: rune.id,
          patchId,
        },
      },
      update: {
        isAvailable: runePatchStatSeed.isAvailable ?? true,
        shortDescription: runePatchStatSeed.shortDescription ?? null,
        fullDescription: runePatchStatSeed.fullDescription ?? null,
        effectTypes: runePatchStatSeed.effectTypes,
        triggerTypes: runePatchStatSeed.triggerTypes,
        targetTypes: runePatchStatSeed.targetTypes,
        baseValue: runePatchStatSeed.baseValue ?? null,
        scalingValue: runePatchStatSeed.scalingValue ?? null,
        cooldown: runePatchStatSeed.cooldown ?? null,
        duration: runePatchStatSeed.duration ?? null,
        maxStacks: runePatchStatSeed.maxStacks ?? null,
        statTypes: runePatchStatSeed.statTypes,
        statBonuses: runePatchStatSeed.statBonuses ?? Prisma.DbNull,
        notes: runePatchStatSeed.notes ?? null,
        deletedAt: null,
      },
      create: {
        patchId,
        runeId: rune.id,
        isAvailable: runePatchStatSeed.isAvailable ?? true,
        shortDescription: runePatchStatSeed.shortDescription ?? null,
        fullDescription: runePatchStatSeed.fullDescription ?? null,
        effectTypes: runePatchStatSeed.effectTypes,
        triggerTypes: runePatchStatSeed.triggerTypes,
        targetTypes: runePatchStatSeed.targetTypes,
        baseValue: runePatchStatSeed.baseValue ?? null,
        scalingValue: runePatchStatSeed.scalingValue ?? null,
        cooldown: runePatchStatSeed.cooldown ?? null,
        duration: runePatchStatSeed.duration ?? null,
        maxStacks: runePatchStatSeed.maxStacks ?? null,
        statTypes: runePatchStatSeed.statTypes,
        statBonuses: runePatchStatSeed.statBonuses ?? Prisma.DbNull,
        notes: runePatchStatSeed.notes ?? null,
      },
    });

    console.log(`Seeded rune patch stat: ${runePatchStatSeed.key}`);
  }

  console.log(`SEEDED RUNES PATCH STATS`);
}
