import { Prisma, PrismaClient } from '../../src/generated/prisma/client.js';
import {
  RuneEffectType,
  RuneStatType,
  RuneTriggerType,
  TargetType,
} from '../../src/generated/prisma/enums.js';

type RunePatchStatSeed = {
  key: string;
  shortDescription?: string | null;
  fullDescription?: string | null;
  effectTypes: RuneEffectType[];
  triggerTypes: RuneTriggerType[];
  targetTypes: TargetType[];
  baseValue?: number | null;
  scalingValue?: number | null;
  cooldown?: number | null;
  duration?: number | null;
  maxStacks?: number | null;
  statTypes: RuneStatType[];
  statBonuses?: Prisma.InputJsonValue;
  notes?: string | null;
};

const runePatchStatSeeds: RunePatchStatSeed[] = [
  {
    key: `electrocute`,
    shortDescription: `3 hits within 3 seconds deal bonus adaptive damage.`,
    fullDescription: `Trong vòng 3 giây, đánh trúng cùng một tướng địch với 3 đòn đánh thường hoặc kỹ năng sẽ gây thêm sát thương thích ứng. Sát thương: 40 - 194 + 35% Sức Mạnh Công Kích cộng thêm + 20% Sức Mạnh Phép Thuật. Hồi chiêu: 20 - 13 giây.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 40,
    scalingValue: 194,
    cooldown: 20,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `dark-harvest`,
    shortDescription: `Damage low-health champions to deal adaptive damage and collect souls.`,
    fullDescription: `Gây sát thương lên tướng còn dưới 50% Máu sẽ gây sát thương thích ứng và thu hồn, tăng vĩnh viễn sát thương thêm 10 mỗi linh hồn. Sát thương: 40 + 10 mỗi linh hồn + 25% Sức Mạnh Công Kích cộng thêm + 15% Sức Mạnh Phép Thuật. Hồi chiêu: 20 giây. Đặt lại còn 1 giây khi tham gia hạ gục.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.STACKING,
      RuneEffectType.SCALING,
    ],
    triggerTypes: [RuneTriggerType.ON_LOW_HEALTH, RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 40,
    cooldown: 20,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `empowerment`,
    shortDescription: `3 consecutive hits deal adaptive damage and amplify champion damage.`,
    fullDescription: `Đánh trúng tướng địch bằng 3 đòn đánh liên tiếp sẽ gây thêm 60 - 200 sát thương thích ứng và khuếch đại sát thương bạn gây ra thêm 9% đến khi rời khỏi giao tranh với tướng. Hồi chiêu: 4 giây.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.UTILITY],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 60,
    scalingValue: 200,
    cooldown: 4,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `lethal-tempo`,
    shortDescription: `Attack champions to stack attack speed. At max stacks, gain range and ignore attack speed cap.`,
    fullDescription: `Nhận cộng dồn Tốc Độ Đánh khi tấn công tướng địch, tối đa 6 lần. Mỗi cộng dồn tăng Tốc Độ Đánh thêm 8 - 16% cho cận chiến hoặc 3 - 10% cho đánh xa trong 6 giây. Ở cộng dồn tối đa, nhận 50 tầm đánh cho cận chiến hoặc 75 tầm đánh cho đánh xa.`,
    effectTypes: [
      RuneEffectType.ATTACK_SPEED,
      RuneEffectType.STACKING,
      RuneEffectType.UTILITY,
    ],
    triggerTypes: [RuneTriggerType.ON_ATTACK, RuneTriggerType.STACK_BASED],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 3,
    scalingValue: 16,
    duration: 6,
    maxStacks: 6,
    statTypes: [RuneStatType.ATTACK_SPEED],
  },
  {
    key: `fleet-footwork`,
    shortDescription: `At 100 Energized stacks, next attack grants attack speed, healing, movement speed, and resource restore against champions.`,
    fullDescription: `Di chuyển, tấn công và sử dụng kỹ năng tăng cộng dồn Tích Điện. Khi đạt 100 cộng dồn, đòn đánh tiếp theo cho 100% Tốc Độ Đánh, hồi 15 - 85 + 30% Sức Mạnh Công Kích cộng thêm + 30% Sức Mạnh Phép Thuật, tăng 20% Tốc Độ Di Chuyển trong 1 giây. Khi tấn công tướng, hồi lại 8% Năng Lượng hoặc Nội Năng đã mất.`,
    effectTypes: [
      RuneEffectType.ATTACK_SPEED,
      RuneEffectType.HEAL,
      RuneEffectType.MOVEMENT_SPEED,
      RuneEffectType.MANA,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [
      RuneTriggerType.ON_ATTACK,
      RuneTriggerType.ON_MOVEMENT,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 15,
    scalingValue: 85,
    duration: 1,
    maxStacks: 100,
    statTypes: [
      RuneStatType.ATTACK_SPEED,
      RuneStatType.MOVEMENT_SPEED,
      RuneStatType.MANA,
    ],
  },
  {
    key: `conqueror`,
    shortDescription: `Stack adaptive force by hitting champions. At max stacks, gain omnivamp.`,
    fullDescription: `Nhận cộng dồn Sức Mạnh Thích Ứng khi các đòn đánh hoặc kỹ năng riêng biệt trúng tướng, tối đa 6 cộng dồn. Mỗi cộng dồn: 3 - 7 Sức Mạnh Công Kích cộng thêm hoặc 4 - 11 Sức Mạnh Phép Thuật trong 6 giây. Ở cộng dồn tối đa, nhận 9% Hút Máu Toàn Phần cho cận chiến hoặc 5% cho đánh xa.`,
    effectTypes: [
      RuneEffectType.ADAPTIVE_FORCE,
      RuneEffectType.STACKING,
      RuneEffectType.SCALING,
      RuneEffectType.UTILITY,
    ],
    triggerTypes: [
      RuneTriggerType.ON_CHAMPION_HIT,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 3,
    scalingValue: 11,
    duration: 6,
    maxStacks: 6,
    statTypes: [RuneStatType.ADAPTIVE_FORCE, RuneStatType.OMNIVAMP],
  },
  {
    key: `grasp-of-the-undying`,
    shortDescription: `Every 3 seconds in combat, empower next attack against champion.`,
    fullDescription: `Mỗi 3 giây trong giao tranh, đòn đánh kế tiếp lên tướng gây thêm sát thương phép bằng 1.5% Máu, hồi Máu bằng 2.5% Máu và tăng thêm 10 Máu vĩnh viễn. Với tướng đánh xa, các hiệu ứng bị giảm 60%.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.HEAL,
      RuneEffectType.HEALTH,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [RuneTriggerType.ON_ATTACK, RuneTriggerType.ON_COMBAT_START],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 10,
    cooldown: 3,
    statTypes: [RuneStatType.HEALTH],
  },
  {
    key: `guardian`,
    shortDescription: `Protect allies and grant shield after enough damage is taken.`,
    fullDescription: `Bảo vệ đồng minh trong phạm vi 350 đơn vị quanh bạn và đồng minh mà bạn nhắm đến bằng kỹ năng trong 2.5 giây. Nếu bạn hoặc đồng minh nhận nhiều sát thương hơn ngưỡng, cả hai nhận lá chắn trong 1.5 giây. Hồi chiêu: 40 - 20 giây. Lá chắn: 45 - 180 + 5% Máu cộng thêm + 15% Sức Mạnh Phép Thuật. Ngưỡng sát thương: 70 - 240.`,
    effectTypes: [RuneEffectType.SHIELD, RuneEffectType.UTILITY],
    triggerTypes: [RuneTriggerType.ON_SHIELD, RuneTriggerType.ON_LOW_HEALTH],
    targetTypes: [TargetType.SELF, TargetType.ALLY],
    baseValue: 45,
    scalingValue: 180,
    cooldown: 40,
    duration: 1.5,
    statTypes: [RuneStatType.HEALTH, RuneStatType.ABILITY_POWER],
  },
  {
    key: `summon-aery`,
    shortDescription: `Attacks and abilities damage enemies or shield allies.`,
    fullDescription: `Đòn đánh và kỹ năng đưa Aery đến mục tiêu, gây sát thương kẻ địch hoặc che chắn cho đồng minh. Sát thương: 15 - 70 + 20% Sức Mạnh Công Kích cộng thêm + 10% Sức Mạnh Phép Thuật. Lá chắn: 30 - 140 + 40% Sức Mạnh Công Kích cộng thêm + 20% Sức Mạnh Phép Thuật.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.SHIELD],
    triggerTypes: [RuneTriggerType.ON_ATTACK, RuneTriggerType.ON_ABILITY_HIT],
    targetTypes: [TargetType.ENEMY, TargetType.ALLY],
    baseValue: 15,
    scalingValue: 140,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `arcane-comet`,
    shortDescription: `Ability damage drops a comet. Comet damage increases with champion hits.`,
    fullDescription: `Gây sát thương lên tướng bằng kỹ năng sẽ thả thiên thạch xuống vị trí của chúng. Khi thiên thạch trúng tướng địch, sát thương thiên thạch tiếp theo sẽ gia tăng. Sát thương: 18 - 95 + 3 x tổng số lần trúng tướng địch + 35% Sức Mạnh Công Kích cộng thêm + 20% Sức Mạnh Phép Thuật. Hồi chiêu: 16 - 8 giây.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.SCALING,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [RuneTriggerType.ON_ABILITY_HIT],
    targetTypes: [TargetType.CHAMPION, TargetType.AREA],
    baseValue: 18,
    scalingValue: 95,
    cooldown: 16,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `phase-rush`,
    shortDescription: `3 hits within 4 seconds grant movement speed and reduce basic ability cooldowns.`,
    fullDescription: `Sử dụng đòn đánh thường hoặc kỹ năng lên tướng địch 3 lần trong vòng 4 giây sẽ tăng Tốc Độ Di Chuyển và giảm thời gian hồi chiêu còn lại của kỹ năng cơ bản đi 20%. Thời gian tác dụng: 3 giây. Tốc Độ Di Chuyển: cận chiến 40% - 60%, đánh xa 30% - 50%. Điểm Hồi Kỹ Năng Cơ Bản: 25. Hồi chiêu: 12 giây.`,
    effectTypes: [
      RuneEffectType.MOVEMENT_SPEED,
      RuneEffectType.COOLDOWN_REDUCTION,
    ],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 30,
    scalingValue: 60,
    cooldown: 12,
    duration: 3,
    statTypes: [RuneStatType.MOVEMENT_SPEED, RuneStatType.ABILITY_HASTE],
  },
  {
    key: `first-strike`,
    shortDescription: `Start combat to gain gold and deal bonus true damage.`,
    fullDescription: `Khởi đầu giao tranh với tướng địch hoặc gây sát thương lên chúng trong vòng 0.25 giây sau khi bắt đầu giao tranh sẽ cho 10 vàng và hiệu ứng trong 3 giây, cho phép gây thêm 7% sát thương chuẩn. Sau khi hiệu ứng kết thúc, nhận vàng thưởng dựa trên lượng sát thương đã gây thêm. Nếu không gây sát thương trong 0.25 giây, bắt đầu hồi chiêu trong 10 giây. Hồi chiêu: 20 - 13 giây.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.GOLD],
    triggerTypes: [
      RuneTriggerType.ON_COMBAT_START,
      RuneTriggerType.ON_CHAMPION_HIT,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 10,
    cooldown: 20,
    duration: 3,
    statTypes: [RuneStatType.GOLD],
  },
  {
    key: `glacial-augment`,
    shortDescription: `Immobilizing champions creates slowing zones, grants defenses, and deals magic damage.`,
    fullDescription: `Vô hiệu hóa tướng địch sẽ tạo vùng băng trong 3 giây và làm chậm kẻ địch. Hiệu ứng làm chậm duy trì 1.5 giây sau khi rời vùng băng. Tạo lớp băng bảo vệ quanh bản thân, tăng chống chịu trong 2.5 giây. Sau khoảng trễ, băng phát nổ gây 25 - 125 + 5% Máu cộng thêm sát thương phép. Hồi chiêu: 20 giây.`,
    effectTypes: [
      RuneEffectType.CROWD_CONTROL,
      RuneEffectType.ARMOR,
      RuneEffectType.MAGIC_RESIST,
      RuneEffectType.DAMAGE,
    ],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION, TargetType.AREA],
    baseValue: 25,
    scalingValue: 125,
    cooldown: 20,
    duration: 3,
    statTypes: [
      RuneStatType.ARMOR,
      RuneStatType.MAGIC_RESIST,
      RuneStatType.HEALTH,
    ],
  },

  // For non-keystone runes, MVP stores detail in fullDescription and keeps numeric fields only when simple.
  {
    key: `cheap-shot`,
    shortDescription: `Bonus true damage against movement-impaired enemies.`,
    fullDescription: `Gây thêm 10 - 45 sát thương chuẩn lên kẻ địch bị hạn chế di chuyển. Hồi chiêu: 7 giây.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.ENEMY],
    baseValue: 10,
    scalingValue: 45,
    cooldown: 7,
    statTypes: [],
  },
  {
    key: `sudden-impact`,
    shortDescription: `After mobility or stealth, next hit deals bonus true damage.`,
    fullDescription: `Sau khi lướt, nhảy, dịch chuyển hoặc thoát trạng thái tàng hình, đòn đánh hoặc kỹ năng kế tiếp lên tướng địch trong vòng 4 giây gây 10 - 80 sát thương chuẩn cộng thêm. Hồi chiêu: 10 giây. Cấp 5: gây thêm 10 sát thương chuẩn. Cấp 9: gây thêm 20 sát thương chuẩn và nhận 10% Tốc Độ Di Chuyển trong 1.5 giây sau khi gây sát thương.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.MOVEMENT_SPEED],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 10,
    scalingValue: 80,
    cooldown: 10,
    duration: 4,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
  },
  {
    key: `empowered-attack`,
    shortDescription: `Periodically empower next attack for bonus adaptive damage.`,
    fullDescription: `Sau mỗi 8 giây, đòn đánh tiếp theo được cường hóa, gây thêm 35 - 50 sát thương thích ứng lên tướng địch. Hiệu quả còn 80% đối với tướng đánh xa.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_ATTACK],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 35,
    scalingValue: 50,
    cooldown: 8,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `mark-of-the-weak`,
    shortDescription: `Active ability damage marks target; next 2 hits deal bonus adaptive damage.`,
    fullDescription: `Gây sát thương lên tướng địch bằng kỹ năng kích hoạt sẽ đặt dấu ấn lên chúng, khiến 2 đòn đánh hoặc kỹ năng kích hoạt kế tiếp trúng mục tiêu đó gây thêm sát thương thích ứng bằng 20 - 35 + 5% Sức Mạnh Công Kích cộng thêm + 2.5% Sức Mạnh Phép Thuật. Hồi chiêu: 15 giây.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_ABILITY_HIT],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 20,
    scalingValue: 35,
    cooldown: 15,
    maxStacks: 2,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `giant-slayer-domination`,
    shortDescription: `Bonus adaptive damage against champions below 50% health.`,
    fullDescription: `Khi gây sát thương lên một tướng dưới 50% Máu, gây 30 - 50 + 7.5% Sức Mạnh Công Kích cộng thêm + 3.5% Sức Mạnh Phép Thuật sát thương thích ứng cộng thêm. Hồi chiêu: 10 giây.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_LOW_HEALTH],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 30,
    scalingValue: 50,
    cooldown: 10,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `prideful-laurel`,
    shortDescription: `Champion takedowns after damaging them grant temporary adaptive force.`,
    fullDescription: `Tham gia hạ gục tướng địch trong vòng 3 giây sau khi gây sát thương lên chúng sẽ ban 5 + 1 mỗi điểm hạ gục tướng bạn đạt được Sức Mạnh Thích Ứng trong 30 giây.`,
    effectTypes: [RuneEffectType.ADAPTIVE_FORCE, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    baseValue: 5,
    duration: 30,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `eyeball-collector`,
    shortDescription: `Takedowns grant adaptive stats, up to 8 stacks.`,
    fullDescription: `Tăng 2 Sức Mạnh Công Kích hoặc 4 Sức Mạnh Phép Thuật sau khi tham gia hạ gục tướng hoặc quái khủng, cộng dồn tối đa 8 lần.`,
    effectTypes: [RuneEffectType.ADAPTIVE_FORCE, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    baseValue: 2,
    maxStacks: 8,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `ingenious-hunter`,
    shortDescription: `Gain item ability haste and stack more from takedowns.`,
    fullDescription: `Nhận 20 Điểm Hồi Kỹ Năng Trang Bị. Mỗi lần hạ gục tướng hoặc quái khủng, nhận thêm 5 Điểm Hồi Kỹ Năng Trang Bị. Cộng dồn tối đa 5 lần.`,
    effectTypes: [RuneEffectType.ABILITY_HASTE, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    baseValue: 20,
    scalingValue: 5,
    maxStacks: 5,
    statTypes: [RuneStatType.ABILITY_HASTE],
  },
  {
    key: `relentless-hunter`,
    shortDescription: `Gain out-of-combat movement speed and stack more from takedowns.`,
    fullDescription: `Nhận 10 Tốc Độ Di Chuyển ngoài giao tranh. Mỗi lần hạ gục tướng hoặc quái khủng, nhận thêm 2 Tốc Độ Di Chuyển ngoài giao tranh. Cộng dồn tối đa 5 lần.`,
    effectTypes: [RuneEffectType.MOVEMENT_SPEED, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    baseValue: 10,
    scalingValue: 2,
    maxStacks: 5,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
  },
  {
    key: `zombie-ward`,
    shortDescription: `Destroying enemy wards creates Zombie Wards and grants adaptive stats.`,
    fullDescription: `Tham gia phá mắt của phe địch sẽ tạo ra một Mắt Thây Ma thế chỗ nó, cho tầm nhìn xung quanh trong 120 giây. Tăng thêm 4 Sức Mạnh Công Kích hoặc 8 Sức Mạnh Phép Thuật, tối đa 5 cộng dồn.`,
    effectTypes: [
      RuneEffectType.VISION,
      RuneEffectType.ADAPTIVE_FORCE,
      RuneEffectType.STACKING,
    ],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.LOCATION, TargetType.SELF],
    baseValue: 4,
    duration: 120,
    maxStacks: 5,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },

  {
    key: `brutal`,
    shortDescription: `Attacks deal bonus adaptive damage to champions.`,
    fullDescription: `Các đòn đánh gây 6 + 8% Sức Mạnh Công Kích cộng thêm sát thương thích ứng lên tướng địch.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_ATTACK],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 6,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `triumph`,
    shortDescription: `Champion takedowns restore health and resource, and grant movement speed.`,
    fullDescription: `Tham gia hạ gục tướng sẽ hồi lại 10% Máu đã mất và 10% Năng Lượng hoặc Nội Năng tối đa, đồng thời cho 35 Tốc Độ Di Chuyển trong 2 giây.`,
    effectTypes: [
      RuneEffectType.HEAL,
      RuneEffectType.MANA,
      RuneEffectType.MOVEMENT_SPEED,
    ],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    baseValue: 10,
    duration: 2,
    statTypes: [RuneStatType.MANA, RuneStatType.MOVEMENT_SPEED],
  },
  {
    key: `courage`,
    shortDescription: `Stack basic ability damage amplification while fighting champions.`,
    fullDescription: `Nhận 2% khuếch đại sát thương kỹ năng cơ bản, có thể cộng dồn mỗi 1 giây khi đang giao tranh với tướng. Cộng dồn tối đa 3 lần và chỉ có hiệu lực lên tướng địch.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.STACKING],
    triggerTypes: [
      RuneTriggerType.ON_COMBAT_START,
      RuneTriggerType.STACK_BASED,
    ],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 2,
    maxStacks: 3,
    statTypes: [],
  },
  {
    key: `last-stand`,
    shortDescription: `Deal bonus adaptive damage while below 60% health.`,
    fullDescription: `Khi Máu ở dưới 60%, các đòn đánh lên tướng địch gây thêm 5% - 11% sát thương thích ứng. Gây tối đa sát thương cộng thêm khi Máu dưới 30%.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_LOW_HEALTH],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 5,
    scalingValue: 11,
    statTypes: [],
  },
  {
    key: `giant-slayer`,
    shortDescription: `Deal bonus adaptive damage to champions above 60% health.`,
    fullDescription: `Các đòn đánh và kỹ năng gây thêm 8% sát thương thích ứng lên tướng địch có trên 60% Máu.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 8,
    statTypes: [],
  },
  {
    key: `coup-de-grace`,
    shortDescription: `Deal bonus adaptive damage to champions below 40% health.`,
    fullDescription: `Gây thêm 8% sát thương thích ứng lên tướng địch còn dưới 40% Máu.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_LOW_HEALTH],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 8,
    statTypes: [],
  },
  {
    key: `legend-alacrity`,
    shortDescription: `Gain attack speed and stack more from takedowns.`,
    fullDescription: `Nhận 3% Tốc Độ Đánh. Tham gia hạ gục quái, tướng địch hoặc lính để nhận thêm tối đa 20% Tốc Độ Đánh.`,
    effectTypes: [RuneEffectType.ATTACK_SPEED, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    baseValue: 3,
    scalingValue: 20,
    statTypes: [RuneStatType.ATTACK_SPEED],
  },
  {
    key: `legend-tenacity`,
    shortDescription: `Gain tenacity and slow resist, stacking from takedowns.`,
    fullDescription: `Nhận 3% Kháng Hiệu Ứng và 3% Kháng Làm Chậm. Tham gia hạ gục quái, tướng địch hoặc lính để nhận thêm tối đa 15% Kháng Hiệu Ứng và 20% Kháng Làm Chậm.`,
    effectTypes: [RuneEffectType.UTILITY, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    baseValue: 3,
    scalingValue: 20,
    statTypes: [],
  },
  {
    key: `legend-bloodline`,
    shortDescription: `Gain omnivamp and stack more from takedowns.`,
    fullDescription: `Nhận 1% Hút Máu Toàn Phần. Tham gia hạ gục quái, tướng địch hoặc lính để nhận thêm tối đa 7% Hút Máu Toàn Phần.`,
    effectTypes: [RuneEffectType.UTILITY, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    baseValue: 1,
    scalingValue: 7,
    statTypes: [RuneStatType.OMNIVAMP],
  },

  {
    key: `demolish`,
    shortDescription: `Charge near enemy turrets and deal bonus turret damage.`,
    fullDescription: `Khi ở trong tầm 550 quanh trụ địch, nhận một điểm vận sức sau mỗi 0.5 giây, tối đa 6 điểm. Khi vận tối đa, đòn đánh thường tiếp theo lên trụ gây 100 + 22% Máu tối đa sát thương vật lý. Hồi chiêu: 30 giây.`,
    effectTypes: [RuneEffectType.DAMAGE, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.STACK_BASED],
    targetTypes: [TargetType.TURRET],
    baseValue: 100,
    cooldown: 30,
    maxStacks: 6,
    statTypes: [RuneStatType.HEALTH],
  },
  {
    key: `font-of-life`,
    shortDescription: `Hitting champions heals yourself and nearby low-health ally.`,
    fullDescription: `Khi đòn đánh hoặc kỹ năng trúng tướng địch, hồi máu cho bản thân và tướng đồng minh thấp Máu nhất gần đó. Đồng minh hồi 3% Máu tối đa của bạn + 15% Sức Mạnh Phép Thuật. Bạn hồi 1% Máu tối đa của bạn + 5% Sức Mạnh Phép Thuật. Hồi chiêu: 20 giây. Hồi máu có 130% hiệu lực nếu bạn là tướng cận chiến.`,
    effectTypes: [RuneEffectType.HEAL],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.SELF, TargetType.ALLY],
    cooldown: 20,
    statTypes: [RuneStatType.HEALTH, RuneStatType.ABILITY_POWER],
  },
  {
    key: `courage-of-the-colossus`,
    shortDescription: `Immobilizing champions grants a shield.`,
    fullDescription: `Khi làm bất động tướng địch, nhận lá chắn hấp thụ lượng sát thương bằng 25 - 45 + 1% Máu tối đa trong 3 giây. Hồi chiêu: 10 giây.`,
    effectTypes: [RuneEffectType.SHIELD],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 25,
    scalingValue: 45,
    cooldown: 10,
    duration: 3,
    statTypes: [RuneStatType.HEALTH],
  },
  {
    key: `perseverance`,
    shortDescription: `Gain armor and magic resist, increased by nearby enemies.`,
    fullDescription: `Nhận 4% Giáp và Kháng Phép. Với mỗi 1 tướng địch ở gần, nhận thêm 3% Giáp và Kháng Phép. Nếu có tối đa 3 tướng địch ở gần, nhận thêm 20% Kháng Làm Chậm.`,
    effectTypes: [
      RuneEffectType.ARMOR,
      RuneEffectType.MAGIC_RESIST,
      RuneEffectType.UTILITY,
    ],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE],
    targetTypes: [TargetType.SELF],
    baseValue: 4,
    scalingValue: 3,
    maxStacks: 3,
    statTypes: [RuneStatType.ARMOR, RuneStatType.MAGIC_RESIST],
  },
  {
    key: `second-wind`,
    shortDescription: `Gain regen and heal after taking champion damage.`,
    fullDescription: `Tăng 5 Máu sau mỗi 5 giây. Sau khi nhận sát thương từ tướng địch, hồi lại 6 + 2% Máu đã mất trong vòng 5 giây tiếp theo. Tăng gấp đôi hiệu ứng đối với tướng cận chiến.`,
    effectTypes: [RuneEffectType.HEAL, RuneEffectType.HEALTH],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.SELF],
    baseValue: 5,
    duration: 5,
    statTypes: [RuneStatType.HEALTH],
  },
  {
    key: `nullifying-orb`,
    shortDescription: `Gain shield when champion damage drops you below 35% health.`,
    fullDescription: `Nếu sát thương từ tướng địch khiến Máu tụt xuống dưới 35% Máu tối đa, nhận lá chắn hấp thụ 60 - 180 sát thương trong 4 giây. Hồi chiêu: 60 giây.`,
    effectTypes: [RuneEffectType.SHIELD],
    triggerTypes: [RuneTriggerType.ON_LOW_HEALTH],
    targetTypes: [TargetType.SELF],
    baseValue: 60,
    scalingValue: 180,
    cooldown: 60,
    duration: 4,
    statTypes: [],
  },
  {
    key: `bone-plating`,
    shortDescription: `Reduce champion damage after being hit by a champion.`,
    fullDescription: `Khi nhận sát thương từ tướng, sát thương hiện tại và sát thương từ 3 kỹ năng hoặc đòn đánh tiếp theo từ tướng lên bạn trong vòng 1.5 giây sẽ được giảm 30 - 60. Hồi chiêu: 60 giây.`,
    effectTypes: [RuneEffectType.UTILITY],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.SELF],
    baseValue: 30,
    scalingValue: 60,
    cooldown: 60,
    duration: 1.5,
    maxStacks: 3,
    statTypes: [],
  },
  {
    key: `overgrowth`,
    shortDescription: `Nearby minion and monster deaths grant permanent maximum health.`,
    fullDescription: `Với mỗi 2 lính hoặc 1 quái bị tiêu diệt ở gần, nhận vĩnh viễn 3 Máu tối đa. Có thể nhận Máu tối đa không giới hạn. Nhận thêm 3% Máu tối đa khi đạt 30 cộng dồn.`,
    effectTypes: [RuneEffectType.HEALTH, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.STACK_BASED],
    targetTypes: [TargetType.SELF],
    baseValue: 3,
    maxStacks: 30,
    statTypes: [RuneStatType.HEALTH],
  },
  {
    key: `revitalize`,
    shortDescription: `Increase healing and shielding, more on low-health targets.`,
    fullDescription: `Tăng 5% hiệu ứng hồi máu hoặc tạo lá chắn. Nếu mục tiêu còn dưới 40% Máu, hiệu ứng tăng thêm 10%.`,
    effectTypes: [RuneEffectType.HEAL, RuneEffectType.SHIELD],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE],
    targetTypes: [TargetType.SELF, TargetType.ALLIES],
    baseValue: 5,
    scalingValue: 10,
    statTypes: [],
  },
  {
    key: `tenacity`,
    shortDescription: `Gain tenacity and resistances when immobilized.`,
    fullDescription: `Nhận 10% Kháng Hiệu Ứng. Nhận 15 - 25 Giáp và Kháng Phép trong 1.5 giây khi bị bất động. Làm mới thời gian hiệu lực khi bị bất động nhiều lần.`,
    effectTypes: [
      RuneEffectType.ARMOR,
      RuneEffectType.MAGIC_RESIST,
      RuneEffectType.UTILITY,
    ],
    triggerTypes: [RuneTriggerType.ON_CHAMPION_HIT],
    targetTypes: [TargetType.SELF],
    baseValue: 10,
    scalingValue: 25,
    duration: 1.5,
    statTypes: [RuneStatType.ARMOR, RuneStatType.MAGIC_RESIST],
  },

  {
    key: `elemental-master`,
    shortDescription: `Increase ultimate damage, healing, and shielding. Takedowns reduce ultimate cooldown.`,
    fullDescription: `Chiêu cuối được tăng 10% sát thương, giá trị hồi máu và tạo lá chắn. Sát thương diện rộng chỉ tăng thêm 5%. Tham gia hạ gục tướng địch giảm 7% thời gian hồi chiêu còn lại cho chiêu cuối.`,
    effectTypes: [
      RuneEffectType.DAMAGE,
      RuneEffectType.HEAL,
      RuneEffectType.SHIELD,
      RuneEffectType.COOLDOWN_REDUCTION,
    ],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE, RuneTriggerType.ON_TAKEDOWN],
    targetTypes: [TargetType.SELF],
    baseValue: 10,
    scalingValue: 7,
    statTypes: [],
  },
  {
    key: `manaflow-band`,
    shortDescription: `Hit champions with abilities or empowered attacks to permanently gain mana.`,
    fullDescription: `Đánh trúng tướng địch bằng kỹ năng hoặc đòn đánh cường hóa sẽ tăng vĩnh viễn Năng Lượng tối đa lên 30, tối đa 300 Năng Lượng.`,
    effectTypes: [RuneEffectType.MANA, RuneEffectType.STACKING],
    triggerTypes: [RuneTriggerType.ON_ABILITY_HIT, RuneTriggerType.ON_ATTACK],
    targetTypes: [TargetType.SELF, TargetType.CHAMPION],
    baseValue: 30,
    maxStacks: 10,
    statTypes: [RuneStatType.MANA],
  },
  {
    key: `sweet-tooth`,
    shortDescription: `Destroy plants for gold and enhanced plant effects.`,
    fullDescription: `Khi phá hủy một cây, nhận 25 vàng và hiệu ứng cây cường hóa. Linh Hoa gần trụ cho thêm 100% vàng. Quả Hồi Phục tăng hồi máu thêm 20%. Hoa Soi Sáng kéo dài tầm nhìn thêm 20%. Hạt Thông Nổ tăng 40% Tốc Độ Di Chuyển trong 2.5 giây sau khi bị đẩy lùi.`,
    effectTypes: [
      RuneEffectType.GOLD,
      RuneEffectType.HEAL,
      RuneEffectType.VISION,
      RuneEffectType.MOVEMENT_SPEED,
      RuneEffectType.UTILITY,
    ],
    triggerTypes: [RuneTriggerType.ON_HIT],
    targetTypes: [TargetType.SELF, TargetType.LOCATION],
    baseValue: 25,
    duration: 2.5,
    statTypes: [RuneStatType.GOLD, RuneStatType.MOVEMENT_SPEED],
  },
  {
    key: `hexflash`,
    shortDescription: `While Flash is on cooldown, replace it with Hexflash.`,
    fullDescription: `Khi Tốc Biến đang hồi chiêu, nó được thay thế bằng Tốc Biến Ma Thuật. Lướt đi một khoảng ngắn dựa trên thời gian vận sức, tối đa 2 giây. Hồi chiêu: 25 giây.`,
    effectTypes: [RuneEffectType.UTILITY, RuneEffectType.MOVEMENT_SPEED],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE],
    targetTypes: [TargetType.SELF, TargetType.LOCATION],
    cooldown: 25,
    duration: 2,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
  },
  {
    key: `transcendence`,
    shortDescription: `Gain ability haste at levels 1 and 5. Later, basic ability hits reduce cooldown.`,
    fullDescription: `Ở cấp 1, nhận 6 Điểm Hồi Kỹ Năng. Ở cấp 5, nhận thêm 6 Điểm Hồi Kỹ Năng. Ở cấp 9, sau khi kỹ năng cơ bản trúng mục tiêu, giảm 10% thời gian hồi chiêu của kỹ năng đó. Hồi chiêu: 8 giây.`,
    effectTypes: [
      RuneEffectType.ABILITY_HASTE,
      RuneEffectType.COOLDOWN_REDUCTION,
    ],
    triggerTypes: [
      RuneTriggerType.ALWAYS_ACTIVE,
      RuneTriggerType.ON_ABILITY_HIT,
    ],
    targetTypes: [TargetType.SELF],
    baseValue: 6,
    scalingValue: 10,
    cooldown: 8,
    statTypes: [RuneStatType.ABILITY_HASTE],
  },
  {
    key: `celerity`,
    shortDescription: `Gain movement speed and increase bonus movement speed effects.`,
    fullDescription: `Tăng 2% Tốc Độ Di Chuyển. Tất cả thưởng Tốc Độ Di Chuyển của bạn cũng sẽ tăng lên 7%.`,
    effectTypes: [RuneEffectType.MOVEMENT_SPEED],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE],
    targetTypes: [TargetType.SELF],
    baseValue: 2,
    scalingValue: 7,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
  },
  {
    key: `absolute-focus`,
    shortDescription: `Gain adaptive force while above 65% health.`,
    fullDescription: `Khi có nhiều hơn 65% Máu, nhận thêm 2 - 20 Sức Mạnh Công Kích hoặc 4 - 40 Sức Mạnh Phép Thuật thích ứng.`,
    effectTypes: [RuneEffectType.ADAPTIVE_FORCE, RuneEffectType.SCALING],
    triggerTypes: [RuneTriggerType.ALWAYS_ACTIVE],
    targetTypes: [TargetType.SELF],
    baseValue: 2,
    scalingValue: 40,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `scorch`,
    shortDescription: `Ability damage burns champions for bonus magic damage.`,
    fullDescription: `Gây sát thương lên tướng địch bằng kỹ năng sẽ thiêu cháy chúng, gây thêm 21 - 49 sát thương phép dựa theo cấp độ sau 1 giây. Hồi chiêu: 8 giây.`,
    effectTypes: [RuneEffectType.DAMAGE],
    triggerTypes: [RuneTriggerType.ON_ABILITY_HIT],
    targetTypes: [TargetType.CHAMPION],
    baseValue: 21,
    scalingValue: 49,
    cooldown: 8,
    duration: 1,
    statTypes: [],
  },
  {
    key: `nimbus-cloak`,
    shortDescription: `After using a summoner spell, gain movement speed.`,
    fullDescription: `Sau khi dùng Phép, tăng 10 - 40% Tốc Độ Di Chuyển cộng thêm trong 3 giây. Lượng tăng tốc phụ thuộc vào thời gian hồi chiêu của Phép.`,
    effectTypes: [RuneEffectType.MOVEMENT_SPEED],
    triggerTypes: [RuneTriggerType.ON_COMBAT_START],
    targetTypes: [TargetType.SELF],
    baseValue: 10,
    scalingValue: 40,
    duration: 3,
    statTypes: [RuneStatType.MOVEMENT_SPEED],
  },
  {
    key: `gathering-storm`,
    shortDescription: `Gain increasing adaptive force over time starting at 6 minutes.`,
    fullDescription: `Từ phút thứ 6 sau khi trận đấu bắt đầu, nhận thêm 2 Sức Mạnh Công Kích hoặc 4 Sức Mạnh Phép Thuật thích ứng, tăng sau mỗi 3 phút lên 5 hoặc 10, 9 hoặc 18, 14 hoặc 28, ...`,
    effectTypes: [RuneEffectType.ADAPTIVE_FORCE, RuneEffectType.SCALING],
    triggerTypes: [RuneTriggerType.AFTER_TIME],
    targetTypes: [TargetType.SELF],
    baseValue: 2,
    statTypes: [RuneStatType.ADAPTIVE_FORCE],
  },
  {
    key: `ixtali-seedjar`,
    shortDescription: `Destroy plants to gain a seed that can be placed later.`,
    fullDescription: `Sau khi phá hủy cây, lập tức nhận một hạt giống thay thế cho phụ kiện trong 60 giây. Hạt giống lớn lên và tự hủy sau khi được gieo tại vị trí chỉ định. Hạt giống có thể thu thập được sau 2 phút kể từ khi trận đấu bắt đầu. Mỗi cây có 30 giây hồi chiêu riêng.`,
    effectTypes: [
      RuneEffectType.UTILITY,
      RuneEffectType.VISION,
      RuneEffectType.MOVEMENT_SPEED,
    ],
    triggerTypes: [RuneTriggerType.ON_HIT, RuneTriggerType.AFTER_TIME],
    targetTypes: [TargetType.SELF, TargetType.LOCATION],
    cooldown: 30,
    duration: 60,
    statTypes: [],
  },
];

export async function seedRunesPatchStats(
  prisma: PrismaClient,
  patchId: string,
) {
  console.log(`SEEDING RUNES PATCH STATS...`);

  for (const runePatchStatSeed of runePatchStatSeeds) {
    const rune = await prisma.rune.findUnique({
      where: {
        key: runePatchStatSeed.key,
      },
    });

    if (!rune) {
      throw new Error(
        `Cannot seed rune patch stat. Missing rune: ${runePatchStatSeed.key}`,
      );
    }

    await prisma.runePatchStat.upsert({
      where: {
        runeId_patchId: {
          runeId: rune.id,
          patchId,
        },
      },
      update: {
        shortDescription: runePatchStatSeed.shortDescription ?? null,
        fullDescription: runePatchStatSeed.fullDescription ?? null,
        effectTypes: runePatchStatSeed.effectTypes,
        triggerTypes: runePatchStatSeed.triggerTypes,
        targetTypes: runePatchStatSeed.targetTypes,
        baseValue: runePatchStatSeed.baseValue ?? null,
        scalingValue: runePatchStatSeed.scalingValue ?? null,
        cooldown: runePatchStatSeed.cooldown ?? null,
        duration: runePatchStatSeed.duration ?? null,
        maxStacks: runePatchStatSeed.maxStacks ?? null,
        statTypes: runePatchStatSeed.statTypes,
        statBonuses: runePatchStatSeed.statBonuses ?? Prisma.DbNull,
        notes: runePatchStatSeed.notes ?? null,
        deletedAt: null,
      },
      create: {
        patchId,
        runeId: rune.id,
        shortDescription: runePatchStatSeed.shortDescription ?? null,
        fullDescription: runePatchStatSeed.fullDescription ?? null,
        effectTypes: runePatchStatSeed.effectTypes,
        triggerTypes: runePatchStatSeed.triggerTypes,
        targetTypes: runePatchStatSeed.targetTypes,
        baseValue: runePatchStatSeed.baseValue ?? null,
        scalingValue: runePatchStatSeed.scalingValue ?? null,
        cooldown: runePatchStatSeed.cooldown ?? null,
        duration: runePatchStatSeed.duration ?? null,
        maxStacks: runePatchStatSeed.maxStacks ?? null,
        statTypes: runePatchStatSeed.statTypes,
        statBonuses: runePatchStatSeed.statBonuses ?? Prisma.DbNull,
        notes: runePatchStatSeed.notes ?? null,
      },
    });

    console.log(`Seeded rune patch stat: ${runePatchStatSeed.key}`);
  }

  console.log(`SEEDED RUNES PATCH STATS`);
}
